### ISSUE TITLE
"Generating tags" might hang due to libvterm issue (not using bundled one)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10196]
The build process might hang in the end due to a libvterm issue:

```
ninja: Entering directory `build'
[1/3] Generating pack/dist/opt/vimball/doc/tags^C

```

This happens due to / with https://github.com/neovim/libvterm/commit/53e8320dd33c69fc67df69cf21460245db9619a9.

This is not included in the bundled libvterm (yet), but relevant already with `-DUSE_BUNDLED_LIBVTERM=OFF`, and when updating libvterm later.

**Comment by blueyed** [comment]
The problem affects just running nvim already..

It loops in
```
#0  0x0000555555859500 in map_int_int_put (map=0x555555d75580, key=255, value=205) at ../src/nvim/map.c:177
#1  0x0000555555a45516 in terminal_init () at ../src/nvim/terminal.c:183
#2  0x0000555555850461 in event_init () at ../src/nvim/main.c:158
#3  0x0000555555850911 in main (argc=1, argv=0x7fffffffd628) at ../src/nvim/main.c:265
```

However, when building Neovim against this libterm version, there are several compiler warnings, which indicates that it likely does something wrong/unexpected when using the newer version:
```
../src/nvim/terminal.c: In function ‘terminal_init’:
../src/nvim/terminal.c:178:12: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘red’
       color.red = 0;
            ^
../src/nvim/terminal.c:179:12: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘green’
       color.green = 0;
            ^
../src/nvim/terminal.c:180:12: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘blue’
       color.blue = (uint8_t)(color_index + 1);
            ^
In file included from ../src/nvim/func_attr.h:44,
                 from include/log.h.generated.h:4,
                 from ../src/nvim/log.h:72,
                 from ../src/nvim/terminal.c:46:
../src/nvim/terminal.c:187:33: error: ‘VTermColor’ {aka ‘union <anonymous>’} has no member named ‘red’
                       RGB_(color.red, color.green, color.blue),
                                 ^
```

**Comment by blueyed** [comment]
Likely still with the exact setup/problematic commit, but that is likely obsolete/replaced, so closing.
