### ISSUE TITLE
"wstream_write: Assertion `!stream->closed' failed." when exit

### ISSUE THREAD

**Issue by choleraehyq** [neovim/neovim#10709]
- `nvim --version`:
```
NVIM v0.3.8
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-20699855-a609-4c8a-9d51-98381960ee3c

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
```
Linux 4.4.0-33.bm.1-amd64 #1 SMP Wed, 24 Jan 2018 15:50:58 +0800 x86_64 GNU/Linux
```
- Terminal name/version:
- `$TERM`:
```
screen
```
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```
I don't know how to reproduce this bug consistently, but it's triggered frequently.

### Actual behaviour
```
nvim: /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/event/wstream.c:78: wstream_write: Assertion `!stream->closed' failed.
Aborted (core dumped)
```
backtrace:
```
(gdb) bt
#0  0x00007fc107777067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fc107778448 in __GI_abort () at abort.c:89
#2  0x00007fc107770266 in __assert_fail_base (fmt=0x7fc1078a8f18 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x6f90ab "!stream->closed", file=file@entry=0x6f8968 "/home/travis/build/neovim/bot-ci/build/neovim/src/nvim/event/wstream.c",
    line=line@entry=78, function=function@entry=0x6f9e28 <__PRETTY_FUNCTION__.15300> "wstream_write") at assert.c:92
#3  0x00007fc107770312 in __GI___assert_fail (assertion=0x6f90ab "!stream->closed", file=0x6f8968 "/home/travis/build/neovim/bot-ci/build/neovim/src/nvim/event/wstream.c", line=78, function=0x6f9e28 <__PRETTY_FUNCTION__.15300> "wstream_write") at assert.c:101
#4  0x0000000000581794 in wstream_write (stream=0x7fc1071f5860, buffer=0x7fc107032460) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/event/wstream.c:78
#5  0x00000000004d02ba in channel_write (channel=channel@entry=0x7fc1071f5800, buffer=0x7fc107032460) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/msgpack_rpc/channel.c:399
#6  0x00000000004d0613 in on_request_event (argv=<optimized out>) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/msgpack_rpc/channel.c:370
#7  0x00000000005803d8 in multiqueue_process_events (this=0x7fc10701a1e0) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/event/multiqueue.c:150
#8  0x0000000000519ecc in event_teardown () at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/main.c:167
#9  0x000000000049777b in mch_exit (r=0) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/os_unix.c:145
#10 0x0000000000526348 in getout (exitval=0) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/main.c:703
#11 0x00000000005a437d in ex_exit.lto_priv.379 (eap=0x7fff2375a4c0) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/ex_docmd.c:6433
#12 0x0000000000578839 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7fff2375aba8, flags=flags@entry=0, cstack=cstack@entry=0x7fff2375a6a0, fgetline=fgetline@entry=0x543c1b <getexline>, cookie=cookie@entry=0x0)
    at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/ex_docmd.c:2238
#13 0x00000000005791cc in do_cmdline (cmdline=<optimized out>, fgetline=0x543c1b <getexline>, cookie=0x0, flags=0) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/ex_docmd.c:593
#14 0x00000000004cc10d in nv_colon (cap=0x7fff2375acf0) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/normal.c:4603
#15 0x00000000004d8cae in normal_execute.lto_priv.190 (state=0x7fff2375ac50, key=<optimized out>) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/normal.c:1137
#16 0x000000000044c551 in state_enter (s=0x7fff2375ac50) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/state.c:73
#17 0x00000000004cec70 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/normal.c:467
#18 0x000000000051a7fd in main (argc=<optimized out>, argv=<optimized out>) at /home/travis/build/neovim/bot-ci/build/neovim/src/nvim/main.c:598
```
### Expected behaviour
No coredumps.

**Comment by blueyed** [comment]
> I don't know how to reproduce this bug consistently, but it's triggered frequently.

Can you try a nightly build / master then, and see if it happens there also, please?

**Comment by lovesegfault** [comment]
I too can reproduce this on Gentoo, often

**Comment by bfredl** [comment]
@lovesegfault please mention the version. Similar bugs (if not exactly this traceback) has been fixed on master since 0.3.8.

**Comment by lovesegfault** [comment]
```
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -march=native -falign-functions=32 -O2 -pipe -fgraphite-identity -floop-nest-optimize -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/var/tmp/portage/app-editors/neovim-0.3.7/work/neovim-0.3.7_build/config -I/var/tmp/portage/app-editors/neovim-0.3.7/work/neovim-0.3.7/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.3.7/work/neovim-0.3.7_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.3.7/work/neovim-0.3.7_build/include
Compiled by portage@bergman

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I guess I need to get 0.3.8

**Comment by blueyed** [comment]
@lovesegfault 
0.3.8 has not many fixes compared to 0.3.7 (only security).
master/nightly (to become 0.4) should be tested instead.

**Comment by choleraehyq** [comment]
@blueyed I'll try to use nightly today.

**Comment by choleraehyq** [comment]
I tried v0.4.0-1581-g6fb0020df, it never happen again, seems it's been fixed in nightly. Thanks!
