### ISSUE TITLE
API: nvim_win_set_option: missing error message for E539 (Illegal character)

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#10810]
`:py3 vim.api.win_set_option(0, 'concealcursor', '1')` results in:

```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 45 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b''
```

Using an integer results in a correct error:

> pynvim.api.nvim.NvimError: b"Option 'concealcursor' requires a string value"

The Vim error itself is: `E539: Illegal character <1>: concealcursor=1` (with `set concealcursor=1`).

With `:lua` it looks similar:
```
:lua print(vim.api.nvim_win_set_option(0, "concealcursor", 1))
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: Option 'concealcursor' requires a string value
:lua print(vim.api.nvim_win_set_option(0, "concealcursor", "1"))
E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1:
```

**Comment by hippo91** [comment]
Hi all. 

I can not reproduce this bug anymore.

When entering `:py3 vim.api.win_set_option(0, 'concealcursor', '1')` i got:

```
Error detected while processing function provider#python3#Call:                                                 
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/anaxi/neovim_env/lib/python3.11/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaxi/neovim_env/lib/python3.11/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: E539: Illegal character <1>
```

which seems quite ok to me.

**Comment by lewis6991** [comment]
Thanks. Closing.

**Comment by hippo91** [comment]
@lewis6991 i was wondering if adding the legal characters in the error message was a good idea or not.
What do you think about it?

**Comment by lewis6991** [comment]
Sounds reasonable.
