### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by YaLTeR** [neovim/neovim#10944]
- `nvim --version`: `NVIM v0.4.0-1957` bd1158f3a
- Operating system/version: Arch Linux x64
- Terminal name/version: alacritty 0.3.3
- `$TERM`: alacritty

Sorry for lack of info, this just happened and I don't know how to reproduce it.

```
#0  0x00007f524343b755 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f5243426851 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007f5243426727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007f5243434026 in __assert_fail () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x000055cb4f055dd6 in tui_raw_line (ui=0x55cb4f39c000, g=<optimized out>, linerow=55, startcol=45, endcol=136, clearcol=136, clearattr=0, flags=0, chunk=0x55cb51b9e990, attrs=0x55cb50656890)
    at /usr/src/debug/neovim-git/src/nvim/tui/tui.c:1291
        c = <optimized out>
        data = 0x7f523c000d90
        grid = 0x7f523c011778
        __PRETTY_FUNCTION__ = "tui_raw_line"
#5  0x000055cb4f046cd3 in ui_bridge_raw_line_event (argv=0x7f5242883718) at /usr/src/debug/neovim-git/src/nvim/ui_bridge.c:154
        ui = <optimized out>
#6  0x000055cb4f1abf5d in multiqueue_process_events (this=0x7f523c000cf0) at /usr/src/debug/neovim-git/src/nvim/event/multiqueue.c:150
        event = {handler = 0x55cb4f046c91 <ui_bridge_raw_line_event>, argv = {0x55cb4f39c110, 0x1, 0x37, 0x2d, 0x88, 0x88, 0x0, 0x0, 0x55cb51b9e990, 0x55cb50656890}}
        __PRETTY_FUNCTION__ = "multiqueue_process_events"
#7  0x000055cb4f1ac1ec in loop_poll_events (loop=0x7f5242883880, ms=<optimized out>) at /usr/src/debug/neovim-git/src/nvim/event/loop.c:70
        mode = <optimized out>
        timeout_expired = false
#8  0x000055cb4f05d552 in tui_main (bridge=0x55cb4f39c110, ui=0x55cb4f39c000) at /usr/src/debug/neovim-git/src/nvim/tui/tui.c:437
        tui_loop = {uv = {data = 0x7f5242883880, active_handles = 4, handle_queue = {0x7f5242883b08, 0x7f523c010ec0}, active_reqs = {unused = {0x0, 0x0}, count = 0}, stop_flag = 0, flags = 0, backend_fd = 16,
            pending_queue = {0x7f52428838c8, 0x7f52428838c8}, watcher_queue = {0x7f52428838d8, 0x7f52428838d8}, watchers = 0x7f523c000b20, nwatchers = 30, nfds = 3, wq = {0x7f52428838f8, 0x7f52428838f8},
            wq_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>,
              __align = 0}, wq_async = {data = 0x0, loop = 0x7f5242883880, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7f5242883dd8, 0x7f5242883b08}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}},
              next_closing = 0x0, flags = 20, async_cb = 0x7f52433b6fd0 <uv.work_done>, queue = {0x7f5242883e20, 0x7f5242883a30}, pending = 0}, cloexec_lock = {__data = {__readers = 0, __writers = 0,
                __wrphase_futex = 0, __writers_futex = 0, __pad3 = 0, __pad4 = 0, __cur_writer = 0, __shared = 0, __rwelision = 0 '\000', __pad1 = "\000\000\000\000\000\000", __pad2 = 0, __flags = 0},
              __size = '\000' <repeats 55 times>, __align = 0}, closing_handles = 0x0, process_handles = {0x7f52428839f0, 0x7f52428839f0}, prepare_handles = {0x7f5242883a00, 0x7f5242883a00}, check_handles = {
              0x7f5242883a10, 0x7f5242883a10}, idle_handles = {0x7f5242883a20, 0x7f5242883a20}, async_handles = {0x7f5242883998, 0x7f5242883e20}, async_unused = 0x0, async_io_watcher = {cb = 0x7f52433ba3f0,
              pending_queue = {0x7f5242883a50, 0x7f5242883a50}, watcher_queue = {0x7f5242883a60, 0x7f5242883a60}, pevents = 1, events = 1, fd = 19}, async_wfd = -1, timer_heap = {min = 0x0, nelts = 0},
            timer_counter = 125, time = 17805472, signal_pipefd = {17, 18}, signal_io_watcher = {cb = 0x7f52433c3df0, pending_queue = {0x7f5242883ab8, 0x7f5242883ab8}, watcher_queue = {0x7f5242883ac8,
                0x7f5242883ac8}, pevents = 1, events = 1, fd = 17}, child_watcher = {data = 0x0, loop = 0x7f5242883880, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7f5242883950, 0x7f5242883890}, u = {
                fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 16, signal_cb = 0x0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0},
              caught_signals = 0, dispatched_signals = 0}, emfile_fd = 20, inotify_read_watcher = {cb = 0x0, pending_queue = {0x0, 0x0}, watcher_queue = {0x0, 0x0}, pevents = 0, events = 0, fd = 0},
            inotify_watchers = 0x0, inotify_fd = -1}, events = 0x7f523c000cb0, thread_events = 0x7f523c000d30, fast_events = 0x7f523c000cf0, children = 0x7f523c000c30, children_watcher = {data = 0x0,
            loop = 0x7f5242883880, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7f5242883ca8, 0x7f5242883dd8}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8,
            signal_cb = 0x0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, children_kill_timer = {data = 0x0,
            loop = 0x7f5242883880, type = UV_TIMER, close_cb = 0x0, handle_queue = {0x7f5242883d40, 0x7f5242883c10}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8, timer_cb = 0x0,
            heap_node = {0x0, 0x0, 0x0}, timeout = 0, repeat = 0, start_id = 0}, poll_timer = {data = 0x7f523c000d70, loop = 0x7f5242883880, type = UV_TIMER, close_cb = 0x0, handle_queue = {0x7f523c011620,
              0x7f5242883ca8}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8, timer_cb = 0x55cb4f1aaac9 <timer_cb>, heap_node = {0x0, 0x0, 0x0}, timeout = 121469, repeat = 20,
            start_id = 63}, async = {data = 0x0, loop = 0x7f5242883880, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7f5242883c10, 0x7f5242883950}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}},
            next_closing = 0x0, flags = 12, async_cb = 0x55cb4f1ad364 <async_cb>, queue = {0x7f5242883a30, 0x7f5242883998}, pending = 2}, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0,
              __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, recursive = 0}
        data = 0x7f523c000d90
#9  0x000055cb4f051bcc in ui_thread_run (data=<optimized out>) at /usr/src/debug/neovim-git/src/nvim/ui_bridge.c:102
        bridge = <optimized out>
#10 0x00007f524339357f in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#11 0x00007f52434fd0e3 in clone () from /usr/lib/libc.so.6
No symbol table info available.
```

**Comment by justinmk** [comment]
Were you running a lot of plugins, perhaps with "many" highlights? https://github.com/neovim/neovim/issues/8782

**Comment by YaLTeR** [comment]
Could be the case, yeah.
