### ISSUE TITLE
:redir terminated by signal SIGABRT

### ISSUE THREAD

**Issue by dm1try** [neovim/neovim#11980]
- `nvim --version`: `NVIM v0.5.0-415-gf8f41d088`
- `vim -u DEFAULTS` (version: 8.1.2292) works
- Operating system/version: osx Catalina

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -c 'redir @*| exe "!ls" | redir END'
```

### Actual behaviour
```
'nvim -u NORC -c 'redir @*| exe…' terminated by signal SIGABRT (Abort)
```
### Expected behaviour
`redir` works

**Comment by zeertzjq** [comment]
Does this bug still exist?

**Comment by dm1try** [comment]
@zeertzjq yeah, I've reproduced that on the latest master a88046fe2.

thought, it's really not important at all. I don't even remember what I was doing)

**Comment by dm1try** [comment]
it does not look like a bug to me today, discussed with gpt
>in practice, it’s kind of clumsy, because !ls runs in a shell subprocess, so the output isn’t Neovim’s command output — which means redir might not actually catch it. You’d probably end up with an empty clipboard or some cryptic error message.
If you actually want to grab ls output into your clipboard, the sensible way is:
nvim -u NORC +"let @* = system('ls')" +q

`nvim -u NORC +"let @* = system('ls')" +q` works as expected

**Comment by justinmk** [comment]
> the output isn’t Neovim’s command output — which means redir might not actually catch it

chatgpt is making assumptions/guesses (perhaps based on how `:!` is implemented in Vim).

In Nvim `:!` output is captured like any other command, and definitely should not cause SIGABRT.

**Comment by dm1try** [comment]
@justinmk Thank you for the explanation. I was trying to revisit some old issues and didn’t even remember what this command was doing. After the explanation from GPT, I started to think it might not even be a bug. Unfortunately, it is.

**Comment by zeertzjq** [comment]
ASAN:
```
=================================================================
==2368146==ERROR: AddressSanitizer: ABRT on unknown address 0x03e800242292 (pc 0x7fd489c9894c bp 0x7fffe6d9dc20 sp 0x7fffe6d9dbe0 T0)
    #0 0x7fd489c9894c in __pthread_kill_implementation /usr/src/debug/glibc/glibc/nptl/pthread_kill.c:44:76
    #1 0x7fd489c3e40f in raise /usr/src/debug/glibc/glibc/signal/../sysdeps/posix/raise.c:26:13
    #2 0x7fd489c25579 in abort /usr/src/debug/glibc/glibc/stdlib/abort.c:77:3
    #3 0x560270d130a0 in loop_uv_run **/src/nvim/event/loop.c:44:5
    #4 0x560270d12ee4 in loop_poll_events **/src/nvim/event/loop.c:80:26
    #5 0x5602714e48f2 in os_breakcheck **/src/nvim/os/input.c:205:3
    #6 0x5602714e495d in line_breakcheck **/src/nvim/os/input.c:220:5
    #7 0x560270ca5563 in call_user_func **/src/nvim/eval/userfunc.c:1021:3
    #8 0x560270cb45b0 in call_user_func_check **/src/nvim/eval/userfunc.c:1410:5
    #9 0x560270ca27fd in call_func **/src/nvim/eval/userfunc.c:1765:17
    #10 0x560270b2f3e4 in eval_call_provider **/src/nvim/eval.c:6537:3
    #11 0x56027093765c in set_clipboard **/src/nvim/clipboard.c:237:3
    #12 0x5602716db026 in finish_write_reg **/src/nvim/register.c:2520:3
    #13 0x5602716d88d5 in write_reg_contents_ex **/src/nvim/register.c:2649:3
    #14 0x5602716d80b3 in write_reg_contents **/src/nvim/register.c:2533:3
    #15 0x5602712c5a24 in redir_write **/src/nvim/message.c:3400:7
    #16 0x5602712d4d7c in msg_puts_len **/src/nvim/message.c:2262:3
    #17 0x5602712b875b in msg_outtrans_len **/src/nvim/message.c:1827:5
    #18 0x5602714fc767 in out_data_append_to_screen **/src/nvim/os/shell.c:1126:7
    #19 0x5602714fc02f in out_data_cb **/src/nvim/os/shell.c:1141:5
    #20 0x560270d27c4b in read_event **/src/nvim/event/rstream.c:180:23
    #21 0x560270d276e8 in invoke_read_cb **/src/nvim/event/rstream.c:233:3
    #22 0x560270d24c81 in read_cb **/src/nvim/event/rstream.c:135:3
    #23 0x560271e8d43e in uv__read **/.deps/build/src/libuv/src/unix/stream.c:1148:7
    #24 0x560271e8b167 in uv__stream_io **/.deps/build/src/libuv/src/unix/stream.c:1208:5
    #25 0x560271e962dc in uv__io_poll **/.deps/build/src/libuv/src/unix/linux.c:1565:11
    #26 0x560271e7a337 in uv_run **/.deps/build/src/libuv/src/unix/core.c:460:5
    #27 0x560270d13267 in loop_uv_run **/src/nvim/event/loop.c:59:3
    #28 0x560270d12ee4 in loop_poll_events **/src/nvim/event/loop.c:80:26
    #29 0x560270d20de3 in proc_wait **/src/nvim/event/proc.c:182:3
    #30 0x5602714f7fd3 in do_os_system **/src/nvim/os/shell.c:936:18
    #31 0x5602714f6dc3 in os_call_shell **/src/nvim/os/shell.c:690:18
    #32 0x5602714f5516 in call_shell **/src/nvim/os/shell.c:742:14
    #33 0x560270d437c5 in do_shell **/src/nvim/ex_cmds.c:1501:3
    #34 0x560270d43212 in do_bang **/src/nvim/ex_cmds.c:1228:5
    #35 0x560270df4565 in ex_bang **/src/nvim/ex_docmd.c:6555:3
    #36 0x560270dacddf in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #37 0x560270d90595 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #38 0x560270d85b56 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #39 0x560270b2b51e in ex_execute **/src/nvim/eval.c:6235:7
    #40 0x560270dacddf in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #41 0x560270d90595 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #42 0x560270d85b56 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #43 0x560270d89bd8 in do_cmdline_cmd **/src/nvim/ex_docmd.c:377:10
    #44 0x560271109a04 in exe_commands **/src/nvim/main.c:1947:5
    #45 0x5602710f7b88 in main **/src/nvim/main.c:587:5
    #46 0x7fd489c27674 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #47 0x7fd489c27728 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #48 0x560270523004 in _start (**/build/bin/nvim+0xc91004) (BuildId: 5b89439699d15b331f7f9e456273a24bdfb8a5d2)

==2368146==Register values:
rax = 0x0000000000000000  rbx = 0x0000000000242292  rcx = 0x00007fd489c9894c  rdx = 0x0000000000000006  
rdi = 0x0000000000242292  rsi = 0x0000000000242292  rbp = 0x00007fffe6d9dc20  rsp = 0x00007fffe6d9dbe0  
 r8 = 0x00007fd489d6e780   r9 = 0x0000000000000000  r10 = 0x0000000000000000  r11 = 0x0000000000000246  
r12 = 0x00007fffe6da90e8  r13 = 0x0000000000000005  r14 = 0x0000000000000006  r15 = 0x0000560272155be8  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT /usr/src/debug/glibc/glibc/nptl/pthread_kill.c:44:76 in __pthread_kill_implementation
==2368146==ABORTING
```

**Comment by zeertzjq** [comment]
Actually I think when redirecting to a clipboard register, the provider should only be called on the end of redirection, not on every append.

**Comment by zeertzjq** [comment]
Related #7193
