### ISSUE TITLE
.deps/build/src/libuv/src/unix/stream.c:1400: uv_write2: Assertion `nbufs > 0' failed.

### ISSUE THREAD

**Issue by ilAYAli** [neovim/neovim#11990]
- nvim --version
```
NVIM v0.5.0-415-gf8f41d088
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/petter/source/neovim/build/config -I/home/petter/source/neovim/src -I/home/petter/source/neovim/.deps/usr/include -I/usr/include -I/home/petter/source/neovim/build/src/nvim/auto -I/home/petter/source/neovim/build/include
Compiled by petter@pwa-lnx

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/petter/local/share/nvim"

Run :checkhealth for more info
```

- Operating system/version:

macOS Mojave
Fedora 31

### how to reproduce
This happens consistently in 0.5.x on both Linux and macOS with `CoC`.
I have not been able to reproduce it without any plugins.
Regardless of plugins, an `assert` in libuv should not happen.
It happens both with the official nightly and with my own, compiled version.

Move the cursor to a function that is called somewhere, and try finding references to it:
```
call CocAction('jumpReferences')
```
### backtrace
```
[Detaching after fork from child process 3827215]
nvim: /home/petter/source/neovim/.deps/build/src/libuv/src/unix/stream.c:1400: uv_write2: Assertion `nbufs > 0' failed.

Thread 2 "nvim" received signal SIGABRT, Aborted.
                                                                                                                                                                        [Switching to Thread 0x7fffea6b9700 (LWP 3827039)]
0x00007ffff7c63625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install pcre2-10.33-16.fc31.x86_64 sssd-client-2.2.2-3.fc31.x86_64
(gdb) bt
#0  0x00007ffff7c63625 in raise () from /lib64/libc.so.6
#1  0x00007ffff7c4c8d9 in abort () from /lib64/libc.so.6
#2  0x00007ffff7c4c7a9 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007ffff7c5ba66 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000075ac92 in uv_write2 (req=<optimized out>, stream=<optimized out>, bufs=<optimized out>, nbufs=<optimized out>, send_handle=<optimized out>, cb=<optimized out>) at /home/petter/source/neovim/.deps/build/src/libuv/src/unix/stream.c:1400
#5  0x00000000006d64e5 in flush_buf (ui=0x959590) at ../src/nvim/tui/tui.c:1996
#6  0x00000000006d40b5 in tui_flush (ui=0x959590) at ../src/nvim/tui/tui.c:1212
#7  0x00000000006dc6d8 in ui_bridge_flush_event (argv=0x7fffea6b8688) at src/nvim/auto/ui_events_bridge.generated.h:109
#8  0x0000000000509947 in multiqueue_process_events (this=0x7fffe4000d30) at ../src/nvim/event/multiqueue.c:157
#9  0x0000000000508d0b in loop_poll_events (loop=0x7fffea6b87d0, ms=-1) at ../src/nvim/event/loop.c:70
#10 0x00000000006d17d5 in tui_main (bridge=0x9596b0, ui=0x959590) at ../src/nvim/tui/tui.c:442
#11 0x00000000006dd3cd in ui_thread_run (data=0x9596b0) at ../src/nvim/ui_bridge.c:104
#12 0x00007ffff7f834e2 in start_thread () from /lib64/libpthread.so.0
#13 0x00007ffff7d28693 in clone () from /lib64/libc.so.6
```
### possible fix
By briefly looking at this, it seems as this can happen if none of the conditions that increment `bufp` in `flush_buf` are met.
This seems to fix the problem, but I don't know if there are any side effects to it.

```
diff --git src/nvim/tui/tui.c src/nvim/tui/tui.c
index 22f4501be..ca2d55bad 100644
--- src/nvim/tui/tui.c
+++ src/nvim/tui/tui.c
@@ -1993,6 +1993,9 @@ static void flush_buf(UI *ui)
     data->is_invisible = false;
   }

+  if (bufp == &bufs[0])
+      return;
+
   uv_write(&req, STRUCT_CAST(uv_stream_t, &data->output_handle),
            bufs, (unsigned)(bufp - bufs), NULL);
   uv_run(&data->write_loop, UV_RUN_DEFAULT);
```

**Comment by teto** [comment]
the problem should be fixed, feel free to reopen if thats not the case.
