### ISSUE TITLE
crash on calling termopen if connected via ssh

### ISSUE THREAD

**Issue by mfussenegger** [neovim/neovim#12151]
- `nvim --version`: NVIM v0.5.0-443-gc5466ba6e
- Operating system/version: Linux 5.6.4-arch1-1
- Terminal name/version: termite v15
- `$TERM`: xterm-termite

### Steps to reproduce using `nvim -u NORC`

Couldn't manage to get it to crash with `nvim -u NORC`

### Steps I used to reproduce

- Connect to the machine via SSH. (I couldn't reproduce it on the PC where I can reproduce the crash via SSH if using it directly). The client machine has the same terminal and the same $TERM as the destination machine.
- Open up nvim
- Call `lua vim.fn.termopen({ "/usr/bin/python", "/path/to/lib/python3.8/site-packages/debugpy/launcher", "cr8/run_crate.py" })`.  I think the command in question doesn't matter, but rather the (amount?) of output it produces. (Same happened when using `:call termopen([...])` - didn't make a difference.

- Sometimes it crashed, sometimes it didn't. It seemed to crash more often if I opened a python file instead of an empty nvim instance.

<details>
  <summary>stacktrace</summary>

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f6d19f25ce5 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f6d19d14780 (LWP 408040))]
(gdb) where
#0  0x00007f6d19f25ce5 in raise () from /usr/lib/libc.so.6
#1  0x00007f6d19f0f857 in abort () from /usr/lib/libc.so.6
#2  0x0000555ec04854b9 in on_scrollback_option_changed (term=term@entry=0x555ec24a22c0, buf=buf@entry=0x555ec201db80)
    at ../src/nvim/terminal.c:1189
#3  0x0000555ec0485901 in refresh_scrollback (term=term@entry=0x555ec24a22c0, buf=buf@entry=0x555ec201db80)
    at ../src/nvim/terminal.c:1242
#4  0x0000555ec04859a8 in refresh_terminal (term=0x555ec24a22c0) at ../src/nvim/terminal.c:1141
#5  0x0000555ec0485a2f in refresh_timer_cb (watcher=<optimized out>, data=<optimized out>) at ../src/nvim/terminal.c:1159
#6  0x0000555ec05d0126 in time_event (argv=<optimized out>) at ../src/nvim/event/time.c:50
#7  0x0000555ec05d16fd in multiqueue_process_events (this=0x555ec200d3b0) at ../src/nvim/event/multiqueue.c:157
#8  0x0000555ec052d391 in nv_event (cap=0x7fffe817ce28) at ../src/nvim/normal.c:8053
#9  0x0000555ec053b957 in normal_execute (state=0x7fffe817cda0, key=<optimized out>) at ../src/nvim/normal.c:1136
#10 0x0000555ec049b64f in state_enter (s=0x7fffe817cda0) at ../src/nvim/state.c:69
#11 0x0000555ec053b9ff in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at ../src/nvim/normal.c:463
#12 0x0000555ec056c7b9 in main (argc=<optimized out>, argv=<optimized out>) at ../src/nvim/main.c:569
(gdb) frame 2
#2  0x0000555ec04854b9 in on_scrollback_option_changed (term=term@entry=0x555ec24a22c0, buf=buf@entry=0x555ec201db80)
    at ../src/nvim/terminal.c:1189
1189	    abort();
```

</details>

<details>
  <summary>explore value term</summary>

```
(gdb) explore value term
'term' is a pointer to a value of type 'Terminal'
Continue exploring it as a pointer to a single value [y/n]: y

  The value of '*term' is of type 'Terminal' which is a typedef of type 'struct terminal'
The value of '*term' is a struct/class of type 'struct terminal' with the following fields:

            opts = <Enter 0 to explore this field of type 'TerminalOptions'>
              vt = <Enter 1 to explore this field of type 'VTerm *'>
             vts = <Enter 2 to explore this field of type 'VTermScreen *'>
         textbuf = <Enter 3 to explore this field of type 'char [8191]'>
       sb_buffer = <Enter 4 to explore this field of type 'ScrollbackLine **'>
      sb_current = <Enter 5 to explore this field of type 'size_t'>
         sb_size = <Enter 6 to explore this field of type 'size_t'>
      sb_pending = 15 .. (Value of type 'int')
      buf_handle = <Enter 8 to explore this field of type 'handle_T'>
          closed = false .. (Value of type '_Bool')
         destroy = false .. (Value of type '_Bool')
   forward_mouse = false .. (Value of type '_Bool')
   invalid_start = 0 .. (Value of type 'int')
     invalid_end = 34 .. (Value of type 'int')
          cursor = <Enter 14 to explore this field of type 'struct {...}'>
  pressed_button = 0 .. (Value of type 'int')
  pending_resize = false .. (Value of type '_Bool')
       color_set = <Enter 17 to explore this field of type '_Bool [16]'>
        refcount = <Enter 18 to explore this field of type 'size_t'>
```
</details>

The setup in which I ran into this is quite complicated I guess, but maybe
somebody can figure out something from the stacktrace.

**Comment by mfussenegger** [comment]
Haven't experienced this anymore since.
