### ISSUE TITLE
heap-buffer-overflow in tui_draw_line while terminal font resized 

### ISSUE THREAD

**Issue by comicfans** [neovim/neovim#12276]
- `nvim --version`:NVIM v0.5.0-473-gc7d3630e2
- `vim -u DEFAULTS` (version: ) behaves differently? not tried
- Operating system/version: archlinux x64
- Terminal name/version: konsole ,ssh to remote server running tmux
- `$TERM`:screen  (I'm running tmux)

### Steps to reproduce using `nvim -u NORC`
can't reproduce
### Actual behaviour
1. using konsole , ssh to anther host, running tmux, and editing file in nvim
2. create another konsole tab,  ssh to same host, using tmux attach to attach to same tmux instance
3. using ctrl-b c create a new tmux tab (and focus in this new tab),  using ctrl+ +/- (which is konsole hotkey to resize font size), that leads terminal size changed
4. observed nvim crashed

asan report:
```
=================================================================
==nvim==2486==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61c000082040 at pc 0x0000004f4cdc bp 0x7f049ef333c0 sp 0x7f049ef32b70
WRITE of size 29 at 0x61c000082040 thread T1
    #0 0x4f4cdb in __asan_memcpy /home/wangxinyu/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:22:3
    #1 0xbb913b in tui_raw_line /home/wangxinyu/neovim/build/../src/nvim/tui/tui.c:1319:5
    #2 0xbdc062 in ui_bridge_raw_line_event /home/wangxinyu/neovim/build/../src/nvim/ui_bridge.c:157:3
    #3 0x718fc3 in multiqueue_process_events /home/wangxinyu/neovim/build/../src/nvim/event/multiqueue.c:157:7
    #4 0x716869 in loop_poll_events /home/wangxinyu/neovim/build/../src/nvim/event/loop.c:70:3
    #5 0xbba083 in tui_main /home/wangxinyu/neovim/build/../src/nvim/tui/tui.c:448:5
    #6 0xbd9a38 in ui_thread_run /home/wangxinyu/neovim/build/../src/nvim/ui_bridge.c:104:3
    #7 0x7f04a2ca24ce in start_thread (/usr/lib/libpthread.so.0+0x94ce)
    #8 0x7f04a2a4a2d2 in clone (/usr/lib/libc.so.6+0xff2d2)

0x61c000082040 is located 64 bytes to the left of 1856-byte region [0x61c000082080,0x61c0000827c0)
allocated by thread T1 here:
    #0 0x4f6060 in calloc /home/wangxinyu/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cc:154:3
    #1 0x8efdd2 in xcalloc /home/wangxinyu/neovim/build/../src/nvim/memory.c:133:15
    #2 0xbc521c in ugrid_resize /home/wangxinyu/neovim/build/../src/nvim/ugrid.c:33:22
    #3 0xbb530e in tui_grid_resize /home/wangxinyu/neovim/build/../src/nvim/tui/tui.c:895:3
    #4 0xbd9f87 in ui_bridge_grid_resize_event /home/wangxinyu/neovim/build/src/nvim/auto/ui_events_bridge.generated.h:159:3
    #5 0x718fc3 in multiqueue_process_events /home/wangxinyu/neovim/build/../src/nvim/event/multiqueue.c:157:7
    #6 0x716869 in loop_poll_events /home/wangxinyu/neovim/build/../src/nvim/event/loop.c:70:3
    #7 0xbba083 in tui_main /home/wangxinyu/neovim/build/../src/nvim/tui/tui.c:448:5
    #8 0xbd9a38 in ui_thread_run /home/wangxinyu/neovim/build/../src/nvim/ui_bridge.c:104:3
    #9 0x7f04a2ca24ce in start_thread (/usr/lib/libpthread.so.0+0x94ce)

Thread T1 created by T0 here:
    #0 0x493390 in pthread_create /home/wangxinyu/llvm-project/compiler-rt/lib/asan/asan_interceptors.cc:209:3
    #1 0xd07ce2 in uv_thread_create_ex /home/wangxinyu/neovim/.deps/build/src/libuv/src/unix/thread.c:258:9

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/wangxinyu/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cc:22:3 in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c38800083b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c38800083c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c38800083d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c38800083e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c38800083f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3880008400: fa fa fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa
  0x0c3880008410: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3880008420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3880008430: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3880008440: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3880008450: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==nvim==2486==ABORTING
```

**Comment by glacambre** [comment]
@comicfans Are you still able to reproduce this crash on master/nightly?

**Comment by comicfans** [comment]
I've retried with v0.5.0-dev+1357-g192f89ea1-dirty, unable to reproduce such crash

**Comment by glacambre** [comment]
Great, thanks! Let's close this issue then :).
