### ISSUE TITLE
LSP Ocaml throws error highlight out of range

### ISSUE THREAD

**Issue by entropitor** [neovim/neovim#12307]
- `nvim --version`: a0a9dae
- Operating system/version: Mac OS X
- Terminal name/version: alacritty
- `$TERM`: xterm256-color

### Steps to reproduce using `nvim -u NORC`
Open an ocaml file with neovim and use `nvim_lsp` configs for ocaml. 

You get an error:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.
lua:661: Line number outside range
```

### Actual behaviour
An error

### Expected behaviour
The highlight works until end of line / file (whichever one is out of range)

**Comment by h-michael** [comment]
@entropitor Please show minimal codes.
And would you show us vim-lsp.log?

`:lua print(vim.lsp.get_log_path())`

**Comment by entropitor** [comment]
I'm getting the following log lines for any ocaml file for me

```
[ ERROR ] 2020-05-13T13:56:24Z+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/.bin/ocaml-language-server"	"stderr"	"(node:14694) UnhandledPromiseRejectionWarning: Error: MethodNotFound\n    at new ResponseError (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/messages.js:46:28)\n    at handleResponse (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/main.js:430:48)\n    at processMessageQueue (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/main.js:258:17)\n    at Immediate.<anonymous> (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/main.js:242:13)\n    at processImmediate (internal/timers.js:456:21)\n"
[ ERROR ] 2020-05-13T13:56:24Z+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/.bin/ocaml-language-server"	"stderr"	"(node:14694) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)\n"
[ ERROR ] 2020-05-13T13:56:24Z+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/.bin/ocaml-language-server"	"stderr"	"(node:14694) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n"
[ ERROR ] 2020-05-13T13:56:26Z+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/.bin/ocaml-language-server"	"stderr"	"(node:14694) UnhandledPromiseRejectionWarning: Error: MethodNotFound\n    at new ResponseError (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/messages.js:46:28)\n    at handleResponse (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/main.js:430:48)\n    at processMessageQueue (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/main.js:258:17)\n    at Immediate.<anonymous> (/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/vscode-jsonrpc/lib/main.js:242:13)\n    at processImmediate (internal/timers.js:456:21)\n"
[ ERROR ] 2020-05-13T13:56:26Z+0200 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:317 ]	"rpc"	"/Users/jens/.cache/nvim/nvim_lsp/ocamlls/node_modules/.bin/ocaml-language-server"	"stderr"	"(node:14694) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)\n"
```
