### ISSUE TITLE
Core dump in file_search.c when searching file with [I and large &path

### ISSUE THREAD

**Issue by romgrk** [neovim/neovim#12397]
- `nvim --version`: NVIM v0.5.0-522-g044eb56ed
- `vim -u DEFAULTS` (version: ) behaves differently? 
- Operating system/version: archlinux

### Steps to reproduce using `nvim -u NORC`

```
nvim --clean
:set path=,,./*;,**2;,/usr/include
:e vendor/tree-sitter/lib/include/tree_sitter/api.h
/TSTree<CR>
[I
```

### Actual behaviour
 - core dump

### Expected behaviour
 - file search

### core dump

```
#0  0x00007f73109ee355 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f73107da780 (LWP 2716455))]
(gdb) bt
#0  0x00007f73109ee355 in raise () from /usr/lib/libc.so.6
#1  0x00007f73109d7853 in abort () from /usr/lib/libc.so.6
#2  0x00007f73109d7727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007f73109e6936 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000564b7e90ca57 in vim_findfile (search_ctx_arg=0x564b8093ea40) at ../src/nvim/file_search.c:853
#5  0x0000564b7e90dcf2 in find_file_in_path_option (ptr=0x564b8107d1ba "stddef.h>", len=8, options=26, 
    first=1, path_option=0x564b80539730 ",,./*;,**2;,/usr/include", find_what=2, 
    rel_fname=0x564b80b81770 "/usr/include/uv.h", suffixes=0x564b80b72860 "")
    at ../src/nvim/file_search.c:1513
#6  0x0000564b7e90d898 in find_file_in_path (ptr=0x564b8107d1ba "stddef.h>", len=8, options=26, first=1, 
    rel_fname=0x564b80b81770 "/usr/include/uv.h") at ../src/nvim/file_search.c:1349
#7  0x0000564b7e9d97d2 in find_file_name_in_path (ptr=0x564b8107d1ba "stddef.h>", len=8, options=26, 
    count=1, rel_fname=0x564b80b81770 "/usr/include/uv.h") at ../src/nvim/path.c:1649
#8  0x0000564b7ead3de7 in file_name_in_line (line=0x564b8107d1b8 " <stddef.h>", col=0, options=26, 
    count=1, rel_fname=0x564b80b81770 "/usr/include/uv.h", file_lnum=0x0) at ../src/nvim/window.c:6160
#9  0x0000564b7ea2d104 in find_pattern_in_path (ptr=0x564b80cb0c3b "setup_transfer_buffer(node_count);", 
    dir=0, len=21, whole=true, skip_comments=false, type=1, count=1, action=4, start_lnum=1, 
    end_lnum=765) at ../src/nvim/search.c:4463
#10 0x0000564b7e9a2722 in nv_brackets (cap=0x7ffd17156458) at ../src/nvim/normal.c:5522
#11 0x0000564b7e9986a8 in normal_execute (state=0x7ffd171563d0, key=91) at ../src/nvim/normal.c:1136
#12 0x0000564b7ea6ae03 in state_enter (s=0x7ffd171563d0) at ../src/nvim/state.c:69
#13 0x0000564b7e99695f in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#14 0x0000564b7e952dd6 in main (argc=1, argv=0x7ffd17156768) at ../src/nvim/main.c:569
```

```
┌──../src/nvim/file_search.c─────────────────────────────────────────────────────────────────────────────┐
│   838                                 &search_ctx->ffsc_visited_list->ffvl_visited_list,               │
│   839                                 file_path                                                        │
│   840                                 , (char_u *)""                                                   │
│   841                                 ) == FAIL) {                                                     │
│   842                           if (p_verbose >= 5) {                                                  │
│   843                             verbose_enter_scroll();                                              │
│   844                             smsg("Already: %s", file_path);                                      │
│   845                             msg_puts("\n");  // don't overwrite this either                      │
│   846                             verbose_leave_scroll();                                              │
│   847                           }                                                                      │
│   848                           continue;                                                              │
│   849                         }                                                                        │
│   850         #endif                                                                                   │
│   851                                                                                                  │
│   852                         /* push dir to examine rest of subdirs later */                          │
│  >853                         assert(i < UCHAR_MAX - 1);                                               │
│   854                         stackp->ffs_filearray_cur = (char_u)(i + 1);                             │
│   855                         ff_push(search_ctx, stackp);                                             │
│   856                                                                                                  │
│   857                         if (!path_with_url((char *)file_path))                                   │
│   858                           simplify_filename(file_path);                                          │
│   859                         if (os_dirname(ff_expand_buffer, MAXPATHL)                               │
│   860                             == OK) {                                                             │
│   861                           p = path_shorten_fname(file_path,                                      │
│   862                               ff_expand_buffer);                                                 │
│   863                           if (p != NULL)                                                         │
│   864                             STRMOVE(file_path, p);                                               │
│   865                         }                                                                        │
│   866         #ifdef FF_VERBOSE                                                                        │
│   867                         if (p_verbose >= 5) {                                                    │
│   868                           verbose_enter_scroll();                                                │
│   869                           smsg("HIT: %s", file_path);                                            │
└────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by TamaMcGlinn** [comment]
Is there any hope this will get fixed? I have been facing this crash every day.

**Comment by justinmk** [comment]
coverity:

```
** CID 352688:    (STRING_NULL)
/src/nvim/path.c: 1704 in find_file_name_in_path()
/src/nvim/path.c: 1721 in find_file_name_in_path()


________________________________________________________________________________________________________
*** CID 352688:    (STRING_NULL)
/src/nvim/path.c: 1704 in find_file_name_in_path()
1698       }
1699     
1700       if ((options & FNAME_INCL) && *curbuf->b_p_inex != NUL) {
1701         tofree = (char_u *)eval_includeexpr((char *)ptr, len);
1702         if (tofree != NULL) {
1703           ptr = tofree;
>>>     CID 352688:    (STRING_NULL)
>>>     Passing unterminated string "(char *)ptr" to "strlen", which expects a null-terminated string.
1704           len = STRLEN(ptr);
1705         }
1706       }
1707     
1708       if (options & FNAME_EXP) {
1709         file_name = find_file_in_path(ptr, len, options & ~FNAME_MESS, true,
/src/nvim/path.c: 1721 in find_file_name_in_path()
1715          */
1716         if (file_name == NULL
1717             && !(options & FNAME_INCL) && *curbuf->b_p_inex != NUL) {
1718           tofree = (char_u *)eval_includeexpr((char *)ptr, len);
1719           if (tofree != NULL) {
1720             ptr = tofree;
>>>     CID 352688:    (STRING_NULL)
>>>     Passing unterminated string "(char *)ptr" to "strlen", which expects a null-terminated string.
1721             len = STRLEN(ptr);
1722             file_name = find_file_in_path(ptr, len, options & ~FNAME_MESS,
1723                                           TRUE, rel_fname);
1724           }
1725         }
1726         if (file_name == NULL && (options & FNAME_MESS)) {

** CID 331356:  Memory - corruptions  (OVERRUN)
```
