### ISSUE TITLE
[Segfault] when in terminal mode and navigating to a file

### ISSUE THREAD

**Issue by vito-c** [neovim/neovim#13424]
- `nvim --version`: aec61074a (head and latest release)
- `vim -u DEFAULTS` (version: ) behaves differently?
- Operating system/version:
- Terminal name/version: iTerm latest version
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
1. open a file in a scala  project  (it might also  happen in other projects? I'm not sure)
2. open a terminal buffer
3. run sbt in a terminal  buffer (sbt is the program used to compile scala projects)
4. compile a project
5. switch to another file in the current terminal  buffer 
6. You will then be greeted with the following sefault.
```

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==4366==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010e77f010 bp 0x7ffee2c4d130 sp 0x7ffee2c4d0e0 T0)
==4366==The signal is caused by a WRITE memory access.
==4366==Hint: address points to the zero page.
#0 0x10e77f010 in erase_internal screen.c:278
#1 0x10e77e717 in erase screen.c:299
#2 0x10e77f756 in erase state.c:47
#3 0x10e781711 in on_csi state.c:1076
#4 0x10e77c79d in do_csi parser.c:36
#5 0x10e77c47d in vterm_input_write parser.c:278
#6 0x10e40dd30 in terminal_receive terminal.c:585
#7 0x10d24ea80 in on_channel_output channel.c:588
#8 0x10d24bf19 in on_channel_data channel.c:566
#9 0x10d5f2d3b in read_event rstream.c:194
#10 0x10d5f1df3 in invoke_read_cb rstream.c:207
#11 0x10d5f081e in read_cb rstream.c:135
#12 0x10e770a25 in uv__stream_io stream.c:1306
#13 0x10e778877 in uv__io_poll kqueue.c
#14 0x10e767000 in uv_run core.c:375
#15 0x10d5d9cb3 in loop_poll_events loop.c:62
#16 0x10de5c49e in inbuf_poll input.c:403
#17 0x10de5bfff in os_inchar input.c:118
#18 0x10e324624 in state_enter state.c:54
#19 0x10dc79cd5 in normal_enter normal.c:463
#20 0x10da072f0 in main main.c:554
#21 0x7fff6f4b1cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

==4366==Register values:
rax = 0x0000000000000000  rbx = 0x00006030002d7aa0  rcx = 0x000060d000076e50  rdx = 0x0000000000000000
rdi = 0x000060d000076e50  rsi = 0x00000000fffffffc  rbp = 0x00007ffee2c4d130  rsp = 0x00007ffee2c4d0e0
r8 = 0x000060d000076e50   r9 = 0x0000000000000000  r10 = 0x00006130000af950  r11 = 0x0000000000000000
r12 = 0x000060d000076ec8  r13 = 0xfffffffdfffffffc  r14 = 0x00000000000000d2  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV screen.c:278 in erase_internal
==4366==ABORTING
Abort trap: 6
```

### Actual behaviour
Sefaults when switching from a terminal  buffer to another file buffer

### Expected behaviour
not to segfault :D

**Comment by matu3ba** [comment]
@vito-c Can you provide a full example with minimal code and all necessary commands as hinted in the new bug template?
I regularly compile stuff in a REPL and have no problems.

If there is no activity in 3-4 weeks, I would suggest to close this due to insufficient information.

**Comment by vito-c** [comment]
I think this was more along the lines of sbt/java not playing well with the REPL after I updated sbt this issue went away so I will close for now. Thanks!
