### ISSUE TITLE
LSP: add workaround for servers that expect (or ignore disabling) dynamicRegistration

### ISSUE THREAD

**Issue by mjlbach** [neovim/neovim#13448]
This affects yaml-language-server, pyright, jdtls, and tsserver (thus far)

With node 15, pyright will now crash when it sends a dynamicRegistration request "client/registerCapability". There are currently no handlers for this command in neovim's lsp implementation, and in theory this should be fine as on initialization all dynamicRegistration capabilities are set to False.

There's some discussion of this with sublime here: https://github.com/sublimelsp/LSP/pull/911

For reference, they ended up just adding dynamicRegistration capability. 

Prior to node 15, this would result in an unhandled promise, which would not interfere with the language server's operation.

```
[ ERROR ] 2020-12-03T14:24:42-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"pyright-langserver"	"stderr"	"(node:8028) UnhandledPromiseRejectionWarning: Error: MethodNotFound\n    at /Users/michael/.npm-packages/lib/node_modules/pyright/dist/vendor.js:2:157227\n    at /Users/michael/.npm-packages/lib/node_modules/pyright/dist/vendor.js:2:157521\n    at Immediate.<anonymous> (/Users/michael/.npm-packages/lib/node_modules/pyright/dist/vendor.js:2:157884)\n    at processImmediate (internal/timers.js:461:21)\n(Use `node --trace-warnings ...` to show where the warning was created)\n"
[ ERROR ] 2020-12-03T14:24:42-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"pyright-langserver"	"stderr"	"(node:8028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)\n"
[ ERROR ] 2020-12-03T14:24:42-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"pyright-langserver"	"stderr"	"(node:8028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\n"
[ DEBUG ] 2020-12-03T14:24:42-0800 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "Registering request handler for workspace/didChangeWorkspaceFolders failed.",    type = 3  }}
[ DEBUG ] 2020-12-03T14:24:42-0800 ] ...neovim-nightly-master/share/nvim/runtime/lua/vim/lsp.lua:471 ]	"notification"	"window/logMessage"	{  message = "Registering request handler for workspace/didChangeWorkspaceFolders failed.",  type = 3}
```

Now, in node 15, unhandled promises terminate nodejs, which means pyright will now crash.

In the long term, language servers should be respecting the dynamicRegistration setting on initialization, I expect pyright doesn't do this as it's primarily developed for vscode, and based on prior interactions I think any push to fix this will have to be from the community side. Lsp-mode in emacs has dynamicRegistration, so it also does not impact

To fix this, there are three options.

1) Implement a placeholder handlers per server that ignores the registerCapability message from the language server
```
    handlers = {
      ['client/registerCapability'] = function(_, _, _, _)
        return {
          result = nil;
          error = nil;
        }
      end
    };
```
2) Implement a global ignore list for handlers not currently implemented in neovim-lsp, this could be done in nvim-lspconfig or in core
3) Implement the dynamicRegistration functionality in core

Edit: Just to be sure we're actually sending all dynamicRegistration = false (Which should be the default anwyays), you can apply  this patch
```patch
diff --git a/runtime/lua/vim/lsp/protocol.lua b/runtime/lua/vim/lsp/protocol.lua
index fd86d8bb9..4f0b22b72 100644
--- a/runtime/lua/vim/lsp/protocol.lua
+++ b/runtime/lua/vim/lsp/protocol.lua
@@ -619,18 +619,8 @@ function protocol.make_client_capabilities()
         -- Send textDocument/didSave after saving (BufWritePost)
         didSave = true;
       };
-      codeAction = {
+      textDocumentSync = {
         dynamicRegistration = false;
-
-        codeActionLiteralSupport = {
-          codeActionKind = {
-            valueSet = (function()
-              local res = vim.tbl_values(protocol.CodeActionKind)
-              table.sort(res)
-              return res
-            end)();
-          };
-        };
       };
       completion = {
         dynamicRegistration = false;
@@ -658,22 +648,11 @@ function protocol.make_client_capabilities()
         -- TODO(tjdevries): Implement this
         contextSupport = false;
       };
-      declaration = {
-        linkSupport = true;
-      };
-      definition = {
-        linkSupport = true;
-      };
-      implementation = {
-        linkSupport = true;
-      };
-      typeDefinition = {
-        linkSupport = true;
-      };
       hover = {
         dynamicRegistration = false;
         contentFormat = { protocol.MarkupKind.Markdown; protocol.MarkupKind.PlainText };
       };
+
       signatureHelp = {
         dynamicRegistration = false;
         signatureInformation = {
@@ -683,6 +662,22 @@ function protocol.make_client_capabilities()
           -- };
         };
       };
+      declaration = {
+        dynamicRegistration = false;
+        linkSupport = true;
+      };
+      definition = {
+        dynamicRegistration = false;
+        linkSupport = true;
+      };
+      typeDefinition = {
+        dynamicRegistration = false;
+        linkSupport = true;
+      };
+      implementation = {
+        dynamicRegistration = false;
+        linkSupport = true;
+      };
       references = {
         dynamicRegistration = false;
       };
@@ -702,12 +697,69 @@ function protocol.make_client_capabilities()
         };
         hierarchicalDocumentSymbolSupport = true;
       };
+      codeAction = {
+        dynamicRegistration = false;
+
+        codeActionLiteralSupport = {
+          codeActionKind = {
+            valueSet = (function()
+              local res = vim.tbl_values(protocol.CodeActionKind)
+              table.sort(res)
+              return res
+            end)();
+          };
+        };
+      };
+      codeLens = {
+        dynamicRegistration = false;
+      };
+      documentLink = {
+        dynamicRegistration = false;
+      };
+      colorProvider = {
+        dynamicRegistration = false;
+      };
+      formatting = {
+        dynamicRegistration = false;
+      };
+      rangeFormatting = {
+        dynamicRegistration = false;
+      };
+      onTypeFormatting = {
+        dynamicRegistration = false;
+      };
       rename = {
         dynamicRegistration = false;
         prepareSupport = true;
       };
+      foldingRange = {
+        dynamicRegistration = false;
+      };
+      selectionRange = {
+        dynamicRegistration = false;
+      };
+      linkedEditingRange = {
+        dynamicRegistration = false;
+      };
+      callHierarchy = {
+        dynamicRegistration = false;
+      };
+      semanticTokens = {
+        dynamicRegistration = false;
+      };
     };
+
     workspace = {
+      applyEdit = true;
+
+      didChangeConfiguration = {
+        dynamicRegistration = false;
+      };
+
+      didChangeWatchedFiles = {
+        dynamicRegistration = false;
+      };
+
       symbol = {
         dynamicRegistration = false;
         symbolKind = {
@@ -721,11 +773,27 @@ function protocol.make_client_capabilities()
         };
         hierarchicalWorkspaceSymbolSupport = true;
       };
+
+      executeCommand = {
+        dynamicRegistration = false;
+      };
+
       workspaceFolders = true;
-      applyEdit = true;
-    };
-    callHierarchy = {
-      dynamicRegistration = false;
+
+      configuration = false;
+
+      semanticTokens = {
+        dynamicRegistration = false;
+      };
+
+      codeLens = {
+        dynamicRegistration = false;
+      };
+
+      fileOperations = {
+        dynamicRegistration = false;
+      };
+
     };
     experimental = nil;
   }
@@ -746,7 +814,7 @@ export interface DocumentFilter {
   --- `{}` to group conditions (e.g. `**​/*.{ts,js}` matches all TypeScript and JavaScript files)
   --- `[]` to declare a range of characters to match in a path segment (e.g., `example.[0-9]` to match on `example.0`, `example.1`, …)
   --- `[!...]` to negate a range of characters to match in a path segment (e.g., `example.[!0-9]` to match on `example.a`, `example.b`, but not `example.0`)
-  pattern?: string;
+  patter?: string;
 }
 --]=]
 ```

**Comment by quantum-booty** [comment]
I have downgraded node to v14, but its still not working. No completions or anything.

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: sqlls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: r_language_server: configuration checked.
  - INFO: bashls: configuration checked.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/home/henryw/virtualenvs/data_sci/bin/python"
  - INFO: Executable: /home/henryw/virtualenvs/data_sci/bin/python
  - INFO: Python version: 3.9.0
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - INFO: $VIRTUAL_ENV is set to: /home/henryw/virtualenvs/data_sci
  - INFO: Python version: 3.9.0
  - OK: $VIRTUAL_ENV provides :!python.


## Node.js provider (optional)
  - INFO: Node.js: v14.15.1
  - INFO: Nvim node.js host: /home/henryw/.nvm/versions/node/v14.15.1/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0
```

**Comment by mjlbach** [comment]
Are you using this PR? If this is about debugging why pyright isn't working on your system you should ask on IRC or gitter and provide your lsp log

**Comment by quantum-booty** [comment]
> Are you using the PR I made to close this? If this is about debugging why pyright isn't working on your system you should ask on IRC or gitter and provide your lsp log
Sorry I thought the reason why pyright couldn't work is because I was using node v15, and this is the thread that tracks this issue.

**Comment by mjlbach** [comment]
The issue described here is a crash of various language servers, pyright included, after an unhandled promise due to the missing callback "client/registerCapability." I have a strong suspicion that is not the problem with your configuration, and if you can provide a debug log to the contrary (that matches that of the issue), that would be great. If it doesn't match the issue, then IRC is a better venue for us to figure out what is unique about your configuration.

**Comment by quantum-booty** [comment]
@mjlbach Thank you, I have posted the error log [here](https://github.com/neovim/nvim-lspconfig/issues/441), could you please help me to debug this?

**Comment by mjlbach** [comment]
Filed an upstream issue, seems to not be the fault of pyright but in vscode-languageserver-node which would affect a lot of nodejs based language servers https://github.com/microsoft/vscode-languageserver-node/issues/713

**Comment by mjlbach** [comment]
Closing because https://github.com/neovim/nvim-lspconfig/pull/471 was merged, but dyamicRegistration is still causing headaches.
