### ISSUE TITLE
Memory leak & no error reported from uncaught exception in autocmd

### ISSUE THREAD

**Issue by seandewar** [neovim/neovim#13490]
- `nvim --version`: **Latest (NVIM v0.5.0-dev+918-g4383c0f95)**
- `vim -u DEFAULTS` behaves differently? **Yes (Vim behaves correctly)**
- Operating system/version: **WSL running Ubuntu 20.04.1 LTS**
- Terminal name/version: **Windows Terminal 1.4.3243.0 / tmux 3.0a**
- `$TERM`: **`xterm-256color` / `tmux-256color`**

### Steps to reproduce using `nvim -u NORC`
Source this:
```vim
au BufWinEnter * throw 'not today'
" the try/endtry is used to also trigger the leak
try
  new
endtry
```
Alternatively, run `nvim --clean -c "au BufWinEnter * th 0" -c "try|new|endt|qa!"` with LSAN to get a quick report.

### Actual behaviour
No exception reported, plus a memory leak (unless the `try`/`endtry` is omitted).

I haven't had much time to check, but my suspicion is that PR #7881 might be the culprit.
A recursive call to `do_cmdline()` sets `current_exception` to `NULL` (`ex_docmd.c:408`),
potentially before it's handled and freed within the block starting at `ex_docmd.c:815` inside
another recursive call deeper in the stack. Commands such as `:new`, `:edit`, etc. can trigger this.

From LSAN:
```
=================================================================
==29553==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x4d558d in malloc (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x4d558d)
    #1 0x115f982 in try_malloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:71:15
    #2 0x115fb5c in xmalloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:105:15
    #3 0xd04838 in throw_exception /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:466:10
    #4 0xd172f9 in ex_throw /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:1153:9
    #5 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #6 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #7 0x708ffe in apply_autocmds_group /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1611:5
    #8 0x70f317 in apply_autocmds_retval /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1311:18
    #9 0x71b199 in open_buffer /home/sean/projects/3rdparty/neovim/build/../src/nvim/buffer.c:336:5
    #10 0xbc1794 in do_ecmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds.c:2588:24
    #11 0xcaccc9 in do_exedit /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:7232:11
    #12 0xcab964 in ex_splitview /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:6967:5
    #13 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #14 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #15 0xc3d6e1 in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2877:3
    #16 0xc38024 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2547:14
    #17 0xc38735 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2528:3
    #18 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #19 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #20 0xc5a283 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:287:10
    #21 0xfd8b9b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1698:5
    #22 0xfc654a in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:500:5
    #23 0x7f04190010b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 33 byte(s) in 1 object(s) allocated from:
    #0 0x4d558d in malloc (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x4d558d)
    #1 0x115f982 in try_malloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:71:15
    #2 0x115fb5c in xmalloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:105:15
    #3 0x1160111 in xmallocz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:182:15
    #4 0x116027e in xmemdupz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:200:17
    #5 0x116180e in xstrdup /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:419:10
    #6 0x1949ade in vim_strsave /home/sean/projects/3rdparty/neovim/build/../src/nvim/strings.c:58:20
    #7 0xd04d11 in throw_exception /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:478:22
    #8 0xd172f9 in ex_throw /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:1153:9
    #9 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #10 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #11 0x708ffe in apply_autocmds_group /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1611:5
    #12 0x70f317 in apply_autocmds_retval /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1311:18
    #13 0x71b199 in open_buffer /home/sean/projects/3rdparty/neovim/build/../src/nvim/buffer.c:336:5
    #14 0xbc1794 in do_ecmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds.c:2588:24
    #15 0xcaccc9 in do_exedit /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:7232:11
    #16 0xcab964 in ex_splitview /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:6967:5
    #17 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #18 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #19 0xc3d6e1 in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2877:3
    #20 0xc38024 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2547:14
    #21 0xc38735 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2528:3
    #22 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #23 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #24 0xc5a283 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:287:10
    #25 0xfd8b9b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1698:5
    #26 0xfc654a in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:500:5
    #27 0x7f04190010b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 10 byte(s) in 1 object(s) allocated from:
    #0 0x4d558d in malloc (/home/sean/projects/3rdparty/neovim/build/bin/nvim+0x4d558d)
    #1 0x115f982 in try_malloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:71:15
    #2 0x115fb5c in xmalloc /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:105:15
    #3 0x1160111 in xmallocz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:182:15
    #4 0x116027e in xmemdupz /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:200:17
    #5 0x116180e in xstrdup /home/sean/projects/3rdparty/neovim/build/../src/nvim/memory.c:419:10
    #6 0x8f7055 in eval_to_string_skip /home/sean/projects/3rdparty/neovim/build/../src/nvim/eval.c:811:14
    #7 0xd171bf in ex_throw /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_eval.c:1143:13
    #8 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #9 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #10 0x708ffe in apply_autocmds_group /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1611:5
    #11 0x70f317 in apply_autocmds_retval /home/sean/projects/3rdparty/neovim/build/../src/nvim/autocmd.c:1311:18
    #12 0x71b199 in open_buffer /home/sean/projects/3rdparty/neovim/build/../src/nvim/buffer.c:336:5
    #13 0xbc1794 in do_ecmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds.c:2588:24
    #14 0xcaccc9 in do_exedit /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:7232:11
    #15 0xcab964 in ex_splitview /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:6967:5
    #16 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #17 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #18 0xc3d6e1 in do_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2877:3
    #19 0xc38024 in cmd_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2547:14
    #20 0xc38735 in ex_source /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_cmds2.c:2528:3
    #21 0xc6b7a4 in do_one_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:1955:5
    #22 0xc54443 in do_cmdline /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:601:20
    #23 0xc5a283 in do_cmdline_cmd /home/sean/projects/3rdparty/neovim/build/../src/nvim/ex_docmd.c:287:10
    #24 0xfd8b9b in exe_commands /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:1698:5
    #25 0xfc654a in main /home/sean/projects/3rdparty/neovim/build/../src/nvim/main.c:500:5
    #26 0x7f04190010b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 91 byte(s) leaked in 3 allocation(s).
```

### Expected behaviour
This message, courtesy of Vim:
```
Error detected while processing BufWinEnter Autocommands for "*":
E605: Exception not caught: not today
```

**Comment by janlazo** [comment]
https://github.com/vim/vim/commit/438d176e35c16d56ff3bb7a80300197ce5a30c4f was not ported yet.

**Comment by zeertzjq** [comment]
Porting <https://github.com/vim/vim/commit/438d176e35c16d56ff3bb7a80300197ce5a30c4f> does not fix this bug.
