### ISSUE TITLE
Calling :q while there is a scheduled function that calls 'vsplit | q' causes a core dump

### ISSUE THREAD

**Issue by apppppppple** [neovim/neovim#14379]
- `nvim --version`:
```
NVIM v0.5.0-dev+1260-ga6504ec33
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/apple/.cache/yay/neovim-git/src/build/config -I/home/apple/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/apple/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/apple/.cache/yay/neovim-git/src/build/include
Compiled by apple

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- `vim -u DEFAULTS` (version: ) behaves differently? N/A afaik
- Operating system/version:
Arch Linux x86_64   5.11.13-arch1-1
glibc 2.33-4
- Terminal name/version:
zsh 5.8.1
- `$TERM`:
alacritty

### Steps to reproduce using `nvim -u NORC`

```vim
nvim -u NORC --cmd "lua vim.schedule(function() vim.cmd('vsplit | q') end)" +q
nvim -u NORC --cmd "lua vim.schedule(function() vim.cmd('vsplit | q') end) vim.cmd('q')" also works
```

### Actual behaviour
Neovim coredumps somewhere in libuv.
### Expected behaviour
Neovim quits normally.

There isn't usually a reason to be calling `:q` right after startup but in my case I'm using the `vsplit | q` to force certain plugins to load early and I'm using `+q` to benchmark my config startup with hyperfine. (As an aside, is there a way to quit w/o finishing scheduled commands first? I don't care too much about how long the commands take, but I am interested in the time it takes to schedule them)

**Comment by zeertzjq** [comment]
In v0.9 this is still reproducible with:
```sh
echo | nvim --clean -es --cmd "lua vim.schedule(function() vim.cmd('vsplit | q') end)" +q
```

**Comment by zeertzjq** [comment]
Stacktrace:
```
=================================================================
==3518820==ERROR: AddressSanitizer: ABRT on unknown address 0x03e80035b164 (pc 0x7efe2f29890c bp 0x7fff68917e10 sp 0x7fff68917dd0 T0)
    #0 0x7efe2f29890c in __pthread_kill_implementation /usr/src/debug/glibc/glibc/nptl/pthread_kill.c:44:76
    #1 0x7efe2f23e39f in raise /usr/src/debug/glibc/glibc/signal/../sysdeps/posix/raise.c:26:13
    #2 0x7efe2f225579 in abort /usr/src/debug/glibc/glibc/stdlib/abort.c:77:3
    #3 0x7efe2f2254e2 in __assert_fail_base /usr/src/debug/glibc/glibc/assert/assert.c:118:3
    #4 0x55d9ccd958f1 in uv__close **/.deps/build/src/libuv/src/unix/core.c:646:3
    #5 0x55d9ccda0a36 in uv__loop_close **/.deps/build/src/libuv/src/unix/loop.c:182:5
    #6 0x55d9ccd93a3a in uv_loop_close **/.deps/build/src/libuv/src/uv-common.c:889:3
    #7 0x55d9cbc3ab82 in stream_set_blocking **/src/nvim/event/stream.c:39:3
    #8 0x55d9cc0160d1 in os_exit **/src/nvim/main.c:690:5
    #9 0x55d9cc01c359 in getout **/src/nvim/main.c:839:3
    #10 0x55d9cbcf74b3 in ex_quit **/src/nvim/ex_docmd.c:4880:7
    #11 0x55d9cbcbcc3f in execute_cmd0 **/src/nvim/ex_docmd.c:1762:7
    #12 0x55d9cbc9fa15 in do_one_cmd **/src/nvim/ex_docmd.c:2392:7
    #13 0x55d9cbc94fd6 in do_cmdline **/src/nvim/ex_docmd.c:679:20
    #14 0x55d9cbc99058 in do_cmdline_cmd **/src/nvim/ex_docmd.c:377:10
    #15 0x55d9cc01ac38 in exe_commands **/src/nvim/main.c:1957:5
    #16 0x55d9cc008da7 in main **/src/nvim/main.c:591:5
    #17 0x7efe2f227634 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #18 0x7efe2f2276e8 in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #19 0x55d9cb424004 in _start (**/build/bin/nvim+0xca3004) (BuildId: a54fcbb165670a2e454b0faa7ae07e8bb6fcef63)

==3518820==Register values:
rax = 0x0000000000000000  rbx = 0x000000000035b164  rcx = 0x00007efe2f29890c  rdx = 0x0000000000000006  
rdi = 0x000000000035b164  rsi = 0x000000000035b164  rbp = 0x00007fff68917e10  rsp = 0x00007fff68917dd0  
 r8 = 0x00007efe2f739000   r9 = 0x0000000000011948  r10 = 0x0000000000100000  r11 = 0x0000000000000246  
r12 = 0x0000000000001000  r13 = 0x000055d9cce028b6  r14 = 0x0000000000000006  r15 = 0x0000000000000086  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT /usr/src/debug/glibc/glibc/nptl/pthread_kill.c:44:76 in __pthread_kill_implementation
==3518820==ABORTING
```

**Comment by zeertzjq** [comment]
Another way to trigger a similar crash:
```sh
echo | nvim --clean -es --cmd "call chanclose(v:stderr)" +q
```
Although this can probably be considered a different issue.

**Comment by zeertzjq** [comment]
Yet another case:
```lua
vim.defer_fn(function()
  vim.cmd('vsplit | quit')
end, 0)
vim.cmd('quit')
```
When using builtin TUI, this causes Nvim to exit with exit code 1 even though there is no error.
