### ISSUE TITLE
Occasional crash (segfault) when closing (and saving) with `nvr --remote-wait` in ml_replace_buf

### ISSUE THREAD

**Issue by rgreenblatt** [neovim/neovim#14447]
NVIM v0.5.0-dev+1178-gf0ace6d41, archlinux, xfce4-terminal

Unfortunately, this issue appears to occur randomly (and rarely); I can't seem to get a reproduction with a minimal init.vim.
Next time this issue occurs, I will try to carefuly reproduce the exact circumstances of the crash to see if it will reproduce and I will comment my results on this issue.
Regardless, I thought I would go ahead and make an issue with just the backtrace in the edge case that someone could already figure out what's going on.
```
#0  0x00007f383320478c in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
#1  0x000055a34b7852d6 in memmove (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>, __dest=<optimized out>, __src=<optimized out>, __len=<optimized out>)
    at /usr/include/bits/string_fortified.h:36
#2  ml_flush_line (buf=buf@entry=0x55a34ea256e0) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/memline.c:2802
#3  0x000055a34b785b16 in ml_replace_buf (buf=0x55a34ea256e0, lnum=4, line=0x55a34e63b540 " ~/d/items   master   gws", copy=<optimized out>)
    at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/memline.c:2453
#4  0x000055a34b785b8d in ml_replace (lnum=<optimized out>, line=<optimized out>, copy=<optimized out>) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/memline.c:2423
#5  0x000055a34b85aa76 in refresh_screen (term=term@entry=0x55a34e9f7210, buf=buf@entry=0x55a34ea256e0) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/terminal.c:1352
#6  0x000055a34b85ab79 in refresh_terminal (term=0x55a34e9f7210) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/terminal.c:1231
#7  0x000055a34b85ad98 in refresh_timer_cb (watcher=<optimized out>, data=<optimized out>) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/terminal.c:1248
#8  0x000055a34b6fb3e9 in time_event (argv=<optimized out>) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/event/time.c:50
#9  0x000055a34b8404c8 in state_handle_k_event () at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/state.c:87
#10 0x000055a34b7aa255 in nv_event (cap=0x7fffa6f6ce38) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/normal.c:8106
#11 0x000055a34b7a2b12 in normal_execute (state=0x7fffa6f6cdb0, key=<optimized out>) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/normal.c:1142
#12 0x000055a34b8403ac in state_enter (s=0x7fffa6f6cdb0) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/state.c:69
#13 0x000055a34b79de81 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/normal.c:463
#14 0x000055a34b77271e in main (argc=-1493774576, argv=<optimized out>) at /home/ryan/.cache/yay/neovim-git/src/neovim-git/src/nvim/main.c:562
```

**Comment by glacambre** [comment]
>Next time this issue occurs, I will try to carefuly reproduce the exact circumstances of the crash to see if it will reproduce and I will comment my results on this issue.

Another thing you could try to do is run all your neovim instances under [rr](https://github.com/rr-debugger/rr). This will record the whole execution of neovim and let you replay it as many times as you need :).

**Comment by jamessan** [comment]
Running a build with ASAN enabled might also be helpful.

**Comment by zeertzjq** [comment]
Does this bug still exist?
