### ISSUE TITLE
SIGSEGV when scrolling in a terminal with i3status after filled

### ISSUE THREAD

**Issue by MultisampledNight** [neovim/neovim#15216]
### Neovim Version

v0.6.0-dev+84-gac5139eae

### Operating system/version:

Arch Linux (rolling release)

### Terminal name/version:

Alacritty 0.8.0 (a1b13e68), also happens on the Linux TTY

### TERM environment variable

`alacritty`, also happens with `linux`

### Installation

Build from repository

### Steps to reproduce

1. Launch up NeoVim (`nvim`, command line arguments don't matter)
2. Make a vertical split (`CTRL-W` + `S`)
3. Type `:term` in any of the two buffers
4. Run any command which causes the terminal buffer to fill up (`ls -la ~`)
5. Launch `i3status`
6. Exit terminal mode (`CTRL-\` + `CTRL-N`), leaving i3status running
7. Shrink the size of the terminal buffer, not sure how much, but sometimes 6 lines less were enough (`CTRL-W` + `24` + `-`)
8. Scroll completely down until the end of the terminal buffer (hold down `J`)
9. Scroll up until the segfault happens (hold down `K`)

### Vim

No, the profile has no influence on the bug

### Expected behavior

i3status continuely printing the status at the bottom "view" of the buffer, and the actual view going up

### Actual behavior

(Isn't the subtitle of the form here a bit misleading? Probably something for another issue)

NeoVim segfaults, causing my shell to print `zsh: segmentation fault (core dumped)` in the color of the status bar, leaving my terminal settings messed up.

Backtrace, made by following the steps of the FAQ:

```c
           PID: 35557 (nvim)
           UID: 1000 (multisn8)
           GID: 985 (users)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-07-29 15:14:30 CEST (11min ago)
  Command Line: /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim-bin/usr/bin/nvim -u NONE
    Executable: /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim-bin/usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (multisn8)
       Boot ID: uwu
    Machine ID: uwu
      Hostname: spacestation
       Storage: /var/lib/systemd/coredump/core.nvim.1000.d91820b7540c4150bd3d7869467af3a8.35557.1627564470000000.zst (present)
     Disk Size: 422.9K
       Message: Process 35557 (nvim) of user 1000 dumped core.
                
                Found module /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim-bin/usr/bin/nvim with build-id: b22e2fec7a2cd2a3b361eacc791865839c2b2675
                Found module linux-vdso.so.1 with build-id: fa889d5e2d990109ed413a89eb5f021aecf7a61b
                Found module libnss_files.so.2 with build-id: 1a36dfc01d3a1010b2ee79766a24a8090a3266d5
                Found module ISO8859-1.so with build-id: d93c01aecc9ab9b0749df9c7d43dd05dd3887577
                Found module libresolv.so.2 with build-id: c915c72668282861a813f7ea3c0780f37b681dc0
                Found module libkeyutils.so.1 with build-id: ac405ddd17be10ce538da3211415ee50c8f8df79
                Found module libkrb5support.so.0 with build-id: c4ee4ad1dc2da57487bc2419b88f1b6873184582
                Found module libcom_err.so.2 with build-id: 86413f38be27bd051645eb9fb0ad0dcace5b2872
                Found module libk5crypto.so.3 with build-id: 632a59ed7c35704d84645e6d1e9873348d1eb802
                Found module libkrb5.so.3 with build-id: c61cb4da63b8a839ee7df99eaf9dbd3d0968534c
                Found module libgssapi_krb5.so.2 with build-id: 9be9d3348399b72b76161a64e6d9fd760b77163a
                Found module libgcc_s.so.1 with build-id: 7f8508bb914546ada778809b64b99d234337d835
                Found module libtirpc.so.3 with build-id: 5bef2adfdee3df283f593b3e2d37b6dac405256a
                Found module ld-linux-x86-64.so.2 with build-id: 040cc3dd10461562f177df39e3be2f3704258c3c
                Found module libc.so.6 with build-id: 4b406737057708c0e4c642345a703c47a61c73dc
                Found module libluajit-5.1.so.2 with build-id: 2559aecfc4b5ac66756fb77424e5f3d384a023be
                Found module libutil.so.1 with build-id: af6d8200064ee6e6a01252884d166b44f0a6121b
                Found module libm.so.6 with build-id: 2b8fd1f869ecab4e0b55e92f2f151897f6818acf
                Found module libpthread.so.0 with build-id: 07c8f95b4f3251d08550217ad8a1f31066229996
                Found module libtree-sitter.so.0 with build-id: 8c660e50eac6348f4485f20bcb1e8f4d76aa2af6
                Found module libunibilium.so.4 with build-id: 1cd9260e1c99a9dd557f5652e7f730a6e132391b
                Found module libtermkey.so.1 with build-id: dce48055fdd2a1a7837bb251c9638e38a4a12129
                Found module libvterm.so.0 with build-id: fe213cf32d56a0c74a898f9583810ea6e4342e2e
                Found module libmsgpackc.so.2 with build-id: fd6c399b20432941854c27e83aaf0ed0634198cc
                Found module librt.so.1 with build-id: 75484da2d6f1515189eefa076e0a40328834cd16
                Found module libnsl.so.2 with build-id: 483b18a0f5dea898b7a147c1662214049d1e5786
                Found module libdl.so.2 with build-id: 5abc547e7b0949f89f3c0e21ab0c8331a7440a8a
                Found module libuv.so.1 with build-id: ee859b0b7168d8b4b6bb06a650b4b53ede6252e0
                Found module libluv.so.1 with build-id: 5b6d9b40493509701eb2e33a95d50ba528616b7d
                Stack trace of thread 35557:
                #0  0x00007f0629784ff5 n/a (libvterm.so.0 + 0x4ff5)
                #1  0x00007f0629785e93 n/a (libvterm.so.0 + 0x5e93)
                #2  0x00007f06297892ef n/a (libvterm.so.0 + 0x92ef)
                #3  0x00007f0629783598 vterm_input_write (libvterm.so.0 + 0x3598)
                #4  0x00005642b947d089 n/a (/home/multisn8/info/projects/shell/quick-neovim-nightly/neovim-bin/usr/bin/nvim + 0x265089)

GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim-bin/usr/bin/nvim...
[New LWP 35557]
[New LWP 35558]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/home/multisn8/info/projects/shell/quick-neovim-nightly/neovim-bin/usr/bin/nvim'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0629784ff5 in ?? () from /usr/lib/libvterm.so.0
[Current thread is 1 (Thread 0x7f0629192780 (LWP 35557))]
(gdb) thread apply all bt full
Thread 2 (Thread 0x7f0628db7640 (LWP 35558)):
#0  0x00007f062948692e in epoll_wait () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f06297ed665 in ?? () from /usr/lib/libuv.so.1
No symbol table info available.
#2  0x00007f06297d9897 in uv_run () from /usr/lib/libuv.so.1
No symbol table info available.
#3  0x00005642b932a3eb in loop_poll_events (loop=0x7f0628db67e0, ms=-1) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/event/loop.c:62
        mode = <optimized out>
        timeout_expired = false
#4  0x00005642b948e98b in tui_main (bridge=0x5642bac9ba90, ui=0x5642bac9b950) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/tui/tui.c:456
        tui_loop = {uv = {data = 0x7f0628db67e0, active_handles = 4, handle_queue = {0x7f0628db6a68, 0x7f0624010f58}, active_reqs = {unused = 0x0, count = 0}, internal_fields = 0x7f0624000b60, stop_flag = 0, flags = 0, backend_fd = 15, pending_queue = {0x7f0628db6828, 0x7f0628db6828}, watcher_queue = {0x7f0628db6838, 0x7f0628db6838}, watchers = 0x7f0624000bb0, nwatchers = 30, nfds = 3, wq = {0x7f0628db6858, 0x7f0628db6858}, wq_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, wq_async = {data = 0x0, loop = 0x7f0628db67e0, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7f0628db6d38, 0x7f0628db6a68}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 20, async_cb = 0x7f06297d5260, queue = {0x7f0628db6d80, 0x7f0628db6990}, pending = 0}, cloexec_lock = {__data = {__readers = 0, __writers = 0, __wrphase_futex = 0, __writers_futex = 0, __pad3 = 0, __pad4 = 0, __cur_writer = 0, __shared = 0, __rwelision = 0 '\000', __pad1 = "\000\000\000\000\000\000", __pad2 = 0, __flags = 0}, __size = '\000' <repeats 55 times>, __align = 0}, closing_handles = 0x0, process_handles = {0x7f0628db6950, 0x7f0628db6950}, prepare_handles = {0x7f0628db6960, 0x7f0628db6960}, check_handles = {0x7f0628db6970, 0x7f0628db6970}, idle_handles = {0x7f0628db6980, 0x7f0628db6980}, async_handles = {0x7f0628db68f8, 0x7f0628db6d80}, async_unused = 0x0, async_io_watcher = {cb = 0x7f06297d9010, pending_queue = {0x7f0628db69b0, 0x7f0628db69b0}, watcher_queue = {0x7f0628db69c0, 0x7f0628db69c0}, pevents = 1, events = 1, fd = 18}, async_wfd = -1, timer_heap = {min = 0x0, nelts = 0}, timer_counter = 18, time = 6333620, signal_pipefd = {16, 17}, signal_io_watcher = {cb = 0x7f06297e35b0, pending_queue = {0x7f0628db6a18, 0x7f0628db6a18}, watcher_queue = {0x7f0628db6a28, 0x7f0628db6a28}, pevents = 1, events = 1, fd = 16}, child_watcher = {data = 0x0, loop = 0x7f0628db67e0, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7f0628db68b0, 0x7f0628db67f0}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 16, signal_cb = 0x0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, emfile_fd = 19, inotify_read_watcher = {cb = 0x0, pending_queue = {0x0, 0x0}, watcher_queue = {0x0, 0x0}, pevents = 0, events = 0, fd = 0}, inotify_watchers = 0x0, inotify_fd = -1}, events = 0x7f0624000d40, thread_events = 0x7f0624000dc0, fast_events = 0x7f0624000d80, children = 0x7f0624000cc0, children_watcher = {data = 0x0, loop = 0x7f0628db67e0, type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7f0628db6c08, 0x7f0628db6d38}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8, signal_cb = 0x0, signum = 0, tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0, dispatched_signals = 0}, children_kill_timer = {data = 0x0, loop = 0x7f0628db67e0, type = UV_TIMER, close_cb = 0x0, handle_queue = {0x7f0628db6ca0, 0x7f0628db6b70}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8, timer_cb = 0x0, heap_node = {0x0, 0x0, 0x0}, timeout = 0, repeat = 0, start_id = 0}, poll_timer = {data = 0x7f0624000e00, loop = 0x7f0628db67e0, type = UV_TIMER, close_cb = 0x0, handle_queue = {0x7f06240116b8, 0x7f0628db6c08}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 8, timer_cb = 0x5642b9329084 <timer_cb>, heap_node = {0x0, 0x0, 0x0}, timeout = 6261392, repeat = 20, start_id = 15}, async = {data = 0x0, loop = 0x7f0628db67e0, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7f0628db6b70, 0x7f0628db68b0}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 12, async_cb = 0x5642b932d510 <async_cb>, queue = {0x7f0628db6990, 0x7f0628db68f8}, pending = 0}, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, recursive = 1}
        data = 0x7f0624000e20
#5  0x00005642b9487488 in ui_thread_run (data=<optimized out>) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/ui_bridge.c:105
        bridge = <optimized out>
#6  0x00007f0629719259 in start_thread () from /usr/lib/libpthread.so.0
No symbol table info available.
#7  0x00007f06294865e3 in clone () from /usr/lib/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7f0629192780 (LWP 35557)):
#0  0x00007f0629784ff5 in ?? () from /usr/lib/libvterm.so.0
No symbol table info available.
#1  0x00007f0629785e93 in ?? () from /usr/lib/libvterm.so.0
No symbol table info available.
#2  0x00007f06297892ef in ?? () from /usr/lib/libvterm.so.0
No symbol table info available.
#3  0x00007f0629783598 in vterm_input_write () from /usr/lib/libvterm.so.0
No symbol table info available.
#4  0x00005642b947d089 in terminal_receive (term=0x5642bad731f0, data=<optimized out>, len=<optimized out>) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/terminal.c:655
No locals.
#5  0x00005642b92d4392 in on_channel_output (stream=<optimized out>, chan=0x5642bad61a20, buf=0x5642bad62190, count=270, eof=<optimized out>, reader=0x5642bad620e8) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/channel.c:613
        r = 270
        ptr = 0x5642bad63ef4 "uwu (redacted)"...
#6  0x00005642b92d446d in on_channel_data (stream=<optimized out>, buf=<optimized out>, count=<optimized out>, data=<optimized out>, eof=<optimized out>) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/channel.c:591
        chan = <optimized out>
#7  0x00005642b932e37b in read_event (argv=argv@entry=0x7ffe146ff8d0) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/event/rstream.c:194
        count = <optimized out>
        eof = <optimized out>
        stream = 0x5642bad61c28
#8  0x00005642b932e469 in invoke_read_cb (stream=stream@entry=0x5642bad61c28, count=count@entry=270, eof=eof@entry=false) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/event/rstream.c:207
        argv = {0x5642bad61c28, 0x10e, 0x0}
#9  0x00005642b932f5f5 in read_cb (uvstream=<optimized out>, cnt=270, buf=<optimized out>) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/event/rstream.c:135
        stream = 0x5642bad61c28
        nread = 270
#10 0x00007f06297e43a1 in ?? () from /usr/lib/libuv.so.1
No symbol table info available.
#11 0x00007f06297e4cf8 in ?? () from /usr/lib/libuv.so.1
No symbol table info available.
#12 0x00007f06297ed266 in ?? () from /usr/lib/libuv.so.1
No symbol table info available.
#13 0x00007f06297d9897 in uv_run () from /usr/lib/libuv.so.1
No symbol table info available.
#14 0x00005642b932a3eb in loop_poll_events (loop=0x5642b95aeb20 <main_loop>, ms=4000) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/event/loop.c:62
        mode = <optimized out>
        timeout_expired = false
#15 0x00005642b93f8526 in inbuf_poll (ms=4000, events=events@entry=0x5642bac75400) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/os/input.c:415
        remaining = 4000
        before = 6333620684080
#16 0x00005642b93f8ad5 in os_inchar (buf=0x0, maxlen=0, ms=-1, tb_change_cnt=0, events=0x5642bac75400) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/os/input.c:118
        result = <optimized out>
#17 0x00005642b94694aa in state_enter (s=0x7ffe14702dd0) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/state.c:54
        check_result = <optimized out>
        key = <optimized out>
        execute_result = <optimized out>
#18 0x00005642b93ca0fe in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/normal.c:464
        state = {state = {check = 0x5642b93ce037 <normal_check>, execute = 0x5642b93ce61b <normal_execute>}, command_finished = false, ctrl_w = false, need_flushbuf = false, set_prevcount = false, previous_got_int = false, cmdwin = false, noexmode = false, toplevel = true, oa = {op_type = 0, regname = 0, motion_type = kMTCharWise, motion_force = 0, use_reg_one = false, inclusive = false, end_adjusted = false, start = {lnum = 0, col = 0, coladd = 0}, end = {lnum = 0, col = 0, coladd = 0}, cursor_start = {lnum = 0, col = 0, coladd = 0}, line_count = 0, empty = false, is_VIsual = false, start_vcol = 0, end_vcol = 0, prev_opcount = 0, prev_count0 = 0, excl_tr_ws = false}, ca = {oap = 0x7ffe14702de8, prechar = 0, cmdchar = 0, nchar = 0, ncharC1 = 0, ncharC2 = 0, extra_char = 0, opcount = 0, count0 = 0, count1 = 0, arg = 0, retval = 0, searchbuf = 0x0}, mapped_len = 0, old_mapped_len = 0, idx = 184, c = 0, old_col = 0, old_pos = {lnum = 63, col = 0, coladd = 0}}
#19 0x00005642b939f2c9 in main (argc=<optimized out>, argv=<optimized out>) at /home/multisn8/info/projects/shell/quick-neovim-nightly/neovim/src/nvim/main.c:567
        fname = <optimized out>
        params = {argc = 3, argv = 0x7ffe14703168, use_vimrc = 0x7ffe14703561 "NONE", clean = false, n_commands = 0, commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, cmds_tofree = "\000\000\000\000\000\000\000\000\000", n_pre_commands = 0, pre_commands = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, edit_type = 0, tagname = 0x0, use_ef = 0x0, input_isatty = true, output_isatty = true, err_isatty = true, input_neverscript = false, no_swap_file = 0, use_debug_break_level = -1, window_count = 1, window_layout = 0, diff_mode = 0, listen_addr = 0x0}
        cwd = 0x0
        use_remote_ui = false
        use_builtin_ui = true
        __PRETTY_FUNCTION__ = "main"
(gdb) q
```

**Comment by zeertzjq** [comment]
Seems fixed now.
