### ISSUE TITLE
PyPy freezes nvim on windows

### ISSUE THREAD

**Issue by tejasvi** [neovim/neovim#15327]
### Neovim Version

v0.5.0-dev+1283-g59eae3b38

### Operating system/version:

Windows 10

### Terminal name/version:

NA

### TERM environment variable

NA

### Installation

Repo release

### Steps to reproduce

1. `:let g:python3_host_prog="pypy3"`
2. `:py3 print("test")`

### Expected behavior

Echoes "test"

### Actual behavior

Editor freezes.

`:checkhealth provider` gives
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "pypy3"
  - INFO: Executable: C:\tools\pypy3.7-v7.3.5-win64\pypy3.EXE
  - INFO: Python version: 3.7.10^M
  - INFO: pynvim version: 0.4.3^M
  - OK: Latest pynvim is installed.
```

PyPy installed from https://downloads.python.org/pypy/pypy3.7-v7.3.5-win64.zip

Works fine on Linux.

**Comment by erw7** [comment]
This is a bug in `pypy3`, as you can easily see by setting the `NVIM_PYTHON_LOG_FILE` environment variable and enabling `pynvim` logging.

```
2021-09-14 22:50:39,671 [ERROR @ base_events.py:default_exception_handler:1619] 10180 - Exception in callback _ProactorBaseWritePipeTransport._loop_writing(<_OverlappedF...ed result=134>)
handle: <Handle _ProactorBaseWritePipeTransport._loop_writing(<_OverlappedF...ed result=134>)>
Traceback (most recent call last):
  File "c:\pypy3.7-v7.3.5-win64\lib-python\3\asyncio\events.py", line 88, in _run self._context.run(self._callback, *self._args)
  File "c:\pypy3.7-v7.3.5-win64\lib_pypy\_contextvars.py", line 41, in run return callable(*args, **kwargs)
  File "c:\pypy3.7-v7.3.5-win64\lib-python\3\asyncio\proactor_events.py", line 370, in _loop_writing self._write_fut = self._loop._proactor.send(self._sock, data)
  File "c:\pypy3.7-v7.3.5-win64\lib-python\3\asyncio\windows_events.py", line 474, in send ov.WriteFile(conn.fileno(), buf)
  File "c:\pypy3.7-v7.3.5-win64\lib_pypy\_overlapped.py", line 359, in WriteFile ret = _kernel32.WriteFile(self.handle, self.write_buffer, len(self.write_buffer), written, self.overlapped)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not bytearray
```

The following patch will fix the problem. If you need to use `pypy3`, you should report yourself to the `pypy3` developers ([Heptapod PyPy](https://foss.heptapod.net/pypy)).

```diff
--- _overlapped.py.orig	2021-08-16 13:38:30.403944500 +0900
+++ _overlapped.py	2021-08-16 17:53:21.577925100 +0900
@@ -344,7 +344,7 @@
 
     def WriteFile(self, handle, buffer):
         self.handle = _int2handle(handle)
-        self.write_buffer = buffer
+        self.write_buffer = bytes(buffer)
         written = _ffi.new('DWORD[1]', [0])
 
         # Check if we have already performed some IO
@@ -353,7 +353,7 @@
 
         self.type = OverlappedType.TYPE_WRITE
         
-        ret = _kernel32.WriteFile(self.handle, self.write_buffer, len(self.write_buffer), written, self.overlapped)
+        ret = _kernel32.WriteFile(self.handle, _ffi.from_buffer(self.write_buffer), len(self.write_buffer), written, self.overlapped)
         
         if ret:
             self.error = _winapi.ERROR_SUCCESS
```
