### ISSUE TITLE
Treesitter highlight hangs with Zig parser.

### ISSUE THREAD

**Issue by TristanCrawford** [neovim/neovim#16050]
### Neovim version (nvim -v)

NVIM v0.6.0-dev+465-gfc1cdb882

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Void Linux 5.13.19_1 x86_64 GNU/Linux

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

Built from source,

### How to reproduce the issue

1. Install the `nvim-treesitter` plugin & enable highlighting (It seems to only occur with highlight for whatever reason)
```lua
-- use-package Example
use {
  'nvim-treesitter/nvim-treesitter',
  config = function()
      require('nvim-treesitter.configs').setup {
          highlight = { enable = true },
      }
  end
}
```
2. Install the Zig parser
`:TSInstall zig` *or* `:TSInstallFromGrammar zig`
3. Open a Zig file.

### Expected behavior

The file should load up and have some tree-sitter powered highlighting.

### Actual behavior

The file doesn't load and nvim just hangs...

GDB Stacktrace:
```gdb
#0  0x000056013d6bd074 in ts_query_cursor.advance ()
#1  0x000056013d6bd5df in ts_query_cursor_next_capture ()
#2  0x000056013d4b29ff in query_next_capture (L=0x7f4220e2f380)
    at /home/tristan/Git/neovim/src/nvim/lua/treesitter.c:1078
#3  0x000056013d6f02cd in lj_BC_FUNCC ()
#4  0x000056013d6d9ee5 in lua_pcall (L=0x7f4220e2f380, nargs=4, nresults=1,
    errfunc=<optimized out>) at lj_api.c:1169
#5  0x000056013d4ae5cb in nlua_call_ref (ref=9, name=0x56013d798935 "line", args=...,
    retval=true, err=0x7ffe9e15a530) at /home/tristan/Git/neovim/src/nvim/lua/executor.c:1293
#6  0x000056013d57c1ce in provider_invoke (ns_id=5, name=0x56013d798935 "line", ref=9, args=...,
    default_true=true) at /home/tristan/Git/neovim/src/nvim/screen.c:177
#7  0x000056013d581e09 in win_line (wp=0x56013d8d4dc0, lnum=1, startrow=0, endrow=46,
    nochange=true, number_only=false, foldinfo=..., providers=0x7ffe9e15bdd0)
    at /home/tristan/Git/neovim/src/nvim/screen.c:2198
#8  0x000056013d5803ce in win_update (wp=0x56013d8d4dc0, providers=0x7ffe9e15bf70)
    at /home/tristan/Git/neovim/src/nvim/screen.c:1579
#9  0x000056013d57d5c5 in update_screen (type=40)
    at /home/tristan/Git/neovim/src/nvim/screen.c:606
#10 0x000056013d4fdff9 in normal_redraw (s=0x7ffe9e15c0d0)
    at /home/tristan/Git/neovim/src/nvim/normal.c:1308
#11 0x000056013d4fe243 in normal_check (state=0x7ffe9e15c0d0)
    at /home/tristan/Git/neovim/src/nvim/normal.c:1398
#12 0x000056013d5dc0ae in state_enter (s=0x7ffe9e15c0d0)
    at /home/tristan/Git/neovim/src/nvim/state.c:27
#13 0x000056013d4fbd6f in normal_enter (cmdwin=false, noexmode=false)
    at /home/tristan/Git/neovim/src/nvim/normal.c:469
#14 0x000056013d4b50b7 in main (argc=1, argv=0x7ffe9e15c478)
    at /home/tristan/Git/neovim/src/nvim/main.c:547
```

**Comment by TristanCrawford** [comment]
*sigh*... I figured it out... I just forgot to rebuild the dependencies, must've been a bug with an old version of tree-sitter.
