### ISSUE TITLE
Neovim on MacOS with M1 processor reports unable to load python module neovim

### ISSUE THREAD

**Issue by josephemorgan** [neovim/neovim#16213]
### Neovim version (nvim -v)

0.5.1

### Vim (not Nvim) behaves the same?

No, vim doesn't import pynvim module

### Operating system/version

MacOS 12.0.1

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

screen-256color

### Installation

Homebrew (brew install neovim)

### How to reproduce the issue

nvim --clean
:checkhealth
Python 3 provider reports:
```
## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /opt/homebrew/bin/python3
  - INFO: Other python executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - ERROR: Command error (job=9, exit code 1): `'/opt/homebrew/bin/python3' -c 'import sys; sys.path =          list(filter(lambda x: x != "", sys.path)); import neovim; print(neovim.__file__)'` (in '/Users/joe')
    stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>  File "/opt/homebrew/lib/    python3.9/site-packages/neovim/__init__.py", line 5, in <module>    import pynvim  File "/opt/homebrew/       lib/python3.9/site-packages/pynvim/__init__.py", line 11, in <module>    from pynvim.msgpack_rpc import       (ErrorResponse, child_session, socket_session,  File "/opt/homebrew/lib/python3.9/site-packages/pynvim/       msgpack_rpc/__init__.py", line 10, in <module>    from pynvim.msgpack_rpc.session import ErrorResponse,       Session  File "/opt/homebrew/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 7, in           <module>    import greenlet  File "/opt/homebrew/lib/python3.9/site-packages/greenlet/__init__.py", line      29, in <module>    from ._greenlet import _C_API # pylint:disable=no-name-in-moduleImportError: dlopen(/      opt/homebrew/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: '/opt/      homebrew/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an         incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_greenlet.cpython-39-darwin.       so' (no such file), '/usr/lib/_greenlet.cpython-39-darwin.so' (no such file)
  - INFO: Python version: 3.9.7
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
```
Also, launching python3 IDLE and running import pynvim gives the following:
```
joe at olorin in ~ took 1m 30s ➜  python3
Python 3.9.7 (default, Oct 12 2021, 22:38:23)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pynvim;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/pynvim/__init__.py", line 11, in <module>
    from pynvim.msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/opt/homebrew/lib/python3.9/site-packages/pynvim/msgpack_rpc/__init__.py", line 10, in <module>
    from pynvim.msgpack_rpc.session import ErrorResponse, Session
  File "/opt/homebrew/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 7, in <module>
    import greenlet
  File "/opt/homebrew/lib/python3.9/site-packages/greenlet/__init__.py", line 29, in <module>
    from ._greenlet import _C_API # pylint:disable=no-name-in-module
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.9/site-packages/greenlet/_greenlet.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_greenlet.cpython-39-darwin.so' (no such file), '/usr/lib/_greenlet.cpython-39-darwin.so' (no such file)```

### Expected behavior

I would expect that python is able to import pynvim, seeing as pynvim is installed

### Actual behavior

Python is unable to import pynvim

**Comment by clason** [comment]
The error in the Python REPL shows that this is not a bug in Neovim; it's either a bug in homebrew's python (or an incomplete upgrade -- try reinstalling python3 and all modules) or in https://github.com/neovim/pynvim.

**Comment by josephemorgan** [comment]
> The error in the Python REPL shows that this is not a bug in Neovim; it's either a bug in homebrew's python (or an incomplete upgrade -- try reinstalling python3 and all modules) or in https://github.com/neovim/pynvim.

Thanks for this info, I incorrectly believed that pynvim was part of neovim, I'll resubmit the issue there.

**Comment by clason** [comment]
It's part of Neovim-the-project, but not part of Nvim-the-editor ;)
