### ISSUE TITLE
Memory leak `cjson/strbuf.c`

### ISSUE THREAD

**Issue by dundargoc** [neovim/neovim#17689]
### Neovim version (nvim -v)

NVIM v0.7.0-dev

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Ubuntu 20.04

### Terminal name/version

Kitty with tmux

### $TERM environment variable

screen-256color

### Installation

Build form repo

### How to reproduce the issue

1. Enable compiler flag `-fsanitize=leak`
2. Compile

### Expected behavior

Compile

### Actual behavior

```
==301245==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1023 byte(s) in 1 object(s) allocated from:
    #0 0x450708 in __interceptor_malloc /tmp/llvm-20220302-9880-1faggz0/llvm-project-13.0.1.src/compiler-rt/lib/lsan/lsan_interceptors.cpp:56:3
    #1 0x80f3f2 in strbuf_init /home/dgoc/programs/neovim/src/cjson/strbuf.c:61:14
    #2 0x80cc2f in json_create_config /home/dgoc/programs/neovim/src/cjson/lua_cjson.c:479:5
    #3 0x80c1b9 in lua_cjson_new /home/dgoc/programs/neovim/src/cjson/lua_cjson.c:1589:5
    #4 0x62d87a in nlua_state_add_stdlib /home/dgoc/programs/neovim/src/nvim/lua/stdlib.c:539:3
    #5 0x627a64 in nlua_state_init /home/dgoc/programs/neovim/src/nvim/lua/executor.c:638:3
    #6 0x6277da in nlua_init /home/dgoc/programs/neovim/src/nvim/lua/executor.c:667:8
    #7 0x6337e0 in main /home/dgoc/programs/neovim/src/nvim/main.c:261:3
    #8 0x7fdc58f2f0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: LeakSanitizer: 1023 byte(s) leaked in 1 allocation(s).
```

**Comment by mjlbach** [comment]
https://github.com/neovim/neovim/issues/16346#issuecomment-974143970
