### ISSUE TITLE
Crash on master `0621cd311`

### ISSUE THREAD

**Issue by lewis6991** [neovim/neovim#17824]
### Neovim version (nvim -v)

0.7dev - `0621cd311`

### Vim (not Nvim) behaves the same?

NA

### Operating system/version

Redhat 7

### Terminal name/version

kitty 0.24.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

Not available but backtrace provided below.

### Actual behavior

Backtrace:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000562b48b953a5 in syn_stack_find_entry (lnum=lnum@entry=2) at [REDACTED]/neovim/src/nvim/syntax.c:1204
1204      for (p = syn_block->b_sst_first; p != NULL; prev = p, p = p->sst_next) {
[Current thread is 1 (LWP 7480)]
(gdb) bt
#0  0x0000562b48b953a5 in syn_stack_find_entry (lnum=lnum@entry=2) at [REDACTED]/neovim/src/nvim/syntax.c:1204
#1  0x0000562b48b95c34 in syntax_end_parsing (lnum=2) at [REDACTED]/neovim/src/nvim/syntax.c:1451
#2  0x0000562b48b5877b in win_update (wp=wp@entry=0x562b4a16bbb0, providers=providers@entry=0x7ffcd59bb400)
    at [REDACTED]/neovim/src/nvim/screen.c:1540
#3  0x0000562b48b5978e in update_screen (type=<optimized out>) at [REDACTED]/neovim/src/nvim/screen.c:583
#4  0x0000562b48ae1cd2 in normal_redraw (s=s@entry=0x7ffcd59bb4e0) at [REDACTED]/neovim/src/nvim/normal.c:1310
#5  0x0000562b48ae3b46 in normal_check (state=0x7ffcd59bb4e0) at [REDACTED]/neovim/src/nvim/normal.c:1400
#6  0x0000562b48b8edd9 in state_enter (s=0x7ffcd59bb4e0) at [REDACTED]/neovim/src/nvim/state.c:30
#7  0x0000562b48ae100b in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>)
    at [REDACTED]/neovim/src/nvim/normal.c:463
#8  0x0000562b48ab0398 in main (argc=<optimized out>, argv=<optimized out>)
    at [REDACTED]/neovim/src/nvim/main.c:572

```

**Comment by zeertzjq** [comment]
Does reverting #17818 fix this?

**Comment by lewis6991** [comment]
Just bisecting now

**Comment by zeertzjq** [comment]
Does this fix the crash?
```diff
diff --git a/src/nvim/screen.c b/src/nvim/screen.c
index 7182e69d0..9aa82baba 100644
--- a/src/nvim/screen.c
+++ b/src/nvim/screen.c
@@ -1553,9 +1553,9 @@ static void win_update(win_T *wp, DecorProviders *providers)
           did_update = DID_FOLD;
           foldinfo.fi_lines--;
           wp->w_lines[idx].wl_lastlnum = lnum + foldinfo.fi_lines;
+        } else {
+          syntax_last_parsed = lnum;
         }
-
-        syntax_last_parsed = lnum;
       }
 
       wp->w_lines[idx].wl_lnum = lnum;
```

**Comment by lewis6991** [comment]
Yes
