### ISSUE TITLE
python error when opening .nvimrc or .vimrc

### ISSUE THREAD

**Issue by vhakulinen** [neovim/neovim#1890]
Error:
```
".nvimrc" 81L, 1560C
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/neovim/__init__.py", line 65, in start_host
    host.start(plugins)
  File "/usr/lib/python3.4/site-packages/neovim/plugin/host.py", line 45, in start
    lambda: self._load(plugins))
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 234, in run
    self._session.run(filter_request_cb, filter_notification_cb, setup_cb)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 117, in run
    raise self._setup_exception
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 93, in on_setup
    setup_cb()
  File "/usr/lib/python3.4/site-packages/neovim/plugin/host.py", line 45, in <lambda>
    lambda: self._load(plugins))
  File "/usr/lib/python3.4/site-packages/neovim/plugin/host.py", line 90, in _load
    self._discover_classes(module, handlers, path)
  File "/usr/lib/python3.4/site-packages/neovim/plugin/host.py", line 114, in _discover_classes
    plugin = cls(self._configure_nvim_for(cls))
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 38, in __init__
    encoding=nvim.options['encoding'].decode('ascii')))
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 39, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 255, in <lambda>
    return lambda *args: session.request(method, *args)
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 221, in request
    'out-request')
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 248, in walk
    return fn(obj, *args)
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 155, in <lambda>
    return lambda o, s, m, k: f1(f2(o, s, m, k), s, m, k)
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 177, in _decode_if_bytes
    return obj.decode(self.encoding, errors=self.encoding_errors)
TypeError: decode() argument 1 must be str, not bytes
Exception ignored in: <script_host.RedirectStream object at 0x7f2d8c63a208>
AttributeError: 'RedirectStream' object has no attribute 'flush'
```

.nvimrc
```
" {{{ Plug
call plug#begin('~/.nvim/plugged')

Plug 'kien/ctrlp.vim'
Plug 'vim-scripts/TaskList.vim'
Plug 'Yggdroot/indentLine'
Plug 'bling/vim-airline'
Plug 'whatyouhide/vim-gotham'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }

call plug#end()
" }}}

" {{{ General
let mapleader=","

filetype on
filetype plugin indent on
syntax on

set laststatus=2
set colorcolumn=80
set number
set title
set wildmenu
"set wildmenu=full
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set noautowrite
set noautowriteall
set nomousehide
set relativenumber
set backspace=indent,eol,start
set cursorline
set nowrap
set listchars+=precedes:<,extends:>

set foldmethod=marker

set background=dark
colorscheme gotham

" }}}

" {{{ Mappings
" automatic bracets
inoremap ( ()<Esc>:let leavechar=")"<CR>i
inoremap { {}<Esc>:let leavechar="}"<CR>i
inoremap [ []<Esc>:let leavechar="]"<CR>i
inoremap ' ''<Esc>:let leavechar="'"<CR>i
inoremap " ""<Esc>:let leavechar="\""<CR>i
imap <C-j> <Esc>:exec "normal f" . leavechar<Cr>a
" exit from insert mode
imap jj <esc>
imap jk <esc>
imap kj <esc>

" CtrlP
nnoremap <Leader>e :CtrlP<CR>
nnoremap <leader>b :CtrlPBuffer<CR>
nnoremap <leader>a :CtrlPBufTagAll<CR>
" Task lists
map <leader>t <Plug>TaskList

" space to open/close folds
nnoremap <space> za

inoremap <C-d> <Del>

" disable arrow keys
inoremap  <up>     <nop>
inoremap  <down>   <nop>
inoremap  <left>   <nop>
inoremap  <right>  <nop>
noremap   <up>     <nop>
noremap   <down>   <nop>
noremap   <left>   <nop>
noremap   <right>  <nop>
" }}}
```

.nvim/
```
.nvim
├── autoload
│   └── plug.vim
└── plugged
    ├── TaskList.vim
    ├── ctrlp.vim
    ├── indentLine
    ├── vim-airline
    └── vim-gotham
```

I'm running Arch Linux 64 bit but the more valuable info I think is that I've installed neovim from AUR and python-client from PIP.

EDIT: Everything worked fine till last night when I was playing with python client and ran `nvim -c 'UpdateRemotePlugins' -c 'q'` multiple times and it threw some errors I didnt catch. After that I removed neovim and python-client installs and cleared `.nvim` directory with no luck. I dont have the plugin source I was playing with me anymore.

**Comment by fwalch** [comment]
I have the same problem, and since I also run Arch and don't remember changing anything related to Neovim's config, I think it might be an Arch package update that broke this.

**Comment by vhakulinen** [comment]
Yup, that was the issue. Removed all neovim related packages from with pacman and pip/pip2 + packages from pip/pip2 which were dependencies of neovim packages.

Thanks for your help!
