### ISSUE TITLE
libtermkey segfaults when receiving CSI u sequence without a unicode key code

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#19183]
### Neovim version (nvim -v)

v0.8.0-dev+532-g60604d6a9

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean`
2. Send `\x1b[;2u` to Nvim

### Expected behavior

No segfault

### Actual behavior

Segfault
ASAN log:
```
=================================================================
==799107==ERROR: AddressSanitizer: SEGV on unknown address 0x615df5f6f570 (pc 0x5608bbcff04e bp 0x000000000006 sp 0x7f9df4ff9bb0 T1)
==799107==The signal is caused by a READ memory access.
    #0 0x5608bbcff04e in termkey_get_keyname **/.deps/build/src/libtermkey/termkey.c:1220:12
    #1 0x5608bbcff04e in termkey_strfkey **/.deps/build/src/libtermkey/termkey.c:1375:26
    #2 0x5608bb996d6b in forward_modified_utf8 **/src/nvim/tui/input.c:236:11
    #3 0x5608bb9954f6 in tk_getkeys **/src/nvim/tui/input.c:346:7
    #4 0x5608bb9902a3 in handle_raw_buffer **/src/nvim/tui/input.c:639:7
    #5 0x5608bb98d9a6 in tinput_read_cb **/src/nvim/tui/input.c:656:3
    #6 0x5608bab157b2 in read_event **/src/nvim/event/rstream.c:191:5
    #7 0x5608bab14a2c in invoke_read_cb **/src/nvim/event/rstream.c:204:3
    #8 0x5608bab1361c in read_cb **/src/nvim/event/rstream.c:133:3
    #9 0x5608bbce8dbf in uv__read **/.deps/build/src/libuv/src/unix/stream.c:1204:7
    #10 0x5608bbce8dbf in uv__stream_io **/.deps/build/src/libuv/src/unix/stream.c:1272:5
    #11 0x5608bbcf0e0e in uv__io_poll **/.deps/build/src/libuv/src/unix/epoll.c:374:11
    #12 0x5608bbcde657 in uv_run **/.deps/build/src/libuv/src/unix/core.c:405:5
    #13 0x5608baafef7a in loop_poll_events **/src/nvim/event/loop.c:60:3
    #14 0x5608bb9ae4a2 in tui_main **/src/nvim/tui/tui.c:506:5
    #15 0x5608bba0c831 in ui_thread_run **/src/nvim/ui_bridge.c:106:3
    #16 0x7f9df688c54c  (/usr/lib/libc.so.6+0x8c54c)
    #17 0x7f9df6911873 in __clone (/usr/lib/libc.so.6+0x111873)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV **/.deps/build/src/libtermkey/termkey.c:1220:12 in termkey_get_keyname
Thread T1 created by T0 here:
    #0 0x5608ba35f7d8 in __interceptor_pthread_create (**/build/bin/nvim+0xc147d8)
    #1 0x5608bbceb10b in uv_thread_create_ex **/.deps/build/src/libuv/src/unix/thread.c:279:9
    #2 0x5608bb99f77a in tui_start **/src/nvim/tui/tui.c:179:10
    #3 0x5608bb9f6898 in ui_builtin_start **/src/nvim/ui.c:139:3
    #4 0x5608baf3d754 in main **/src/nvim/main.c:343:7
    #5 0x7f9df682928f  (/usr/lib/libc.so.6+0x2928f)

==799107==ABORTING
```

**Comment by zeertzjq** [comment]
New ASAN log:
```
**/src/termkey/termkey.c:780:51: runtime error: index -1 out of bounds for type 'struct keyinfo[32]'
    #0 0x56516a91aca8 in emit_codepoint **/src/termkey/termkey.c:780:69
    #1 0x56516a8f3832 in handle_csi_u **/src/termkey/driver-csi.c:150:7
    #2 0x56516a8fcca2 in peekkey_csi **/src/termkey/driver-csi.c:567:14
    #3 0x56516a8f075f in peekkey **/src/termkey/driver-csi.c:720:18
    #4 0x56516a90d4de in peekkey **/src/termkey/termkey.c:883:11
    #5 0x56516a90cbc5 in termkey_getkey **/src/termkey/termkey.c:1042:23
    #6 0x56516a5fc758 in tk_getkey **/src/nvim/tui/input.c:434:50
    #7 0x56516a5fbe2e in tk_getkeys **/src/nvim/tui/input.c:442:20
    #8 0x56516a5f7620 in handle_raw_buffer **/src/nvim/tui/input.c:720:7
    #9 0x56516a5f4f60 in tinput_read_cb **/src/nvim/tui/input.c:749:3
    #10 0x5651697c298b in read_event **/src/nvim/event/rstream.c:190:5
    #11 0x5651697c229b in invoke_read_cb **/src/nvim/event/rstream.c:203:3
    #12 0x5651697c0d3c in read_cb **/src/nvim/event/rstream.c:132:3
    #13 0x56516aa636ea in uv__read **/.deps/build/src/libuv/src/unix/stream.c:1143:7
    #14 0x56516aa6101c in uv__stream_io **/.deps/build/src/libuv/src/unix/stream.c:1203:5
    #15 0x56516aa6cde5 in uv__io_poll **/.deps/build/src/libuv/src/unix/linux.c:1526:11
    #16 0x56516aa4f4b5 in uv_run **/.deps/build/src/libuv/src/unix/core.c:447:5
    #17 0x5651697ab2ad in loop_uv_run **/src/nvim/event/loop.c:63:5
    #18 0x5651697ab711 in loop_poll_events **/src/nvim/event/loop.c:85:26
    #19 0x56516a672974 in ui_client_run **/src/nvim/ui_client.c:120:5
    #20 0x565168f5247f in main **/src/nvim/main.c:389:5
    #21 0x7efdab459ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #22 0x7efdab459d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #23 0x565168e19d94 in _start (**/build/bin/nvim+0xbe6d94) (BuildId: c515a501ada749989be044affbd83e97d4afa85c)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/termkey/termkey.c:780:51 in 
```
