### ISSUE TITLE
Segfault when `--headless rpcrequest(stioopen({}),...)` is redirected to file

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#19374]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-nightly-12-g977790746

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux r4 5.18.0-1-amd64 1 SMP PREEMPT_DYNAMIC Debian 5.18.2-1 (2022-06-06) x86_64 GNU/Linux

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

Appimage

### How to reproduce the issue

```
nvim --headless --cmd 'call rpcrequest(stdioopen({"rpc":v:true}),"nvim_command","echo hello")' >/tmp/tmp
```

### Expected behavior

Rpc request is written to /tmp/tmp.

### Actual behavior

Segfault without anything being written to the file. Removing the redirection makes the crash disappear.

Piping to `tee /tmp/tmp` instead of directly redirecting to a file is a suitable workaround for my usecase.

**Comment by zeertzjq** [comment]
ASAN:
```
=================================================================
==185425==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x5cd1f2047985 bp 0x7ffd95850040 sp 0x7ffd95850020 T0)
==185425==The signal is caused by a READ memory access.
==185425==Hint: address points to the zero page.
    #0 0x5cd1f2047985 in uv__check_before_write **/.deps/build/src/libuv/src/unix/stream.c:1294:3
    #1 0x5cd1f204774e in uv_write2 **/.deps/build/src/libuv/src/unix/stream.c:1337:9
    #2 0x5cd1f2047cc7 in uv_write **/.deps/build/src/libuv/src/unix/stream.c:1405:10
    #3 0x5cd1f0d51b73 in wstream_write **/src/nvim/event/wstream.c:91:7
    #4 0x5cd1f13dc996 in channel_write **/src/nvim/msgpack_rpc/channel.c:495:15
    #5 0x5cd1f13db7c8 in send_request **/src/nvim/msgpack_rpc/channel.c:551:3
    #6 0x5cd1f13d8b29 in rpc_send_call **/src/nvim/msgpack_rpc/channel.c:203:3
    #7 0x5cd1f0c1f579 in f_rpcrequest **/src/nvim/eval/funcs.c:6965:19
    #8 0x5cd1f0badcba in call_internal_func **/src/nvim/eval/funcs.c:290:3
    #9 0x5cd1f0cbbd30 in call_func **/src/nvim/eval/userfunc.c:1709:15
    #10 0x5cd1f0cb820d in get_func_tv **/src/nvim/eval/userfunc.c:557:11
    #11 0x5cd1f0cf1daa in ex_call_inner **/src/nvim/eval/userfunc.c:3127:9
    #12 0x5cd1f0cefeb9 in ex_call **/src/nvim/eval/userfunc.c:3369:14
    #13 0x5cd1f0de1f0c in execute_cmd0 **/src/nvim/ex_docmd.c:1674:7
    #14 0x5cd1f0dbeb37 in do_one_cmd **/src/nvim/ex_docmd.c:2343:7
    #15 0x5cd1f0daf2f2 in do_cmdline **/src/nvim/ex_docmd.c:633:20
    #16 0x5cd1f0db4400 in do_cmdline_cmd **/src/nvim/ex_docmd.c:342:10
    #17 0x5cd1f113395a in exe_pre_commands **/src/nvim/main.c:1891:5
    #18 0x5cd1f111f091 in main **/src/nvim/main.c:442:3
    #19 0x7e91322efccf  (/usr/lib/libc.so.6+0x23ccf) (BuildId: 1bc67512a1f89c5a034f03e066cbd11fc7905cb4)
    #20 0x7e91322efd89 in __libc_start_main (/usr/lib/libc.so.6+0x23d89) (BuildId: 1bc67512a1f89c5a034f03e066cbd11fc7905cb4)
    #21 0x5cd1f03b2d94 in _start (**/build/bin/nvim+0xc09d94) (BuildId: b16cbbba647981bbbecc4bf9d0097edf2420d5ca)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV **/.deps/build/src/libuv/src/unix/stream.c:1294:3 in uv__check_before_write
==185425==ABORTING
```
