### ISSUE TITLE
Using nested vim.defer_fn() on exit leaks luv handles

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#19727]
### Neovim version (nvim -v)

v0.10.0-dev-1595+gabac33605

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

Run
```sh
nvim --clean -c 'lua vim.defer_fn(function() vim.defer_fn(function() vim.defer_fn(function() end, 0) end, 0) end, 0)' -c quit
```
or run `nvim --clean` and source this Lua file:
```lua
vim.defer_fn(function()
  vim.defer_fn(function()
    vim.defer_fn(function()
    end, 0)
  end, 0)
end, 0)
vim.cmd('quit')
```
with ASAN

Nesting is not necessary as of v0.10.0-dev-1595+gabac33605

### Expected behavior

No leak of luv handles

### Actual behavior

2 seconds hang on exit because of leaked luv handles

**Comment by zeertzjq** [comment]
Solving this leak will likely also solve the leak happening on `master`:
```
 RUN      T2994 vim.lsp.diagnostic vim.lsp.diagnostic.on_publish_diagnostics correctly handles UTF-16 offsets: 7.59 ms OK
==================== File /home/runner/work/neovim/neovim/build/log/asan.37230 ====================
= 
= =================================================================
= ==37230==ERROR: LeakSanitizer: detected memory leaks
= 
= Direct leak of 466 byte(s) in 1 object(s) allocated from:
=     #0 0x4e07ad in malloc ??:?
=     #1 0x126aab2 in try_malloc /home/runner/work/neovim/neovim/src/nvim/memory.c:76:15
=     #2 0x126acac in xmalloc /home/runner/work/neovim/neovim/src/nvim/memory.c:110:15
=     #3 0x126b246 in xmallocz /home/runner/work/neovim/neovim/src/nvim/memory.c:189:15
=     #4 0x126b39e in xmemdupz /home/runner/work/neovim/neovim/src/nvim/memory.c:207:17
=     #5 0x126c7a8 in xstrdup /home/runner/work/neovim/neovim/src/nvim/memory.c:426:10
=     #6 0x106395d in nlua_luv_cfpcall /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:195:5
=     #7 0x1f16cb9 in uv__wait_children /home/runner/nvim-deps/build/src/libuv/src/unix/process.c:156:5
= 
= SUMMARY: AddressSanitizer: 466 byte(s) leaked in 1 allocation(s).
===================================================================================================
nan ms test/helpers.lua:255: Found runtime errors in logfile(s): /home/runner/work/neovim/neovim/build/log/asan.37230

stack traceback:
	test/helpers.lua:255: in function 'check_logs'
	test/functional/helpers.lua:914: in function <test/functional/helpers.lua:913>
```

**Comment by zeertzjq** [comment]
After 22eb2ba18336df6cd70a88f666818ee5d8ba92d2 this no longer leaks memory, but it leaks luv handles.

**Comment by zeertzjq** [comment]
Fixing this may break callers that rely on the timer being closed immediately before the schedule function is called rather than in a previous event loop iteration.

**Comment by zeertzjq** [comment]
Maybe it's possible to make a list of timers that are triggered on exit, and free them when no user code can be executed?

**Comment by zeertzjq** [comment]
This is now also causing high CPU usage when running TUI tests in an ASAN build.
