### ISSUE TITLE
Memory leak when luv callback calls vim.schedule() after vim.schedule() callback on exit

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#19732]
### Neovim version (nvim -v)

v0.8.0-dev-818-g0d9e09bf6

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean` with ASAN
2. Source the following Lua file:
```lua
local handle, _ = vim.loop.spawn(vim.v.progpath, {
  args = {'-u', 'NONE', '--headless'},
}, function()
  vim.schedule(function() end)
end)

vim.schedule(function()
  handle:kill(15)
end)

vim.cmd('quit')
```

### Expected behavior

No memory leak

### Actual behavior

Memory leak:
```
1 lua references were leaked!
=================================================================
==2804382==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x562d03a50d79 in malloc (**/build/bin/nvim+0xcd1d79)
    #1 0x562d04767352 in try_malloc **/src/nvim/memory.c:76:15
    #2 0x562d0476751c in xmalloc **/src/nvim/memory.c:110:15
    #3 0x562d045645b6 in nlua_ref **/src/nvim/lua/executor.c:1149:56
    #4 0x562d04564630 in nlua_ref_global **/src/nvim/lua/executor.c:1158:10
    #5 0x562d04570d30 in nlua_schedule **/src/nvim/lua/executor.c:329:15
    #6 0x562d053fd0f5 in lj_BC_FUNCC (**/build/bin/nvim+0x267e0f5)

SUMMARY: AddressSanitizer: 3 byte(s) leaked in 1 allocation(s).
```

**Comment by zeertzjq** [comment]
This is similar to #19727 but harder to fix.

**Comment by przepompownia** [comment]
Having still ASAN logs I get similar message from LeakSanitizer with (not small as the above example)

```sh
nvim --clean -u treesitter-mem-leak.lua --headless -c 'TSUpdateSync' -c 'q' 
```

```lua
local configDir = vim.fn.expand('<sfile>:p:h')
vim.notify(configDir)

vim.env['XDG_CONFIG_HOME'] = configDir
vim.env['XDG_DATA_HOME'] = configDir .. '/.xdg/data'
vim.env['XDG_STATE_HOME'] = configDir .. '/.xdg/state'
vim.env['XDG_CACHE_HOME'] = configDir .. '/.xdg/cache'
local stdPathConfig = vim.fn.stdpath('config')

vim.opt.runtimepath:prepend(stdPathConfig)
vim.opt.packpath:prepend(stdPathConfig)
local plugins_path = vim.fn.fnamemodify('plugins/', ':p')

for name, url in pairs{
  ['nvim-treesitter'] = 'https://github.com/nvim-treesitter/nvim-treesitter',
} do
  local install_path = plugins_path .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end
require'nvim-treesitter.configs'.setup {
  ensure_installed = {
    'sql',
  },
}
```
```c++
All parsers are up-to-date!1 lua references were leaked!
=================================================================
==810446==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x563a213dbd9e in __interceptor_malloc (.../bin/nvim+0xcd8d9e) (BuildId: 8eb8a38bf7eba028136aa27869712ca74507fd48)
    #1 0x563a221b0ae6 in try_malloc .../src/nvim/memory.c:88:15
    #2 0x563a221b0cbc in xmalloc .../src/nvim/memory.c:122:15
    #3 0x563a21febd16 in nlua_ref .../src/nvim/lua/executor.c:1297:51
    #4 0x563a21febd90 in nlua_ref_global .../src/nvim/lua/executor.c:1306:10
    #5 0x563a21ff7f60 in nlua_schedule .../src/nvim/lua/executor.c:376:15
    #6 0x563a22e2ecc5 in lj_BC_FUNCC (.../bin/nvim+0x272bcc5) (BuildId: 8eb8a38bf7eba028136aa27869712ca74507fd48)

SUMMARY: AddressSanitizer: 3 byte(s) leaked in 1 allocation(s).

```

**Comment by zeertzjq** [comment]
This backtrace is quite common and doesn't really mean much.

**Comment by przepompownia** [comment]
In practice, is it not worth paying attention to or it's only not enough precise (or something else)?

**Comment by zeertzjq** [comment]
After 22eb2ba18336df6cd70a88f666818ee5d8ba92d2 this no longer leaks memory, but it leaks luv handles.

**Comment by zeertzjq** [comment]
Actually this is same as #19727 now.
