### ISSUE TITLE
wildoptions=pum leaks memory when using S-Tab to complete a path twice

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#19873]
### Neovim version (nvim -v)

Tested on 6b9852cc4188d9ca7bce8e7592dcfca38539c743 and e23c5fda0a3fe385af615372c474d4dad3b74464, both have the leak

### Vim (not Nvim) behaves the same?

No, Vim 9.0.223 with wildoptions=pum

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.25.2

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

1. Run `nvim --clean` in cloned `neovim/neovim` repository
2. Press `:cd s<S-Tab>n<S-Tab>`

### Expected behavior

No memory leak

### Actual behavior

Memory leak:
```
=================================================================
==809481==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 240 byte(s) in 1 object(s) allocated from:
    #0 0x5600c3564dea in __interceptor_realloc.part.0 asan_malloc_linux.cpp.o
    #1 0x5600c42d4632 in xrealloc **/src/nvim/memory.c:161:15
    #2 0x5600c3f30a51 in ga_grow **/src/nvim/garray.c:106:14
    #3 0x5600c45cbe37 in addfile **/src/nvim/path.c:1511:3
    #4 0x5600c45db851 in do_path_expand **/src/nvim/path.c:766:13
    #5 0x5600c45cb935 in path_expand **/src/nvim/path.c:588:10
    #6 0x5600c45c92ea in gen_expand_wildcards **/src/nvim/path.c:1317:32
    #7 0x5600c45d4775 in expand_wildcards **/src/nvim/path.c:2178:12
    #8 0x5600c45d463c in expand_wildcards_eval **/src/nvim/path.c:2146:11
    #9 0x5600c3912bb3 in ExpandFromContext **/src/nvim/cmdexpand.c:1970:11
    #10 0x5600c391b5b3 in expand_cmdline **/src/nvim/cmdexpand.c:1836:7
    #11 0x5600c391742f in showmatches **/src/nvim/cmdexpand.c:541:9
    #12 0x5600c3e46057 in command_line_execute **/src/nvim/ex_getln.c:1281:7
    #13 0x5600c4a393de in state_enter **/src/nvim/state.c:88:26
    #14 0x5600c3e255d8 in command_line_enter **/src/nvim/ex_getln.c:819:3
    #15 0x5600c3e20b4c in getcmdline **/src/nvim/ex_getln.c:2459:10
    #16 0x5600c3e28c18 in getexline **/src/nvim/ex_getln.c:2654:18
    #17 0x5600c3d84cb4 in do_cmdline **/src/nvim/ex_docmd.c:508:30
    #18 0x5600c440b41b in nv_colon **/src/nvim/normal.c:4050:20
    #19 0x5600c43f7825 in normal_execute **/src/nvim/normal.c:1170:3
    #20 0x5600c4a393de in state_enter **/src/nvim/state.c:88:26
    #21 0x5600c43c8f90 in normal_enter **/src/nvim/normal.c:469:3
    #22 0x5600c40ff666 in main **/src/nvim/main.c:585:3
    #23 0x7fba3faa92cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 7d4293a9bbe1f068ab7ae807c2d9377395eb5b41)

Indirect leak of 189 byte(s) in 12 object(s) allocated from:
    #0 0x5600c3565cb9 in malloc (**/build/bin/nvim+0xcdfcb9)
    #1 0x5600c42d4112 in try_malloc **/src/nvim/memory.c:77:15
    #2 0x5600c42d42dc in xmalloc **/src/nvim/memory.c:111:15
    #3 0x5600c45cbd50 in addfile **/src/nvim/path.c:1499:15
    #4 0x5600c45db851 in do_path_expand **/src/nvim/path.c:766:13
    #5 0x5600c45cb935 in path_expand **/src/nvim/path.c:588:10
    #6 0x5600c45c92ea in gen_expand_wildcards **/src/nvim/path.c:1317:32
    #7 0x5600c45d4775 in expand_wildcards **/src/nvim/path.c:2178:12
    #8 0x5600c45d463c in expand_wildcards_eval **/src/nvim/path.c:2146:11
    #9 0x5600c3912bb3 in ExpandFromContext **/src/nvim/cmdexpand.c:1970:11
    #10 0x5600c391b5b3 in expand_cmdline **/src/nvim/cmdexpand.c:1836:7
    #11 0x5600c391742f in showmatches **/src/nvim/cmdexpand.c:541:9
    #12 0x5600c3e46057 in command_line_execute **/src/nvim/ex_getln.c:1281:7
    #13 0x5600c4a393de in state_enter **/src/nvim/state.c:88:26
    #14 0x5600c3e255d8 in command_line_enter **/src/nvim/ex_getln.c:819:3
    #15 0x5600c3e20b4c in getcmdline **/src/nvim/ex_getln.c:2459:10
    #16 0x5600c3e28c18 in getexline **/src/nvim/ex_getln.c:2654:18
    #17 0x5600c3d84cb4 in do_cmdline **/src/nvim/ex_docmd.c:508:30
    #18 0x5600c440b41b in nv_colon **/src/nvim/normal.c:4050:20
    #19 0x5600c43f7825 in normal_execute **/src/nvim/normal.c:1170:3
    #20 0x5600c4a393de in state_enter **/src/nvim/state.c:88:26
    #21 0x5600c43c8f90 in normal_enter **/src/nvim/normal.c:469:3
    #22 0x5600c40ff666 in main **/src/nvim/main.c:585:3
    #23 0x7fba3faa92cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 7d4293a9bbe1f068ab7ae807c2d9377395eb5b41)

SUMMARY: AddressSanitizer: 429 byte(s) leaked in 13 allocation(s).
```

Note: this memory leak only happens with wildoptions=pum

**Comment by zeertzjq** [comment]
Closing in favor of #19874
