### ISSUE TITLE
Segfault when triggering completion in silent mode

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#20062]
### Neovim version (nvim -v)

v0.8.0-dev-1013-g1ffd527c8

### Vim (not Nvim) behaves the same?

No, Vim 9.0.231

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.26.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

### How to reproduce the issue

Run `nvim --clean -E -s --cmd 'exe "norm! i\<C-X>\<C-V>"' --cmd 'q!'`

### Expected behavior

No segfault

### Actual behavior

Segfault:
```
**/src/nvim/popupmenu.c:146:53: runtime error: member access within null pointer of type 'ScreenGrid' (aka 'struct ScreenGrid')
    #0 0x5642bb9bd1c4 in pum_display **/src/nvim/popupmenu.c:146:53
    #1 0x5642bb43233e in ins_compl_show_pum **/src/nvim/insexpand.c:1260:3
    #2 0x5642bb4420f5 in show_pum **/src/nvim/insexpand.c:4292:3
    #3 0x5642bb43f67a in ins_complete **/src/nvim/insexpand.c:4270:5
    #4 0x5642bae1f7fd in insert_do_complete **/src/nvim/edit.c:1181:7
    #5 0x5642badfb584 in insert_execute **/src/nvim/edit.c:616:5
    #6 0x5642bbdedade in state_enter **/src/nvim/state.c:88:26
    #7 0x5642bae0409c in insert_enter **/src/nvim/edit.c:331:5
    #8 0x5642badf8d8e in edit **/src/nvim/edit.c:1257:3
    #9 0x5642bb819abe in invoke_edit **/src/nvim/normal.c:7053:7
    #10 0x5642bb7eff47 in nv_edit **/src/nvim/normal.c:7030:5
    #11 0x5642bb7da015 in normal_execute **/src/nvim/normal.c:1172:3
    #12 0x5642bb7d2cdf in normal_cmd **/src/nvim/normal.c:7412:9
    #13 0x5642bb19a2f8 in exec_normal **/src/nvim/ex_docmd.c:6410:5
    #14 0x5642bb19a00b in exec_normal_cmd **/src/nvim/ex_docmd.c:6393:3
    #15 0x5642bb1aa4d6 in ex_normal **/src/nvim/ex_docmd.c:6325:7
    #16 0x5642bb179b82 in execute_cmd0 **/src/nvim/ex_docmd.c:1590:7
    #17 0x5642bb156ac3 in do_one_cmd **/src/nvim/ex_docmd.c:2240:7
    #18 0x5642bb1466b0 in do_cmdline **/src/nvim/ex_docmd.c:584:20
    #19 0x5642baeaeacd in ex_execute **/src/nvim/eval.c:7724:7
    #20 0x5642bb179b82 in execute_cmd0 **/src/nvim/ex_docmd.c:1590:7
    #21 0x5642bb156ac3 in do_one_cmd **/src/nvim/ex_docmd.c:2240:7
    #22 0x5642bb1466b0 in do_cmdline **/src/nvim/ex_docmd.c:584:20
    #23 0x5642bb14c4f0 in do_cmdline_cmd **/src/nvim/ex_docmd.c:287:10
    #24 0x5642bb4e0ccf in exe_pre_commands **/src/nvim/main.c:1783:7
    #25 0x5642bb4ceb83 in main **/src/nvim/main.c:385:3
    #26 0x7f200cbaa2cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #27 0x7f200cbaa389 in __libc_start_main (/usr/lib/libc.so.6+0x23389) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #28 0x5642ba860de4 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/popupmenu.c:146:53 in 
```

**Comment by zeertzjq** [comment]
Duplicate of #14565
