### ISSUE TITLE
nvim/message.c:2425: msg_scroll_flush: Assertion `row >= 0' failed.

### ISSUE THREAD

**Issue by dimbleby** [neovim/neovim#20153]
### Neovim version (nvim -v)

v0.8.0-dev-1070-g9b4cab012

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

ubuntu 22.04

### Terminal name/version

tmux

### $TERM environment variable

tmux-256color

### Installation

compile from source

### How to reproduce the issue

```
nvim --clean
:set cmdheight=0
:!ls /etc
<Enter>
g<
```

### Expected behavior

command window is reopened, see listed files

### Actual behavior

crash
```
nvim/message.c:2425: msg_scroll_flush: Assertion `row >= 0' failed.
```

**Comment by glepnir** [comment]
@Shougo  `cmdheight=0` relate

**Comment by zeertzjq** [comment]
ASAN also reports a heap-buffer-overflow:
```
=================================================================
==558316==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6130000078f8 at pc 0x555a5802b2d1 bp 0x7fffb7b89c10 sp 0x7fffb7b89c08
READ of size 8 at 0x6130000078f8 thread T0
    #0 0x555a5802b2d0 in grid_fill **/src/nvim/grid.c:412:22
    #1 0x555a583f12ae in do_more_prompt **/src/nvim/message.c:2963:11
    #2 0x555a58403143 in show_sb_text **/src/nvim/message.c:2628:5
    #3 0x555a58500a03 in nv_g_cmd **/src/nvim/normal.c:6381:5
    #4 0x555a584d8fe5 in normal_execute **/src/nvim/normal.c:1172:3
    #5 0x555a58aedf0e in state_enter **/src/nvim/state.c:88:26
    #6 0x555a584aa760 in normal_enter **/src/nvim/normal.c:471:3
    #7 0x555a581ce876 in main **/src/nvim/main.c:583:3
    #8 0x7f7078a5d2cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #9 0x7f7078a5d389 in __libc_start_main (/usr/lib/libc.so.6+0x23389) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)
    #10 0x555a5755dde4 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

0x6130000078f8 is located 8 bytes to the left of 376-byte region [0x613000007900,0x613000007a78)
allocated by thread T0 here:
    #0 0x555a57612cb9 in malloc (**/build/bin/nvim+0xcf9cb9)
    #1 0x555a583b5312 in try_malloc **/src/nvim/memory.c:80:15
    #2 0x555a583b54dc in xmalloc **/src/nvim/memory.c:114:15
    #3 0x555a58031c51 in grid_alloc **/src/nvim/grid.c:651:21
    #4 0x555a583d78c1 in msg_grid_validate **/src/nvim/message.c:169:5
    #5 0x555a58890900 in showmode **/src/nvim/screen.c:691:3
    #6 0x555a57accebd in update_screen **/src/nvim/drawscreen.c:667:5
    #7 0x555a58532f27 in normal_redraw **/src/nvim/normal.c:1289:5
    #8 0x555a58530aaa in normal_check **/src/nvim/normal.c:1381:5
    #9 0x555a58aed90a in state_enter **/src/nvim/state.c:30:35
    #10 0x555a584aa760 in normal_enter **/src/nvim/normal.c:471:3
    #11 0x555a581ce876 in main **/src/nvim/main.c:583:3
    #12 0x7f7078a5d2cf  (/usr/lib/libc.so.6+0x232cf) (BuildId: 9c28cfc869012ebbd43cdb0f1eebcd14e1b8bdd8)

SUMMARY: AddressSanitizer: heap-buffer-overflow **/src/nvim/grid.c:412:22 in grid_fill
Shadow bytes around the buggy address:
  0x0c267fff8ec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff8ed0: 00 00 00 00 00 00 00 00 00 00 00 00 00 fa fa fa
  0x0c267fff8ee0: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c267fff8ef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff8f00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c267fff8f10: 00 00 00 00 00 00 00 00 fa fa fa fa fa fa fa[fa]
  0x0c267fff8f20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff8f30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c267fff8f40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa
  0x0c267fff8f50: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c267fff8f60: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==558316==ABORTING
```

**Comment by Shougo** [comment]
I don't reproduce the problem.

> v0.8.0-dev-1070-g9b4cab012

It seems old.  Please use HEAD.  The HEAD is `NVIM v0.8.0-dev-2538-g907fc8ac3`.

**Comment by zeertzjq** [comment]
`:hi<Esc>` can be used instead of `:!ls /etc<Enter>`

**Comment by dimbleby** [comment]
v0.8.0-dev-1070-g9b4cab012 was HEAD at time of reporting, nothing relevant has changed since then.  

Per zeertzjq, this still reproduces at today's HEAD.

**Comment by Shougo** [comment]
Please test #20182.

**Comment by dimbleby** [comment]
well it doesn't crash, but also `g<` doesn't do anything now

**Comment by Shougo** [comment]
Hm... scrollback is broken.  But I don't know what is the right fix.

**Comment by dimbleby** [comment]
`nvim/message.c:2415: msg_scroll_flush: Assertion 'to_scroll >=0' failed.`

Please test these yourself - using me as a repl is kind of absurd.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/20188 is better.
So my PR is closed.
