### ISSUE TITLE
Crash in reset_synblock() when saving multiple buffers

### ISSUE THREAD

**Issue by nghialm269** [neovim/neovim#20197]
### Neovim version (nvim -v)

NVIM v0.8.0-dev-1091-gbf6de51f5

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty 0.10.1

### $TERM environment variable

tmux-256color

### Installation

Build from repo

### How to reproduce the issue

- Trigger LSP rename to trigger changes in multiple files
- Save all files using `:wa`
- Sometimes nvim saves successfully, sometimes crashes

full backtrace: 

[bt.txt](https://github.com/neovim/neovim/files/9565432/bt.txt)

### Expected behavior

Not crashed

### Actual behavior

nvim crashed

**Comment by zeertzjq** [comment]
Sounds similar to #19989

**Comment by karlc1** [comment]
Yesterday I spent over an hour writing a complicated function in go. When it was finally working, I was just going to move it to a different file before committing, so i yank-deleted it from the original file, pasted it in the new file and typed :wa. Neovim crashed, but not before actually saving the original file (where the function was deleted), so my work was lost.

I have had this issue before, but recently I encounter it more frequently, Not sure if it's because neovim changed or if I changed my workflow to save multiple files more often, but it's really starting to become a problem for me. It does not happen every time I try to save multiple files, but often enough. After the crash I  get a message like:

pkg/database/statements.go"free(): invalid pointer

**Comment by yutkat** [comment]
@karlc1 Are you using noice.nvim? If so, reverting back to before this commit(https://github.com/folke/noice.nvim/commit/13bed5763abd9a0c4c84abd794f26772cb850fe8) may improve this problem.
If you remove this line it will work.
https://github.com/folke/noice.nvim/blob/7b62ccfc236e51e78e5b2fc7d3068eacd65e4590/lua/noice/view/scrollbar.lua#L135

Note that this problem does not occur when autocmd is disabled or when the formatter is not set.

**Comment by Gelio** [comment]
I kept encountering this problem for quite some time. I've narrowed it down to [fidget.nvim](https://github.com/j-hui/fidget.nvim) causing it.

I've noticed that the actions that lead to the crash are:

1. I have some modified buffers with LSP with `vim.lsp.buf.format({ async = false })` on `BufWritePre` 
2. The buffers are in the background (hidden) - I have some other buffer open.
3. I do `:wqa`. This attempts to save the buffers. It first sends the formatting requests to the LSP servers due to the `BufWritePre` autocmd.
4. LSP servers send progress notifications to Neovim. fidget.nvim displays these notifications (creates windows and buffers)
5. After the formatting is done, fidget.nvim attempts to delete its windows and buffers.
6. When it gets to deleting some fidget.nvim buffer (the buffer which was created after `:wqa` started executing), Neovim crashes.

    I've noticed that at that time, the fidget.nvim buffer for some reason becomes the current buffer. I have no clue how that happens.

Backtrace: [bt.txt](https://github.com/j-hui/fidget.nvim/files/9945897/bt.txt)

I managed to come up with a workaround for figdet.nvim so it no longer crashes: https://github.com/j-hui/fidget.nvim/pull/111. The actual workaround for this crash is the conditional call of `vim.api.nvim_buf_delete`. It would be great if the workaround was not required.

**Comment by yutkat** [comment]
minimal init.lua.
markdownlint is required.

```lua
vim.cmd([[syntax enable]])
vim.cmd([[filetype plugin indent on]])

local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/opt/packer.nvim"
if vim.fn.empty(vim.fn.glob(install_path)) == 1 then
	vim.api.nvim_command("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
end
vim.cmd([[packadd packer.nvim]])
vim.o.termguicolors = true

local function load_plugins()
	return require("packer").startup(function()
		use({ "wbthomason/packer.nvim", opt = true })
		use({
			"folke/noice.nvim",
			requires = {
				"MunifTanjim/nui.nvim",
				"rcarriga/nvim-notify",
			},
			config = function()
				require("noice").setup({})
			end,
		})

		use({
			"jose-elias-alvarez/null-ls.nvim",
			event = "VimEnter",
			requires = { "nvim-lua/plenary.nvim" },
			config = function()
				local null_ls = require("null-ls")
				local sources = {
					null_ls.builtins.formatting.markdownlint.with({
						condition = function()
							return vim.fn.executable("markdownlint") > 0
						end,
					}),
				}
				null_ls.setup({
					sources = sources,
				})
			end,
		})
	end)
end
load_plugins()
```


https://user-images.githubusercontent.com/8683947/203376171-b3916cfd-2aeb-4d1b-895c-75c51e1cd353.mp4

**Comment by yutkat** [comment]
In my environment, I feel like the current HEAD(d25889ab7607918a152bab5ce4d14e54575ec11b) has fewer crashing events (but sometimes it crashes).

**Comment by yutkat** [comment]
new minimal init.lua

```lua
vim.cmd([[syntax enable]])
vim.cmd([[filetype plugin indent on]])

local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/opt/packer.nvim"
if vim.fn.empty(vim.fn.glob(install_path)) == 1 then
	vim.api.nvim_command("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
end
vim.cmd([[packadd packer.nvim]])
vim.cmd([[colorscheme desert]])
vim.o.termguicolors = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2

local function load_plugins()
	return require("packer").startup(function()
		use({ "wbthomason/packer.nvim", opt = true })
		use({
			"folke/noice.nvim",
			requires = {
				"MunifTanjim/nui.nvim",
				"rcarriga/nvim-notify",
			},
			config = function()
				require("noice").setup({})
			end,
		})

		use({
			"jose-elias-alvarez/null-ls.nvim",
			requires = { "nvim-lua/plenary.nvim" },
			config = function()
				local null_ls = require("null-ls")
				local sources = {
					null_ls.builtins.formatting.stylua,
					null_ls.builtins.formatting.prettier,
					null_ls.builtins.diagnostics.eslint,
				}
				local augroup = vim.api.nvim_create_augroup("LspFormatting", { clear = true })
				local on_attach = function(client, bufnr)
					if client.supports_method("textDocument/formatting") then
						vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
						vim.api.nvim_create_autocmd({ "BufWritePre" }, {
							group = augroup,
							buffer = bufnr,
							callback = function()
								vim.lsp.buf.format({ bufnr = bufnr })
							end,
						})
					end
				end

				null_ls.setup({
					debug = true,
					sources = sources,
					on_attach = on_attach,
				})
			end,
		})
		use({
			"neovim/nvim-lspconfig",
			config = function()
				require("lspconfig")["sumneko_lua"].setup({})
				require("lspconfig")["tsserver"].setup({})
			end,
		})
	end)
end

load_plugins()
```

1. `PackerSync`
2. `git clone https://github.com/maku77/template-nextjs-ts-eslint-prettier` (Anything made by typescript and using prettier)
3. cd template-nextjs-ts-eslint-prettier
4. `npm install`
5. watch the below video.


https://user-images.githubusercontent.com/8683947/203708577-c36c4812-7d3b-46f4-ac1c-e6ba38573250.mp4

**Comment by yutkat** [comment]
I've investigated and this problem seems to occur from this commit (126fe7fbc9c88c412c8067d9d146d998baf6dd47 https://github.com/neovim/neovim/pull/19916).

**Comment by zeertzjq** [comment]
Can you describe the steps using text instead of video?

**Comment by yutkat** [comment]
1. use this minimal init.lua
```lua
vim.cmd([[syntax enable]])
vim.cmd([[filetype plugin indent on]])

local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/opt/packer.nvim"
if vim.fn.empty(vim.fn.glob(install_path)) == 1 then
	vim.api.nvim_command("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
end
vim.cmd([[packadd packer.nvim]])
vim.cmd([[colorscheme desert]])
vim.o.termguicolors = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2

local function load_plugins()
	return require("packer").startup(function()
		use({ "wbthomason/packer.nvim", opt = true })
		use({
			"folke/noice.nvim",
			requires = {
				"MunifTanjim/nui.nvim",
				"rcarriga/nvim-notify",
			},
			config = function()
				require("noice").setup({})
			end,
		})

		use({
			"jose-elias-alvarez/null-ls.nvim",
			requires = { "nvim-lua/plenary.nvim" },
			config = function()
				local null_ls = require("null-ls")
				local sources = {
					null_ls.builtins.formatting.stylua,
					null_ls.builtins.formatting.prettier,
					null_ls.builtins.diagnostics.eslint,
				}
				local augroup = vim.api.nvim_create_augroup("LspFormatting", { clear = true })
				local on_attach = function(client, bufnr)
					if client.supports_method("textDocument/formatting") then
						vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
						vim.api.nvim_create_autocmd({ "BufWritePre" }, {
							group = augroup,
							buffer = bufnr,
							callback = function()
								vim.lsp.buf.format({ bufnr = bufnr })
							end,
						})
					end
				end

				null_ls.setup({
					debug = true,
					sources = sources,
					on_attach = on_attach,
				})
			end,
		})
		use({
			"neovim/nvim-lspconfig",
			config = function()
				require("lspconfig")["sumneko_lua"].setup({})
				require("lspconfig")["tsserver"].setup({})
			end,
		})
	end)
end

load_plugins()
```

2. Open `nvim`
3. `:PackerSync`
4. `:qa`
5. `git clone https://github.com/maku77/template-nextjs-ts-eslint-prettier` (Anything made by typescript and using prettier)
6. `cd template-nextjs-ts-eslint-prettier`
7. `npm install`
8. `nvim src/interfaces/index.ts src/utils/sample-data.ts`
9.  Edit src/interfaces/index.ts a little (insert line breaks, etc.)
10. `:bn` Move to the other buffer
11. `:wa` Save all buffers
12. nvim crashes with the following error
                                                                                                                                                                                                                   
```
free(): invalid pointer
[1]    45762 IOT instruction (core dumped)  nvim src/interfaces/index.ts src/utils/sample-data.ts
```

**Comment by zeertzjq** [comment]
Thanks. I can reproduce it.

**Comment by zeertzjq** [comment]
```
=================================================================
==194543==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x627000002c00 in thread T0
    #0 0x55c967519c02 in __interceptor_free.part.0 asan_malloc_linux.cpp.o
    #1 0x55c9682cb574 in xfree **/src/nvim/memory.c:136:3
    #2 0x55c968a5d9c8 in reset_synblock **/src/nvim/syntax.c:3016:5
    #3 0x55c9678426bf in set_curbuf **/src/nvim/buffer.c:1534:7
    #4 0x55c96783a9c1 in do_buffer **/src/nvim/buffer.c:1483:3
    #5 0x55c9675ccbb3 in nvim_buf_delete **/src/nvim/api/buffer.c:1130:16
    #6 0x55c96756b9ec in nlua_api_nvim_buf_delete **/build/src/nvim/auto/lua_api_c_bindings.generated.c:1154:3
    #7 0x55c968f68d15 in lj_BC_FUNCC (**/build/bin/nvim+0x2758d15) (BuildId: f48627b9752de85d4abd03100f8c77233e2f4423)
    #8 0x55c968f52a1a in lua_pcall **/.deps/build/src/luajit/src/lj_api.c:1145:12
    #9 0x55c9680b2d7d in nlua_pcall **/src/nvim/lua/executor.c:153:16
    #10 0x55c9680c0f82 in nlua_schedule_event **/src/nvim/lua/executor.c:332:7
    #11 0x55c967cea740 in multiqueue_process_events **/src/nvim/event/multiqueue.c:153:7
    #12 0x55c9680bedc1 in nlua_wait **/src/nvim/lua/executor.c:436:3
    #13 0x55c968f68d15 in lj_BC_FUNCC (**/build/bin/nvim+0x2758d15) (BuildId: f48627b9752de85d4abd03100f8c77233e2f4423)
    #14 0x55c968f52a1a in lua_pcall **/.deps/build/src/luajit/src/lj_api.c:1145:12
    #15 0x55c9680b2d7d in nlua_pcall **/src/nvim/lua/executor.c:153:16
    #16 0x55c9680b53cf in nlua_call_ref **/src/nvim/lua/executor.c:1531:7
    #17 0x55c96781e052 in call_autocmd_callback **/src/nvim/autocmd.c:2114:21
    #18 0x55c967819942 in getnextac **/src/nvim/autocmd.c:2196:9
    #19 0x55c967d6514f in do_cmdline **/src/nvim/ex_docmd.c:514:30
    #20 0x55c96780f9f3 in apply_autocmds_group **/src/nvim/autocmd.c:1894:5
    #21 0x55c967815bc3 in apply_autocmds_exarg **/src/nvim/autocmd.c:1577:10
    #22 0x55c967ead2d6 in buf_write **/src/nvim/fileio.c:2345:11
    #23 0x55c967d558f1 in buf_write_all **/src/nvim/ex_cmds2.c:436:13
    #24 0x55c967d26cf1 in do_wqall **/src/nvim/ex_cmds.c:2118:11
    #25 0x55c967d991ef in execute_cmd0 **/src/nvim/ex_docmd.c:1616:7
    #26 0x55c967d76204 in do_one_cmd **/src/nvim/ex_docmd.c:2272:7
    #27 0x55c967d65e5e in do_cmdline **/src/nvim/ex_docmd.c:579:20
    #28 0x55c9684065db in nv_colon **/src/nvim/normal.c:3213:20
    #29 0x55c9683f2815 in normal_execute **/src/nvim/normal.c:1180:3
    #30 0x55c968a01197 in state_enter **/src/nvim/state.c:99:26
    #31 0x55c9683d6260 in normal_enter **/src/nvim/normal.c:477:3
    #32 0x55c9680e37c0 in main **/src/nvim/main.c:595:3
    #33 0x7fef80a8028f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)
    #34 0x7fef80a80349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)
    #35 0x55c967465d44 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

0x627000002c00 is located 11008 bytes inside of 12448-byte region [0x627000000100,0x6270000031a0)
allocated by thread T0 here:
    #0 0x55c96751af71 in __interceptor_calloc (**/build/bin/nvim+0xd0af71) (BuildId: f48627b9752de85d4abd03100f8c77233e2f4423)
    #1 0x55c9682cb616 in xcalloc **/src/nvim/memory.c:150:15
    #2 0x55c96783bf33 in buflist_new **/src/nvim/buffer.c:1818:11
    #3 0x55c968e014f0 in win_alloc_firstwin **/src/nvim/window.c:3930:14
    #4 0x55c968e013c0 in win_alloc_first **/src/nvim/window.c:3896:7
    #5 0x55c9680e0365 in early_init **/src/nvim/main.c:205:3
    #6 0x55c9680e0e01 in main **/src/nvim/main.c:270:3
    #7 0x7fef80a8028f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)

SUMMARY: AddressSanitizer: bad-free asan_malloc_linux.cpp.o in __interceptor_free.part.0
==194543==ABORTING
```

**Comment by zeertzjq** [comment]
https://github.com/vim/vim/issues/11631

**Comment by yutkat** [comment]
Thank you very much :smile:  I can confirm that it will not crash anymore.
