### ISSUE TITLE
Segfault after switching tab page and dragging status line

### ISSUE THREAD

**Issue by wsx-ucb** [neovim/neovim#20780]
### Neovim version (nvim -v)

NVIM v0.8.0

### Vim (not Nvim) behaves the same?

Yes, for Vim 9.0.800

### Operating system/version

macOS 12.6

### Terminal name/version

iTerm2 3.5.0beta7, and also reproducible on other terminals

### $TERM environment variable

xterm-256color

### Installation

Nixpkgs

### How to reproduce the issue

First start with factory defaults `nvim --clean`.
Now click somewhere on the status line, and keep holding it and execute `:tabnew`.
After switching to the new tab (the mouse should still be held down), drag the mouse away from the status line.

### Expected behavior

Neovim should not segfault, and the status line should be dragged with the mouse after switching to the new tab page.

### Actual behavior

Neovim segfault with error `'nvim --clean' terminated by signal SIGSEGV (Address boundary error)`
<details>
<summary>Crash report</summary>

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               nvim [99398]
Path:                  /Volumes/VOLUME/*/nvim
Identifier:            nvim
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        fish [66911]
Responsible:           iTerm2 [1599]
User ID:               501

Date/Time:             2022-10-22 10:19:17.3370 -0700
OS Version:            macOS 12.6 (21G115)
Report Version:        12
Bridge OS Version:     6.6 (19P6067)
Anonymous UUID:        8ECCFA4C-65BD-ECB7-1F05-1A0BDC438543

Sleep/Wake UUID:       DCE0D47F-8C85-41C2-A875-BFC9E04F2D96

Time Awake Since Boot: 1500000 seconds
Time Since Wake:       1750 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [99398]

VM Region Info: 0 is not in any region.  Bytes before following region: 4546125824
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10ef86000-10f2c0000    [ 3304K] r-x/r-x SM=COW  ...VOLUME/*/nvim

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	       0x10f2461ff win_drag_status_line + 79
1   ???                           	       0x10f109e3d jump_to_mouse + 685
2   ???                           	       0x10f1176a4 do_mouse + 1700
3   ???                           	       0x10f11c6b7 normal_execute + 5943
4   ???                           	       0x10f1ebfaa state_enter + 106
5   ???                           	       0x10f116fd5 normal_enter + 133
6   ???                           	       0x10f0d283a main + 11178
7   dyld                          	       0x11eabe52e start + 462

Thread 1:
0   libsystem_kernel.dylib        	    0x7ff814d9a34e kevent + 10
1   ???                           	       0x10f516633 uv__io_poll + 995
2   ???                           	       0x10f5025a8 uv_run + 488
3   ???                           	       0x10f04d094 loop_poll_events + 116
4   ???                           	       0x10f213d2d tui_main + 637
5   libsystem_pthread.dylib       	    0x7ff814dd24e1 _pthread_start + 125
6   libsystem_pthread.dylib       	    0x7ff814dcdf6b thread_start + 15


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000001  rbx: 0x0000000000000018  rcx: 0x0000600001964300  rdx: 0x000060000196c040
  rdi: 0x00007f934b008200  rsi: 0x00000000ffffffff  rbp: 0x00007ff7b0f788a0  rsp: 0x00007ff7b0f78860
   r8: 0x0000000000000007   r9: 0x0000000000000001  r10: 0x0000000000000000  r11: 0x0000000000000212
  r12: 0x00000000ffffffff  r13: 0x0000000000000000  r14: 0x00000000ffffffff  r15: 0x000000010f2fa784
  rip: 0x000000010f2461ff  rfl: 0x0000000000010202  cr2: 0x0000000000000000
  
Logical CPU:     4
Error Code:      0x00000004 (no mapping for user data read)
Trap Number:     14

Thread 0 instruction stream:
  5c 41 5d 41 5e 41 5f 5d-c3 0f 1f 84 00 00 00 00  \A]A^A_]........
  00 55 48 89 e5 41 57 41-56 41 55 41 54 53 48 83  .UH..AWAVAUATSH.
  ec 18 41 89 f6 48 8b 05-55 9e 07 00 48 8b 00 48  ..A..H..U...H..H
  89 45 d0 48 8d 05 87 2e-0b 00 48 8b 00 48 85 c0  .E.H......H..H..
  75 07 c6 05 31 1e 0b 00-01 48 8b 57 58 48 8d 0d  u...1....H.WXH..
  a5 45 0b 00 48 8b 09 48-39 ca 74 10 4c 8b 6a 18  .E..H..H9.t.L.j.
 [41]80 7d 00 02 75 15 4c-89 ef eb 03 48 89 d7 49  A.}..u.L....H..I	<==
  89 d5 49 39 cd 75 2a e9-b7 00 00 00 49 39 cd 0f  ..I9.u*.....I9..
  84 ab 00 00 00 49 8b 7d-18 49 39 cd 0f 84 a1 00  .....I.}.I9.....
  00 00 66 2e 0f 1f 84 00-00 00 00 00 0f 1f 44 00  ..f...........D.
  00 49 83 7d 20 00 75 1d-48 39 cf 0f 84 7f 00 00  .I.} .u.H9......
  00 4c 8b 6f 18 49 39 cd-74 76 49 8b 7d 18 49 83  .L.o.I9.tvI.}.I.

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x11eab9000 -        0x11eb24fff dyld (*) <71febccd-d9dc-3599-9971-2b3407c588a8> /usr/lib/dyld
    0x7ff814d94000 -     0x7ff814dcbfff libsystem_kernel.dylib (*) <8cc28466-fd2f-3c80-9834-9525b7beac19> /usr/lib/system/libsystem_kernel.dylib
    0x7ff814dcc000 -     0x7ff814dd7fff libsystem_pthread.dylib (*) <b5454e27-e8c7-3fdb-b77f-714f1e82e70b> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=414.1M resident=0K(0%) swapped_out_or_unallocated=414.1M(100%)
Writable regions: Total=594.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=594.4M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                    8K        1 
MALLOC                           193.6M       33 
MALLOC guard page                   16K        4 
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
ObjC additional data                15K        1 
STACK GUARD                       56.0M        2 
Stack                             16.0M        2 
VM_ALLOCATE                        392K        5 
__DATA                            3119K      161 
__DATA_CONST                      5194K       82 
__DATA_DIRTY                       209K       50 
__LINKEDIT                       315.2M       39 
__TEXT                            98.8M      164 
__UNICODE                         1152K        2 
dyld private memory               1024K        1 
shared memory                       12K        2 
===========                     =======  ======= 
TOTAL                              1.0G      551 
TOTAL, minus reserved VM space   690.8M      551 



-----------
Full Report
-----------

{"app_name":"nvim","timestamp":"2022-10-22 10:19:17.00 -0700","app_version":"","slice_uuid":"00000000-0000-0000-0000-000000000000","build_version":"","platform":1,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.6 (21G115)","incident_id":"F681782D-E7DA-4E1F-A909-8C82B6CCC108","name":"nvim"}
{
  "uptime" : 1500000,
  "procLaunch" : "2022-10-22 10:18:58.3722 -0700",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,2",
  "procStartAbsTime" : 1583448633918796,
  "coalitionID" : 1473,
  "osVersion" : {
    "train" : "macOS 12.6",
    "build" : "21G115",
    "releaseType" : "User"
  },
  "captureTime" : "2022-10-22 10:19:17.3370 -0700",
  "incident" : "F681782D-E7DA-4E1F-A909-8C82B6CCC108",
  "bug_type" : "309",
  "pid" : 99398,
  "procExitAbsTime" : 1583467597444447,
  "cpuType" : "X86-64",
  "procName" : "nvim",
  "procPath" : "\/Volumes\/VOLUME\/*\/nvim",
  "parentProc" : "fish",
  "parentPid" : 66911,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "8ECCFA4C-65BD-ECB7-1F05-1A0BDC438543",
  "responsiblePid" : 1599,
  "responsibleProc" : "iTerm2",
  "wakeTime" : 1750,
  "bridgeVersion" : {"build":"19P6067","train":"6.6"},
  "sleepWakeUUID" : "DCE0D47F-8C85-41C2-A875-BFC9E04F2D96",
  "sip" : "enabled",
  "vmRegionInfo" : "0 is not in any region.  Bytes before following region: 4546125824\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10ef86000-10f2c0000    [ 3304K] r-x\/r-x SM=COW  ...VOLUME\/*\/nvim",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000000","rawCodes":[1,0],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000000"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":99398},
  "vmregioninfo" : "0 is not in any region.  Bytes before following region: 4546125824\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      10ef86000-10f2c0000    [ 3304K] r-x\/r-x SM=COW  ...VOLUME\/*\/nvim",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":17629673,"instructionState":{"instructionStream":{"bytes":[92,65,93,65,94,65,95,93,195,15,31,132,0,0,0,0,0,85,72,137,229,65,87,65,86,65,85,65,84,83,72,131,236,24,65,137,246,72,139,5,85,158,7,0,72,139,0,72,137,69,208,72,141,5,135,46,11,0,72,139,0,72,133,192,117,7,198,5,49,30,11,0,1,72,139,87,88,72,141,13,165,69,11,0,72,139,9,72,57,202,116,16,76,139,106,24,65,128,125,0,2,117,21,76,137,239,235,3,72,137,215,73,137,213,73,57,205,117,42,233,183,0,0,0,73,57,205,15,132,171,0,0,0,73,139,125,24,73,57,205,15,132,161,0,0,0,102,46,15,31,132,0,0,0,0,0,15,31,68,0,0,73,131,125,32,0,117,29,72,57,207,15,132,127,0,0,0,76,139,111,24,73,57,205,116,118,73,139,125,24,73,131],"offset":96}},"threadState":{"r13":{"value":0},"rax":{"value":1},"rflags":{"value":66050},"cpu":{"value":4},"r14":{"value":4294967295},"rsi":{"value":4294967295},"r8":{"value":7},"cr2":{"value":0},"rdx":{"value":105553142923328},"r10":{"value":0},"r9":{"value":1},"r15":{"value":4549748612,"symbolLocation":0,"symbol":"mouse_col"},"rbx":{"value":24},"trap":{"value":14,"description":"(no mapping for user data read)"},"err":{"value":4},"r11":{"value":530},"rip":{"value":4549009919,"matchesCrashFrame":1},"rbp":{"value":140701802662048},"rsp":{"value":140701802661984},"r12":{"value":4294967295},"rcx":{"value":105553142891264},"flavor":"x86_THREAD_STATE","rdi":{"value":140270595244544}},"queue":"com.apple.main-thread","frames":[{"imageOffset":4549009919,"symbol":"win_drag_status_line","symbolLocation":79,"imageIndex":0},{"imageOffset":4547714621,"symbol":"jump_to_mouse","symbolLocation":685,"imageIndex":0},{"imageOffset":4547770020,"symbol":"do_mouse","symbolLocation":1700,"imageIndex":0},{"imageOffset":4547790519,"symbol":"normal_execute","symbolLocation":5943,"imageIndex":0},{"imageOffset":4548640682,"symbol":"state_enter","symbolLocation":106,"imageIndex":0},{"imageOffset":4547768277,"symbol":"normal_enter","symbolLocation":133,"imageIndex":0},{"imageOffset":4547487802,"symbol":"main","symbolLocation":11178,"imageIndex":0},{"imageOffset":21806,"symbol":"start","symbolLocation":462,"imageIndex":1}]},{"id":17629674,"frames":[{"imageOffset":25422,"symbol":"kevent","symbolLocation":10,"imageIndex":2},{"imageOffset":4551960115,"symbol":"uv__io_poll","symbolLocation":995,"imageIndex":0},{"imageOffset":4551878056,"symbol":"uv_run","symbolLocation":488,"imageIndex":0},{"imageOffset":4546941076,"symbol":"loop_poll_events","symbolLocation":116,"imageIndex":0},{"imageOffset":4548803885,"symbol":"tui_main","symbolLocation":637,"imageIndex":0},{"imageOffset":25825,"symbol":"_pthread_start","symbolLocation":125,"imageIndex":3},{"imageOffset":8043,"symbol":"thread_start","symbolLocation":15,"imageIndex":3}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4809527296,
    "size" : 442368,
    "uuid" : "71febccd-d9dc-3599-9971-2b3407c588a8",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703478398976,
    "size" : 229376,
    "uuid" : "8cc28466-fd2f-3c80-9834-9525b7beac19",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703478628352,
    "size" : 49152,
    "uuid" : "b5454e27-e8c7-3fdb-b77f-714f1e82e70b",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 140703475372032,
  "size" : 19331678208,
  "uuid" : "73669942-bd8a-3e40-951f-7fbe07b51cb8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=414.1M resident=0K(0%) swapped_out_or_unallocated=414.1M(100%)\nWritable regions: Total=594.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=594.4M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                    8K        1 \nMALLOC                           193.6M       33 \nMALLOC guard page                   16K        4 \nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nObjC additional data                15K        1 \nSTACK GUARD                       56.0M        2 \nStack                             16.0M        2 \nVM_ALLOCATE                        392K        5 \n__DATA                            3119K      161 \n__DATA_CONST                      5194K       82 \n__DATA_DIRTY                       209K       50 \n__LINKEDIT                       315.2M       39 \n__TEXT                            98.8M      164 \n__UNICODE                         1152K        2 \ndyld private memory               1024K        1 \nshared memory                       12K        2 \n===========                     =======  ======= \nTOTAL                              1.0G      551 \nTOTAL, minus reserved VM space   690.8M      551 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
}
}
```
</details>

**Comment by zeertzjq** [comment]
UBSan:
```
**/src/nvim/window.c:5799:13: runtime error: member access within null pointer of type 'frame_T' (aka 'struct frame_S')
    #0 0x5614a3aac9e3 in win_drag_status_line **/src/nvim/window.c:5799:13
    #1 0x5614a2fcfbe0 in jump_to_mouse **/src/nvim/mouse.c:324:7
    #2 0x5614a3070402 in do_mouse **/src/nvim/normal.c:1904:16
    #3 0x5614a30d039b in nv_mouse **/src/nvim/normal.c:3441:9
    #4 0x5614a3096aa5 in normal_execute **/src/nvim/normal.c:1173:3
    #5 0x5614a36ac197 in state_enter **/src/nvim/state.c:88:26
    #6 0x5614a3066cb0 in normal_enter **/src/nvim/normal.c:471:3
    #7 0x5614a2d88ce0 in main **/src/nvim/main.c:580:3
    #8 0x7f44fe91b28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)
    #9 0x7f44fe91b349 in __libc_start_main (/usr/lib/libc.so.6+0x23349) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)
    #10 0x5614a212ed94 in _start /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/window.c:5799:13 in 
```
