### ISSUE TITLE
nvim --api-info broken on Windows

### ISSUE THREAD

**Issue by saep** [neovim/neovim#20977]
### Neovim version (nvim -v)

v0.8.0-1210-gd367ed9b2

### Vim (not Nvim) behaves the same?

not applicable

### Operating system/version

Windows 10

### Terminal name/version

any

### $TERM environment variable

any

### Installation

winget

### How to reproduce the issue

```
nvim --api-info | python -c "import msgpack, sys, yaml; yaml.dump(msgpack.unpackb(sys.stdin.buffer.read()), sys.stdout)"
```

### Expected behavior

`nvim --api-info` is parseable

### Actual behavior

Parsing breaks on Windows only.

I might be doing something wrong, but I think the output of `nvim --api-info` is broken on windows.

When running `nvim --api-info | python -c "import msgpack, sys, yaml; yaml.dump(msgpack.unpackb(sys.stdin.buffer.read()), sys.stdout)"` in various shells

- cmd or git-bash: `ValueError: <class 'int'> is not allowed for map key`

- Powershell: 
    ```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\saep\AppData\Local\Programs\Python\Python311\Lib\site-packages\msgpack\fallback.py", line 133, in unpackb
        raise ExtraData(ret, unpacker._get_extradata())
    msgpack.exceptions.ExtraData: unpack(b) received extra data.
    ```

I've noticed this when I was trying to make [nvim-hs compilable on Windows](https://github.com/neovimhaskell/nvim-hs/issues/100).
After I have hidden the unix-specific part behind a compiler flag, the code generation failed and I started investigating this.

I've attached the output of `nvim --api-info | base64` from git bash and my
linux build of nvim, so that it can be pasted
https://toolslick.com/conversion/data/messagepack-to-json# or something
similar.

[nixos-0.8.0.msgpack.b64.TXT](https://github.com/neovim/neovim/files/9946787/nixos-0.8.0.msgpack.b64.TXT)
[git-bash-0.8.0.msgpack.b64.TXT](https://github.com/neovim/neovim/files/9946788/git-bash-0.8.0.msgpack.b64.TXT)

For reference the Linux version (nixos-unstable):
   
    NVIM v0.8.0
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compiled by nixbld
    
    Features: +acl +iconv +tui

**Comment by justinmk** [comment]
Can you try redirecting `nvim --api-info` to a file and see if a CRLF was added or something like that?

**Comment by saep** [comment]
The first difference in the binary output is a CR before a LF (`0d 0a` instead of `0a`).

I've done these steps for the different command line prompts:

    nvim --api-info > some-file
    xxd some-file

Linux
```
00000000: 86a7 7665 7273 696f 6e87 a56d 616a 6f72  ..version..major
00000010: 00a5 6d69 6e6f 7208 a570 6174 6368 00aa  ..minor..patch..
00000020: 7072 6572 656c 6561 7365 c2a9 6170 695f  prerelease..api_
00000030: 6c65 7665 6c0a ae61 7069 5f63 6f6d 7061  level..api_compa
...
```

Windows cmd.exe and git-bash
```
00000000: 86a7 7665 7273 696f 6e87 a56d 616a 6f72  ..version..major
00000010: 00a5 6d69 6e6f 7208 a570 6174 6368 00aa  ..minor..patch..
00000020: 7072 6572 656c 6561 7365 c2a9 6170 695f  prerelease..api_
00000030: 6c65 7665 6c0d 0aae 6170 695f 636f 6d70  level...api_comp
...
```

Windows powershell (I guess you can'tdo this simple redirecting in powershell)
```
00000000: fffe e500 ba00 7600 6500 7200 7300 6900  ......v.e.r.s.i.
00000010: 6f00 6e00 e700 d100 6d00 6100 6a00 6f00  o.n.....m.a.j.o.
00000020: 7200 0000 d100 6d00 6900 6e00 6f00 7200  r.....m.i.n.o.r.
00000030: 0800 d100 7000 6100 7400 6300 6800 0000  ....p.a.t.c.h...
00000040: ac00 7000 7200 6500 7200 6500 6c00 6500  ..p.r.e.r.e.l.e.
00000050: 6100 7300 6500 2c25 1023 6100 7000 6900  a.s.e.,%.#a.p.i.
00000060: 5f00 6c00 6500 7600 6500 6c00 0d00 0a00  _.l.e.v.e.l.....
00000070: ab00 6100 7000 6900 5f00 6300 6f00 6d00  ..a.p.i._.c.o.m.
00000080: 7000 6100 7400 6900 6200 6c00 6500 0000  p.a.t.i.b.l.e...
00000090: ab00 6100 7000 6900 5f00 7000 7200 6500  ..a.p.i._.p.r.e.
...
```

**Comment by 3N4N** [comment]
In Ubuntu, PowerShell v7.2.7 outputs this:

```
00000000: efbf bdef bfbd 7665 7273 696f 6eef bfbd  ......version...
00000010: efbf bd6d 616a 6f72 00ef bfbd 6d69 6e6f  ...major....mino
00000020: 7209 efbf bd70 6174 6368 00ef bfbd 7072  r....patch....pr
00000030: 6572 656c 6561 7365 c3a9 6170 695f 6c65  erelease..api_le
00000040: 7665 6c0a efbf bd61 7069 5f63 6f6d 7061  vel....api_compa
00000050: 7469 626c 6500 efbf bd61 7069 5f70 7265  tible....api_pre
00000060: 7265 6c65 6173 65c2 a966 756e 6374 696f  release..functio
00000070: 6e73 efbf bd00 efbf bdef bfbd efbf bd73  ns.............s
```

**Comment by saep** [comment]
Just FYI: I can get the same output in powershell as with cmd/git-bash with the following command:

```
Start-Process -RedirectStandardOutput powershell-0.8.0.msgpack nvim -ArgumentList --api-info 
```

**Comment by justinmk** [comment]
So if I'm reading the above correctly, this is indeed likely a CRLF issue? Should be an easy fix.

**Comment by erw7** [comment]
> So if I'm reading the above correctly, this is indeed likely a CRLF issue? Should be an easy fix.

Yes. I don't know what the intent of those who obscure the issue by citing PowerShell is, but PowerShell pipeline encoding is a different matter (https://github.com/PowerShell/PowerShell/issues/1908). The only problem with Neovim is the conversion of newline codes(`LF` -> `CRLF`). I don't know why Window user contributors can't fix a problem as simple as this, but it should be fixed by simply calling `_setmode`.

Ref. https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=msvc-170

**Comment by 3N4N** [comment]
I didn't work on this issue.  That must be why I'm confused, but I don't understand what erw7 said.  For me, if the output of a command is the same in Windows+cmd and Linux+bash but different in powershell, then the obvious assumption is that there is something weird going on in powershell.

But, as I said, I didn't look into it, so maybe more than a cursory glance is needed to understand it.

On a different matter, I want to point out that [saep's comment][1] is wrong.  Or at least I got a different result:

```
PS C:\> nvim --api-info | xxd | head -4
00000000: c3a5 c2ba 7665 7273 696f 6ec3 a7c3 916d  ....version....m
00000010: 616a 6f72 00c3 916d 696e 6f72 09c3 9170  ajor...minor...p
00000020: 6174 6368 00c2 ac70 7265 7265 6c65 6173  atch...prereleas
00000030: 65e2 949c c2ae 6170 695f 6c65 7665 6c0b  e.....api_level.
```

[1]: https://github.com/neovim/neovim/issues/20977#issuecomment-1306012186

**Comment by erw7** [comment]
> For me, if the output of a command is the same in Windows+cmd and Linux+bash but different in powershell, then the obvious assumption is that there is something weird going on in powershell.

You should look more carefully at https://github.com/neovim/neovim/issues/20977#issuecomment-1306012186. Obviously, `0a`(LF) has changed to `0d0a` (CRLF).

#### Linux

 ```
...
0000030: 6c65 7665 6c0a ae61 7069 5f63 6f6d 7061  level..api_compa
...
```

#### Windows cmd.exe and git-bash

```
...
00000030: 6c65 7665 6c0d 0aae 6170 695f 636f 6d70  level...api_comp
...
```

> On a different matter, I want to point out that https://github.com/neovim/neovim/issues/20977#issuecomment-1306012186 is wrong. Or at least I got a different result:

In this Issue you should not mention PowerShell results. It only brings confusion and does nothing to help.

**Comment by 3N4N** [comment]
> I don't know why Window user contributors can't fix a problem as simple as this, but it should be fixed by simply calling `_setmode` or change to use `uv_fs_write()` instead of `write()`.

Umm.  So what's the fix?  I could test it out if you could elaborate.  Use `_setmode()` on what, stdout?  To what, binary?  `uv_fs_write()` instead of `write()` where?
