### ISSUE TITLE
when using shada, Neovim slow to exit and makes a large amount of irrelevant IO calls before exiting

### ISSUE THREAD

**Issue by dllu** [neovim/neovim#21082]
### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

no VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 19 2022 04:59:57)

### Operating system/version

Ubuntu 20.04

### Terminal name/version

alacritty 0.9.0

### $TERM environment variable

alacritty

### Installation

ppa:neovim-ppa/unstable

### How to reproduce the issue

Vim sometimes slow to close when there are other instances or recent instances that have opened files that are mounted through `sshfs`, even though I am not currently opening any files on `sshfs`.

1. mount some slow devices, e.g. using `sshfs` for remote servers that are physically locate thousands of kilometers away so that they have bad ping
2. open some files with nvim on the slow device
3. open a new instance of nvim, without opening any files, and try to close it quickly.

Please note: since this problem has to do with shada, I could not use `nvim --clean` (which disabled shada).

### Expected behavior

The Neovim that was opened in the last step should close quickly since I haven't opened any files with it so it should not be making any reads and writes. I don't really see any reason why it should touch the other files in the `shada` since I haven't opened any files in my current session.

### Actual behavior

Here is a gif of the behavior:

![vimslow mp4](https://user-images.githubusercontent.com/14482624/202317060-5b12fff9-d8be-4f31-a698-85bd4fc0290a.gif)

I have also opened `hx` just for comparison (it closes quickly).

Using `strace nvim 2> strace.log`, I notice that it is in fact making a ton of reads and writes. Unfortunately I cannot attach `strace.log` since it contains a lot of confidential data from my work machine.

However, here is a redacted exerpt of the strace log, where I have changed all of the actual slow paths to `/home/dllu/slow_path`. 
```
openat(AT_FDCWD, "/home/dllu/.local/state/nvim/shada/main.shada", O_RDONLY|O_CLOEXEC) = 26
statx(AT_FDCWD, "/home/dllu/.local/state/nvim/shada/main.shada", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|0x1000, stx_attributes=0, stx_mode=S_IFREG|0600, stx_size=144424, ...}) = 0
openat(AT_FDCWD, "/home/dllu/.local/state/nvim/shada/main.shada.tmp.a", O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW|O_CLOEXEC, 0600) = 27
brk(0x558f381f7000)                     = 0x558f381f7000
brk(0x558f382ce000)                     = 0x558f382ce000
brk(0x558f383a5000)                     = 0x558f383a5000
brk(0x558f3847c000)                     = 0x558f3847c000
brk(0x558f38553000)                     = 0x558f38553000
getpid()                                = 1884796
getcwd("/home/dllu", 1025)              = 11
getcwd("/home/dllu", 4096)              = 11
chdir("/home/dllu")                     = 0
chdir("/home/dllu/slow_path") = 0
getcwd("/home/dllu/slow_path", 4096) = 38
chdir("/home/dllu")                     = 0
statx(AT_FDCWD, "slow_path", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS|0x1000, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=30619, ...}) = 0
getcwd("/home/dllu", 1025)              = 11
getcwd("/home/dllu", 4096)              = 11
chdir("/home/dllu")                     = 0
chdir("/home/dllu/slow_path") = 0
getcwd("/home/dllu/slow_path", 4096) = 89
chdir("/home/dllu")                     = 0
statx(AT_FDCWD, "slow_path", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS|0x1000, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=5237, ...}) = 0
getcwd("/home/dllu", 1025)              = 11
getcwd("/home/dllu", 4096)              = 11
chdir("/home/dllu")                     = 0
chdir("/home/dllu/slow_path") = 0
getcwd("/home/dllu/slow_path", 4096) = 93
chdir("/home/dllu")                     = 0
statx(AT_FDCWD, "slow_path", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS|0x1000, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=43725, ...}) = 0
getcwd("/home/dllu", 1025)              = 11
getcwd("/home/dllu", 4096)              = 11
chdir("/home/dllu")                     = 0
chdir("/home/dllu/slow_path") = 0
getcwd("/home/dllu/slow_path", 4096) = 36
chdir("/home/dllu")                     = 0
statx(AT_FDCWD, "slow_path", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_BASIC_STATS|0x1000, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=1439, ...}) = 0
getcwd("/home/dllu", 1025)              = 11
getcwd("/home/dllu", 4096)              = 11
chdir("/home/dllu")                     = 0
chdir("/home/dllu/slow_path") = 0
getcwd("/home/dllu/slow_path", 4096) = 83
chdir("/home/dllu")                     = 0
```

However, when I set `set shada="NONE"` in my `init.vim`, it becomes lightning fast.

**Comment by AzerAfram** [comment]
What's the problem with changing the config/init file then testing on everything?

**Comment by AzerAfram** [comment]
@dllu, was `set shada` initialized by default?

**Comment by WGH-** [comment]
I'm having the same issue.

In my case, several of the once opened files are on `autofs` partition managed by systemd. I have set this up so my external HDD drive is lazily mounted on first access. However, when drive is not connected, every access syscall is very slow - it goes from kernel back to userspace, which has to check whether drive is connected or not before returning an error.

```
[pid 2747289] statx(AT_FDCWD, "/mnt/<redacted>/kek.sh", AT_STATX_SYNC_AS_STAT, STATX_ALL, 0x7ffc8458f6f0) = -1 ENODEV (No such device) <0.249575>
```

Almost 0.25 seconds for a single file!

**Comment by WGH-** [comment]
It's possible to add `AT_NO_AUTOMOUNT` flag to not trigger autofs automounting. 

But I don't think checking metadata of previously opened files on exit is a good idea. How this metadata is even used, anyway?

**Comment by zeertzjq** [comment]
It hard to know from this thread if this is caused by Nvim itself or some plugin. Does `:ls` show files that are in the slow paths before exiting?

**Comment by WGH-** [comment]
> Does `:ls` show files that are in the slow paths before exiting?

Nope.

Here's the stack trace, by the way:
```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f38ded6891b in ?? () from /usr/lib64/libuv.so.1
#2  0x00007f38ded57dc0 in ?? () from /usr/lib64/libuv.so.1
#3  0x00007f38ded59062 in ?? () from /usr/lib64/libuv.so.1
#4  0x00007f38ded5b630 in uv_fs_stat () from /usr/lib64/libuv.so.1
#5  0x0000560859b2dcd2 in os_stat (name=0x560859d4fb20 <NameBuff> "/mnt/<redacted>/kek.sh", statbuf=0x7ffc41a63e70)
    at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/os/fs.c:741
#6  0x00005608599930d0 in os_fileid (file_id=0x7ffc41a63e60, path=0x560859d4fb20 <NameBuff>"/mnt/<redacted>/kek.sh")
    at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/os/fs.c:1153
#7  buflist_new (ffname_arg=<optimized out>, sfname_arg=<optimized out>, lnum=1, flags=0) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/buffer.c:1749
#8  0x0000560859ac2049 in cleanup_jumplist (wp=0x56085bbb0b00, checktail=<optimized out>) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/mark.c:1389
#9  0x0000560859ba4fb2 in shada_write (sd_reader=0x7ffc41a640a0, sd_writer=0x7ffc41a64050) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/shada.c:2654
#10 shada_write_file (file=<optimized out>, nomerge=false) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/shada.c:3064
#11 0x0000560859aafdb5 in getout (exitval=0) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/main.c:693
#12 0x0000560859a3884f in ex_quit (eap=0x7ffc41a645c0) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/ex_docmd.c:4531
#13 ex_quit (eap=0x7ffc41a645c0) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/ex_docmd.c:4476
#14 0x0000560859c41fc5 in execute_cmd0.constprop.0 (retv=0x7ffc41a64538, eap=0x7ffc41a645c0, errormsg=0x7ffc41a64530, preview=<optimized out>)
    at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/ex_docmd.c:1620
#15 0x0000560859a3bd01 in do_one_cmd (cookie=0x0, fgetline=0x560859a4cf00 <getexline>, cstack=0x7ffc41a64780, flags=0, cmdlinep=0x7ffc41a64528)
    at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/ex_docmd.c:2275
#16 do_cmdline (cmdline=<optimized out>, fgetline=0x560859a4cf00 <getexline>, cookie=0x0, flags=0) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/ex_docmd.c:584
#17 0x0000560859afeac3 in nv_colon (cap=0x7ffc41a64e60) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/normal.c:4058
#18 0x0000560859af9040 in normal_execute (state=0x7ffc41a64de0, key=<optimized out>) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/normal.c:1172
#19 0x0000560859bc1fa1 in state_enter (s=0x7ffc41a64de0) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/state.c:88
#20 0x0000560859af62f0 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/normal.c:471
#21 0x000056085993c1b7 in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src/nvim/main.c:583
```

**Comment by WGH-** [comment]
Apparently, this is a dup of e.g. #12969 and #12075.

I don't agree that solution is satisfactory though.

**Comment by zeertzjq** [comment]
Regression from #10898
