### ISSUE TITLE
Memory leak with tabline click functions

### ISSUE THREAD

**Issue by erw7** [neovim/neovim#21765]
### Describe the bug

If the `'tabline'` contains the execute function label, a memory leak occurs.

```
==13812==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x4e31fd in malloc (/home/erw7/src/github.com/neovim/neovim/build/bin/nvim+0x4e31fd)
    #1 0x12e0712 in try_malloc /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/memory.c:89:15
    #2 0x12e08fc in xmalloc /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/memory.c:123:15
    #3 0x12e0e96 in xmallocz /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/memory.c:202:15
    #4 0x12e0fee in xmemdupz /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/memory.c:220:17
    #5 0x1a79e01 in build_stl_str_hl /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/statusline.c:1324:32
    #6 0x1a6a44b in win_redr_custom /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/statusline.c:370:11
    #7 0x1a6ca84 in draw_tabline /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/statusline.c:736:5
    #8 0x9e9c86 in update_screen /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/drawscreen.c:538:5
    #9 0x1471415 in normal_redraw /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/normal.c:1297:5
    #10 0x146edea in normal_check /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/normal.c:1389:5
    #11 0x1a58616 in state_enter /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/state.c:41:35
    #12 0x13f6a2c in normal_enter /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/normal.c:478:3
    #13 0x518352 in main /home/erw7/src/github.com/neovim/neovim/build/../src/nvim/main.c:628:3
    #14 0x7f4118b34082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: 5 byte(s) leaked in 1 allocation(s).
```

A call to `stl_clear_click_defs` is required in the following `if` clause as in the case of `winbar` and `statusline`.

https://github.com/neovim/neovim/blob/a37c686d21c1ad4e50f455e989642d38435d41ba/src/nvim/statusline.c#L284

### Steps to reproduce

```
nvim --clean --headless --listen /tmp/nvim.pipe
```

On other terminals

```vim
nvim --clean
:let con=sockconnect('pipe', '/tmp/nvim.pipe',#{rpc:v:true}) | call rpcrequest(con, 'nvim_command', 'set tal=%T%@Test@Test%X%X') | call rpcrequest(con, 'nvim_command', 'tabnew') | call rpcrequest(con, 'nvim_command', 'tabnew') | call rpcnotify(con, 'nvim_command', 'qa')
```

### Expected behavior

No memory leak

### Neovim version (nvim -v)

NVIM v0.9.0-dev-656+g93d99aefd

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

N/A

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

build from repo

**Comment by luukvbaal** [comment]
It seems this got lost in this refactor PR:
https://github.com/neovim/neovim/pull/21008/files#diff-909f74662e9735298c70bea7938380ca5cac521154fbf6e243d4c54b5ef82ccaL996-L998

I can add it back including a test, the original vim comment could use an update as well I think.

**Comment by zeertzjq** [comment]
I think it can be updated.
