### ISSUE TITLE
d06b4933ede420a294a9e2009b47eac0b89866e8 build fail on mac 

### ISSUE THREAD

**Issue by timfeirg** [neovim/neovim#2280]
this is the error messages:

```bash
Updating /Library/Caches/Homebrew/neovim--git
==> Checking out branch master
==> Downloading https://github.com/libuv/libuv/archive/v1.4.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libuv-1.4.2.tar.gz
==> Downloading https://github.com/msgpack/msgpack-c/archive/cpp-1.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--msgpack-1.0.0.tar.gz
==> Downloading http://luajit.org/download/LuaJIT-2.0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--luajit-2.0.3.tar.gz
==> Downloading https://github.com/keplerproject/luarocks/archive/0587afbb5fe8ceb2f2eea16f486bd6183bf02f29.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--luarocks-29.tar.gz
==> Downloading https://github.com/mauke/unibilium/archive/v1.1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libunibilium-1.1.2.tar.gz
==> Downloading https://github.com/neovim/libtermkey/archive/8c0cb7108cc63218ea19aa898968eede19e19603.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libtermkey-19603.tar.gz
==> Downloading https://github.com/neovim/libvterm/archive/1b745d29d45623aa8d22a7b9288c7b0e331c7088.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim--libvterm-7088.tar.gz
==> make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX:PATH=/usr/local/Cellar/neovim/HEAD" install

make[3]: *** [build/src/unibilium-stamp/unibilium-download] Error 1
make[2]: *** [CMakeFiles/unibilium.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [deps] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/neovim/homebrew-neovim/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect': Failed to connect to: https://api.github.com/search/issues?q=neovim+repo:Homebrew/homebrew+in:title+state:open&per_page=100 (GitHub::Error)
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:343:in `open'
	from /usr/local/Library/Homebrew/utils.rb:373:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:401:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:145:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:141:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:184:in `dump'
	from /usr/local/Library/brew.rb:162:in `rescue in <main>'
	from /usr/local/Library/brew.rb:65:in `<main>'
```

**Comment by jszakmeister** [comment]
Issues with Homebrew's Neovim recipe belong over [here](https://github.com/neovim/homebrew-neovim).  Do realize that github.com has been under attack?  See https://github.com/blog/1981-large-scale-ddos-attack-on-github-com and https://status.github.com/.  It has affected things like downloads (which is where your recipe failed), cloning the git repo, and other things.
