### ISSUE TITLE
Assert failure when resizing after multiline messages and calling screenstring() in VimResized

### ISSUE THREAD

**Issue by zeertzjq** [neovim/neovim#22919]
### Problem

Assert failure when resizing after multiline messages and calling screenstring() in VimResized

### Steps to reproduce

1. Run `nvim --clean`
2. Source the following file:
```vim
autocmd VimResized * call screenstring(1, 1)
echo "abc\ndef"
set lines=10
```
3. `message.c:2429: void msg_scroll_flush(void): Assertion `row >= 0' failed.`
```
                Stack trace of thread 185633:
                #0  0x00007feaeb42b8ec n/a (libc.so.6 + 0x878ec)
                #1  0x00007feaeb3dcea8 raise (libc.so.6 + 0x38ea8)
                #2  0x00007feaeb3c653d abort (libc.so.6 + 0x2253d)
                #3  0x00007feaeb3c645c n/a (libc.so.6 + 0x2245c)
                #4  0x00007feaeb3d59f6 __assert_fail (libc.so.6 + 0x319f6)
                #5  0x000055f4643b3932 msg_scroll_flush (nvim + 0x1d7932)
                #6  0x000055f4642e19f6 screenchar_adjust (nvim + 0x1059f6)
                #7  0x000055f464303453 f_screenstring (nvim + 0x127453)
                #8  0x000055f4642f200f call_internal_func (nvim + 0x11600f)
                #9  0x000055f464310556 call_func (nvim + 0x134556)
                #10 0x000055f464310968 get_func_tv (nvim + 0x134968)
                #11 0x000055f46431472b ex_call (nvim + 0x13872b)
                #12 0x000055f46432c5a4 execute_cmd0 (nvim + 0x1505a4)
                #13 0x000055f46432e42a do_one_cmd (nvim + 0x15242a)
                #14 0x000055f46432f008 do_cmdline (nvim + 0x153008)
                #15 0x000055f46429d3d4 apply_autocmds_group (nvim + 0xc13d4)
                #16 0x000055f46429d883 apply_autocmds (nvim + 0xc1883)
                #17 0x000055f4642d1488 screen_resize (nvim + 0xf5488)
                #18 0x000055f4643e3c83 set_num_option (nvim + 0x207c83)
                #19 0x000055f4643e58a2 do_set_num (nvim + 0x2098a2)
                #20 0x000055f4643e5aa9 do_set_option_value (nvim + 0x209aa9)
                #21 0x000055f4643e5fe4 do_set_option (nvim + 0x209fe4)
                #22 0x000055f4643e60c9 do_set (nvim + 0x20a0c9)
                #23 0x000055f4643e6306 ex_set (nvim + 0x20a306)
                #24 0x000055f46432c5a4 execute_cmd0 (nvim + 0x1505a4)
                #25 0x000055f46432e42a do_one_cmd (nvim + 0x15242a)
                #26 0x000055f46432f008 do_cmdline (nvim + 0x153008)
                #27 0x000055f464438c9a do_source (nvim + 0x25cc9a)
                #28 0x000055f464439204 cmd_source (nvim + 0x25d204)
                #29 0x000055f464439247 ex_source (nvim + 0x25d247)
                #30 0x000055f46432c5a4 execute_cmd0 (nvim + 0x1505a4)
                #31 0x000055f46432e42a do_one_cmd (nvim + 0x15242a)
                #32 0x000055f46432f008 do_cmdline (nvim + 0x153008)
                #33 0x000055f4643d04b8 nv_colon (nvim + 0x1f44b8)
                #34 0x000055f4643cf323 normal_execute (nvim + 0x1f3323)
                #35 0x000055f464468f85 state_enter (nvim + 0x28cf85)
                #36 0x000055f4643c7993 normal_enter (nvim + 0x1eb993)
                #37 0x000055f464254c41 main (nvim + 0x78c41)
                #38 0x00007feaeb3c7790 n/a (libc.so.6 + 0x23790)
                #39 0x00007feaeb3c784a __libc_start_main (libc.so.6 + 0x2384a)
                #40 0x000055f464250045 _start (nvim + 0x74045)
                ELF object binary architecture: AMD x86-64
```

### Expected behavior

No assert failure

### Neovim version (nvim -v)

v0.9.0-dev-1357+g68d6ca794

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
Actually anything that calls `msg_scroll_flush()` can cause this crash, including `:redraw` and `:sleep`.

**Comment by przepompownia** [comment]
@zeertzjq can you check if the following test reproduces this bug or exposes some other?
```lua
local configDir = vim.fn.expand('<sfile>:p:h')

vim.env['XDG_CONFIG_HOME'] = configDir
vim.env['XDG_DATA_HOME'] = configDir .. '/.xdg/data'
vim.env['XDG_STATE_HOME'] = configDir .. '/.xdg/state'
vim.env['XDG_CACHE_HOME'] = configDir .. '/.xdg/cache'
local stdPathConfig = vim.fn.stdpath('config')

vim.opt.runtimepath:prepend(stdPathConfig)
vim.opt.packpath:prepend(stdPathConfig)
local plugins_path = vim.fn.fnamemodify('plugins/', ':p')

for name, url in pairs {
  ['nui'] = 'https://github.com/MunifTanjim/nui.nvim',
  ['noice.nvim'] = 'https://github.com/folke/noice.nvim',
} do
  local install_path = plugins_path .. name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('noice').setup({})
vim.notify_once('\n')
```

I try to find something similar but it's not so easy. 

```cpp
                Stack trace of thread 485218:                                                                                                                                                                                                   
                #0  0x00007fa249def0ec __pthread_kill_implementation (libc.so.6 + 0x8a0ec)                                                                                                                                                      
                #1  0x00007fa249da1462 __GI_raise (libc.so.6 + 0x3c462)                                                                                                                                                                         
                #2  0x00007fa249d8b4b2 __GI_abort (libc.so.6 + 0x264b2)                                                                                                                                                                         
                #3  0x00007fa249d8b3d5 __assert_fail_base (libc.so.6 + 0x263d5)                                                                                                                                                                 
                #4  0x00007fa249d9a3a2 __assert_fail (libc.so.6 + 0x353a2)                                                                                                                                                                      
                #5  0x00005607cf7d3df1 msg_scroll_flush (nvim + 0x1ebdf1)                                                                                                                                                                       
                #6  0x00005607cf8b5cfb ui_flush (nvim + 0x2cdcfb)
                #7  0x00005607cf6f59e5 screen_resize (nvim + 0x10d9e5)
                #8  0x00005607cf8b4947 ui_refresh (nvim + 0x2cc947)
                #9  0x00005607cf8b6932 ui_add_cb (nvim + 0x2ce932)
                #10 0x00005607cf7a50ea n/a (nvim + 0x1bd0ea) 
                #11 0x00007fa24a030a26 n/a (libluajit-5.1.so.2 + 0xaa26)
                #12 0x00007fa24a08b1ee lua_pcall (libluajit-5.1.so.2 + 0x651ee)
                #13 0x00005607cf79f6d8 nlua_pcall (nvim + 0x1b76d8)
                #14 0x00005607cf7a3ff1 nlua_call_ref (nvim + 0x1bbff1)
                #15 0x00005607cf6c1231 n/a (nvim + 0xd9231)
                #16 0x00005607cf6c338f getnextac (nvim + 0xdb38f)
                #17 0x00005607cf751ec3 do_cmdline (nvim + 0x169ec3)
                #18 0x00005607cf6c1f49 apply_autocmds_group (nvim + 0xd9f49)
                #19 0x00005607cf6c25ff apply_autocmds (nvim + 0xda5ff)
                #20 0x00005607cf679077 main (nvim + 0x91077) 
                #21 0x00007fa249d8c6ca __libc_start_call_main (libc.so.6 + 0x276ca)
                #22 0x00007fa249d8c785 __libc_start_main_impl (libc.so.6 + 0x27785)
                #23 0x00005607cf674685 _start (nvim + 0x8c685)
                 
                Stack trace of thread 485220:
                #0  0x0000000000000000 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
```

**Comment by zeertzjq** [comment]
Another

**Comment by Grazfather** [comment]
I get a similar error (but the assertion is `to_scroll >= 0`).

I sometimes get it when I edit a fennel file, but only with "fennel.vim" installed.

I can reproduce it without opening a file when I add `-V2` to the command line. It goes away with `-u NONE`, so it's still something in my config causing it. Running v0.10.0-dev from the ubuntu unstable ppa.

**Comment by zeertzjq** [comment]
Related issues: #31002 #32319

**Comment by LorenzoPiombini** [comment]
I am working on a fix for issue #32319 and #31002, and i was trying to create a scenario where assert(to_scroll >= 0) fires.

and i might have came across another edge case.

step to reproduce:
run the build with --clean flag and source this file

```vim
" tiny screen
set lines=10 cmdheight=1

" Enable verbose output (equivalent to nvim -V2)
set verbose=2

" messages into the message grid
for i in range(1, 100)
  echomsg "msg " . i
endfor

"Autocmd that forces redraw (causes msg_grid_pos & discount desync)
autocmd VimResized * redraw

"multiple rapid resizes, triggering flush() repeatedly
set lines=15
set lines=8
set lines=12
set lines=9
set lines=14
```


when you see the screen:

<img width="661" height="470" alt="Image" src="https://github.com/user-attachments/assets/3890d005-360b-4282-a57e-53add79dd48b" />

hit k or up arrow key, to make the screen scrolling up one line:

<img width="1396" height="595" alt="Image" src="https://github.com/user-attachments/assets/da8625ed-63ee-434f-8cd3-28634eefb80a" />


now hold space to scroll all the way down, and you should see another crash related to assert failure:

src/nvim/ui.c:463: ui_line: Assertion `0 <= row && row < grid->rows' failed. 

back trace:
```gdb
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c4527e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7c2881b in __assert_fail_base (fmt=0x7ffff7dd01e8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x555555b3237d "0 <= row && row < grid->rows", 
    file=file@entry=0x555555b32358 "/home/lpiombini/neovim/src/nvim/ui.c", line=line@entry=463, 
    function=function@entry=0x555555b324a0 <__PRETTY_FUNCTION__.3> "ui_line") at ./assert/assert.c:96
#6  0x00007ffff7c3b517 in __assert_fail (assertion=0x555555b3237d "0 <= row && row < grid->rows", 
    file=0x555555b32358 "/home/lpiombini/neovim/src/nvim/ui.c", line=463, 
    function=0x555555b324a0 <__PRETTY_FUNCTION__.3> "ui_line") at ./assert/assert.c:105
#7  0x0000555555962040 in ui_line (grid=0x555555c3fbe0 <msg_grid>, row=14, invalid_row=false, startcol=0, 
    endcol=-1815690620, clearcol=118, clearattr=1, wrap=false) at /home/lpiombini/neovim/src/nvim/ui.c:463
#8  0x000055555581f19f in msg_scroll_flush () at /home/lpiombini/neovim/src/nvim/message.c:2614
#9  0x000055555596230f in ui_flush () at /home/lpiombini/neovim/src/nvim/ui.c:555
#10 0x0000555555732e68 in ex_redraw (eap=0x7fffffffb850) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:6779
#11 0x00005555557265e7 in execute_cmd0 (retv=0x7fffffffb808, eap=0x7fffffffb850, errormsg=0x7fffffffb820, 
    preview=false) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:1762
#12 0x0000555555728424 in do_one_cmd (cmdlinep=0x7fffffffba70, flags=7, cstack=0x7fffffffbb80, 
    fgetline=0x55555564f347 <getnextac>, cookie=0x7fffffffc1a0) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:2392
#13 0x0000555555723dee in do_cmdline (cmdline=0x0, fgetline=0x55555564f347 <getnextac>, cookie=0x7fffffffc1a0, 
    flags=7) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:679
#14 0x000055555564e679 in apply_autocmds_group (event=EVENT_VIMRESIZED, fname=0x555555c897e0 "", fname_io=0x0, 
    force=false, group=-3, buf=0x555555c79550, eap=0x0, data=0x0) at /home/lpiombini/neovim/src/nvim/autocmd.c:1872
#15 0x000055555564da88 in apply_autocmds (event=EVENT_VIMRESIZED, fname=0x0, fname_io=0x0, force=false, 
    buf=0x555555c79550) at /home/lpiombini/neovim/src/nvim/autocmd.c:1507
#16 0x000055555569e2f3 in screen_resize (width=118, height=15) at /home/lpiombini/neovim/src/nvim/drawscreen.c:352
#17 0x0000555555855490 in did_set_lines_or_columns (args=0x7fffffffc430)
    at /home/lpiombini/neovim/src/nvim/option.c:2135
#18 0x00005555558583a7 in did_set_option (opt_idx=kOptLines, varp=0x555555c5b9a0 <p_lines>, old_value=..., 
    new_value=..., opt_flags=0, set_sid=0, direct=false, value_replaced=true, errbuf=0x7fffffffc7a0 "\001", 
    errbuflen=80) at /home/lpiombini/neovim/src/nvim/option.c:3485
#19 0x0000555555859127 in set_option (opt_idx=kOptLines, value=..., opt_flags=0, set_sid=0, direct=false, 
    value_replaced=true, errbuf=0x7fffffffc7a0 "\001", errbuflen=80) at /home/lpiombini/neovim/src/nvim/option.c:3719
#20 0x00005555558535d2 in do_one_set_option (opt_flags=0, argp=0x7fffffffc778, did_show=0x7fffffffc787, 
    errbuf=0x7fffffffc7a0 "\001", errbuflen=80, errmsg=0x7fffffffc790)
    at /home/lpiombini/neovim/src/nvim/option.c:1335
#21 0x0000555555853799 in do_set (arg=0x555555cc2719 "=15", opt_flags=0)
    at /home/lpiombini/neovim/src/nvim/option.c:1384
#22 0x0000555555851d38 in ex_set (eap=0x7fffffffc910) at /home/lpiombini/neovim/src/nvim/option.c:733
#23 0x00005555557265e7 in execute_cmd0 (retv=0x7fffffffc8c8, eap=0x7fffffffc910, errormsg=0x7fffffffc8e0, 
    preview=false) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:1762
#24 0x0000555555728424 in do_one_cmd (cmdlinep=0x7fffffffcb30, flags=7, cstack=0x7fffffffcc40, 
    fgetline=0x5555558d2722 <getsourceline>, cookie=0x7fffffffd240)
    at /home/lpiombini/neovim/src/nvim/ex_docmd.c:2392
#25 0x0000555555723dee in do_cmdline (
    cmdline=0x555555cc1e80 "\" Make the screen tiny (forces heavy message scrolling)", 
    fgetline=0x5555558d2722 <getsourceline>, cookie=0x7fffffffd240, flags=7)
    at /home/lpiombini/neovim/src/nvim/ex_docmd.c:679
#26 0x00005555558d190b in do_source_ext (fname=0x555555cc32f7 "trigger_assert_toscroll", check_other=false, 
    is_vimrc=0, ret_sid=0x0, eap=0x0, ex_lua=false, str=0x0) at /home/lpiombini/neovim/src/nvim/runtime.c:2294
#27 0x00005555558d1cec in do_source (fname=0x555555cc32f7 "trigger_assert_toscroll", check_other=false, is_vimrc=0, 
    ret_sid=0x0) at /home/lpiombini/neovim/src/nvim/runtime.c:2369
#28 0x00005555558d070b in cmd_source (fname=0x555555cc32f7 "trigger_assert_toscroll", eap=0x7fffffffd420)
    at /home/lpiombini/neovim/src/nvim/runtime.c:1861
#29 0x00005555558d075d in ex_source (eap=0x7fffffffd420) at /home/lpiombini/neovim/src/nvim/runtime.c:1869
#30 0x00005555557265e7 in execute_cmd0 (retv=0x7fffffffd3d8, eap=0x7fffffffd420, errormsg=0x7fffffffd3f0, 
    preview=false) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:1762
#31 0x0000555555728424 in do_one_cmd (cmdlinep=0x7fffffffd640, flags=0, cstack=0x7fffffffd750,
#22 0x0000555555851d38 in ex_set (eap=0x7fffffffc910) at /home/lpiombini/neovim/src/nvim/option.c:733
#23 0x00005555557265e7 in execute_cmd0 (retv=0x7fffffffc8c8, eap=0x7fffffffc910, errormsg=0x7fffffffc8e0, 
    preview=false) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:1762
#24 0x0000555555728424 in do_one_cmd (cmdlinep=0x7fffffffcb30, flags=7, cstack=0x7fffffffcc40, 
    fgetline=0x5555558d2722 <getsourceline>, cookie=0x7fffffffd240)
    at /home/lpiombini/neovim/src/nvim/ex_docmd.c:2392
#25 0x0000555555723dee in do_cmdline (
    cmdline=0x555555cc1e80 "\" Make the screen tiny (forces heavy message scrolling)", 
    fgetline=0x5555558d2722 <getsourceline>, cookie=0x7fffffffd240, flags=7)
    at /home/lpiombini/neovim/src/nvim/ex_docmd.c:679
#26 0x00005555558d190b in do_source_ext (fname=0x555555cc32f7 "trigger_assert_toscroll", check_other=false, 
    is_vimrc=0, ret_sid=0x0, eap=0x0, ex_lua=false, str=0x0) at /home/lpiombini/neovim/src/nvim/runtime.c:2294
#27 0x00005555558d1cec in do_source (fname=0x555555cc32f7 "trigger_assert_toscroll", check_other=false, is_vimrc=0, 
    ret_sid=0x0) at /home/lpiombini/neovim/src/nvim/runtime.c:2369
#28 0x00005555558d070b in cmd_source (fname=0x555555cc32f7 "trigger_assert_toscroll", eap=0x7fffffffd420)
    at /home/lpiombini/neovim/src/nvim/runtime.c:1861
#29 0x00005555558d075d in ex_source (eap=0x7fffffffd420) at /home/lpiombini/neovim/src/nvim/runtime.c:1869
#30 0x00005555557265e7 in execute_cmd0 (retv=0x7fffffffd3d8, eap=0x7fffffffd420, errormsg=0x7fffffffd3f0, 
    preview=false) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:1762
#31 0x0000555555728424 in do_one_cmd (cmdlinep=0x7fffffffd640, flags=0, cstack=0x7fffffffd750, 
--Type <RET> for more, q to quit, c to continue without paging--
    fgetline=0x55555574250c <getexline>, cookie=0x0) at /home/lpiombini/neovim/src/nvim/ex_docmd.c:2392
#32 0x0000555555723dee in do_cmdline (cmdline=0x0, fgetline=0x55555574250c <getexline>, cookie=0x0, flags=0)
    at /home/lpiombini/neovim/src/nvim/ex_docmd.c:679
#33 0x000055555583b456 in nv_colon (cap=0x7fffffffddc0) at /home/lpiombini/neovim/src/nvim/normal.c:3197
#34 0x0000555555836ebc in normal_execute (state=0x7fffffffdd50, key=58)
    at /home/lpiombini/neovim/src/nvim/normal.c:1253
#35 0x000055555591583a in state_enter (s=0x7fffffffdd50) at /home/lpiombini/neovim/src/nvim/state.c:100
#36 0x0000555555834fb0 in normal_enter (cmdwin=false, noexmode=false) at /home/lpiombini/neovim/src/nvim/normal.c:523
#37 0x00005555557d5bae in main (argc=3, argv=0x7fffffffe158) at /home/lpiombini/neovim/src/nvim/main.c:658
```
it does happen only with this steps. 

if you go up one line on the first screen, and scroll line by line with down arrow key or j, it won't cause assertion failure.
if you go up one line at the first screen, and you then go down one line, and use space to fast scroll, it won't crashes

my build version is :

NVIM v0.12.0-dev-1705+g1cc905ed45-dirty
Build type: Debug
LuaJIT 2.1.1763318511
Compilation: /usr/bin/cc -g  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wno-unused-function -fsigned-char -fstack-protector-strong -Wno-conversion -fno-common -Wimplicit-fallthrough -fdiagnostics-color=auto  -DHAVE_UNIBILIUM -DNVIM_LOG_DEBUG -DUNIT_TESTING -D_GNU_SOURCE -DUTF8PROC_STATIC -I/home/lpiombini/neovim/.deps/usr/include/luajit-2.1 -I/home/lpiombini/neovim/.deps/usr/include -I/home/lpiombini/neovim/build/src/nvim/auto -I/home/lpiombini/neovim/build/include -I/home/lpiombini/neovim/build/cmake.config -I/home/lpiombini/neovim/src -I/usr/include 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"


it does not happen in the older version that i have installed on my server via apt package manager:


NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

does it happen on your machine/set up???
