### ISSUE TITLE
Segfault while running :Neomake!

### ISSUE THREAD

**Issue by Moeryn** [neovim/neovim#2309]
I was trying a neovim plugin: https://github.com/benekastah/neomake

I simply did:

```
   :Neomake!
```

And nvim crashed while executing the job.

I compile nvim from 27ead64:

```
   make; sudo make install
```

Here is the backtrace.

```
#0  0x00007f734283fa56 in _int_malloc (av=0x7f7342b4de40, bytes=79) at malloc.c:4665
#1  0x00007f7342841a70 in *__GI___libc_malloc (bytes=79) at malloc.c:3660
#2  0x00007f7342846ab2 in *__GI___strdup (s=0x19d5270 ' ' <repeats 24 times>, "exe 'sign unplace '.existing.id.' buffer='.entry.bufnr") at strdup.c:43
#3  0x00000000005e6536 in xstrdup (str=0x19d5270 ' ' <repeats 24 times>, "exe 'sign unplace '.existing.id.' buffer='.entry.bufnr") at /neovim/src/nvim/memory.c:365
#4  0x00000000005e52cc in vim_strsave (string=0x19d5270 ' ' <repeats 24 times>, "exe 'sign unplace '.existing.id.' buffer='.entry.bufnr") at /neovim/src/nvim/strings.c:54
#5  0x00000000004c44b3 in store_loop_line (gap=0x7fff269a1a10, line=0x19d5270 ' ' <repeats 24 times>, "exe 'sign unplace '.existing.id.' buffer='.entry.bufnr") at /neovim/src/nvim/ex_docmd.c:1017
#6  0x00000000004c3609 in do_cmdline (cmdline=0x0, fgetline=0x5a52e6 <get_func_line>, cookie=0x19db680, flags=7) at /neovim/src/nvim/ex_docmd.c:579
#7  0x00000000005a47b3 in call_user_func (fp=0x19628c0, argcount=1, argvars=0x7fff269a2400, rettv=0x7fff269a25c0, firstline=238, lastline=238, selfdict=0x0) at /neovim/src/nvim/eval.c:19016
#8  0x000000000058b6cf in call_func (funcname=0x1a158a0 "\200\375Q116_AddExprCallback", len=22, rettv=0x7fff269a25c0, argcount=1, argvars=0x7fff269a2400, firstline=238, lastline=238, doesrange=0x7fff269a25bc, evaluate=1, selfdict=0x0) at /neovim/src/nvim/eval.c:6964
#9  0x000000000058b2e1 in get_func_tv (name=0x1a158a0 "\200\375Q116_AddExprCallback", len=22, rettv=0x7fff269a25c0, arg=0x7fff269a25e0, firstline=238, lastline=238, doesrange=0x7fff269a25bc, evaluate=1, selfdict=0x0) at /neovim/src/nvim/eval.c:6830
#10 0x0000000000583fc7 in ex_call (eap=0x7fff269a26a0) at /neovim/src/nvim/eval.c:2706
#11 0x00000000004c62b5 in do_one_cmd (cmdlinep=0x7fff269a2d00, sourcing=1, cstack=0x7fff269a2860, fgetline=0x5a52e6 <get_func_line>, cookie=0x1a1b210) at /neovim/src/nvim/ex_docmd.c:1914
#12 0x00000000004c373b in do_cmdline (cmdline=0x0, fgetline=0x5a52e6 <get_func_line>, cookie=0x1a1b210, flags=7) at /neovim/src/nvim/ex_docmd.c:620
#13 0x00000000005a47b3 in call_user_func (fp=0x19861e0, argcount=2, argvars=0x7fff269a3230, rettv=0x7fff269a33f0, firstline=238, lastline=238, selfdict=0x0) at /neovim/src/nvim/eval.c:19016
#14 0x000000000058b6cf in call_func (funcname=0x19d78d0 "\200\375Q116_ProcessJobOutput", len=23, rettv=0x7fff269a33f0, argcount=2, argvars=0x7fff269a3230, firstline=238, lastline=238, doesrange=0x7fff269a33ec, evaluate=1, selfdict=0x0) at /neovim/src/nvim/eval.c:6964
#15 0x000000000058b2e1 in get_func_tv (name=0x19d78d0 "\200\375Q116_ProcessJobOutput", len=23, rettv=0x7fff269a33f0, arg=0x7fff269a3410, firstline=238, lastline=238, doesrange=0x7fff269a33ec, evaluate=1, selfdict=0x0) at /neovim/src/nvim/eval.c:6830
#16 0x0000000000583fc7 in ex_call (eap=0x7fff269a34d0) at /neovim/src/nvim/eval.c:2706
#17 0x00000000004c62b5 in do_one_cmd (cmdlinep=0x7fff269a3b30, sourcing=1, cstack=0x7fff269a3690, fgetline=0x5a52e6 <get_func_line>, cookie=0x1a14dc0) at /neovim/src/nvim/ex_docmd.c:1914
#18 0x00000000004c373b in do_cmdline (cmdline=0x0, fgetline=0x5a52e6 <get_func_line>, cookie=0x1a14dc0, flags=7) at /neovim/src/nvim/ex_docmd.c:620
#19 0x00000000005a47b3 in call_user_func (fp=0x1914190, argcount=3, argvars=0x7fff269a4060, rettv=0x7fff269a4220, firstline=238, lastline=238, selfdict=0x0) at /neovim/src/nvim/eval.c:19016
#20 0x000000000058b6cf in call_func (funcname=0x19bba40 "\200\375Q116_RegisterJobOutput", len=24, rettv=0x7fff269a4220, argcount=3, argvars=0x7fff269a4060, firstline=238, lastline=238, doesrange=0x7fff269a421c, evaluate=1, selfdict=0x0) at /neovim/src/nvim/eval.c:6964
#21 0x000000000058b2e1 in get_func_tv (name=0x19bba40 "\200\375Q116_RegisterJobOutput", len=24, rettv=0x7fff269a4220, arg=0x7fff269a4240, firstline=238, lastline=238, doesrange=0x7fff269a421c, evaluate=1, selfdict=0x0) at /neovim/src/nvim/eval.c:6830
#22 0x0000000000583fc7 in ex_call (eap=0x7fff269a4300) at /neovim/src/nvim/eval.c:2706
#23 0x00000000004c62b5 in do_one_cmd (cmdlinep=0x7fff269a4960, sourcing=1, cstack=0x7fff269a44c0, fgetline=0x5a52e6 <get_func_line>, cookie=0x1a25930) at /neovim/src/nvim/ex_docmd.c:1914
#24 0x00000000004c373b in do_cmdline (cmdline=0x0, fgetline=0x5a52e6 <get_func_line>, cookie=0x1a25930, flags=7) at /neovim/src/nvim/ex_docmd.c:620
#25 0x00000000005a47b3 in call_user_func (fp=0x1987c60, argcount=3, argvars=0x7fff269a4db0, rettv=0x7fff269a4da0, firstline=238, lastline=238, selfdict=0x19d9cc0) at /neovim/src/nvim/eval.c:19016
#26 0x00000000005a7947 in on_job_event (event=...) at /neovim/src/nvim/eval.c:20279
#27 0x00000000005ecd5b in process_events_from (queue=0x1438810) at /neovim/src/nvim/os/event.c:182
#28 0x00000000005ecd37 in event_process () at /neovim/src/nvim/os/event.c:174
#29 0x000000000055de2c in normal_cmd (oap=0x7fff269a4f30, toplevel=true) at /neovim/src/nvim/normal.c:491
#30 0x00000000005c384f in main_loop (cmdwin=0, noexmode=0) at /neovim/src/nvim/main.c:708
#31 0x00000000005c3268 in main (argc=2, argv=0x7fff269a5218) at /neovim/src/nvim/main.c:495
```

**Comment by justinmk** [comment]
@Moeryn can you try latest master? The event system underwent major changes.

**Comment by justinmk** [comment]
Please re-open if you are able to reproduce on latest.
