### ISSUE TITLE
Segfault while running :Neomake pylint

### ISSUE THREAD

**Issue by Moeryn** [neovim/neovim#2310]
I was trying a neovim plugin: https://github.com/benekastah/neomake

I simply did:
```
   :Neomake pylint
```
And nvim crashed while executing the job.

I compile nvim from 27ead64:
```
   make; sudo make install
```
Here is the backtrace.

```
#0  0x00007f7bbef6d165 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007f7bbef703e0 in *__GI_abort () at abort.c:92
#2  0x00007f7bbefa739b in __libc_message (do_abort=<optimized out>, fmt=<optimized out>) at ../sysdeps/unix/sysv/linux/libc_fatal.c:189
#3  0x00007f7bbefb0be6 in malloc_printerr (action=3, str=0x7f7bbf08b270 "double free or corruption (!prev)", ptr=<optimized out>) at malloc.c:6312
#4  0x00007f7bbefb598c in *__GI___libc_free (mem=<optimized out>) at malloc.c:3738
#5  0x0000000000589b29 in dict_free (d=0x2aec880, recurse=1) at /neovim/src/nvim/eval.c:5741
#6  0x00000000005899b3 in dict_unref (d=0x2aec880) at /neovim/src/nvim/eval.c:5698
#7  0x00000000005a7346 in free_term_job_data (data=0x2b1fe00) at /neovim/src/nvim/eval.c:20102
#8  0x00000000005a7842 in term_job_data_decref (data=0x2b1fe00) at /neovim/src/nvim/eval.c:20237
#9  0x00000000005a7989 in on_job_event (event=...) at /neovim/src/nvim/eval.c:20287
#10 0x00000000005ecd5b in process_events_from (queue=0x25998b0) at /neovim/src/nvim/os/event.c:182
#11 0x00000000005ecd37 in event_process () at /neovim/src/nvim/os/event.c:174
#12 0x000000000055de2c in normal_cmd (oap=0x7ffffb45e540, toplevel=true) at /neovim/src/nvim/normal.c:491
#13 0x00000000005c384f in main_loop (cmdwin=0, noexmode=0) at /neovim/src/nvim/main.c:708
#14 0x00000000005c3268 in main (argc=2, argv=0x7ffffb45e828) at /neovim/src/nvim/main.c:495
```

**Comment by justinmk** [comment]
@Moeryn can you try latest master? The event system underwent major changes.
