### ISSUE TITLE
`:substitute` with expression replacement containing method call crashes neovim

### ISSUE THREAD

**Issue by tmillr** [neovim/neovim#23321]
### Problem

Open nvim.
Type in `:s/^/\=submatch(0)->printf(`.
Now type in `)` and nvim will crash.

I tried it out real quick in vim and it didn't crash, but it might need more investigation.

## Some things to note

* The pattern doesn't seem to matter, it just has to match.

* The exit code is **139**.

* With `LHS->printf()`, LHS goes in as the 2nd arg to printf, not the 1st.

* It doesn't crash if the pattern doesn't match, or if an arg is provided to `printf()` before typing the ending `)`.

* It also crashes if you type `:s/^/\=submatch(0)->printf('%s')` and then remove the argument to `printf()` by hand (e.g. by hitting backspace until the arg is gone and only `:s/^/\=submatch(0)->printf()` remains).

* It **doesn't** crash if you **don't** call it/type it out as a method (e.g. `:s/^/\=printf('%s', submatch(0))`, `:s/^/\=printf(submatch(0))`, or even `:s/^/\=printf()`).

* When I tried to reproduce the crash in vim real quick, I invoked vim with `vim -i NONE -u NONE -n`.

Maybe the reason vim doesn't crash is simply due to a difference between vim and nvim when it comes to default option settings?

### Steps to reproduce

1. Start Neovim: `nvim -i NONE -u NONE -n`
2. Type in: `:s/^/\=submatch(0)->printf(`
3. Now type `)`, and neovim crashes

### Expected behavior

shouldn't crash

### Neovim version (nvim -v)

NVIM v0.9.0, build: Release

### Vim (not Nvim) behaves the same?

TODO

### Operating system/version

macOS Ventura 13.2

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Installation

homebrew

**Comment by zeertzjq** [comment]
ASAN log:
```
=================================================================
==562411==ERROR: AddressSanitizer: negative-size-param: (size=-16)
    #0 0x55c9c4f604e8 in __asan_memcpy (**/build/bin/nvim+0xc734e8) (BuildId: 4118ba17f78a25d8e6b6374bdd0ae3e88f0256cd)
    #1 0x55c9c56494e9 in call_internal_method **/src/nvim/eval/funcs.c:292:3
    #2 0x55c9c574ce50 in call_func **/src/nvim/eval/userfunc.c:1714:15
    #3 0x55c9c574948d in get_func_tv **/src/nvim/eval/userfunc.c:556:11
    #4 0x55c9c55c0d11 in eval_func **/src/nvim/eval.c:2278:13
    #5 0x55c9c558f6b9 in eval_method **/src/nvim/eval.c:3448:13
    #6 0x55c9c558cbf2 in handle_subscript **/src/nvim/eval.c:7334:15
    #7 0x55c9c55b8b9e in eval7 **/src/nvim/eval.c:3213:11
    #8 0x55c9c55b5119 in eval6 **/src/nvim/eval.c:2922:7
    #9 0x55c9c55b328d in eval5 **/src/nvim/eval.c:2778:7
    #10 0x55c9c55b1c42 in eval4 **/src/nvim/eval.c:2653:7
    #11 0x55c9c55b0a3d in eval3 **/src/nvim/eval.c:2562:7
    #12 0x55c9c55599ad in eval2 **/src/nvim/eval.c:2484:7
    #13 0x55c9c5548d1c in eval1 **/src/nvim/eval.c:2388:7
    #14 0x55c9c5545c7f in eval0 **/src/nvim/eval.c:2343:9
    #15 0x55c9c554a474 in eval_to_string **/src/nvim/eval.c:934:7
    #16 0x55c9c6107ae3 in vim_regsub_both **/src/nvim/regexp.c:1824:31
    #17 0x55c9c610d8b4 in vim_regsub_multi **/src/nvim/regexp.c:1696:16
    #18 0x55c9c581c392 in do_sub **/src/nvim/ex_cmds.c:3914:20
    #19 0x55c9c58241dc in ex_substitute_preview **/src/nvim/ex_cmds.c:4692:16
    #20 0x55c9c586f161 in execute_cmd0 **/src/nvim/ex_docmd.c:1621:15
    #21 0x55c9c586b5b3 in execute_cmd **/src/nvim/ex_docmd.c:1702:3
    #22 0x55c9c59109bb in cmdpreview_may_show **/src/nvim/ex_getln.c:2479:21
    #23 0x55c9c5902abd in command_line_changed **/src/nvim/ex_getln.c:2562:10
    #24 0x55c9c590f253 in command_line_handle_key **/src/nvim/ex_getln.c:2126:10
    #25 0x55c9c58ff064 in command_line_execute **/src/nvim/ex_getln.c:1339:10
    #26 0x55c9c648a6ec in state_enter **/src/nvim/state.c:99:26
    #27 0x55c9c58de3b6 in command_line_enter **/src/nvim/ex_getln.c:815:3
    #28 0x55c9c58da84c in getcmdline **/src/nvim/ex_getln.c:2624:18
    #29 0x55c9c58e32e8 in getexline **/src/nvim/ex_getln.c:2866:10
    #30 0x55c9c583bd66 in do_cmdline **/src/nvim/ex_docmd.c:495:30
    #31 0x55c9c5e929b2 in nv_colon **/src/nvim/normal.c:3237:18
    #32 0x55c9c5e7e465 in normal_execute **/src/nvim/normal.c:1196:3
    #33 0x55c9c648a6ec in state_enter **/src/nvim/state.c:99:26
    #34 0x55c9c5e61b30 in normal_enter **/src/nvim/normal.c:497:3
    #35 0x55c9c4faaef5 in main **/src/nvim/main.c:640:3
    #36 0x7f9b49de878f  (/usr/lib/libc.so.6+0x2378f) (BuildId: 4a4bec3d95a1804443e852958fe59ed461135ce9)
    #37 0x7f9b49de8849 in __libc_start_main (/usr/lib/libc.so.6+0x23849) (BuildId: 4a4bec3d95a1804443e852958fe59ed461135ce9)
    #38 0x55c9c4eaad54 in _start (**/build/bin/nvim+0xbbdd54) (BuildId: 4118ba17f78a25d8e6b6374bdd0ae3e88f0256cd)

Address 0x7f9b48301030 is located in stack of thread T0 at offset 48 in frame
    #0 0x55c9c574894f in get_func_tv **/src/nvim/eval/userfunc.c:529

  This frame has 3 object(s):
    [32, 368) 'argvars' (line 530) <== Memory access at offset 48 is inside this variable
    [432, 436) 'argcount' (line 531)
    [448, 456) 'argp' (line 534)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: negative-size-param (**/build/bin/nvim+0xc734e8) (BuildId: 4118ba17f78a25d8e6b6374bdd0ae3e88f0256cd) in __asan_memcpy
==562411==ABORTING
```

**Comment by zeertzjq** [comment]
Reproducible in versions as early as v0.6.0

**Comment by zeertzjq** [comment]
Minimal repro:
```vim
silent! eval ''->printf()
```

**Comment by zeertzjq** [comment]
In Vim this seems to use uninitialized memory.
