### ISSUE TITLE
nvim crashes while showing messages by `:mes` the terminal height increases

### ISSUE THREAD

**Issue by haolian9** [neovim/neovim#23570]
### Problem

hi folks, i just happened to find out a reliable way to crash nvim :P

### Steps to reproduce

* in a tmux window
* `$ nvim --clean +'so test.lua'`
* `q` # to dissmiss the showed messages
* `tmux-cmd :split` # now we have `a-b` pane, and nvim runs in `a`
* go back to nvim
* `:mes`
* go to pane `b`, close it
* nvim likely crashes

```
-- test.lua
for i = 1, 100 do
  vim.notify("msg#" .. i)
end
```

### Expected behavior

on such situation, nvim will not crash

### Neovim version (nvim -v)

0.9.0

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

archlinux

### Terminal name/version

st 0.9

### $TERM environment variable

tmux-256color

### Installation

archlinux's community repo

**Comment by haolian9** [comment]
i got some info from the coredump, hope them can help.
<details>

<summary> coredumpctl gdb -1 </summary>

```
> coredumpctl gdb -1
           PID: 184343 (nvim)
           UID: 1000 (haoliang)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-05-10 20:03:49 CST (11s ago)
  Command Line: /usr/bin/nvim --embed --clean $'+so test.lua'
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (haoliang)
       Boot ID: c04f752f7c1c4c76a611c9ba64709bc2
    Machine ID: d77baaa4f7764a32a82debb91014174b
      Hostname: rescuer
       Storage: /var/lib/systemd/coredump/core.nvim.1000.c04f752f7c1c4c76a611c9ba64709bc2.184343.1683720229000000.zst (present)
  Size on Disk: 263.1K
       Message: Process 184343 (nvim) of user 1000 dumped core.

                Stack trace of thread 184343:
                #0  0x00007f39a35f0941 n/a (libc.so.6 + 0x15a941)
                #1  0x000055fb58571c80 grid_fill (nvim + 0x1bcc80)
                #2  0x000055fb585db346 n/a (nvim + 0x226346)
                #3  0x000055fb585dbe07 n/a (nvim + 0x226e07)
                #4  0x000055fb585dd679 n/a (nvim + 0x228679)
                #5  0x000055fb585d4633 msg_putchar_attr (nvim + 0x21f633)
                #6  0x000055fb585d74b2 msg_start (nvim + 0x2224b2)
                #7  0x000055fb585d759f msg_multiattr (nvim + 0x22259f)
                #8  0x000055fb585da428 ex_messages (nvim + 0x225428)
                #9  0x000055fb5873ff61 n/a (nvim + 0x38af61)
                #10 0x000055fb58536c89 do_cmdline (nvim + 0x181c89)
                #11 0x000055fb585f6817 n/a (nvim + 0x241817)
                #12 0x000055fb585f05e1 n/a (nvim + 0x23b5e1)
                #13 0x000055fb586bec17 state_enter (nvim + 0x309c17)
                #14 0x000055fb585ef499 normal_enter (nvim + 0x23a499)
                #15 0x000055fb5842a728 main (nvim + 0x75728)
                #16 0x00007f39a34b9850 n/a (libc.so.6 + 0x23850)
                #17 0x00007f39a34b990a __libc_start_main (libc.so.6 + 0x2390a)
                #18 0x000055fb5842cb55 _start (nvim + 0x77b55)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/nvim...
Reading symbols from /home/haoliang/.cache/debuginfod_client/a9e4823b803d3cad5bf15a983fb477e610953cab/debuginfo...
[New LWP 184343]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/nvim --embed --clean +so test.lua'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f39a35f0941 in ?? () from /usr/lib/libc.so.6
>>>
>>> bt
#0  0x00007f39a35f0941 in ?? () from /usr/lib/libc.so.6
#1  0x000055fb58571c80 in schar_cmp (sc2=0x7ffcd77bbdf0 " ",
    sc1=0xa13746ed41310 <error: Cannot access memory at address 0xa13746ed41310>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/grid.h:52
#2  grid_fill (grid=0x55fb5883daa0 <msg_grid>, start_row=<optimized out>,
    end_row=<optimized out>, start_col=<optimized out>, end_col=<optimized out>,
    c1=<optimized out>, c2=<optimized out>, attr=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/grid.c:430
#3  0x000055fb585db346 in do_more_prompt (typed_char=typed_char@entry=0)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:2940
#4  0x000055fb585dbe07 in msg_puts_display (str=0x7ffcd77bc050 "\n", maxlen=-1,
    attr=0, recurse=0) at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:2248
#5  0x000055fb585dd679 in msg_puts_attr_len (str=0x7ffcd77bc050 "\n", len=-1, attr=0)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:2096
#6  0x000055fb585d4633 in msg_puts_attr_len (attr=0, len=-1, str=0x7ffcd77bc050 "\n")
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:2052
#7  msg_puts_attr (attr=0, s=0x7ffcd77bc050 "\n")
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:2036
#8  msg_putchar_attr (c=c@entry=10, attr=attr@entry=0)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:1480
#9  0x000055fb585d74b2 in msg_putchar (c=10)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:1465
#10 msg_start () at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:1431
#11 0x000055fb585d759f in msg_multiattr (hl_msg=..., kind=0x55fb5874c646 "echomsg",
    history=history@entry=false)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:275
#12 0x000055fb585da428 in ex_messages (eap_p=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/message.c:1100
#13 0x000055fb5873ff61 in execute_cmd0.constprop.0 (retv=0x7ffcd77bc308,
    eap=0x7ffcd77bc390, errormsg=0x7ffcd77bc300, preview=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/ex_docmd.c:1620
#14 0x000055fb58536c89 in do_one_cmd (cookie=0x0,
    fgetline=0x55fb5854aef0 <getexline>, cstack=0x7ffcd77bc550, flags=0,
    cmdlinep=0x7ffcd77bc2f8)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/ex_docmd.c:2279
#15 do_cmdline (cmdline=<optimized out>, fgetline=0x55fb5854aef0 <getexline>,
    cookie=0x0, flags=0) at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/ex_docmd.c:578
#16 0x000055fb585f6817 in nv_colon (cap=0x7ffcd77bcc80)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/normal.c:3228
#17 0x000055fb585f05e1 in normal_execute (state=0x7ffcd77bcc00, key=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/normal.c:1196
#18 0x000055fb586bec17 in state_enter (s=0x7ffcd77bcc00)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/state.c:99
#19 0x000055fb585ef499 in normal_enter (cmdwin=<optimized out>,
    noexmode=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/normal.c:497
#20 0x000055fb5842a728 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/main.c:641

>>> frame 2
#2  grid_fill (grid=0x55fb5883daa0 <msg_grid>, start_row=<optimized out>,
    end_row=<optimized out>, start_col=<optimized out>, end_col=<optimized out>,
    c1=<optimized out>, c2=<optimized out>, attr=<optimized out>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/grid.c:430
Downloading source file /usr/src/debug/neovim/neovim-0.9.0/src/nvim/grid.c
430           if (schar_cmp(grid->chars[off], sc) || grid->attrs[off] != attr || rdb_flags & RDB_NODELTA) {
>>> info locals
off = <optimized out>
dirty_first = 2147483647
lineoff = <optimized out>
last = <optimized out>
dirty_last = 0
col = 0
row = <optimized out>
sc = " \000\377\377\373U", '\000' <repeats 22 times>
row_off = <optimized out>
col_off = <optimized out>

>>> frame 1
#1  0x000055fb58571c80 in schar_cmp (sc2=0x7ffcd77bbdf0 " ",
    sc1=0xa13746ed41310 <error: Cannot access memory at address 0xa13746ed41310>)
    at /usr/src/debug/neovim/neovim-0.9.0/src/nvim/grid.h:52
Downloading source file /usr/src/debug/neovim/neovim-0.9.0/src/nvim/grid.h
52        return strncmp(sc1, sc2, sizeof(schar_T));
>>> info locals
No locals.
>>> print sc1
$1 = 0xa13746ed41310 <error: Cannot access memory at address 0xa13746ed41310>
>>> print sc2
$2 = 0x7ffcd77bbdf0 " "
```

</details>

**Comment by zeertzjq** [comment]
ASAN:
```
=================================================================
==200948==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x612000025e18 at pc 0x55dcbcf335c1 bp 0x7ffedf7076d0 sp 0x7ffedf7076c8
READ of size 8 at 0x612000025e18 thread T0
    #0 0x55dcbcf335c0 in grid_fill **/src/nvim/grid.c:427:22
    #1 0x55dcbd2bca67 in do_more_prompt **/src/nvim/message.c:2940:13
    #2 0x55dcbd2cba60 in msg_puts_display **/src/nvim/message.c:2248:13
    #3 0x55dcbd2c117e in msg_puts_attr_len **/src/nvim/message.c:2096:5
    #4 0x55dcbd2c060f in msg_puts_attr **/src/nvim/message.c:2036:3
    #5 0x55dcbd2a646e in msg_putchar_attr **/src/nvim/message.c:1481:3
    #6 0x55dcbd2bf614 in msg_putchar **/src/nvim/message.c:1466:3
    #7 0x55dcbd2a7789 in msg_start **/src/nvim/message.c:1432:5
    #8 0x55dcbd2a67cb in msg_multiattr **/src/nvim/message.c:275:3
    #9 0x55dcbd2b7bff in ex_messages **/src/nvim/message.c:1100:9
    #10 0x55dcbcd90c2e in execute_cmd0 **/src/nvim/ex_docmd.c:1634:7
    #11 0x55dcbcd6dd03 in do_one_cmd **/src/nvim/ex_docmd.c:2293:7
    #12 0x55dcbcd5e58d in do_cmdline **/src/nvim/ex_docmd.c:592:20
    #13 0x55dcbd3c51e7 in nv_colon **/src/nvim/normal.c:3238:18
    #14 0x55dcbd3b0c95 in normal_execute **/src/nvim/normal.c:1200:3
    #15 0x55dcbd9c33bc in state_enter **/src/nvim/state.c:99:26
    #16 0x55dcbd394350 in normal_enter **/src/nvim/normal.c:499:3
    #17 0x55dcbc4c7ef0 in main **/src/nvim/main.c:636:3
    #18 0x7fd2bddd984f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #19 0x7fd2bddd9909 in __libc_start_main (/usr/lib/libc.so.6+0x23909) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)
    #20 0x55dcbc3c7d54 in _start (**/build/bin/nvim+0xbccd54) (BuildId: d099cd75e832e3b332bba11bdd3d32e29decba9f)

0x612000025e18 is located 32 bytes to the right of 312-byte region [0x612000025cc0,0x612000025df8)
allocated by thread T0 here:
    #0 0x55dcbc47f2e9 in __interceptor_malloc (**/build/bin/nvim+0xc842e9) (BuildId: d099cd75e832e3b332bba11bdd3d32e29decba9f)
    #1 0x55dcbd280ba6 in try_malloc **/src/nvim/memory.c:88:15
    #2 0x55dcbd280d7c in xmalloc **/src/nvim/memory.c:122:15
    #3 0x55dcbcf3aeb1 in grid_alloc **/src/nvim/grid.c:690:23
    #4 0x55dcbc9c3059 in default_grid_alloc **/src/nvim/drawscreen.c:190:3
    #5 0x55dcbc9c4c13 in screen_resize **/src/nvim/drawscreen.c:297:10
    #6 0x55dcbdb8ff4b in ui_refresh **/src/nvim/ui.c:228:3
    #7 0x55dcbc6fc786 in nvim_ui_try_resize **/src/nvim/api/ui.c:278:3
    #8 0x55dcbc67a023 in handle_nvim_ui_try_resize **/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:5662:3
    #9 0x55dcbd36183a in request_event **/src/nvim/msgpack_rpc/channel.c:425:19
    #10 0x55dcbcce6677 in multiqueue_oneshot_event **/src/nvim/event/multiqueue.c:275:7
    #11 0x55dcbcce52b0 in multiqueue_process_events **/src/nvim/event/multiqueue.c:153:7
    #12 0x55dcbd2bbce5 in do_more_prompt **/src/nvim/message.c:2888:7
    #13 0x55dcbd2cba60 in msg_puts_display **/src/nvim/message.c:2248:13
    #14 0x55dcbd2c117e in msg_puts_attr_len **/src/nvim/message.c:2096:5
    #15 0x55dcbd2c060f in msg_puts_attr **/src/nvim/message.c:2036:3
    #16 0x55dcbd2a646e in msg_putchar_attr **/src/nvim/message.c:1481:3
    #17 0x55dcbd2bf614 in msg_putchar **/src/nvim/message.c:1466:3
    #18 0x55dcbd2a7789 in msg_start **/src/nvim/message.c:1432:5
    #19 0x55dcbd2a67cb in msg_multiattr **/src/nvim/message.c:275:3
    #20 0x55dcbd2b7bff in ex_messages **/src/nvim/message.c:1100:9
    #21 0x55dcbcd90c2e in execute_cmd0 **/src/nvim/ex_docmd.c:1634:7
    #22 0x55dcbcd6dd03 in do_one_cmd **/src/nvim/ex_docmd.c:2293:7
    #23 0x55dcbcd5e58d in do_cmdline **/src/nvim/ex_docmd.c:592:20
    #24 0x55dcbd3c51e7 in nv_colon **/src/nvim/normal.c:3238:18
    #25 0x55dcbd3b0c95 in normal_execute **/src/nvim/normal.c:1200:3
    #26 0x55dcbd9c33bc in state_enter **/src/nvim/state.c:99:26
    #27 0x55dcbd394350 in normal_enter **/src/nvim/normal.c:499:3
    #28 0x55dcbc4c7ef0 in main **/src/nvim/main.c:636:3
    #29 0x7fd2bddd984f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)

SUMMARY: AddressSanitizer: heap-buffer-overflow **/src/nvim/grid.c:427:22 in grid_fill
Shadow bytes around the buggy address:
  0x0c247fffcb70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fffcb80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fffcb90: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fffcba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fffcbb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa
=>0x0c247fffcbc0: fa fa fa[fa]fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fffcbd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c247fffcbe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 fa
  0x0c247fffcbf0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fffcc00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fffcc10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==200948==ABORTING
```

**Comment by zeertzjq** [comment]
This seems to only happen if the first resize after the more prompt increases the screen height. If the first resize decreases the screen height then subsequent resizes do not crash.
