### ISSUE TITLE
In channel1->nvim->channel2 nested rpcrequest, closing channel2 after responding can return error on channel1

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#24214]
### Problem

I set up a scenario in which I have two RPC channels (the first one is over stdio as I'm running an embedded Neovim, but I don't think that's relevant) and on the first channel I send a request asking Neovim to send a request to the second. I then return a response to the second channel and immediately close the connection. Sometimes, the first channel will receive an error saying that the channel closed even though the response was sent on the second channel before it was closed.

Here is some traffic demonstrating this behavior:
```
------------------------------------  client1  ------------------------------------
Plugin -> Neovim:
[ 0
, 0
, "nvim_set_client_info"
, [ "177a9549-74af-3924-5dee-38abdd3623d9", {}, "remote", {}, {} ]
]
Neovim -> Plugin: [ 1, 0, nil, nil ]
Plugin -> Neovim: [ 0, 1, "nvim_list_chans", [] ]
Neovim -> Plugin:
[ 1
, 1
, nil
, [ { "id": 1
    , "stream": "stdio"
    , "client":
          { "name": "177a9549-74af-3924-5dee-38abdd3623d9"
          , "version": { "major": 0 }
          , "type": "remote"
          , "methods": {}
          , "attributes": {}
          }
    , "mode": "rpc"
    }
  , { "id": 2, "stream": "stderr", "mode": "bytes" }
  ]
]
Plugin -> Neovim:
[ 0, 2, "nvim_set_client_info", [ "client1", {}, "remote", {}, {} ] ]
Neovim -> Plugin: [ 1, 2, nil, nil ]
Plugin -> Neovim:
[ 0, 3, "nvim_call_function", [ "rpcrequest", [ 3, "rpc" ] ] ]
Neovim -> Plugin:
[ 1
, 3
, [ 0
  , "Vim:Error invoking 'rpc' on channel 3 (client2):\nch 3 was closed by the client"
  ]
, nil
]
("Neovim -> Plugin: Connection closed" (angstrom_exit_status (Ok ())))
("Plugin -> Neovim: Connection closed" (angstrom_exit_status (Ok ())))
-----------------------------------------------------------------------------------
------------------------------------  client2  ------------------------------------
Plugin -> Neovim:
[ 0
, 0
, "nvim_set_client_info"
, [ "f0beaf41-b871-3984-ab44-2ba3e44e48fc", {}, "remote", {}, {} ]
]
Neovim -> Plugin: [ 1, 0, nil, nil ]
Plugin -> Neovim: [ 0, 1, "nvim_list_chans", [] ]
Neovim -> Plugin:
[ 1
, 1
, nil
, [ { "id": 1
    , "stream": "stdio"
    , "client":
          { "name": "client1"
          , "version": { "major": 0 }
          , "type": "remote"
          , "methods": {}
          , "attributes": {}
          }
    , "mode": "rpc"
    }
  , { "id": 2, "stream": "stderr", "mode": "bytes" }
  , { "id": 3
    , "stream": "socket"
    , "client":
          { "name": "f0beaf41-b871-3984-ab44-2ba3e44e48fc"
          , "version": { "major": 0 }
          , "type": "remote"
          , "methods": {}
          , "attributes": {}
          }
    , "mode": "rpc"
    }
  ]
]
Plugin -> Neovim:
[ 0, 2, "nvim_set_client_info", [ "client2", {}, "remote", {}, {} ] ]
Neovim -> Plugin: [ 1, 2, nil, nil ]
Neovim -> Plugin: [ 0, 1, "rpc", [] ]
Plugin -> Neovim: [ 2, "nvim_eval", [ "0" ] ]
Plugin -> Neovim: [ 0, 3, "nvim_get_current_buf", [] ]
Neovim -> Plugin: [ 1, 3, nil, 1 ]
Plugin -> Neovim: [ 0, 4, "nvim_get_current_buf", [] ]
Neovim -> Plugin: [ 1, 4, nil, 1 ]
Plugin -> Neovim: [ 1, 1, nil, nil ]
("Plugin -> Neovim: Connection closed" (angstrom_exit_status (Ok ())))
("Neovim -> Plugin: Connection closed" (angstrom_exit_status (Ok ())))
-----------------------------------------------------------------------------------
```
The key line is at the end of the `client2` log: `Plugin -> Neovim: [1, 1, nil, nil]`, which tells us that the plugin did send the response to Neovim before closing the connection.

### Steps to reproduce
Run the script below - it will probably repro within the first 2K runs. `vim.schedule` is used to delay closing until after Neovim has responded to the request.

```lua
function test()
  local nvim = vim.fn.jobstart({ vim.v.progpath, "--embed", "--headless", "--clean", "-n" }, { rpc = true })
  vim.rpcrequest(nvim, "nvim_exec_lua", "vim.schedule(function() vim.cmd \"quit\" end)", {})
  local jobwait_result = vim.fn.jobwait({nvim}, 1000)[1]
  if jobwait_result < 0 then
    vim.fn.jobstop(nvim)
    error("Unexpected jobwait result: "..jobwait_result)
  end
end

function run(num_tests)
  for i = 1, (num_tests or 10000) do
    local succeeded, message = pcall(test)
    if not succeeded then
      error("Failure on run "..i..":\n"..message)
    end
  end
  print("All "..num_tests.." runs succeeded")
end
```

### Expected behavior

No error. The response was returned on channel2 successfully, so channel1 should receive a successful response.

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

CentOS 7.9

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by justinmk** [comment]
Potentially related:

- https://github.com/neovim/neovim/issues/4468
- https://github.com/neovim/neovim/issues/21630

**Comment by zeertzjq** [comment]
In the latest version this also leaks memory:
```

=================================================================
==2391731==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 30 byte(s) in 1 object(s) allocated from:
    #0 0x5648c7390b05 in malloc (**/build/bin/nvim+0xda4b05) (BuildId: 18cefede229fbf4f33f8361170af92533aa3dc36)
    #1 0x5648c800d074 in try_malloc **/src/nvim/memory.c:113:15
    #2 0x5648c800d2d4 in xmalloc **/src/nvim/memory.c:147:15
    #3 0x5648c800d6ea in xmallocz **/src/nvim/memory.c:219:15
    #4 0x5648c800d813 in xmemdupz **/src/nvim/memory.c:237:17
    #5 0x5648c75384a2 in cstr_to_string **/src/nvim/api/private/helpers.c:340:13
    #6 0x5648c80cf074 in chan_close_on_err **/src/nvim/msgpack_rpc/channel.c:535:21
    #7 0x5648c80c2e0c in receive_msgpack **/src/nvim/msgpack_rpc/channel.c:225:5
    #8 0x5648c7a9b8ab in read_event **/src/nvim/event/rstream.c:180:23
    #9 0x5648c7a9b348 in invoke_read_cb **/src/nvim/event/rstream.c:233:3
    #10 0x5648c7a986e6 in read_cb **/src/nvim/event/rstream.c:126:7
    #11 0x5648c8c0d312 in uv__stream_eof **/.deps/build/src/libuv/src/unix/stream.c:938:3
    #12 0x5648c8c0afa4 in uv__stream_io **/.deps/build/src/libuv/src/unix/stream.c:1224:5
    #13 0x5648c8c160ac in uv__io_poll **/.deps/build/src/libuv/src/unix/linux.c:1565:11
    #14 0x5648c8bfa107 in uv_run **/.deps/build/src/libuv/src/unix/core.c:460:5
    #15 0x5648c7a86ec7 in loop_uv_run **/src/nvim/event/loop.c:59:3
    #16 0x5648c7a86b44 in loop_poll_events **/src/nvim/event/loop.c:80:26
    #17 0x5648c80c5973 in rpc_send_call **/src/nvim/msgpack_rpc/channel.c:161:3
    #18 0x5648c7e52026 in nlua_rpc **/src/nvim/lua/executor.c:1276:21
    #19 0x5648c7e4f008 in nlua_rpcrequest **/src/nvim/lua/executor.c:1248:10
    #20 0x5648c8b9d9d5 in lj_BC_FUNCC (**/build/bin/nvim+0x25b19d5) (BuildId: 18cefede229fbf4f33f8361170af92533aa3dc36)

SUMMARY: AddressSanitizer: 30 byte(s) leaked in 1 allocation(s).
```
