### ISSUE TITLE
When :terminal encounters a very long line with 'number' set, libvterm aborts neovim

### ISSUE THREAD

**Issue by lf-** [neovim/neovim#25234]
### Problem

Neovim crashes when subjected to a very long line in the terminal when 'number' is set. I found this while grepping and having the misfortune of matching minified javascript.

Context (libvterm src/screen.c):

```
(gdb) list
660	  }
661	
662	  /* We really expect the cursor position to be set by now */
663	  if(active && (new_cursor.row == -1 || new_cursor.col == -1)) {
664	    fprintf(stderr, "screen_resize failed to update cursor position\n");
665	    abort();
666	  }
667	
668	  if(old_row >= 0 && bufidx == BUFIDX_PRIMARY) {
669	    /* Push spare lines to scrollback buffer */
```

Backtrace:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fdf2a2b18a3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007fdf2a261668 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fdf2a2494b8 in __GI_abort () at abort.c:79
#4  0x00007fdf2a68f06b in resize_buffer (screen=screen@entry=0x55b56419ef90, bufidx=bufidx@entry=0, new_rows=new_rows@entry=29, new_cols=new_cols@entry=109, active=true, statefields=statefields@entry=0x7ffc82f5a2f0) at src/screen.c:665
#5  0x00007fdf2a6924c3 in resize (new_rows=29, new_cols=109, fields=0x7ffc82f5a2f0, user=0x55b56419ef90) at src/screen.c:763
#6  0x00007fdf2a68c27d in on_resize (rows=29, cols=109, user=0x55b5641aa0f0) at src/state.c:1993
#7  0x000055b5622fb7ba in terminal_check_size (term=0x55b5641bc300) at /home/jade/co/neovim/src/nvim/terminal.c:408
#8  0x000055b5620a95cf in win_update (wp=0x55b5640efbd0, providers=0x7ffc82f5a5f0) at /home/jade/co/neovim/src/nvim/drawscreen.c:1494
#9  0x000055b5620a7286 in update_screen () at /home/jade/co/neovim/src/nvim/drawscreen.c:632
#10 0x000055b5622fbdce in terminal_check (state=0x7ffc82f5a720) at /home/jade/co/neovim/src/nvim/terminal.c:539
#11 0x000055b5622d65d7 in state_enter (s=0x7ffc82f5a720) at /home/jade/co/neovim/src/nvim/state.c:40
#12 0x000055b5622fbaaa in terminal_enter () at /home/jade/co/neovim/src/nvim/terminal.c:467
#13 0x000055b5620af8b6 in edit (cmdchar=105, startln=false, count=1) at /home/jade/co/neovim/src/nvim/edit.c:1240
#14 0x000055b562207261 in invoke_edit (cap=0x7ffc82f5a980, repl=0, cmd=105, startln=0) at /home/jade/co/neovim/src/nvim/normal.c:6272
#15 0x000055b5622071f5 in nv_edit (cap=0x7ffc82f5a980) at /home/jade/co/neovim/src/nvim/normal.c:6249
#16 0x000055b5621fc291 in normal_execute (state=0x7ffc82f5a910, key=105) at /home/jade/co/neovim/src/nvim/normal.c:1228
#17 0x000055b5622d6761 in state_enter (s=0x7ffc82f5a910) at /home/jade/co/neovim/src/nvim/state.c:99
#18 0x000055b5621fa50d in normal_enter (cmdwin=false, noexmode=false) at /home/jade/co/neovim/src/nvim/normal.c:517
#19 0x000055b561fed05d in main (argc=7, argv=0x7ffc82f5ad28) at /home/jade/co/neovim/src/nvim/main.c:647
```

### Steps to reproduce

In your neovim checkout:

```
VIMRUNTIME=./runtime ./build/bin/nvim --clean --cmd 'set number' -c 'term bash'
```

then paste:

```
head -c 1000000 < /dev/zero | tr '\0' 'a'
```

into the terminal.

### Expected behavior

Should at least not crash. I don't care that much about a giant line being displayed properly, but currently it crashes, which is annoying.

### Neovim version (nvim -v)

46402c16c0c38701469c52fb28d16f2483cc7a72

### Vim (not Nvim) behaves the same?

unsurprisingly, no, 9.0.1882

### Operating system/version

Arch Linux

### Terminal name/version

alacritty 0.12.2 (9d9982df)

### $TERM environment variable

alacritty

### Installation

reproduces in a git checkout

**Comment by zeertzjq** [comment]
Related: #23762

**Comment by zeertzjq** [comment]
Let's close this for now. Reflow is now disabled and a fix in libvterm is needed to re-enable it.
