### ISSUE TITLE
Deadlock after saving

### ISSUE THREAD

**Issue by smurfix** [neovim/neovim#25853]
### Problem

Sometimes (every week or so, for me) nvim locks up after saving a file.

Stack dump:

```gdb
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393,
    expected=0, futex_word=0x556363d1ae2c) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x556363d1ae2c,
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0,
    private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007f755e99de0b in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x556363d1ae2c, expected=expected@entry=0,
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0)
    at ./nptl/futex-internal.c:139
#3  0x00007f755e9a0468 in __pthread_cond_wait_common (abstime=0x0, clockid=0,
    mutex=0x556363d1add8, cond=0x556363d1ae00) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=cond@entry=0x556363d1ae00,
    mutex=mutex@entry=0x556363d1add8) at ./nptl/pthread_cond_wait.c:618
#5  0x00007f755ecee169 in uv_cond_wait (cond=cond@entry=0x556363d1ae00,
    mutex=mutex@entry=0x556363d1add8) at ./src/unix/thread.c:800
#6  0x0000556362d2bbfb in ui_bridge_suspend (b=0x556363d1ac80)
    at ./src/nvim/ui_bridge.c:185
#7  0x0000556362b892a3 in ui_call_suspend ()
    at ./build/src/nvim/auto/ui_events_call.generated.h:53
#8  ex_stop (eap=<optimized out>) at ./src/nvim/ex_docmd.c:6950
#9  0x0000556362b7a6f6 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffe45732408,
    flags=flags@entry=10, cstack=cstack@entry=0x7ffe45732490,
    fgetline=fgetline@entry=0x0, cookie=cookie@entry=0x0) at ./src/nvim/ex_docmd.c:1972
#10 0x0000556362b7cae3 in do_cmdline (cmdline=<optimized out>, fgetline=0x0,
    cookie=0x0, flags=10) at ./src/nvim/ex_docmd.c:595
#11 0x0000556362c2c8dc in normal_execute (state=0x7ffe45732a80, key=<optimized out>)
    at ./src/nvim/normal.c:1166
#12 0x0000556362cff1ad in state_enter (s=0x7ffe45732a80) at ./src/nvim/state.c:89
#13 0x0000556362c2b304 in normal_enter (cmdwin=<optimized out>,
    noexmode=<optimized out>) at ./src/nvim/normal.c:463
#14 0x0000556362a8c24a in main (argc=<optimized out>, argv=<optimized out>)
    at ./src/nvim/main.c:576
(gdb) inf thr
  Id   Target Id                              Frame
* 1    Thread 0x7f755e8ead40 (LWP 14397) "vi" __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x556363d1ae2c)
    at ./nptl/futex-internal.c:57
  2    Thread 0x7f755dc5f6c0 (LWP 14398) "vi" __futex_abstimed_wait_common64 (
    private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x7f7558011210)
    at ./nptl/futex-internal.c:57
(gdb) thr 2
[Switching to thread 2 (Thread 0x7f755dc5f6c0 (LWP 14398))]
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393,
    expected=0, futex_word=0x7f7558011210) at ./nptl/futex-internal.c:57
57	in ./nptl/futex-internal.c
(gdb) whe
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393,
    expected=0, futex_word=0x7f7558011210) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x7f7558011210,
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0,
    private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007f755e99de0b in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x7f7558011210, expected=expected@entry=0,
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0)
    at ./nptl/futex-internal.c:139
#3  0x00007f755e9a0468 in __pthread_cond_wait_common (abstime=0x0, clockid=0,
    mutex=0x7f75580111c0, cond=0x7f75580111e8) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=cond@entry=0x7f75580111e8,
    mutex=mutex@entry=0x7f75580111c0) at ./nptl/pthread_cond_wait.c:618
#5  0x00007f755ecee169 in uv_cond_wait (cond=cond@entry=0x7f75580111e8,
    mutex=mutex@entry=0x7f75580111c0) at ./src/unix/thread.c:800
#6  0x0000556362d2330b in tinput_flush (input=input@entry=0x7f7558010f28,
    wait_until_empty=wait_until_empty@entry=true) at ./src/nvim/tui/input.c:191
#7  0x0000556362d260b1 in tinput_read_cb (stream=<optimized out>, buf=<optimized out>,
    count_=<optimized out>, eof=<optimized out>, data=0x7f7558010f28)
    at ./src/nvim/tui/input.c:668
#8  tinput_read_cb (stream=<optimized out>, buf=<optimized out>,
    count_=<optimized out>, data=0x7f7558010f28, eof=<optimized out>)
    at ./src/nvim/tui/input.c:658
#9  0x0000556362b62b08 in read_event (argv=<optimized out>)
    at ./src/nvim/event/rstream.c:192
#10 0x0000556362b6696e in invoke_read_cb (stream=0x7f7558011018,
    count=<optimized out>, eof=<optimized out>) at ./src/nvim/event/rstream.c:205
#11 0x00007f755eceb2ed in uv__read (stream=stream@entry=0x7f7558011020)
    at ./src/unix/stream.c:1201
#12 0x00007f755ecebd78 in uv__stream_io (loop=<optimized out>, w=0x7f75580110a8,
    events=1) at ./src/unix/stream.c:1270
#13 0x00007f755ecf3e3c in uv__io_poll (loop=loop@entry=0x7f755dc5e8b0,
    timeout=<optimized out>) at ./src/unix/epoll.c:374
#14 0x00007f755ece09e4 in uv_run (loop=loop@entry=0x7f755dc5e8b0,
    mode=mode@entry=UV_RUN_ONCE) at ./src/unix/core.c:406
#15 0x0000556362d2a577 in loop_poll_events (ms=-1, loop=0x7f755dc5e8b0)
    at ./src/nvim/event/loop.c:61
#16 tui_main (bridge=0x556363d1ac80, ui=0x556363d1ab40) at ./src/nvim/tui/tui.c:507
#17 0x00007f755e9a1044 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:442
#18 0x00007f755ea2161c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```

### Steps to reproduce

```
$ start_some_memory_gobbling_job &  # most likely
$ nvim FILE.txt
[ edit edit edit ]
ZZ

[ screen, last two lines ]
FILE.txt [+]                                                           171,28         53%
"FILE.txt"[cursor]
```

At this point, the file's new content has been written correctly; the lock-up happens afterwards. `lsof -p###` shows that the file is no longer open.

### Expected behavior

No deadlock. :-P

### Neovim version (nvim -v)

NVIM v0.7.2

### Vim (not Nvim) behaves the same?

unknown, I don't use it often enough to (maybe) hit the problem

### Operating system/version

Debian bookworm

### Terminal name/version

gnome-term, kity

### $TERM environment variable

xterm-256, kitty

### Installation

Debian bookworm

**Comment by clason** [comment]
Please use a current Neovim version; we are at 0.9.4 now (download the appimage for testing if your distro does not carry it).

**Comment by justinmk** [comment]
Mutexes were removed so this is no longer relevant. Please try the latest version before reporting issues.
