### ISSUE TITLE
set emoji crashes nvim, listchars leadmultispace displays wrong symbols

### ISSUE THREAD

**Issue by FalcoGer** [neovim/neovim#26160]
### Problem

I have this setting in my init file:

```
set listchars=tab:<->,eol:$,lead:-,leadmultispace:\|-->,trail:·,extends:>,precedes:<
set emoji
```

But when I have more than 1 space in front of a word, I get something like this with random kanji symbols:

![image](https://github.com/neovim/neovim/assets/16250196/57d7213b-a2aa-4854-ac53-c1089a9109f3)

The last time I know for sure that it worked was with `NVIM v0.10.0-dev-e59cf3b3a`
I know it has been broken for at least a week now. I'm not sure when this error started.

When doing this manually and not loading it from a config file, doing `:set emoji` or `:set noemoji` sometimes crashes nvim

### Steps to reproduce

1. nvim --clean
2. `:set list`
3. `:set listchars=tab:<->,eol:$,lead:-,leadmultispace:\|-->,trail:·,extends:>,precedes:<`
4. type some text, for example
```text
    f
    f    f
f    
```
5. `:set emoji`

You will then either get a segfault or the leadmultispace characters are displayed with random symbols.

[![asciicast](https://asciinema.org/a/hd6XkgevrxQAr9fPnoUZr41Xk.svg)](https://asciinema.org/a/hd6XkgevrxQAr9fPnoUZr41Xk)

### Expected behavior

- No crash
- Characters are displayed correctly

### Neovim version (nvim -v)

NVIM v0.10.0-dev-8c6b0a5f2

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Ubuntu Mate 22.04

### Terminal name/version

kitty 0.30.1

### $TERM environment variable

xterm-kitty

### Installation

built from repo

**Comment by FalcoGer** [comment]
I just put `set noemoji` in my config, but it still displays the wrong symbols. I'm not sure what's going on.

**Comment by FalcoGer** [comment]
Here is a backtrace

```text
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140434286128000) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fb967bd2b80
        old_mask = {
          __val = {94429909587448, 94429900300584, 140727484950538, 4294967295, 140727484789168, 0, 0, 140727484789136, 140727484788560, 140434283443821, 94429909713712,
            94429898958662, 140727484788512, 94429894109398, 140727484788816, 140727484788816}
        }
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140434286128000) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140434286128000, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007fb9678a0476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007fb9678867f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {
          __sigaction_handler = {
            sa_handler = 0x55e22d3900b0,
            sa_sigaction = 0x55e22d3900b0
          },
          sa_mask = {
            __val = {94429894104954, 94429909680392, 94429899431758, 94429909680304, 94429894085577, 16, 140727484790624, 72057594037927936, 94429909680400,
              10983823949590186496, 94429909680304, 94429910368864, 46, 94429909680400, 46, 94429900378024}
          },
          sa_flags = 743135853,
          sa_restorer = 0x55e22d3900b0
        }
        sigs = {
          __val = {32, 0, 2, 140727484788624, 140727484788752, 0, 0, 0, 0, 0, 0, 94429898958662, 10983823949590186496, 3, 1, 94429909711440}
        }
#5  0x00007fb9678e7676 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fb967a39b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
        ap = {{
            gp_offset = 24,
            fp_offset = 0,
            overflow_arg_area = 0x7ffdabbdb1c0,
            reg_save_area = 0x7ffdabbdb150
          }}
        fd = <optimized out>
        list = <optimized out>
        nlist = <optimized out>
        cp = <optimized out>
#6  0x00007fb9678fecfc in malloc_printerr (str=str@entry=0x7fb967a3c710 "free(): double free detected in tcache 2") at ./malloc/malloc.c:5664
No locals.
#7  0x00007fb9679010ab in _int_free (av=0x7fb967a77c80 <main_arena>, p=0x55e22d427150, have_lock=0) at ./malloc/malloc.c:4473
        tmp = <optimized out>
        cnt = <optimized out>
        e = 0x55e22d427160
        tc_idx = 2
        size = 64
        fb = <optimized out>
        nextchunk = <optimized out>
        nextsize = <optimized out>
        nextinuse = <optimized out>
        prevsize = <optimized out>
        bck = <optimized out>
        fwd = <optimized out>
        __PRETTY_FUNCTION__ = "_int_free"
#8  0x00007fb967903453 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
        ar_ptr = <optimized out>
        p = <optimized out>
        err = 0
#9  0x000055e22c6e90f8 in set_chars_option.llvm ()
No symbol table info available.
#10 0x000055e22c6e0e69 in check_chars_options ()
No symbol table info available.
#11 0x000055e22c6d4bb8 in set_option.llvm ()
No symbol table info available.
#12 0x000055e22c6d069c in do_set ()
No symbol table info available.
#13 0x000055e22c5b8bef in execute_cmd0 ()
No symbol table info available.
#14 0x000055e22c5b402a in do_cmdline ()
No symbol table info available.
#15 0x000055e22c6ae105 in nv_colon.llvm ()
No symbol table info available.
#16 0x000055e22c6aa391 in normal_execute.llvm ()
No symbol table info available.
#17 0x000055e22c7bb016 in state_enter ()
No symbol table info available.
#18 0x000055e22c4629c3 in main ()
No symbol table info available.
#19 0x00007fb967887d90 in __libc_start_call_main (main=main@entry=0x55e22c45e380 <main>, argc=argc@entry=3, argv=argv@entry=0x7ffdabbdc688)
    at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {
          cancel_jmp_buf = {{
              jmp_buf = {0, 2009278470812189197, 140727484794504, 94429893747584, 94429900115048, 140434286379072, -2010519253372911091, -1976892154008059379},
              mask_was_saved = 0
            }},
          priv = {
            pad = {0x0, 0x0, 0x0, 0x0},
            data = {
              prev = 0x0,
              cleanup = 0x0,
              canceltype = 0
            }
          }
        }
        not_first_call = <optimized out>
#20 0x00007fb967887e40 in __libc_start_main_impl (main=0x55e22c45e380 <main>, argc=3, argv=0x7ffdabbdc688, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffdabbdc678) at ../csu/libc-start.c:392
No locals.
#21 0x000055e22c45d725 in _start ()
No symbol table info available.
```
