### ISSUE TITLE
Neovim crashes when invoking unknown function via `call` via `nvim_cmd`.

### ISSUE THREAD

**Issue by ddickstein** [neovim/neovim#26289]
### Problem

```
:call Foo()
E117: Unknown function: Foo

:call nvim_exec2("call Foo()", {})
E5555: API call: nvim_exec2(): Vim(call):E117: Unknown function: Foo

:call nvim_cmd({ "cmd": "call", "args": [ "Foo()" ] }, {})
SIGSEGV
```

### Steps to reproduce

As above

### Expected behavior

E5555: API call: nvim_cmd(): Vim(call):E117: Unknown function: Foo

### Neovim version (nvim -v)

0.9.1

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Rocky Linux 8.8

### Terminal name/version

xfce4-terminal 1.0.4

### $TERM environment variable

tmux-256color

### Installation

build from repo

**Comment by ddickstein** [comment]
Have not had a chance yet to test this on nightly.

**Comment by zeertzjq** [comment]
ASAN:
```
**/src/nvim/eval/userfunc.c:3373:62: runtime error: member access within null pointer of type 'cstack_T'
    #0 0x56155138ad53 in ex_call **/src/nvim/eval/userfunc.c:3373:62
    #1 0x56155147b91c in execute_cmd0 **/src/nvim/ex_docmd.c:1638:7
    #2 0x561551477ad2 in execute_cmd **/src/nvim/ex_docmd.c:1716:3
    #3 0x561550c3b0f5 in nvim_cmd **/src/nvim/api/command.c:658:3
    #4 0x561550cec9bc in handle_nvim_cmd **/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:2997:15
    #5 0x56155129d7dd in api_wrapper **/src/nvim/eval/funcs.c:352:19
    #6 0x56155124ce1a in call_internal_func **/src/nvim/eval/funcs.c:272:3
    #7 0x561551356722 in call_func **/src/nvim/eval/userfunc.c:1708:15
    #8 0x561551352bfd in get_func_tv **/src/nvim/eval/userfunc.c:554:11
    #9 0x56155138ca8a in ex_call_inner **/src/nvim/eval/userfunc.c:3126:9
    #10 0x56155138ab99 in ex_call **/src/nvim/eval/userfunc.c:3368:14
    #11 0x56155147b91c in execute_cmd0 **/src/nvim/ex_docmd.c:1638:7
    #12 0x561551458808 in do_one_cmd **/src/nvim/ex_docmd.c:2297:7
    #13 0x561551449076 in do_cmdline **/src/nvim/ex_docmd.c:596:20
    #14 0x561551aa408f in nv_colon **/src/nvim/normal.c:3216:18
    #15 0x561551a8f5d5 in normal_execute **/src/nvim/normal.c:1220:3
    #16 0x56155209b691 in state_enter **/src/nvim/state.c:96:26
    #17 0x561551a72548 in normal_enter **/src/nvim/normal.c:509:3
    #18 0x561550b7cf58 in main **/src/nvim/main.c:640:3
    #19 0x7f2cffab2ccf  (/usr/lib/libc.so.6+0x27ccf) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #20 0x7f2cffab2d89 in __libc_start_main (/usr/lib/libc.so.6+0x27d89) (BuildId: 8bfe03f6bf9b6a6e2591babd0bbc266837d8f658)
    #21 0x561550a42d94 in _start (**/build/bin/nvim+0xbc9d94) (BuildId: 87fd7b9d6105b9d77e3100fc387058eba8544600)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/eval/userfunc.c:3373:62 in 
```

**Comment by zeertzjq** [comment]
Related #24556
