### ISSUE TITLE
pynvim.api.common.NvimError: Vim:<action-code>:1: SyntaxWarning: invalid escape sequence '\e'      

### ISSUE THREAD

**Issue by rickalex21** [neovim/neovim#26377]
### Problem

Looks like there may be a bug in NVims Python emulation layer. 

```text
Error executing vim.schedule lua callback: function cmp_nvim_ultisnips#get_current_snippets[33]..provider#python3#Call, line 18: Vim(return):Error invoking 'python
_execute' on channel 8 (python3-script-host):                                                                                                                      
Traceback (most recent call last):                                                                                                                                 
  File "<string>", line 22, in <module>                                                                                                                            
  File "/usr/lib/python3.12/site-packages/pynvim/api/nvim.py", line 287, in command                                                                                
    return self.request('nvim_command', string, **kwargs)                                                                                                          
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
  File "/usr/lib/python3.12/site-packages/pynvim/api/nvim.py", line 182, in request                                                                                
    res = self._session.request(name, *args, **kwargs)                                                                                                             
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
  File "/usr/lib/python3.12/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                     
    raise self.error_wrapper(err)                                                                                                                                  
pynvim.api.common.NvimError: Vim:<action-code>:1: SyntaxWarning: invalid escape sequence '\e'                                                                      
stack traceback:                                                                                                                                                   
        [C]: in function 'load_snippets'                                                                                                                           
        ...ged/cmp-nvim-ultisnips/lua/cmp_nvim_ultisnips/source.lua:27: in function 'complete'                                                                     
        ...ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/source.lua:334: in function 'complete'                                                                    
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:299: in function 'complete'                                                                    
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:169: in function 'autoindent'                                                                  
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'                                                                   
        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/init.lua:338: in function 'callback'                                                                    
        ...ie/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:165: in function <...ie/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:163>  
```

### Steps to reproduce

It randomly happens when I try to open a file with `:vs` to open another file with tab.

### Expected behavior

No errors.

### Neovim version (nvim -v)

NVIM v0.9.4

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Linux void 6.5.13_1 #1 SMP PREEMPT_DYNAMIC Thu Nov 30 23:19:06 UTC 2023 x86_64 GNU/Linux

### Terminal name/version

kitty 0.31.0 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Installation

xbps-install -S neovim

**Comment by wookayin** [comment]
Please provide specific reproducible steps. The '\e` character probably comes from a snippet file in your config, so you may want to take a look at those snippet files. This is likely to be a plugin error, not neovim core (or pynvim's error): `cmp_nvim_ultisnips#get_current_snippets`

**Comment by rickalex21** [comment]
@wookayin This is similar to what the maintainer of Ultisnips said: "This is almost certainly a bug in NVims Python emulation layer."

**Comment by wookayin** [comment]
@rickalex21 Would you please put a link to that comment please?

**Comment by wookayin** [comment]
https://github.com/SirVer/ultisnips/issues/1546
https://github.com/quangnguyen30192/cmp-nvim-ultisnips/issues/80#issuecomment-1817547469 (actually your comment doesn't look relevant to the original issue)

Again, without looking at your actual snippet or code, people can't help you much.
