### ISSUE TITLE
Volar Quits with Exit Code 1 on Neovim Nightly

### ISSUE THREAD

**Issue by lucario387** [neovim/neovim#27424]
### Problem

Since commit 2e982f1aad9f1a03562b7a451d642f76b04c37cb, Volar LSP always exit a few seconds after attached to a Vue buffer.

### Steps to reproduce using "nvim -u minimal_init.lua"

- Do `npx create-vite@latest --template vue-ts bug-volar && cd bug-volar && npm i`
- `minimal_init.lua`:
```lua
local pattern = 'vue'
local cmd = {'vue-language-server' , '--stdio'}
-- Add files/folders here that indicate the root of a project
local root_markers = { 'package.json'}
-- Change to table with settings if required
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd('FileType', {
  pattern = pattern,
  callback = function(args)
    local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
    local root_dir = match and vim.fn.fnamemodify(match, ':p:h') or nil
    vim.lsp.start({
      name = 'bugged-volar',
      cmd = cmd,
      root_dir = root_dir,
      settings = settings,
      init_options = {
        typescript = {
          tsdk = "",
        },
      },
    })
  end
})
```
- `nvim --clean -u minimal_init.lua src/App.vue`

### Expected behavior

Volar to not quit after a few seconds of attaching

### Additional Information:

- Using the minimal reproduce template on 0.9.5 gives this log file:
```
[START][2024-02-11 20:08:19] LSP logging initiated
[WARN][2024-02-11 20:08:19] ...lsp/handlers.lua:137	"The language server volar triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

- Using the same minimal template on nightly creates this log:
```
[START][2024-02-11 20:11:28] LSP logging initiated
[WARN][2024-02-11 20:11:29] ...lsp/handlers.lua:134	"The language server volar triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2024-02-11 20:11:32] .../lua/vim/lsp.lua:823	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
[ERROR][2024-02-11 20:11:32] .../vim/lsp/rpc.lua:798	"rpc"	"/home/lucario387/.local/share/nvim/mason/bin/vue-language-server"	"stderr"	"/home/lucario387/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:565\n                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n                                               ^\n\nResponseError: MethodNotFound\n    at handleResponse (/home/lucario387/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n    at handleMessage (/home/lucario387/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n    at processMessageQueue (/home/lucario387/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n    at Immediate.<anonymous> (/home/lucario387/.local/share/nvim/mason/packages/vue-language-server/node_modules/@vue/language-server/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n    at process.processImmediate (node:internal/timers:478:21) {\n  code: -32601,\n  data: undefined\n}\n\nNode.js v20.11.0\n"
```

The problem seems to be from not having a handler due to deferred loading

cc. @wookayin

### Neovim version (nvim -v)

ed1b66bd998b98ee8cf76b5a23c323352588dd56

### Language server name/version

Volar 1.8.27

### Operating system/version

Linux 6.7.4-arch1-1

**Comment by gegoune** [comment]
For me, volar quits on first save to the buffer.

**Comment by lewis6991** [comment]
I'm not able to reproduce. I get this log:

```
[START][2024-02-11 17:38:33] LSP logging initiated
[WARN][2024-02-11 17:38:33] ...lsp/handlers.lua:573	"No typescript found, vue-language-server will not work."
[WARN][2024-02-11 17:38:33] ...lsp/handlers.lua:134	"The language server bugged-volar triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"

```

**Comment by lewis6991** [comment]
Ah I can reproduce now by saving the buffer with the config in nvim-lspconfig

**Comment by lewis6991** [comment]
@lucario387 @gegoune can you check with #27427.

I'm not sure why https://github.com/neovim/neovim/commit/2e982f1aad9f1a03562b7a451d642f76b04c37cb caused this. I would have expected 2e982f1a to.

**Comment by gegoune** [comment]
@lewis6991 I can confirm that #27427 indeed fixes Solar's crash for me. Thank you so much!

**Comment by lucario387** [comment]
Can confirm this is working :D 

Thank you for the fix
