### ISSUE TITLE
`decor_virt_lines` fails on scroll when there are virt_lines outside the viewport

### ISSUE THREAD

**Issue by lukas-reineke** [neovim/neovim#28290]
### Problem

When there is an ext mark with virtual lines outside of the current displayed area, and you scroll to it with for example `<C-f>`, this assertion is false https://github.com/neovim/neovim/blob/8cca7871555e15f53de3dc4325c8d0203a78622a/src/nvim/decoration.c#L891

### Steps to reproduce

`nvim --clean`

```
100o
<ESC>
gg

:lua vim.api.nvim_buf_set_extmark(1, vim.api.nvim_create_namespace "foo", 100, 0, { virt_lines = { { { "hello world", "Normal" } } } })

<C-f>
```

### Expected behavior

This shouldn't fail.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2873+g8cca78715

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Arch Linux

### Terminal name/version

kitty 0.33.0

### $TERM environment variable

xterm-kitty

### Installation

build from repo

**Comment by zeertzjq** [comment]
Backtrace:
```
=================================================================
==51549==ERROR: AddressSanitizer: ABRT on unknown address 0x03e80000c95d (pc 0x7d926058432c bp 0x7d926034ec00 sp 0x7ffeb7292ab0 T0)
    #0 0x7d926058432c  (/usr/lib/libc.so.6+0x8d32c) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #1 0x7d92605336c7 in raise (/usr/lib/libc.so.6+0x3c6c7) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #2 0x7d926051b4b7 in abort (/usr/lib/libc.so.6+0x244b7) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #3 0x7d926051b3db  (/usr/lib/libc.so.6+0x243db) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #4 0x7d926052bd45 in __assert_fail (/usr/lib/libc.so.6+0x34d45) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #5 0x5ade1aa7c9dd in decor_virt_lines **/src/nvim/decoration.c:891:3
    #6 0x5ade1b772e6b in win_get_fill **/src/nvim/plines.c:700:20
    #7 0x5ade1b5154c3 in get_scroll_overlap **/src/nvim/move.c:2365:15
    #8 0x5ade1b5134e6 in pagescroll **/src/nvim/move.c:2503:45
    #9 0x5ade1b56a360 in nv_page **/src/nvim/normal.c:2269:5
    #10 0x5ade1b569425 in normal_execute **/src/nvim/normal.c:1229:3
    #11 0x5ade1bb8ae29 in state_enter **/src/nvim/state.c:101:26
    #12 0x5ade1b5474ca in normal_enter **/src/nvim/normal.c:518:3
    #13 0x5ade1b270769 in main **/src/nvim/main.c:663:3
    #14 0x7d926051cccf  (/usr/lib/libc.so.6+0x25ccf) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #15 0x7d926051cd89 in __libc_start_main (/usr/lib/libc.so.6+0x25d89) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af)
    #16 0x5ade1a51ed64 in _start (**/build/bin/nvim+0xbedd64) (BuildId: a9ef478ae18fe33a64b2eb0a78ba809b2f3ab09d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/usr/lib/libc.so.6+0x8d32c) (BuildId: c0caa0b7709d3369ee575fcd7d7d0b0fc48733af) 
==51549==ABORTING
```

**Comment by zeertzjq** [comment]
Backtrace:
```
#0  0x00007ffff7cfe32c in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7cad6c8 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff7c954b8 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7c953dc in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff7ca5d46 in __assert_fail () from /usr/lib/libc.so.6
#5  0x000055555669f9de in decor_virt_lines (wp=0x526000000100, lnum=0, lines=0x0, has_fold=kNone) at **/src/nvim/decoration.c:891
#6  0x0000555557395e6c in win_get_fill (wp=0x526000000100, lnum=0) at **/src/nvim/plines.c:700
#7  0x00005555571384c4 in get_scroll_overlap (dir=FORWARD) at **/src/nvim/move.c:2365
#8  0x00005555571364e7 in pagescroll (dir=FORWARD, count=1, half=false) at **/src/nvim/move.c:2503
#9  0x000055555718d361 in nv_page (cap=0x7ffff5e04690) at **/src/nvim/normal.c:2269
#10 0x000055555718c426 in normal_execute (state=0x7ffff5e04620, key=6) at **/src/nvim/normal.c:1229
#11 0x00005555577ade2a in state_enter (s=0x7ffff5e04620) at **/src/nvim/state.c:101
#12 0x000055555716a4cb in normal_enter (cmdwin=false, noexmode=false) at **/src/nvim/normal.c:518
#13 0x0000555556e9376a in main (argc=3, argv=0x7fffffffe118) at **/src/nvim/main.c:663
```

**Comment by zeertzjq** [comment]
This seems to be missing a pair of parentheses:
```diff
diff --git a/src/nvim/move.c b/src/nvim/move.c
index c055f6baa..4448091b8 100644
--- a/src/nvim/move.c
+++ b/src/nvim/move.c
@@ -2362,7 +2362,7 @@ static int get_scroll_overlap(Direction dir)
   }
 
   loff.lnum = dir == FORWARD ? curwin->w_botline : curwin->w_topline - 1;
-  loff.fill = win_get_fill(curwin, loff.lnum + dir == BACKWARD)
+  loff.fill = win_get_fill(curwin, loff.lnum + (dir == BACKWARD))
               - (dir == FORWARD ? curwin->w_filler_rows : curwin->w_topfill);
   loff.height = loff.fill > 0 ? 1 : plines_win_nofill(curwin, loff.lnum, true);
 
```
