### ISSUE TITLE
assertion `"!(schar_high(sc) &&   >  schar_idx(sc) >= glyph_cache.h.n_keys)"` fails if `$LINES <= 16`

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#28419]
### Problem

Nvim can crash at the start within terminal window smaller than 17 lines (for me):

```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007fe0ffbc71cf in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007fe0ffb79472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fe0ffb634b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fe0ffb633d5 in __assert_fail_base (fmt=0x7fe0ffcd7dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55bf8a819ad8 "!(schar_high(sc) && schar_idx(sc) >= glyph_cache.h.n_keys)",
    file=file@entry=0x55bf8a819aa0 ".../src/nvim/grid.c", line=line@entry=192, function=function@entry=0x55bf8a7b9b50 <__PRETTY_FUNCTION__.7> "schar_get_first_byte") at ./assert/assert.c:92
#5  0x00007fe0ffb723a2 in __assert_fail (assertion=assertion@entry=0x55bf8a819ad8 "!(schar_high(sc) && schar_idx(sc) >= glyph_cache.h.n_keys)", file=file@entry=0x55bf8a819aa0 ".../src/nvim/grid.c",
    line=line@entry=192, function=function@entry=0x55bf8a7b9b50 <__PRETTY_FUNCTION__.7> "schar_get_first_byte") at ./assert/assert.c:101
#6  0x000055bf8a549851 in schar_get_first_byte (sc=4294967295) at .../src/nvim/grid.c:192
#7  0x000055bf8a54985e in schar_in_arabic_block (sc=<optimized out>) at .../src/nvim/grid.c:215
#8  0x000055bf8a54dd04 in line_do_arabic_shape (buf=0x55bf8bf5beb0, cols=cols@entry=10) at .../src/nvim/grid.c:240
#9  0x000055bf8a552e22 in grid_put_linebuf (grid=0x55bf8a8ea2c0 <msg_grid>, row=15, coloff=0, col=96, endcol=106, clear_width=106, bg_attr=0, last_vcol=-1, flags=0) at .../src/nvim/grid.c:677
#10 0x000055bf8a5532de in grid_line_flush () at .../src/nvim/grid.c:573
#11 0x000055bf8a5b93f1 in display_showcmd () at .../src/nvim/normal.c:2096
#12 0x000055bf8a5b9c78 in add_to_showcmd (c=<optimized out>) at .../src/nvim/normal.c:1995
#13 0x000055bf8a5baf35 in normal_execute (state=0x7ffff1a83af0, key=<optimized out>) at .../src/nvim/normal.c:1100
#14 0x000055bf8a65c94e in state_enter (s=0x7ffff1a83af0) at .../src/nvim/state.c:101
#15 0x000055bf8a5b84d3 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at .../src/nvim/normal.c:518
#16 0x000055bf8a57e9dd in main (argc=5, argv=<optimized out>) at .../src/nvim/main.c:663

```

### Steps to reproduce

1. open terminal and reduce its height to 16 lines or lower
2. run `nvim --clean --cmd startinsert` 

### Expected behavior

No crash

### Neovim version (nvim -v)

v0.10.0-dev-2960+g52d2851ca

### Vim (not Nvim) behaves the same?

no, 9.1.0199

### Operating system/version

Debian Sid

### Terminal name/version

alacritty 0.14.0-dev (6585d604)

### $TERM environment variable

alacritty

### Installation

from repo

**Comment by przepompownia** [comment]
I don't know how much they are similar but I get at leas two other backtraces from the same repro:
```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007fe9c21241cf in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007fe9c20d6472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fe9c20c04b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fe9c20c03d5 in __assert_fail_base (fmt=0x7fe9c2234dc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x560b59846cb0 "(size_t)attrs[c - startcol] < kv_size(tui->attrs)",
    file=file@entry=0x560b598467e0 ".../src/nvim/tui/tui.c", line=line@entry=1618, function=function@entry=0x560b597fe378 <__PRETTY_FUNCTION__.0.lto_priv.67> "tui_raw_line") at ./assert/assert.c:92
#5  0x00007fe9c20cf3a2 in __assert_fail (assertion=assertion@entry=0x560b59846cb0 "(size_t)attrs[c - startcol] < kv_size(tui->attrs)", file=file@entry=0x560b598467e0 ".../src/nvim/tui/tui.c",
    line=line@entry=1618, function=function@entry=0x560b597fe378 <__PRETTY_FUNCTION__.0.lto_priv.67> "tui_raw_line") at ./assert/assert.c:101
#6  0x0000560b596a4b50 in tui_raw_line (tui=0x560b5b6167e0, g=<optimized out>, linerow=14, startcol=95, endcol=105, clearcol=105, clearattr=0, flags=0, chunk=0x560b5b5e0990, attrs=0x560b5b629030)
    at .../src/nvim/tui/tui.c:1618
#7  0x0000560b596ab339 in ui_client_event_raw_line (g=<optimized out>) at .../src/nvim/ui_client.c:230
#8  0x0000560b595d3fe2 in parse_msgpack (channel=channel@entry=0x560b5b5ecef0) at .../src/nvim/msgpack_rpc/channel.c:293
#9  0x0000560b595d4246 in receive_msgpack (stream=<optimized out>, rbuf=0x560b5b5ed710, c=<optimized out>, data=0x560b5b5ecef0, eof=<optimized out>) at .../src/nvim/msgpack_rpc/channel.c:263
#10 0x0000560b5952c4c1 in read_event (argv=argv@entry=0x7fff10d696d0) at .../src/nvim/event/rstream.c:191
#11 0x0000560b5952c5d9 in invoke_read_cb (stream=stream@entry=0x560b5b5ed100, count=count@entry=5069, eof=eof@entry=false) at .../src/nvim/event/rstream.c:204
#12 0x0000560b5952d70e in read_cb (uvstream=<optimized out>, cnt=5069, buf=<optimized out>) at .../src/nvim/event/rstream.c:133
#13 0x0000560b597bc30a in uv.read ()
#14 0x0000560b597bcb00 in uv.stream_io ()
#15 0x0000560b597c37b1 in uv.io_poll ()
#16 0x0000560b597b214f in uv_run ()
#17 0x0000560b595286e2 in loop_uv_run (loop=loop@entry=0x560b59913340 <main_loop>, ms=-1) at .../src/nvim/event/loop.c:61
#18 0x0000560b5952955d in loop_poll_events (loop=0x560b59913340 <main_loop>, ms=<optimized out>) at .../src/nvim/event/loop.c:82
#19 0x0000560b596aaf18 in ui_client_run (remote_ui=<optimized out>) at .../src/nvim/ui_client.c:131
#20 0x0000560b5959b368 in main (argc=2, argv=<optimized out>) at .../src/nvim/main.c:402
```
and
```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f5a25e7b1cf in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f5a25e2d472 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f5a25e174b2 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f5a25e173d5 in __assert_fail_base (fmt=0x7f5a25f8bdc8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x55d981975d22 "attrs[i] >= 0",
    file=file@entry=0x55d98199b090 ".../src/nvim/ui_compositor.c", line=line@entry=546, function=function@entry=0x55d98195b950 <__PRETTY_FUNCTION__.0.lto_priv.69> "ui_comp_raw_line") at ./assert/assert.c:92
#5  0x00007f5a25e263a2 in __assert_fail (assertion=assertion@entry=0x55d981975d22 "attrs[i] >= 0", file=file@entry=0x55d98199b090 ".../src/nvim/ui_compositor.c", line=line@entry=546,
    function=function@entry=0x55d98195b950 <__PRETTY_FUNCTION__.0.lto_priv.69> "ui_comp_raw_line") at ./assert/assert.c:101
#6  0x000055d981800200 in ui_comp_raw_line (grid=<optimized out>, row=13, startcol=95, endcol=105, clearcol=105, clearattr=0, flags=0, chunk=0x55d9827c3084, attrs=0x55d9827c47c4)
    at .../src/nvim/ui_compositor.c:546
#7  0x000055d9817fb330 in ui_call_raw_line (grid=3, row=13, startcol=95, endcol=105, clearcol=105, clearattr=0, flags=0, chunk=0x55d9827c3084, attrs=0x55d9827c47c4)
    at .../build/src/nvim/auto/ui_events_call.generated.h:232
#8  0x000055d9817fc9dc in ui_line (grid=0x55d981a5b2c0 <msg_grid>, row=13, invalid_row=<optimized out>, startcol=95, endcol=105, clearcol=105, clearattr=0, wrap=false) at .../src/nvim/ui.c:474
#9  0x000055d9816c423c in grid_put_linebuf (grid=0x55d981a5b2c0 <msg_grid>, row=13, coloff=0, col=105, endcol=105, clear_width=<optimized out>, bg_attr=<optimized out>, last_vcol=<optimized out>, flags=0)
    at .../src/nvim/grid.c:800
#10 0x000055d9816c42de in grid_line_flush () at .../src/nvim/grid.c:573
#11 0x000055d98172a3f1 in display_showcmd () at .../src/nvim/normal.c:2096
#12 0x000055d98172ac78 in add_to_showcmd (c=<optimized out>) at .../src/nvim/normal.c:1995
#13 0x000055d98172bf35 in normal_execute (state=0x7ffcd3ebf190, key=<optimized out>) at .../src/nvim/normal.c:1100
#14 0x000055d9817cd94e in state_enter (s=0x7ffcd3ebf190) at .../src/nvim/state.c:101
#15 0x000055d9817294d3 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at .../src/nvim/normal.c:518
#16 0x000055d9816ef9dd in main (argc=5, argv=<optimized out>) at .../src/nvim/main.c:663
```

**Comment by przepompownia** [comment]
Fixed, thanks!
