### ISSUE TITLE
Segfault when editing html part in markdown

### ISSUE THREAD

**Issue by mlthlschr** [neovim/neovim#28644]
### Problem

When I edit a markdown file containing a html block, nvim segfaults when i edit text in brackets in that html block. 

Example:

```md
### <a id="this-is-a-random-id"></a> This is a header with custom id
```

If I `ci"` and enter two letters, nvim crashes. The same happens with `f"dwi`.

<details>
<summary>Open dump file backtrace</summary>

```
GNU gdb (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nvim...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.artixlinux.org>
[?2004hEnable debuginfod for this session? (y or [n]) y
[?2004l
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /usr/bin/nvim...
(No debugging symbols found in nvim)

warning: Can't open file anon_inode:[io_uring] which was expanded to anon_inode:[io_uring] during file-backed mapping note processing
[New LWP 27086]
[New LWP 27088]
[New LWP 27089]
Downloading separate debug info for /usr/lib/libluv.so.1...
Downloading separate debug info for /usr/lib/libtermkey.so.1...
Downloading separate debug info for /usr/lib/libvterm.so.0...
Downloading separate debug info for /usr/lib/libmsgpackc.so.2...
Downloading separate debug info for /usr/lib/libtree-sitter.so.0...
Downloading separate debug info for /usr/lib/libunibilium.so.4...
Downloading separate debug info for /usr/lib/libluajit-5.1.so.2...
Downloading separate debug info for /usr/lib/libm.so.6...
Downloading separate debug info for /usr/lib/libuv.so.1...
Downloading separate debug info for /usr/lib/libc.so.6...
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2...
Downloading separate debug info for /home/malte/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/markdown.so...
Downloading separate debug info for /usr/share/nvim/runtime/parser/markdown_inline.so...
Downloading separate debug info for /home/malte/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/html.so...
Downloading separate debug info for system-supplied DSO at 0x7ffef46be000...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `nvim --embed NMEA.md'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007a2e36565e3e in __GI___libc_free (mem=0x30) at malloc.c:3375
Downloading source file /usr/src/debug/glibc/glibc/malloc/malloc.c...
3375	  if (chunk_is_mmapped (p))                       /* release mmapped memory. */
[Current thread is 1 (Thread 0x7a2e364c5740 (LWP 27086))]
[?2004h(gdb) thread apply all bt full
[?2004l
Thread 3 (LWP 27089):
#0  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x0

Thread 2 (LWP 27088):
#0  0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x0

Thread 1 (Thread 0x7a2e364c5740 (LWP 27086)):
#0  0x00007a2e36565e3e in __GI___libc_free (mem=0x30) at malloc.c:3375
        ar_ptr = <optimized out>
        p = <optimized out>
        err = <optimized out>
#1  0x00007a2e3691eb04 in tree_sitter_html_external_scanner_destroy () from /home/malte/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/html.so
No symbol table info available.
#2  0x00007a2e3689d96e in ts_parser_reset () from /usr/lib/libtree-sitter.so.0
No symbol table info available.
#3  0x00007a2e3689e040 in ts_parser_parse () from /usr/lib/libtree-sitter.so.0
No symbol table info available.
#4  0x0000652c62e4565d in ?? ()
No symbol table info available.
#5  0x00007a2e367f7ef6 in ?? () from /usr/lib/libluajit-5.1.so.2
No symbol table info available.
#6  0x00007a2e3680aab3 in lua_pcall () from /usr/lib/libluajit-5.1.so.2
No symbol table info available.
#7  0x0000652c62e327c1 in ?? ()
No symbol table info available.
#8  0x0000652c62e42935 in nlua_call_ref ()
No symbol table info available.
#9  0x0000652c62fde679 in ?? ()
No symbol table info available.
#10 0x0000652c62d4cc24 in decor_providers_invoke_buf ()
No symbol table info available.
#11 0x0000652c62d62e05 in update_screen ()
No symbol table info available.
#12 0x0000652c62d703b4 in ?? ()
No symbol table info available.
#13 0x0000652c62d69d72 in ?? ()
No symbol table info available.
#14 0x0000652c62f624e2 in state_enter ()
No symbol table info available.
#15 0x0000652c62d66ff6 in edit ()
No symbol table info available.
#16 0x0000652c62ea8958 in op_change ()
No symbol table info available.
#17 0x0000652c62eb1b94 in do_pending_operator ()
No symbol table info available.
#18 0x0000652c62e92890 in ?? ()
No symbol table info available.
#19 0x0000652c62f62597 in state_enter ()
No symbol table info available.
#20 0x0000652c62e91fd9 in normal_enter ()
No symbol table info available.
#21 0x0000652c62ccb777 in main ()
No symbol table info available.
[?2004h(gdb) 
```
</details>

The dump file looks a bit empty so let me know if I can help you more.

What I can see is some issue with tree sitter. I tried to `:TsUpdate` but it seems that everything is up to date.

I have not observed that behaviour before. Might be some broken dependency due to a system update. I will restart my machine and close the ticket if its fixed by then. But for now I open the ticket as it would be lost after reboot.

### Steps to reproduce

nvim file.md
file only contains `<a id="this-is-a-random-id"></a>`
move to first char of that line
ci"
enter two letters
`sigsegv(11)`

### Expected behavior

no segfault, normal text input

### Neovim version (nvim -v)

0.9.5 Release

### Vim (not Nvim) behaves the same?

do not have vim installed

### Operating system/version

artix latest

### Terminal name/version

alacritty 0.13.2 (bb8ea18e), tmux 3.4

### $TERM environment variable

tmux-256color

### Installation

pacman

**Comment by clason** [comment]
Cannot reproduce. We need a complete and reproducible setup (including the exact commit hash of the markdown and html parser used).

**Comment by clason** [comment]
Stacktrace shows that the html parser is crashing (in its external scanner); there's nothing we can do about that. Make sure your nvim-treesitter (including all parers) is fully updated; if you can still reproduce, open an issue at tree-sitter/tree-sitter-html.

**Comment by mlthlschr** [comment]
Thanks for the quick feedback. Gonna check that parser.
