### ISSUE TITLE
LSP de-sync when using softtabstop=-1 with foldmethod=indent

### ISSUE THREAD

**Issue by icholy** [neovim/neovim#29119]
### Problem

When using `softtabstop=-1` and `foldmethod=indent` inserting tab characters can result in a de-sync. This looks very similar to https://github.com/neovim/neovim/issues/25092 but I've confirmed it's not a regression.

### Steps to reproduce

Repo: https://github.com/icholy/nvim-bug-29119

**init.lua**
``` lua
vim.o.foldmethod = "indent"
vim.o.softtabstop = -1

vim.api.nvim_create_autocmd("FileType", {
        pattern = "go",
        callback = function()
		vim.lsp.start({ cmd = { "gopls" } })
        end
})
```

**main.go**

``` go
package main

func main() {
	println()
}
```

**Steps:**

1. `nvim --clean -u init.lua main.go`
2. Insert `<TAB>` character right before `println()` call.
3. Leave insert mode with `<ESC>`.

**See:**

![image](https://github.com/neovim/neovim/assets/943597/06d5e7fa-b227-482a-9081-59f5c0b6b5f3)

### Expected behavior

No de-sync

### Neovim version (nvim -v)

NVIM v0.11.0-dev-139+ga18652ed6

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

Ubuntu 22.04.4 LTS

### Terminal name/version

alacritty 0.12.2

### $TERM environment variable

alacritty

### Installation

bob

**Comment by wookayin** [comment]
Please refrain from using external repositories as reproduction step. It'd be great if this issue can be self-contained.

**Comment by icholy** [comment]
@wookayin the issue description contains the exact same contents as the repo I linked.

**Comment by icholy** [comment]
@wookayin I'm able to reproduce with luals as well. I generally use gopls for repros because it's fast to initialize & less buggy than other LSPs in general.

**Comment by icholy** [comment]
Here's the LSP log:

```
[START][2024-06-02 00:50:08] LSP logging initiated
[INFO][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:731	"Starting RPC client"	{  cmd = { "gopls" },  extra = {}}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      general = {        positionEncodings = { "utf-16" }      },      textDocument = {        callHierarchy = {          dynamicRegistration = false        },        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }            }          },          dataSupport = true,          dynamicRegistration = true,          isPreferredSupport = true,          resolveSupport = {            properties = { "edit" }          }        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            resolveSupport = {              properties = { "additionalTextEdits" }            },            snippetSupport = true          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 }          },          completionList = {            itemDefaults = { "editRange", "insertTextFormat", "insertTextMode", "data" }          },          contextSupport = false,          dynamicRegistration = false        },        declaration = {          linkSupport = true        },        definition = {          dynamicRegistration = true,          linkSupport = true        },        diagnostic = {          dynamicRegistration = false        },        documentHighlight = {          dynamicRegistration = false        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        formatting = {          dynamicRegistration = true        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = true        },        implementation = {          linkSupport = true        },        inlayHint = {          dynamicRegistration = true,          resolveSupport = {            properties = { "textEdits", "tooltip", "location", "command" }          }        },        publishDiagnostics = {          dataSupport = true,          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 }          }        },        rangeFormatting = {          dynamicRegistration = true        },        references = {          dynamicRegistration = false        },        rename = {          dynamicRegistration = true,          prepareSupport = true        },        semanticTokens = {          augmentsSyntaxTokens = true,          dynamicRegistration = false,          formats = { "relative" },          multilineTokenSupport = false,          overlappingTokenSupport = true,          requests = {            full = {              delta = true            },            range = false          },          serverCancelSupport = false,          tokenModifiers = { "declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary" },          tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", "variable", "property", "enumMember", "event", "function", "method", "macro", "keyword", "modifier", "comment", "string", "number", "regexp", "operator", "decorator" }        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            activeParameterSupport = true,            documentationFormat = { "markdown", "plaintext" },            parameterInformation = {              labelOffsetSupport = true            }          }        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = true,          willSaveWaitUntil = true        },        typeDefinition = {          linkSupport = true        }      },      window = {        showDocument = {          support = true        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false          }        },        workDoneProgress = true      },      workspace = {        applyEdit = true,        configuration = true,        didChangeConfiguration = {          dynamicRegistration = false        },        didChangeWatchedFiles = {          dynamicRegistration = false,          relativePatternSupport = true        },        inlayHint = {          refreshSupport = true        },        semanticTokens = {          refreshSupport = true        },        symbol = {          dynamicRegistration = false,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 }          }        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" }        },        workspaceFolders = true      }    },    clientInfo = {      name = "Neovim",      version = "0.11.0-dev+ga18652ed6"    },    processId = 16424,    rootPath = vim.NIL,    rootUri = vim.NIL,    trace = "off",    workDoneToken = "1",    workspaceFolders = vim.NIL  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      callHierarchyProvider = true,      codeActionProvider = {        codeActionKinds = { "quickfix", "refactor.extract", "refactor.inline", "refactor.rewrite", "source.fixAll", "source.organizeImports" },        resolveProvider = true      },      codeLensProvider = vim.empty_dict(),      completionProvider = {        triggerCharacters = { "." }      },      definitionProvider = true,      documentFormattingProvider = true,      documentHighlightProvider = true,      documentLinkProvider = vim.empty_dict(),      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "gopls.add_dependency", "gopls.add_import", "gopls.add_telemetry_counters", "gopls.apply_fix", "gopls.change_signature", "gopls.check_upgrades", "gopls.diagnose_files", "gopls.edit_go_directive", "gopls.fetch_vulncheck_result", "gopls.gc_details", "gopls.generate", "gopls.go_get_package", "gopls.list_imports", "gopls.list_known_packages", "gopls.maybe_prompt_for_telemetry", "gopls.mem_stats", "gopls.regenerate_cgo", "gopls.remove_dependency", "gopls.reset_go_mod_diagnostics", "gopls.run_go_work_command", "gopls.run_govulncheck", "gopls.run_tests", "gopls.start_debugging", "gopls.start_profile", "gopls.stop_profile", "gopls.test", "gopls.tidy", "gopls.toggle_gc_details", "gopls.update_go_sum", "gopls.upgrade_dependency", "gopls.vendor", "gopls.views", "gopls.workspace_stats" }      },      foldingRangeProvider = true,      hoverProvider = true,      implementationProvider = true,      inlayHintProvider = vim.empty_dict(),      referencesProvider = true,      renameProvider = {        prepareProvider = true      },      selectionRangeProvider = true,      semanticTokensProvider = {        full = true,        legend = {          tokenModifiers = { "declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary" },          tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", "variable", "property", "enumMember", "event", "function", "method", "macro", "keyword", "modifier", "comment", "string", "number", "regexp", "operator", "decorator" }        },        range = true      },      signatureHelpProvider = {        triggerCharacters = { "(", "," }      },      textDocumentSync = {        change = 2,        openClose = true,        save = vim.empty_dict()      },      typeDefinitionProvider = true,      workspace = {        workspaceFolders = {          changeNotifications = "workspace/didChangeWorkspaceFolders",          supported = true        }      },      workspaceSymbolProvider = true    },    serverInfo = {      name = "gopls",      version = '{"GoVersion":"go1.22.0","Path":"golang.org/x/tools/gopls","Main":{"Path":"golang.org/x/tools/gopls","Version":"v0.15.3","Sum":"h1:zbdOidFrPTc8Bx0YrN5QKgJ0zCjyGi0L27sKQ/bDG5o=","Replace":null},"Deps":[{"Path":"github.com/BurntSushi/toml","Version":"v1.2.1","Sum":"h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=","Replace":null},{"Path":"github.com/google/go-cmp","Version":"v0.6.0","Sum":"h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=","Replace":null},{"Path":"golang.org/x/exp/typeparams","Version":"v0.0.0-20221212164502-fae10dda9338","Sum":"h1:2O2DON6y3XMJiQRAS1UWU+54aec2uopH3x7MAiqGW6Y=","Replace":null},{"Path":"golang.org/x/mod","Version":"v0.15.0","Sum":"h1:SernR4v+D55NyBH2QiEQrlBAnj1ECL6AGrA5+dPaMY8=","Replace":null},{"Path":"golang.org/x/sync","Version":"v0.6.0","Sum":"h1:5BMeUDZ7vkXGfEr1x9B4bRcTH4lpkTkpdh0T/J+qjbQ=","Replace":null},{"Path":"golang.org/x/telemetry","Version":"v0.0.0-20240209200032-7b892fcb8a78","Sum":"h1:vcVnuftN4J4UKLRcgetjzfU9FjjgXUUYUc3JhFplgV4=","Replace":null},{"Path":"golang.org/x/text","Version":"v0.14.0","Sum":"h1:ScX5w1eTa3QqT8oi6+ziP7dTV1S2+ALU0bI+0zXKWiQ=","Replace":null},{"Path":"golang.org/x/tools","Version":"v0.18.1-0.20240412183611-d92ae0781217","Sum":"h1:uH9jJYgeLCvblH0S+03kFO0qUDxRkbLRLFiKVVDl7ak=","Replace":null},{"Path":"golang.org/x/vuln","Version":"v1.0.1","Sum":"h1:KUas02EjQK5LTuIx1OylBQdKKZ9jeugs+HiqO5HormU=","Replace":null},{"Path":"honnef.co/go/tools","Version":"v0.4.6","Sum":"h1:oFEHCKeID7to/3autwsWfnuv69j3NsfcXbvJKuIcep8=","Replace":null},{"Path":"mvdan.cc/gofumpt","Version":"v0.6.0","Sum":"h1:G3QvahNDmpD+Aek/bNOLrFR2XC6ZAdo62dZu65gmwGo=","Replace":null},{"Path":"mvdan.cc/xurls/v2","Version":"v2.5.0","Sum":"h1:lyBNOm8Wo71UknhUs4QTFUNNMyxy2JEIaKKo0RWOh+8=","Replace":null}],"Settings":[{"Key":"-buildmode","Value":"exe"},{"Key":"-compiler","Value":"gc"},{"Key":"DefaultGODEBUG","Value":"httplaxcontentlength=1,httpmuxgo121=1,panicnil=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1"},{"Key":"CGO_ENABLED","Value":"1"},{"Key":"CGO_CFLAGS","Value":""},{"Key":"CGO_CPPFLAGS","Value":""},{"Key":"CGO_CXXFLAGS","Value":""},{"Key":"CGO_LDFLAGS","Value":""},{"Key":"GOARCH","Value":"amd64"},{"Key":"GOOS","Value":"linux"},{"Key":"GOAMD64","Value":"v1"}],"Version":"v0.15.3"}'    }  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:286	"rpc.send"	{  jsonrpc = "2.0",  method = "initialized",  params = vim.empty_dict()}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:286	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "go",      text = "package main\n\nfunc main() {\nprintln()\n}\n\n",      uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go",      version = 3    }  }}
[INFO][2024-06-02 00:50:08] ...m/lsp/client.lua:620	"LSP[gopls]"	"server_capabilities"	{  server_capabilities = {    callHierarchyProvider = true,    codeActionProvider = {      codeActionKinds = { "quickfix", "refactor.extract", "refactor.inline", "refactor.rewrite", "source.fixAll", "source.organizeImports" },      resolveProvider = true    },    codeLensProvider = vim.empty_dict(),    completionProvider = {      triggerCharacters = { "." }    },    definitionProvider = true,    documentFormattingProvider = true,    documentHighlightProvider = true,    documentLinkProvider = vim.empty_dict(),    documentSymbolProvider = true,    executeCommandProvider = {      commands = { "gopls.add_dependency", "gopls.add_import", "gopls.add_telemetry_counters", "gopls.apply_fix", "gopls.change_signature", "gopls.check_upgrades", "gopls.diagnose_files", "gopls.edit_go_directive", "gopls.fetch_vulncheck_result", "gopls.gc_details", "gopls.generate", "gopls.go_get_package", "gopls.list_imports", "gopls.list_known_packages", "gopls.maybe_prompt_for_telemetry", "gopls.mem_stats", "gopls.regenerate_cgo", "gopls.remove_dependency", "gopls.reset_go_mod_diagnostics", "gopls.run_go_work_command", "gopls.run_govulncheck", "gopls.run_tests", "gopls.start_debugging", "gopls.start_profile", "gopls.stop_profile", "gopls.test", "gopls.tidy", "gopls.toggle_gc_details", "gopls.update_go_sum", "gopls.upgrade_dependency", "gopls.vendor", "gopls.views", "gopls.workspace_stats" }    },    foldingRangeProvider = true,    hoverProvider = true,    implementationProvider = true,    inlayHintProvider = vim.empty_dict(),    referencesProvider = true,    renameProvider = {      prepareProvider = true    },    selectionRangeProvider = true,    semanticTokensProvider = {      full = true,      legend = {        tokenModifiers = { "declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", "defaultLibrary" },        tokenTypes = { "namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", "variable", "property", "enumMember", "event", "function", "method", "macro", "keyword", "modifier", "comment", "string", "number", "regexp", "operator", "decorator" }      },      range = true    },    signatureHelpProvider = {      triggerCharacters = { "(", "," }    },    textDocumentSync = {      change = 2,      openClose = true,      save = vim.empty_dict()    },    typeDefinitionProvider = true,    workspace = {      workspaceFolders = {        changeNotifications = "workspace/didChangeWorkspaceFolders",        supported = true      }    },    workspaceSymbolProvider = true  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 1,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = "744700557183600534"  }}
[DEBUG][2024-06-02 00:50:08] ...m/lsp/client.lua:678	"LSP[gopls]"	"client.request"	1	"textDocument/semanticTokens/full"	{  textDocument = {    uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go"  }}	<function 1>	1
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 2,  jsonrpc = "2.0",  method = "textDocument/semanticTokens/full",  params = {    textDocument = {      uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go"    }  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:423	"server_request: callback result"	{  result = vim.NIL,  status = true}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 1,  jsonrpc = "2.0",  result = vim.NIL}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "744700557183600534",    value = {      kind = "begin",      message = "Loading packages...",      title = "Setting up workspace"    }  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 2,  jsonrpc = "2.0",  method = "workspace/configuration",  params = {    items = { {        scopeUri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8",        section = "gopls"      } }  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:423	"server_request: callback result"	{  result = { vim.NIL },  status = true}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 2,  jsonrpc = "2.0",  result = { vim.NIL }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2024/06/02 00:50:08 go info for /home/icholy/src/github.com/icholy/nvim-bug-8\n(view type AdHocView)\n(root dir /home/icholy/src/github.com/icholy/nvim-bug-8)\n(go version go version go1.22.0 linux/amd64)\n(build flags: [])\n(go env: {GOOS:linux GOARCH:amd64 GOCACHE:/home/icholy/.cache/go-build GOMODCACHE:/home/icholy/go/pkg/mod GOPATH:/home/icholy/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.0 linux/amd64\n GOWORK: GOPACKAGESDRIVER:})\n(env overlay: map[])\n\n",    type = 3  }}
[INFO][2024-06-02 00:50:08] ...lsp/handlers.lua:628	"2024/06/02 00:50:08 go info for /home/icholy/src/github.com/icholy/nvim-bug-8\n(view type AdHocView)\n(root dir /home/icholy/src/github.com/icholy/nvim-bug-8)\n(go version go version go1.22.0 linux/amd64)\n(build flags: [])\n(go env: {GOOS:linux GOARCH:amd64 GOCACHE:/home/icholy/.cache/go-build GOMODCACHE:/home/icholy/go/pkg/mod GOPATH:/home/icholy/go GOPRIVATE: GOFLAGS: GO111MODULE: GoVersion:22 GoVersionOutput:go version go1.22.0 linux/amd64\n GOWORK: GOPACKAGESDRIVER:})\n(env overlay: map[])\n\n"
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2024/06/02 00:50:08 go/packages.Load #1\n\tsnapshot=0\n\tdirectory=file:///home/icholy/src/github.com/icholy/nvim-bug-8\n\tquery=[./ builtin]\n\tpackages=2\n",    type = 3  }}
[INFO][2024-06-02 00:50:08] ...lsp/handlers.lua:628	"2024/06/02 00:50:08 go/packages.Load #1\n\tsnapshot=0\n\tdirectory=file:///home/icholy/src/github.com/icholy/nvim-bug-8\n\tquery=[./ builtin]\n\tpackages=2\n"
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "2024/06/02 00:50:08 go/packages.Load #1: updating metadata for 1 packages\n",    type = 3  }}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = "744700557183600534",    value = {      kind = "end",      message = "Finished loading packages."    }  }}
[INFO][2024-06-02 00:50:08] ...lsp/handlers.lua:628	"2024/06/02 00:50:08 go/packages.Load #1: updating metadata for 1 packages\n"
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  error = {    code = 0,    message = "semantictokens are disabled"  },  id = 2,  jsonrpc = "2.0"}
[DEBUG][2024-06-02 00:50:08] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = {},    uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go",    version = 3  }}
[DEBUG][2024-06-02 00:50:11] .../vim/lsp/rpc.lua:286	"rpc.send"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          ["end"] = {            character = 0,            line = 3          },          start = {            character = 0,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 1,            line = 3          },          start = {            character = 1,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 2,            line = 3          },          start = {            character = 2,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 3,            line = 3          },          start = {            character = 3,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 4,            line = 3          },          start = {            character = 4,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 5,            line = 3          },          start = {            character = 5,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 6,            line = 3          },          start = {            character = 6,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 7,            line = 3          },          start = {            character = 7,            line = 3          }        },        rangeLength = 0,        text = " "      }, {        range = {          ["end"] = {            character = 11,            line = 3          },          start = {            character = 0,            line = 3          }        },        rangeLength = 11,        text = "\tprintln()\0"      } },    textDocument = {      uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go",      version = 12    }  }}
[DEBUG][2024-06-02 00:50:11] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        message = "expected ';', found 'ILLEGAL'",        range = {          ["end"] = {            character = 10,            line = 3          },          start = {            character = 10,            line = 3          }        },        severity = 1,        source = "syntax"      } },    uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go",    version = 12  }}
[DEBUG][2024-06-02 00:50:11] .../vim/lsp/rpc.lua:286	"rpc.send"	{  jsonrpc = "2.0",  method = "$/cancelRequest",  params = {    id = 2  }}
[DEBUG][2024-06-02 00:50:11] ...m/lsp/client.lua:678	"LSP[gopls]"	"client.request"	1	"textDocument/semanticTokens/full"	{  textDocument = {    uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go"  }}	<function 1>	1
[DEBUG][2024-06-02 00:50:11] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 3,  jsonrpc = "2.0",  method = "textDocument/semanticTokens/full",  params = {    textDocument = {      uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go"    }  }}
[DEBUG][2024-06-02 00:50:11] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  error = {    code = 0,    message = "semantictokens are disabled"  },  id = 3,  jsonrpc = "2.0"}
```

The `textDocument/didChange` is including a null terminator for some reason `"\tprintln()\0"`

```
{
    jsonrpc = "2.0",
    method = "textDocument/didChange",
    params = {
        contentChanges = {
            {
                range = {["end"] = {character = 0, line = 3}, start = {character = 0, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 1, line = 3}, start = {character = 1, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 2, line = 3}, start = {character = 2, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 3, line = 3}, start = {character = 3, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 4, line = 3}, start = {character = 4, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 5, line = 3}, start = {character = 5, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 6, line = 3}, start = {character = 6, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 7, line = 3}, start = {character = 7, line = 3}},
                rangeLength = 0,
                text = " "
            },
            {
                range = {["end"] = {character = 11, line = 3}, start = {character = 0, line = 3}},
                rangeLength = 11,
                text = "\tprintln()\0"
            }
        },
        textDocument = {uri = "file:///home/icholy/src/github.com/icholy/nvim-bug-8/main.go", version = 12}
    }
}
```

**Comment by icholy** [comment]
The `on_lines` ranges are correct, it's `nvim_buf_lines` is returning bad data in the `on_lines` callback (putting it in a `vim.schedule` works correctly):

**init.lua**
``` lua
vim.o.foldmethod = "indent"
vim.o.softtabstop = -1

vim.api.nvim_create_autocmd("BufEnter", {
    callback = function()
        vim.api.nvim_buf_attach(0, false, {
            on_lines = function (_, bufnr, _, firstline, _, new_lastline)
                local lines = vim.api.nvim_buf_get_lines(bufnr, firstline, new_lastline, true) 
                vim.print(lines)
            end
        })
    end
})
```

**test.txt**
``` plain
a
b
```

**Steps:**
* `nvim --clean -u init.lua test.txt`
* `I<TAB>`
* `:messages`

**Output:**
```
{ " a" }
{ "  a" }
{ "   a" }
{ "    a" }
{ "     a" }
{ "      a" }
{ "       a" }
{ "        a" }
{ "\ta\0     a" }
```

**Comment by icholy** [comment]
The `ml_get_buf_len` function is returning the wrong value https://github.com/neovim/neovim/blob/05435a915a8446a8c2d824551fbea2dc1d7b5e98/src/nvim/api/buffer.c#L1426

The `bufstr` is `\ta` but the `bufstrlen` is 3 which (incorrectly) includes the null terminator. This is is because the 

The incorrect `buf->b_ml.ml_line_len` value is being set here: https://github.com/neovim/neovim/blob/05435a915a8446a8c2d824551fbea2dc1d7b5e98/src/nvim/memline.c#L1941

```
Hardware watchpoint 2: -location buf->b_ml.ml_line_len

Old value = 4
New value = 2
0x0000560d9197021a in ml_get_buf_impl (buf=0x560d931046b0, lnum=1, will_change=false) at /home/icholy/src/github.com/neovim/neovim/src/nvim/memline.c:1941
1941        buf->b_ml.ml_line_len = (colnr_T)(end - start);
(gdb) bt
#0  0x0000560d9197021a in ml_get_buf_impl (buf=0x560d931046b0, lnum=1, will_change=false) at /home/icholy/src/github.com/neovim/neovim/src/nvim/memline.c:1941
#1  0x0000560d9196feb3 in ml_get_buf (buf=0x560d931046b0, lnum=1) at /home/icholy/src/github.com/neovim/neovim/src/nvim/memline.c:1820
#2  0x0000560d919e3326 in plines_win_nofold (wp=0x560d931019d0, lnum=1) at /home/icholy/src/github.com/neovim/neovim/src/nvim/plines.c:768
#3  0x0000560d918d07cc in checkSmall (wp=0x560d931019d0, fp=0x560d931a3790, lnum_off=0) at /home/icholy/src/github.com/neovim/neovim/src/nvim/fold.c:1550
#4  0x0000560d918d072a in check_closed (wp=0x560d931019d0, fp=0x560d931a3790, use_levelp=0x7ffeb379af1e, level=0, maybe_smallp=0x7ffeb379af1d, lnum_off=0) at /home/icholy/src/github.com/neovim/neovim/src/nvim/fold.c:1524
#5  0x0000560d918cdc43 in hasFoldingWin (win=0x560d931019d0, lnum=1, firstp=0x7ffeb379af74, lastp=0x0, cache=false, infop=0x0) at /home/icholy/src/github.com/neovim/neovim/src/nvim/fold.c:226
#6  0x0000560d917e0a91 in changed_common (buf=0x560d931046b0, lnum=1, col=0, lnume=2, xtra=0) at /home/icholy/src/github.com/neovim/neovim/src/nvim/change.c:361
#7  0x0000560d917e0dce in changed_bytes (lnum=1, col=0) at /home/icholy/src/github.com/neovim/neovim/src/nvim/change.c:435
#8  0x0000560d917e0f23 in inserted_bytes (lnum=1, start_col=0, old_col=2, new_col=1) at /home/icholy/src/github.com/neovim/neovim/src/nvim/change.c:471
#9  0x0000560d918254f0 in ins_tab () at /home/icholy/src/github.com/neovim/neovim/src/nvim/edit.c:4433
#10 0x0000560d9181d7da in insert_handle_key (s=0x7ffeb379b490) at /home/icholy/src/github.com/neovim/neovim/src/nvim/edit.c:1036
#11 0x0000560d9181cc59 in insert_execute (state=0x7ffeb379b490, key=9) at /home/icholy/src/github.com/neovim/neovim/src/nvim/edit.c:697
#12 0x0000560d91a78e8e in state_enter (s=0x7ffeb379b490) at /home/icholy/src/github.com/neovim/neovim/src/nvim/state.c:101
#13 0x0000560d9181c153 in insert_enter (s=0x7ffeb379b490) at /home/icholy/src/github.com/neovim/neovim/src/nvim/edit.c:346
#14 0x0000560d9181de28 in edit (cmdchar=105, startln=false, count=1) at /home/icholy/src/github.com/neovim/neovim/src/nvim/edit.c:1296
#15 0x0000560d919a2bbe in invoke_edit (cap=0x7ffeb379b680, repl=0, cmd=105, startln=0) at /home/icholy/src/github.com/neovim/neovim/src/nvim/normal.c:6258
#16 0x0000560d919a2b12 in nv_edit (cap=0x7ffeb379b680) at /home/icholy/src/github.com/neovim/neovim/src/nvim/normal.c:6230
#17 0x0000560d919970eb in normal_execute (state=0x7ffeb379b610, key=105) at /home/icholy/src/github.com/neovim/neovim/src/nvim/normal.c:1230
#18 0x0000560d91a78e8e in state_enter (s=0x7ffeb379b610) at /home/icholy/src/github.com/neovim/neovim/src/nvim/state.c:101
#19 0x0000560d91995317 in normal_enter (cmdwin=false, noexmode=false) at /home/icholy/src/github.com/neovim/neovim/src/nvim/normal.c:519
#20 0x0000560d9193b2db in main (argc=6, argv=0x7ffeb379b9e8) at /home/icholy/src/github.com/neovim/neovim/src/nvim/main.c:665
```

It's being updated by the folding code. This checks out because `foldmethod=indent` is required to trigger this bug.

**Comment by zeertzjq** [comment]
This change seems to fix the problem:
```diff
vim.o.foldmethod = "indent"
vim.o.softtabstop = -1

vim.api.nvim_create_autocmd("BufEnter", {
    callback = function()
        vim.api.nvim_buf_attach(0, false, {
            on_lines = function (_, bufnr, _, firstline, _, new_lastline)
                local lines = vim.api.nvim_buf_get_lines(bufnr, firstline, new_lastline, true) 
                vim.print(lines)
            end
        })
    end
})
```

**Comment by zeertzjq** [comment]
This change seems to fix the problem:
```diff
diff --git a/src/nvim/edit.c b/src/nvim/edit.c
index 595b4da58..05ad0368f 100644
--- a/src/nvim/edit.c
+++ b/src/nvim/edit.c
@@ -4430,6 +4430,7 @@ static bool ins_tab(void)
         }
         if (!(State & VREPLACE_FLAG)) {
           curbuf->b_ml.ml_line_len -= i;
+          curbuf->b_ml.ml_flags |= ML_LINE_DIRTY;
           inserted_bytes(fpos.lnum, change_col,
                          cursor->col - change_col, fpos.col - change_col);
         }
```
