### ISSUE TITLE
Crashed when executing LazyCheck

### ISSUE THREAD

**Issue by japinli** [neovim/neovim#29112]
### Problem

```
$ nvim --version
NVIM v0.11.0-dev-139+ga18652ed6
Build type: RelWithDebInfo
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
$ uname -a
Linux dell-dev 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble
```
![nvim-lazyhealth-crash](https://github.com/neovim/neovim/assets/20606090/7b5b01ce-3702-4d09-bc03-5106bfdf7357)

### Steps to reproduce

```
git clone https://github.com/neovim/neovim.git
cd neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
git clone https://github.com/LazyVim/starter ~/.config/nvim
nvim
```

After installing, use `:LazyHealth` to check lazyvim, in the result of `LazyHealth`, if I try to execute `:LazyHealth` again, it will crash.

Here is the backtrace:

```
#0  frame2win (frp=frp@entry=0x0) at /home/japin/Tools/neovim/src/nvim/window.c:3473
3473	  while (frp->fr_win == NULL) {
[Current thread is 1 (Thread 0x71be5001fb80 (LWP 107943))]
(gdb) bt
#0  frame2win (frp=frp@entry=0x0) at /home/japin/Tools/neovim/src/nvim/window.c:3473
#1  0x00006376f34f03e6 in winframe_find_altwin (win=win@entry=0x6376f39e2c50, dirp=dirp@entry=0x7ffde51427ac, tp=tp@entry=0x6376f3a3f9f0, altfr=altfr@entry=0x7ffde5142730)
    at /home/japin/Tools/neovim/src/nvim/window.c:3219
#2  0x00006376f34f2165 in winframe_remove (win=win@entry=0x6376f39e2c50, dirp=0x7ffde51427ac, tp=tp@entry=0x6376f3a3f9f0, unflat_altfr=unflat_altfr@entry=0x0)
    at /home/japin/Tools/neovim/src/nvim/window.c:3156
#3  0x00006376f34f4d2b in win_free_mem (win=win@entry=0x6376f39e2c50, dirp=dirp@entry=0x7ffde51427ac, tp=tp@entry=0x6376f3a3f9f0) at /home/japin/Tools/neovim/src/nvim/window.c:3080
#4  0x00006376f34f4f89 in win_close_othertab (win=0x6376f39e2c50, free_buf=free_buf@entry=0, tp=0x6376f3a3f9f0) at /home/japin/Tools/neovim/src/nvim/window.c:3058
#5  0x00006376f34f8639 in close_windows (buf=0x6376f3ab6890, keep_curwin=false) at /home/japin/Tools/neovim/src/nvim/window.c:2515
#6  0x00006376f32b7254 in do_buffer (action=action@entry=4, start=start@entry=1, dir=dir@entry=1, count=<optimized out>, count@entry=20, forceit=forceit@entry=0)
    at /home/japin/Tools/neovim/src/nvim/buffer.c:1401
#7  0x00006376f32b7658 in do_bufdel (command=4, arg=<optimized out>, addr_count=1, start_bnr=<optimized out>, end_bnr=20, forceit=0)
    at /home/japin/Tools/neovim/src/nvim/buffer.c:1075
#8  0x00006376f334cc2c in ex_bunload (eap=0x7ffde5143050) at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:4467
#9  0x00006376f33440ad in execute_cmd0 (retv=retv@entry=0x7ffde5142974, eap=eap@entry=0x7ffde5143050, errormsg=errormsg@entry=0x7ffde5142978, preview=preview@entry=false)
    at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:1706
#10 0x00006376f3344714 in execute_cmd (eap=0x7ffde5143050, cmdinfo=<optimized out>, preview=<optimized out>) at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:1791
#11 0x00006376f3282688 in nvim_cmd (channel_id=9223372036854775809, cmd=<optimized out>, opts=0x7ffde51432e7, arena=0x7ffde5143300, err=0x7ffde51432f0)
    at /home/japin/Tools/neovim/src/nvim/api/command.c:646
#12 0x00006376f3399585 in nlua_api_nvim_cmd (lstate=0x71be4fde0380) at /home/japin/Tools/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.h:1780
#13 0x00006376f357e9e6 in lj_BC_FUNCC ()
#14 0x00006376f356aa09 in lua_pcall (L=L@entry=0x71be4fde0380, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=-4) at lj_api.c:1122
#15 0x00006376f33a90a6 in nlua_pcall (lstate=0x71be4fde0380, nargs=2, nresults=1) at /home/japin/Tools/neovim/src/nvim/lua/executor.c:173
#16 0x00006376f33b676e in nlua_exec (str=..., args=..., mode=kRetNilBool, arena=0x0, err=0x7ffde51435a0) at /home/japin/Tools/neovim/src/nvim/lua/executor.c:1559
#17 0x00006376f3352545 in ex_checkhealth (eap=0x7ffde5143ab0) at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:7491
#18 0x00006376f33440ad in execute_cmd0 (retv=retv@entry=0x7ffde5143aa4, eap=eap@entry=0x7ffde5143ab0, errormsg=errormsg@entry=0x7ffde5143aa8, preview=preview@entry=false)
    at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:1706
#19 0x00006376f3345862 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffde5143cf8, flags=flags@entry=7, cstack=cstack@entry=0x7ffde5143d80,
    fgetline=fgetline@entry=0x6376f346fa73 <get_str_line>, cookie=cookie@entry=0x7ffde5144430) at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:2375
#20 0x00006376f3346411 in do_cmdline (cmdline=<optimized out>, fgetline=0x6376f346fa73 <get_str_line>, cookie=0x7ffde5144430, flags=7)
    at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:665
#21 0x00006376f346fd00 in source_using_linegetter (cookie=cookie@entry=0x7ffde5144430, fgetline=fgetline@entry=0x6376f346fa73 <get_str_line>, traceback_name=<optimized out>)
    at /home/japin/Tools/neovim/src/nvim/runtime.c:1980
#22 0x00006376f346fd7a in do_source_str (cmd=<optimized out>, traceback_name=<optimized out>) at /home/japin/Tools/neovim/src/nvim/runtime.c:2030
#23 0x00006376f32a7dc0 in exec_impl (channel_id=9223372036854775809, src=..., opts=opts@entry=0x7ffde5144537, err=err@entry=0x7ffde5144540)
    at /home/japin/Tools/neovim/src/nvim/api/vimscript.c:89
#24 0x00006376f32a7ef7 in nvim_exec2 (channel_id=<optimized out>, src=..., opts=0x7ffde5144537, err=0x7ffde5144540) at /home/japin/Tools/neovim/src/nvim/api/vimscript.c:58
#25 0x00006376f33a656d in nlua_api_nvim_exec2 (lstate=0x71be4fde0380) at /home/japin/Tools/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.h:7375
#26 0x00006376f357e9e6 in lj_BC_FUNCC ()
#27 0x00006376f356aa09 in lua_pcall (L=L@entry=0x71be4fde0380, nargs=nargs@entry=1, nresults=nresults@entry=0, errfunc=errfunc@entry=-3) at lj_api.c:1122
#28 0x00006376f33a90a6 in nlua_pcall (lstate=0x71be4fde0380, nargs=1, nresults=0) at /home/japin/Tools/neovim/src/nvim/lua/executor.c:173
#29 0x00006376f33b8dae in nlua_do_ucmd (cmd=<optimized out>, eap=<optimized out>, preview=false) at /home/japin/Tools/neovim/src/nvim/lua/executor.c:2309
#30 0x00006376f34de78a in do_ucmd (eap=0x7ffde51448c0, preview=false) at /home/japin/Tools/neovim/src/nvim/usercmd.c:1642
#31 0x00006376f33441d5 in execute_cmd0 (retv=retv@entry=0x7ffde51448b4, eap=eap@entry=0x7ffde51448c0, errormsg=errormsg@entry=0x7ffde51448b8, preview=preview@entry=false)
    at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:1698
#32 0x00006376f3345862 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffde5144b08, flags=flags@entry=0, cstack=cstack@entry=0x7ffde5144b90,
    fgetline=fgetline@entry=0x6376f335a270 <getexline>, cookie=cookie@entry=0x0) at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:2375
#33 0x00006376f3346411 in do_cmdline (cmdline=<optimized out>, fgetline=0x6376f335a270 <getexline>, cookie=0x0, flags=0) at /home/japin/Tools/neovim/src/nvim/ex_docmd.c:665
#34 0x00006376f340216a in nv_colon (cap=0x7ffde51451b0) at /home/japin/Tools/neovim/src/nvim/normal.c:3181
#35 0x00006376f33fca37 in normal_execute (state=0x7ffde5145140, key=<optimized out>) at /home/japin/Tools/neovim/src/nvim/normal.c:1229
#36 0x00006376f34a2a82 in state_enter (s=0x7ffde5145140) at /home/japin/Tools/neovim/src/nvim/state.c:101
```

### Expected behavior

No crash.

### Neovim version (nvim -v)

NVIM v0.11.0-dev-139+ga18652ed6

### Vim (not Nvim) behaves the same?

Only test on nvim

### Operating system/version

Ubuntu 22.04

### Terminal name/version

GNOME Terminal/3.52.0

### $TERM environment variable

xterm-256color

### Installation

Compiled

**Comment by clason** [comment]
Sorry, but without a minimal reproducing example (and LazyVim is everything but minimal) we can't do anything here. Please report this to LazyVim first. If they can help you extract a minimal repro (without plugins), we can reopen this.
