### ISSUE TITLE
cmdexpand: nextwild: Assertion `ccline->cmdpos >= i` failed on completion inside cmdline

### ISSUE THREAD

**Issue by przepompownia** [neovim/neovim#29586]
### Problem

I get assertion failure (`src/nvim/cmdexpand.c:266: nextwild: Assertion 'ccline->cmdpos >= i' failed.`) trying to complete Lua expressions inside the cmdline:
```cpp
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007f025329eb6f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007f02532504e2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f02532394ed in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007f0253239415 in __assert_fail_base (fmt=0x7f02533afba8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x562764acd2e0 "ccline->cmdpos >= i",
    file=file@entry=0x562764ae6ba0 ".../src/nvim/cmdexpand.c", line=line@entry=266, function=function@entry=0x562764a88f58 <__PRETTY_FUNCTION__.9> "nextwild") at ./assert/assert.c:92
#5  0x00007f0253249002 in __assert_fail (assertion=assertion@entry=0x562764acd2e0 "ccline->cmdpos >= i", file=file@entry=0x562764ae6ba0 ".../src/nvim/cmdexpand.c", line=line@entry=266,
    function=function@entry=0x562764a88f58 <__PRETTY_FUNCTION__.9> "nextwild") at ./assert/assert.c:101
#6  0x000056276476153e in nextwild (xp=0x7ffcf049a1d8, type=3, options=8, escape=true) at .../src/nvim/cmdexpand.c:266
#7  0x00005627647ed2e6 in command_line_wildchar_complete (s=s@entry=0x7ffcf049a100) at .../src/nvim/ex_getln.c:1099
#8  0x00005627647eef7a in command_line_execute (state=0x7ffcf049a100, key=<optimized out>) at .../src/nvim/ex_getln.c:1367
#9  0x000056276492e962 in state_enter (s=0x7ffcf049a100) at .../src/nvim/state.c:101
#10 0x00005627647ec9a0 in command_line_enter (firstc=firstc@entry=58, count=count@entry=1, indent=indent@entry=0, clear_ccline=clear_ccline@entry=true) at .../src/nvim/ex_getln.c:851
#11 0x00005627647ece07 in getcmdline (firstc=firstc@entry=58, count=count@entry=1, indent=indent@entry=0, do_concat=do_concat@entry=true) at .../src/nvim/ex_getln.c:2739
#12 0x00005627647ece35 in getexline (c=58, cookie=<optimized out>, indent=0, do_concat=true) at .../src/nvim/ex_getln.c:2982
#13 0x00005627647d9a97 in do_cmdline (cmdline=<optimized out>, fgetline=0x5627647ece0c <getexline>, cookie=0x0, flags=0) at .../src/nvim/ex_docmd.c:579
#14 0x000056276488f4e5 in nv_colon (cap=0x7ffcf049aac0) at .../src/nvim/normal.c:3182
#15 0x000056276488d4b9 in normal_execute (state=0x7ffcf049aa50, key=<optimized out>) at .../src/nvim/normal.c:1230
#16 0x000056276492e962 in state_enter (s=0x7ffcf049aa50) at .../src/nvim/state.c:101
#17 0x000056276488a603 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at .../src/nvim/normal.c:519
#18 0x0000562764850968 in main (argc=3, argv=<optimized out>) at .../src/nvim/main.c:664
```

### Steps to reproduce

- `nvim --clean`
- `:lua ; 1`
- jump before the semicolon, type `fun` and press `<Tab>`

### Expected behavior

No crash

### Neovim version (nvim -v)

v0.11.0-dev-353+g34fa54355

### Vim (not Nvim) behaves the same?

no, 9.1.496

### Operating system/version

Debian Sid

### Terminal name/version

alcritty 0.14.0-dev (da554e41)

### $TERM environment variable

alacritty

### Installation

from repo

**Comment by przepompownia** [comment]
Thank you @zeertzjq
