### ISSUE TITLE
SIGSEGV on malformed OSC8 sequence

### ISSUE THREAD

**Issue by glacambre** [neovim/neovim#30084]
### Problem

Neovim segfaults when parsing malformed OSC8 sequences. Stack trace:
```
#0  __memcpy_avx512_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:832
#1  0x000056498c310bee in on_osc (command=8, frag={str = 0x5649cbcd757f "", len = 1073741823, initial = false, final = false}, user=0x5649cbd10710) at /home/me/prog/neovim/src/nvim/terminal.c:296
#2  0x000056498c3933c5 in on_osc (command=8, frag={str = 0x5649cbcd757f "", len = 1073741823, initial = false, final = false}, user=0x5649cbce0180) at /home/me/prog/neovim/src/vterm/state.c:1803
#3  0x000056498c387820 in string_fragment (vt=0x5649cbd0e7f0, str=0x5649cbcd757f "", len=18446744073709551615, final=false) at /home/me/prog/neovim/src/vterm/parser.c:76
#4  0x000056498c38839e in vterm_input_write (vt=0x5649cbd0e7f0, bytes=0x5649cbcd7550 "\033]8;;http://example.com\033\\This is a link\033]8;;\033\r\n", len=47) at /home/me/prog/neovim/src/vterm/parser.c:382
#5  0x000056498c312db3 in terminal_receive (term=0x5649cbd10710, data=0x5649cbcd7550 "\033]8;;http://example.com\033\\This is a link\033]8;;\033\r\n", len=47) at /home/me/prog/neovim/src/nvim/terminal.c:966
#6  0x000056498c05e110 in on_channel_output (stream=0x5649cbd0d340, chan=0x5649cbd0d160, buf=0x5649cbcd7550 "\033]8;;http://example.com\033\\This is a link\033]8;;\033\r\n", count=47, eof=false, 
    reader=0x5649cbd0d840) at /home/me/prog/neovim/src/nvim/channel.c:680
#7  0x000056498c05dff5 in on_channel_data (stream=0x5649cbd0d340, buf=0x5649cbcd7550 "\033]8;;http://example.com\033\\This is a link\033]8;;\033\r\n", count=47, data=0x5649cbd0d160, eof=false)
    at /home/me/prog/neovim/src/nvim/channel.c:652
#8  0x000056498c0ff52b in read_event (argv=0x7fff010243a0) at /home/me/prog/neovim/src/nvim/event/rstream.c:181
#9  0x000056498c0ff8c2 in invoke_read_cb (stream=0x5649cbd0d340, eof=false) at /home/me/prog/neovim/src/nvim/event/rstream.c:233
#10 0x000056498c0ff2f4 in read_cb (uvstream=0x5649cbd0d348, cnt=47, buf=0x7fff01024490) at /home/me/prog/neovim/src/nvim/event/rstream.c:136
#11 0x000056498c46ba1a in uv.read ()
#12 0x000056498c46c210 in uv.stream_io ()
#13 0x000056498c472ea1 in uv.io_poll ()
#14 0x000056498c46185f in uv_run ()
#15 0x000056498c0fc228 in loop_uv_run (loop=0x56498c6157c0 <main_loop>, ms=0) at /home/me/prog/neovim/src/nvim/event/loop.c:61
#16 0x000056498c0fc284 in loop_poll_events (loop=0x56498c6157c0 <main_loop>, ms=0) at /home/me/prog/neovim/src/nvim/event/loop.c:82
#17 0x000056498c24b93a in os_breakcheck () at /home/me/prog/neovim/src/nvim/os/input.c:199
#18 0x000056498c14fd1f in vgetorpeek (advance=false) at /home/me/prog/neovim/src/nvim/getchar.c:2552
#19 0x000056498c14e3f7 in vpeekc () at /home/me/prog/neovim/src/nvim/getchar.c:1815
#20 0x000056498c2eba0e in state_enter (s=0x7fff01028770) at /home/me/prog/neovim/src/nvim/state.c:61
#21 0x000056498c20c667 in normal_enter (cmdwin=false, noexmode=false) at /home/me/prog/neovim/src/nvim/normal.c:520
#22 0x000056498c1b1228 in main (argc=5, argv=0x7fff01028b58) at /home/me/prog/neovim/src/nvim/main.c:661
```

### Steps to reproduce

```
nvim --clean --cmd 'term printf "\033]8;;http://example.com\033\\This is a link\033]8;;\033\n"'
```

### Expected behavior

No crash.

### Neovim version (nvim -v)

current master ( 33464189bc02b2555e26dc4e9f7b3fbbcdd02490 )

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux

### Terminal name/version

Kitty

### $TERM environment variable

xterm-256-color

### Installation

AppImage & built from source

**Comment by glacambre** [comment]
D'oh, actually, looking at the stack trace, the problem seems to be in libvterm itself... I guess the bug reports should go to libvterm's bug tracker then? :grimacing:

**Comment by clason** [comment]
>  I guess the bug reports should go to libvterm's bug tracker then? 

Oh, you sweet summer child... (If you can find it, go ahead!)

Joking aside, we have vendored vterm in order to support OSC8, so this is in fact a Neovim issue.
