### ISSUE TITLE
Crashes when trying to load Python host

### ISSUE THREAD

**Issue by Jackevansevo** [neovim/neovim#3016]
I'm trying to run Ultisnips https://github.com/SirVer/ultisnips but I get errors as soon as a load my nvimrc

```
call plug#begin('~/.nvim/plugged')

Plug 'SirVer/ultisnips'

call plug#end()
```

Running the latest version of Neovim in OpenSuse 13.2 (fresh install), similar issues have been reported in the past but none of the solutions are currently working for me

I have tried the following:

1. Removed Neovim and reinstalled, issue still persists

2. Check the results of  :echo has('python') and :echo has('python3') both return 1 successfully

3. Ran pip uninstall neovim and reinstalled for python python2 and python3. Pip freeze tells me I have the pip module: neovim==0.0.36 installed

Following the instructions on the troubleshooting page 

- running

    :let [interp, errors] = provider#pythonx#Detect(2) 
- followed by

    :echo interp
- results in 'python2' being echoed
- then running

     :echo errors
- show a blank result

Error looks like the following when I open a file with neovim
```
"nvimrc" 5L, 77C
Vim(if):Channel was closed by the client
Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
Error detected while processing function provider#python3#Call:
line   15:
E168: :finish used outside of a sourced file
Error detected while processing FileType Auto commands for "*":
E117: Unknown function: UltiSnips#FileTypeChanged
```

Looking at .nvimlog I get the following after the error occurs

```
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/neovim/__init__.py", line 65, in start_host
    host = Host(Nvim.from_session(session))
  File "/usr/lib/python3.4/site-packages/neovim/plug
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: in/host.py", line 39, in __init__
    self._nvim_encoding = nvim.options['encoding']
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 43, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.4/site-packages/neovim/api/comm
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: on.py", line 258, in <lambda>
    return lambda *args: session.request(method, *args)
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 223, in request
    return walk(self._in, self._session.request(name, *args), self, name,
  File "/u
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: sr/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 74, in request
    v = self._blocking_request(method, args)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 146, in _blocking_request
    self._async_session
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: .request(method, args, response_cb)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/async_session.py", line 44, in request
    self._msgpack_stream.send([0, request_id, method, args])
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: /msgpack_stream.py", line 37, in send
    self._event_loop.send(self._packer.pack(msg))
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 734, in pack
    self._pack(obj)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py",
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr:  line 722, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 676, in _pack
    obj = obj.encode(self._encoding, self._unicode_errors)
TypeError: encode() argument 1 must be str, not bytes
2015/07/15 14:15:55 [error @ job_err:344] 29389 - Channel 1 stderr: 

2015/07/15 14:15:55 [error @ call_set_error:740] 29389 - msgpack-rpc: Channel was closed by the client
2015/07/15 14:15:55 [info @ main_loop:514] 29389 - Starting Neovim main loop.

```

**Comment by justinmk** [comment]
see https://github.com/neovim/neovim/issues/3000

may be fixed by https://github.com/neovim/neovim/pull/3010

**Comment by tarruda** [comment]
@Jackevansevo can you see if #3309 fixes the problem?

**Comment by Jackevansevo** [comment]
Using a newer build (compiled Sep  9 2015 20:09:50)                                                                                                                                                                                                                                I no longer seem to have the same issue. Nobody else seems to have reported the same issues, so I'd guess the problem was solved. Apologies for not coming back and reporting my finding / being unable to diagnose the source of the problem. (close this issue?)

**Comment by tarruda** [comment]
@Jackevansevo feel free to reopen if you see it again
