### ISSUE TITLE
Fails to run neo-vim : permission denied

### ISSUE THREAD

**Issue by alexDarcy** [neovim/neovim#3019]
**Update** : I'm trying to use YouCompleteMe.

I have a "permission denied" whene I try to run neovim (the version installed with pip). Steps to reproduce : 

1)  pip2 install --user neovim
2) Try to run neovim but it failed with 

    $ ~/.local/bin/pynvim
    Traceback (most recent call last):
      File "/home/alex/.local/bin/pynvim", line 9, in <module>
        load_entry_point('neovim==0.0.36', 'console_scripts', 'pynvim')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 552, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2344, in load
        self.require(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in require
        items = working_set.resolve(reqs, env, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 833, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'click>=3.0' distribution was not found and is required by the application

3) Install click with apt-get install python-click
4) Try to run 

    $ ~/.local/bin/pynvim
    Traceback (most recent call last):
      File "/home/alex/.local/bin/pynvim", line 9, in <module>
        load_entry_point('neovim==0.0.36', 'console_scripts', 'pynvim')()
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 590, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "/home/alex/.local/lib/python2.7/site-packages/neovim/ui/cli.py", line 59, in main
        nvim = attach('child', argv=nvim_argv)
      File "/home/alex/.local/lib/python2.7/site-packages/neovim/__init__.py", line 89, in attach
        child_session(argv) if session_type == 'child' else
      File "/home/alex/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/__init__.py", line 41, in child_session
        return session('child', argv)
      File "/home/alex/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/__init__.py", line 17, in session
        loop = EventLoop(transport_type, *args, **kwargs)
      File "/home/alex/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
        getattr(self, '_connect_{0}'.format(transport_type))(*args)
      File "/home/alex/.local/lib/python2.7/site-packages/neovim/msgpack_rpc/event_loop/asyncio.py", line 94, in _connect_child
        self._loop.run_until_complete(coroutine)
      File "/home/alex/.local/lib/python2.7/site-packages/trollius/base_events.py", line 350, in run_until_complete
        return future.result()
      File "/home/alex/.local/lib/python2.7/site-packages/trollius/futures.py", line 286, in result
        raise self._exception
    OSError: [Errno 13] Permission denied

My OS is Debian Testing.

**Comment by fwalch** [comment]
Running `nvim` works?

**Comment by alexDarcy** [comment]
Ho... yes, it does. However, YouCompleteMe does not seem to work. Do you have any pointer ?

**Comment by alexDarcy** [comment]
Okay, I've found https://github.com/neovim/neovim/tree/master/contrib/YouCompleteMe and it is working now :)
I would like to add a link to that in the documentation. Do you know if it is a good idea and if it is, where I could document it ?

**Comment by justinmk** [comment]
It's in the wiki: https://github.com/neovim/neovim/wiki/Development-tips#navigating-the-code
