### ISSUE TITLE
nvim does not throw IndexError when out of line in vim.current.buffer. #128

### ISSUE THREAD

**Issue by SirVer** [neovim/neovim#3044]
Reopened from https://github.com/neovim/python-client/issues/128 as requested.

The line to test is `:py import vim; vim.current.buffer[100000]`. In regular vim you'll get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: line number out of range
```

In nvim no error is thrown. 

This was surfaced through [this UltiSnips test](https://github.com/SirVer/ultisnips/blob/master/test/test_ContextSnippets.py#L118) which is the last one failing with neovim in my current test branch, which is nice. 

On another note: I found out the hard way that nvim sets a bunch of options differently on startup (for example `smarttab`, `autoindent` and `backspace`) when started using `-u NONE` than vim. Is that intentional?

**Comment by mhinz** [comment]
For the latter see `:h nvim-option-defaults`.

**Comment by fmoralesc** [comment]
@SirVer Yes, the defaults changes are intentional. The complete list of implemented and proposed changes is being tracked at #2676 .

**Comment by justinmk** [comment]
Fixed (with a nicer traceback).

```
:py3 import vim; vim.current.buffer[100000]

Error detected while processing function provider#python3#Call:                                                              
line   18:                                                                                                                   
Traceback (most recent call last):                                                                                           
  File "<string>", line 1, in <module>                                                                                       
  File "/usr/local/lib/python3.4/dist-packages/neovim/api/buffer.py", line 34, in __getitem__                                
    return self._session.request('buffer_get_line', self, idx)                                                               
  File "/usr/local/lib/python3.4/dist-packages/neovim/api/nvim.py", line 129, in request                                     
    res = self._session.request(name, *args, **kwargs)                                                                       
  File "/usr/local/lib/python3.4/dist-packages/neovim/msgpack_rpc/session.py", line 98, in request                           
    raise self.error_wrapper(err)                                                                                            
neovim.api.nvim.NvimError: b'Index out of bounds'
```
