### ISSUE TITLE
Output more than 50 lines in `vim.schedule_wrap` when exiting Neovim, stuck.

### ISSUE THREAD

**Issue by petricavalry** [neovim/neovim#30502]
### Problem

Running `:wq` with following Lua code:

```lua
-- string with 51 lines
local result = ""
for _ = 0, 50 do
   result = result .. "\n"
end

-- output `result` just generated after file saved
vim.api.nvim_create_autocmd("BufWritePost", {
    callback = function()
        vim.system({ "ls" }, vim.schedule_wrap(function(obj)
            vim.notify(result)
            -- `vim.print` and `print` also get stuck
        end))
    end,
})
```

Neovim will getting stuck (can't do anything, expect `pkill nvim`).

Thanks for all the amazing work in Neovim.

### Steps to reproduce

Put these codes into `~/.config/nvim/init.lua`.

```lua
local result = ""
for _ = 0, 50 do
   result = result .. "\n"
end

-- output `result` just generated after file saved
vim.api.nvim_create_autocmd("BufWritePost", {
    callback = function()
        vim.system({ "ls" }, vim.schedule_wrap(function(obj)
            vim.notify(result)
            -- `vim.print` and `print` also get stuck
        end))
    end,
})
```

Then execute `:wq`.

I can't reproduce it **with** `nvim --clean -u minimal.lua` in Arch Linux (Neovim 0.10.1), but successfully reproduced it by put codes into `~/.config/nvim/init.lua`.

But I successfully reproduced it in Alpine (Neovim 0.10.0, running in Docker).

### Expected behavior

Neovim should exit after running `:wq`.

### Nvim version (nvim -v)

0.10.0

### Vim (not Nvim) behaves the same?

No, Vim 9.1

### Operating system/version

Alpine 3.20.3

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

Alpine Package Keeper (APK)

**Comment by wookayin** [comment]
Cannot reproduce in my linux machines. Does the number 50 have something to do with your terminal size?

**Comment by petricavalry** [comment]
Thanks for your help. The number 50 is not related to my terminal size.

Here is the backtrace I got by attaching to stuck Neovim processing (`gdb -p <PID>`).

```
#0  0x00007ce4cb5996fd in epoll_pwait () from /usr/lib/libc.so.6
#1  0x000058f1ee837170 in uv__io_poll (loop=0x58f1ee9e2720 <main_loop>, timeout=2000)
    at /home/atlanticappraisal/neovim/.deps/build/src/libuv/src/unix/linux.c:1449
#2  0x000058f1ee81a2da in uv_run (loop=0x58f1ee9e2720 <main_loop>, mode=UV_RUN_ONCE)
    at /home/atlanticappraisal/neovim/.deps/build/src/libuv/src/unix/core.c:458
#3  0x000058f1ee4aaa01 in loop_uv_run (loop=0x58f1ee9e2720 <main_loop>, ms=-1)
    at /home/atlanticappraisal/neovim/src/nvim/event/loop.c:61
#4  0x000058f1ee4aaa5d in loop_poll_events (loop=0x58f1ee9e2720 <main_loop>, ms=-1)
    at /home/atlanticappraisal/neovim/src/nvim/event/loop.c:82
#5  0x000058f1ee5fb7fa in inbuf_poll (ms=-1, events=0x58f218dad600) at /home/atlanticappraisal/neovim/src/nvim/os/input.c:497
#6  0x000058f1ee5fad99 in input_get (buf=0x58f218dd4ba0 "\204)\372\227\367X", maxlen=48, ms=-1, tb_change_cnt=0, events=0x58f218dad600)
    at /home/atlanticappraisal/neovim/src/nvim/os/input.c:155
#7  0x000058f1ee51d81f in get_keystroke (events=0x58f218dad600) at /home/atlanticappraisal/neovim/src/nvim/input.c:114
#8  0x000058f1ee5a71b3 in do_more_prompt (typed_char=0) at /home/atlanticappraisal/neovim/src/nvim/message.c:2755
#9  0x000058f1ee5a600c in msg_puts_display (str=0x7fff0a993c21 "\n", maxlen=-1, attr=0, recurse=0)
    at /home/atlanticappraisal/neovim/src/nvim/message.c:2218
#10 0x000058f1ee5a5a55 in msg_puts_len (str=0x7fff0a993c21 "\n", len=-1, attr=0)
    at /home/atlanticappraisal/neovim/src/nvim/message.c:2098
#11 0x000058f1ee5a58a5 in msg_puts_attr (s=0x7fff0a993c21 "\n", attr=0) at /home/atlanticappraisal/neovim/src/nvim/message.c:2038
#12 0x000058f1ee5a4540 in msg_putchar_attr (c=10, attr=0) at /home/atlanticappraisal/neovim/src/nvim/message.c:1498
#13 0x000058f1ee5a107c in msg_multiline (s=0x58f218e4273f '\n' <repeats 20 times>, attr=0, check_int=true, need_clear=0x7fff0a993c9b)
    at /home/atlanticappraisal/neovim/src/nvim/message.c:270
#14 0x000058f1ee5a114f in msg_multiattr (hl_msg=..., kind=0x58f1ee853a71 "echomsg", history=true)
    at /home/atlanticappraisal/neovim/src/nvim/message.c:291
#15 0x000058f1ee3dd7da in nvim_echo (chunks=..., history=true, opts=0x7fff0a993d76, err=0x7fff0a993d80)
    at /home/atlanticappraisal/neovim/src/nvim/api/vim.c:799
#16 0x000058f1ee53b741 in nlua_api_nvim_echo (lstate=0x7ce4cb2ba380)
    at /home/atlanticappraisal/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.h:5313
#17 0x000058f1ee7c8626 in lj_BC_FUNCC ()
#18 0x000058f1ee7b3edd in lua_pcall (L=0x7ce4cb2ba380, nargs=<optimized out>, nresults=0, errfunc=<optimized out>) at lj_api.c:1122
#19 0x000058f1ee54fe78 in nlua_pcall (lstate=0x7ce4cb2ba380, nargs=0, nresults=0)
    at /home/atlanticappraisal/neovim/src/nvim/lua/executor.c:174
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x000058f1ee550802 in nlua_schedule_event (argv=0x7fff0a993f08) at /home/atlanticappraisal/neovim/src/nvim/lua/executor.c:372
#21 0x000058f1ee4ab652 in multiqueue_process_events (self=0x58f218dad520)
    at /home/atlanticappraisal/neovim/src/nvim/event/multiqueue.c:149
#22 0x000058f1ee4ac608 in proc_teardown (loop=0x58f1ee9e2720 <main_loop>) at /home/atlanticappraisal/neovim/src/nvim/event/proc.c:144
#23 0x000058f1ee55f4bf in event_teardown () at /home/atlanticappraisal/neovim/src/nvim/main.c:177
#24 0x000058f1ee56052a in os_exit (r=0) at /home/atlanticappraisal/neovim/src/nvim/main.c:684
#25 0x000058f1ee560929 in getout (exitval=0) at /home/atlanticappraisal/neovim/src/nvim/main.c:821
#26 0x000058f1ee4c881b in ex_quit (eap=0x7fff0a9941f0) at /home/atlanticappraisal/neovim/src/nvim/ex_docmd.c:4772
#27 0x000058f1ee4c08d3 in execute_cmd0 (retv=0x7fff0a9941a8, eap=0x7fff0a9941f0, errormsg=0x7fff0a9941c0, preview=false)
    at /home/atlanticappraisal/neovim/src/nvim/ex_docmd.c:1714
#28 0x000058f1ee4c277c in do_one_cmd (cmdlinep=0x7fff0a994410, flags=0, cstack=0x7fff0a994520, fgetline=0x58f1ee4dacce <getexline>,
    cookie=0x0) at /home/atlanticappraisal/neovim/src/nvim/ex_docmd.c:2358
#29 0x000058f1ee4be2c8 in do_cmdline (cmdline=0x0, fgetline=0x58f1ee4dacce <getexline>, cookie=0x0, flags=0)
    at /home/atlanticappraisal/neovim/src/nvim/ex_docmd.c:667
#30 0x000058f1ee5c1f4c in nv_colon (cap=0x7fff0a994b90) at /home/atlanticappraisal/neovim/src/nvim/normal.c:3177
#31 0x000058f1ee5bdae3 in normal_execute (state=0x7fff0a994b20, key=58) at /home/atlanticappraisal/neovim/src/nvim/normal.c:1235
#32 0x000058f1ee69b1a7 in state_enter (s=0x7fff0a994b20) at /home/atlanticappraisal/neovim/src/nvim/state.c:102
#33 0x000058f1ee5bbd37 in normal_enter (cmdwin=false, noexmode=false) at /home/atlanticappraisal/neovim/src/nvim/normal.c:521
#34 0x000058f1ee5604be in main (argc=2, argv=0x7fff0a994f18) at /home/atlanticappraisal/neovim/src/nvim/main.c:660
```
