### ISSUE TITLE
segfault on specific bytes since utf8proc casefolding

### ISSUE THREAD

**Issue by ibuki2003** [neovim/neovim#30527]
### Problem

reading or pasting specific bytes, nvim crashes.

running bisect on `bcb17689d..64847fbdc` results 328ea02eb7dec32286ae6c691ecef71d988c905b `is the first bad commit`

### Steps to reproduce

1.create init.lua
```lua
vim.opt.rtp:append("/path/to/ccc.nvim") -- github.com/uga-rosa/ccc.nvim ref: 790aa88
-- NOTE: causal code must be in the plugin but I couldn't find that. sorry

local ccc = require("ccc")
ccc.setup({
    highlighter = {
        auto_enable = true,
    },
})
vim.opt.ignorecase = true
```

2.create a.bin
```
% xxd a.bin
00000000: a314 92f9 edb7 bb2f 5ebc                 ......./^.
```

3.open the file
```
$ nvim
:e ++enc=utf-8 a.bin
```

4.nvim crashes

### Expected behavior

nvim should not crash

### Nvim version (nvim -v)

v0.11.0-dev-836+g64847fbdc

### Vim (not Nvim) behaves the same?

no (the plugin does not work on Vim)

### Operating system/version

ArchLinux 6.10.10-arch1-1

### Terminal name/version

Alacritty 0.13.2

### $TERM environment variable

alacritty

### Installation

build from repo

**Comment by zeertzjq** [comment]
Backtrace:
```
**/src/nvim/mbyte.c:1389:41: runtime error: null pointer passed as argument 1, which is declared to never be null
**/build/include/mbyte.h.generated.h:23:96: note: nonnull attribute specified here
    #0 0x5f318badd07d in utf_fold **/src/nvim/mbyte.c:1389:28
    #1 0x5f318bf8df69 in nfa_regmatch **/src/nvim/regexp.c:15246:35
    #2 0x5f318bf733af in nfa_regtry **/src/nvim/regexp.c:15536:16
    #3 0x5f318bf70533 in nfa_regexec_both **/src/nvim/regexp.c:15721:12
    #4 0x5f318beefd4e in nfa_regexec_nl **/src/nvim/regexp.c:15885:10
    #5 0x5f318bee8396 in vim_regexec_string **/src/nvim/regexp.c:16111:16
    #6 0x5f318bee930f in vim_regexec_nl **/src/nvim/regexp.c:16165:10
    #7 0x5f318b4b637f in find_some_match **/src/nvim/eval/funcs.c:4532:15
    #8 0x5f318b48f03d in f_matchlist **/src/nvim/eval/funcs.c:4784:3
    #9 0x5f318b4446db in call_internal_func **/src/nvim/eval/funcs.c:285:3
    #10 0x5f318b52bfa6 in call_func **/src/nvim/eval/userfunc.c:1745:15
    #11 0x5f318b957f1e in nlua_call **/src/nvim/lua/executor.c:1208:3
    #12 0x5f318c7a8015 in lj_BC_FUNCC (**/build/bin/nvim+0x268f015) (BuildId: 3cb276404987243fc03d80c23e8e56e09ba64b6f)
    #13 0x5f318c791ef9 in lua_pcall **/.deps/build/src/luajit/src/lj_api.c:1151:12
    #14 0x5f318b953f85 in nlua_pcall **/src/nvim/lua/executor.c:174:16
    #15 0x5f318b95bb92 in nlua_call_ref **/src/nvim/lua/executor.c:1608:7
    #16 0x5f318b0bd659 in call_autocmd_callback **/src/nvim/autocmd.c:2057:21
    #17 0x5f318b0bb891 in getnextac **/src/nvim/autocmd.c:2108:9
    #18 0x5f318b61243a in do_cmdline **/src/nvim/ex_docmd.c:580:30
    #19 0x5f318b0b00a0 in apply_autocmds_group **/src/nvim/autocmd.c:1842:5
    #20 0x5f318b0b840a in apply_autocmds_retval **/src/nvim/autocmd.c:1539:18
    #21 0x5f318b0c9fa6 in open_buffer **/src/nvim/buffer.c:382:3
    #22 0x5f318b5dcf88 in do_ecmd **/src/nvim/ex_cmds.c:2568:24
    #23 0x5f318b65e2ee in do_exedit **/src/nvim/ex_docmd.c:5509:9
    #24 0x5f318b666cee in ex_edit **/src/nvim/ex_docmd.c:5441:3
    #25 0x5f318b6423bf in execute_cmd0 **/src/nvim/ex_docmd.c:1714:7
    #26 0x5f318b61f17e in do_one_cmd **/src/nvim/ex_docmd.c:2358:7
    #27 0x5f318b613205 in do_cmdline **/src/nvim/ex_docmd.c:667:20
    #28 0x5f318bc68f17 in nv_colon **/src/nvim/normal.c:3177:18
    #29 0x5f318bc549c5 in normal_execute **/src/nvim/normal.c:1235:3
    #30 0x5f318c1e6c9a in state_enter **/src/nvim/state.c:100:26
    #31 0x5f318bc3536f in normal_enter **/src/nvim/normal.c:521:3
    #32 0x5f318b9857a7 in main **/src/nvim/main.c:660:3
    #33 0x76e998332e07 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #34 0x76e998332ecb in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #35 0x5f318ad58d24 in _start (**/build/bin/nvim+0xc3fd24) (BuildId: 3cb276404987243fc03d80c23e8e56e09ba64b6f)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/mbyte.c:1389:41 
```
