### ISSUE TITLE
termopen() invoked with "nvim -u" stores wrong 'channel'

### ISSUE THREAD

**Issue by arizvisa** [neovim/neovim#30765]
### Problem

Using the python provider during initialization, I appear to be encountering an issue with the `jobpid()` function returning the "wrong" pid for a terminal started with `termopen()`. I get that this doesn't make sense. The way I'm identifying it's the wrong pid is by examining the name of the buffer created by `termopen()`.

I've currently only tested it in a non-development environment, and I believe my distro's package manager is a version behind. I'll follow-up in a bit with a test against the most recent commit. I've also attached the output of the current version along with the results of `:checkhealth`.

[versioninfo-checkhealth.txt](https://github.com/user-attachments/files/17346093/versioninfo-checkhealth.txt)

### Steps to reproduce

Place the following script inside a file:

```
pythonx cwd = vim.eval("fnamemodify({!r}, ':~')".format(__import__('os').getcwd()))
pythonx print('work', [cwd])
pythonx cmd = '/usr/bin/python -i'
pythonx job = vim.eval("termopen({!r}, {{}})".format(cmd))
pythonx print('got', [job])
pythonx pid = vim.eval("jobpid({!s})".format(job))
pythonx print('pid', [pid])
echomsg ' '
pythonx print('expected-buffer-name', ["term://{cwd}//{pid}:{command}".format(cwd=cwd, pid=pid, command=cmd)])
echomsg ' '
echomsg 'buffer-list:'
ls!
echomsg ' '
if has('linux')
    echomsg 'process-tree:'
    let out = system('pgrep nvim | xargs -n1 -t pstree -cagplt')
    for line in split(out, "\n") | echomsg "    ".line | endfor
    echomsg ' '
endif
call input('Press <RETURN> to exit editor...')
exit
```

Run it with `nvim --clean -u whatever.vim` it should emit the current working directory, use `termopen()` to open up another terminal, output its pid, and then list the currently available buffers. The extra crap is just for emitting the process tree. Specifically in its output, the pid being returned is different from the one in the buffer name being emitted by `:ls!`.

In my environment, the output looks like:
```
work ['~/work/vim-incpy']
got ['4']
pid ['2280138']

expected-buffer-name ['term://~/work/vim-incpy//2280138:/bin/sh -i']

buffer-list:
  1 %aR  "term://~/work/vim-incpy//2280139:/bin/sh -i" line 1

...

                                                                                                                                                                                    
Press <RETURN> to exit editor...                                                                                                                                                    
```

In this output, the pid returned by `jobpid()` is 2280138, whereas the buffer name suggests 2280139.

### Expected behavior

I was expecting the pid used for the terminal buffer name to be the same as returned by `jobpid()`. However, it appears to be different.

### Nvim version (nvim -v)

0.10.1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora Linux 40

### Terminal name/version

console

### $TERM environment variable

screen-256color

### Installation

system package manager

**Comment by arizvisa** [comment]
Testing against the following version (based on commit 8b98642002d0506d20628683958cb5c97a0dad80), and inside an isolated environment based on ubuntu.
```
# cat /etc/*version /etc/*release
bookworm/sid
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

# nvim -V1 -v
NVIM v0.10.2
Build type: Debug
LuaJIT 2.1.1713484068
Compilation: /usr/bin/cc -g  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fsigned-char -fstack-protector-strong -Wno-conversion -fno-common -Wimplicit-fallthrough -fdiagnostics-color=auto  -DNVIM_LOG_DEBUG -DUNIT_TESTING -DHAVE_UNIBILIUM -D_GNU_SOURCE -DINCLUDE_GENERATED_DECLARATIONS -I/root/neo/.deps/usr/include/luajit-2.1 -I/root/neo/.deps/usr/include -I/root/neo/build/src/nvim/auto -I/root/neo/build/include -I/root/neo/build/cmake.config -I/root/neo/src -I/usr/include 

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Full output of version information and `:checkhealth`: [versioninfo-checkhealth2.txt](https://github.com/user-attachments/files/17346152/versioninfo-checkhealth2.txt)

Running `nvim --clean -u /path/to/vimscript/` yields the following output:
```
work ['~/neo']
got ['4']
Error detected while processing /root/neo/whygod.vim[6]..function provider#python3#Call:
line    1:
E5108: Error executing lua Vim:Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pynvim/plugin/script_host.py", line 210, in eval
    obj = self.request("vim_eval", expr)
  File "/usr/local/lib/python3.10/dist-packages/pynvim/api/nvim.py", line 199, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pynvim/msgpack_rpc/session.py", line 139, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E900: Invalid channel id
stack traceback:
        [C]: at 0x557de60c0616
E5108: Error executing lua Vim:Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pid' is not defined
stack traceback:
        [C]: at 0x557de60c0616

E5108: Error executing lua Vim:Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'pid' is not defined
stack traceback:
        [C]: at 0x557de60c0616

buffer-list:
  1 %aF  "term://~/neo//12168:/usr/bin/python -i" line 1
```

Strangely enough, the `termopen()` function is returning a job id (`4`), but usage of that id with `jobpid()` throws an E900 error. However, performing the same sequence commands outside of initialization results in everything working as one would expect. So it might appear that the python provider (which I'm not too familiar with) and the job api are conflicting somehow during initialization...

**Comment by zeertzjq** [comment]
Cannot reproduce on Arch Linux with Nvim v0.10.2 or v0.11.0-dev-946+g25665b365c

**Comment by justinmk** [comment]
There is a lot of irrelevant details here. IIUC, the central question is reproducible with this one-line `nvim -u test.vim` script:

    pythonx print(vim.eval("termopen('sh', {})"))

That prints "4" (confirm via `:messages`), but then `:echo &channel` prints "5".

Invoking with `nvim -u` seems to be required to reproduce the issue. It's *not* reproducible when running `:pythonx` interactively, nor with `nvim -c`:

    nvim --clean -c "pythonx print(vim.eval(\"termopen('sh', {})\"))"

**Comment by arizvisa** [comment]
Using the official archlinux container that they're hosting on docker hub for reproduceability.

```
$ podman run --rm --interactive --tty docker://archlinux:latest
Trying to pull docker.io/library/archlinux:latest...
Getting image source signatures
Copying blob 8709a4023469 done   | 
Copying blob 4a2362ff7b57 done   | 
Copying config 67236c95c0 done   | 
Writing manifest to image destination
[root@236941cbb7d9 /]#
[root@236941cbb7d9 /]# pacman --noconfirm -Syu && pacman --noconfirm -Sy neovim python python-pynvim
:: Synchronizing package databases...
 core downloading...
 extra downloading...
...
[root@236941cbb7d9 /]# 
[root@236941cbb7d9 /]# cat >| t.vim
pythonx cwd = vim.eval("fnamemodify({!r}, ':~')".format(__import__('os').getcwd()))
pythonx print('work', [cwd])
...
[root@236941cbb7d9 /]# nvim -u t.vim
work ['/']
got ['4']
pid ['289']

expected-buffer-name ['term://///289:/usr/bin/python -i']

buffer-list:
  1 %aR  "term:///.//290:/usr/bin/python -i" line 1

process-tree:
    pstree -cagplt 284                                                                                                                                                              
    nvim,284,284 -u t.vim                                                                                                                                                           
      `-nvim,285,285 --embed -u t.vim                                                                                                                                               
          |-python,289,289 -i                                                                                                                                                       
          |-python,290,290 -i                                                                                                                                                       
          |-python3,288,288 -c import sys; sys.path = [p for p in sys.path if p != ""]; import neovim; neovim.start_host() script_host.py                                           
          `-sh,291,291 -c pgrep nvim | xargs -n1 -t pstree -cagplt                                                                                                                  
              `-xargs,293,291 -n1 -t pstree -cagplt                                                                                                                                 
                  `-pstree,294,291 -cagplt 284                                                                                                                                      
    pstree -cagplt 285                                                                                                                                                              
    nvim,285,285 --embed -u t.vim                                                                                                                                                   
      |-python,289,289 -i                                                                                                                                                           
      |-python,290,290 -i                                                                                                                                                           
      |-python3,288,288 -c import sys; sys.path = [p for p in sys.path if p != ""]; import neovim; neovim.start_host() script_host.py                                               
      `-sh,291,291 -c pgrep nvim | xargs -n1 -t pstree -cagplt                                                                                                                      
          `-xargs,293,291 -n1 -t pstree -cagplt                                                                                                                                     
              `-pstree,295,291 -cagplt 285                                                                                                                                          

[root@236941cbb7d9 /]# 
exit
```
full log: [arch-linux-log.txt](https://github.com/user-attachments/files/17351269/arch-linux-log.txt)

**Comment by arizvisa** [comment]
literally tried for the past hour to see if i could repro with other providers (perl and node), thinking it would be reproduceable in \_any\_ provider as long as it's done from initialization..but failed pretty horribly at that.

**Comment by zeertzjq** [comment]
Provider is not needed. The same happens without provider.
```vim
echomsg termopen('sh', {})
```

**Comment by zeertzjq** [comment]
Workaround: use `bufload('')` before calling `termopen()`.

**Comment by justinmk** [comment]
Can't reproduce this. With `test.vim` : 

```
echomsg termopen('sh', {})
```

then:

```
Error in /Users/x/test.vim[1]..BufReadCmd Autocommands for "term://*":
jobstart(...,{term=true}) requires unmodified buffer
3
:echo &channel
3
```

**Comment by zeertzjq** [comment]
I also found another problem. The following leads to wrong scrollback:
```sh
nvim --clean test/functional/fixtures/bigfile.txt -u test_open_term.vim
```
Content of `test_open_term.vim`:
```vim
let chan = nvim_open_term(0, {})
call chansend(chan, join(range(1000), "\n"))
```
It can happen when editing stdin as well:
```sh
cat test/functional/fixtures/bigfile.txt | nvim --clean -u test_open_term.vim
```

I'm not sure what should happen in these two cases. Perhaps the file or stdin content be passed to the terminal first, then the content from `chansend()`.
