### ISSUE TITLE
Segfault when new window is created inside WinLeave event callback

### ISSUE THREAD

**Issue by apollo1321** [neovim/neovim#31236]
### Problem

If new window is created in WinLeave event callback when closing current tab page, neovim segfaults with the following stack trace:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000559beb72f584 in frame2win (frp=0x0) at /home/apollo1321/neovim/src/nvim/window.c:3474
3474      while (frp->fr_win == NULL) {
(gdb) bt
#0  0x0000559beb72f584 in frame2win (frp=0x0) at /home/apollo1321/neovim/src/nvim/window.c:3474
#1  0x0000559beb72ec33 in winframe_find_altwin (win=0x559becc7d780, dirp=0x7ffe293b5048, tp=0x559becb5c7b0, altfr=0x7ffe293b4f98) at /home/apollo1321/neovim/src/nvim/window.c:3211
#2  0x0000559beb72e9f6 in winframe_remove (win=0x559becc7d780, dirp=0x7ffe293b5048, tp=0x559becb5c7b0, unflat_altfr=0x0) at /home/apollo1321/neovim/src/nvim/window.c:3148
#3  0x0000559beb72e94d in win_free_mem (win=0x559becc7d780, dirp=0x7ffe293b5048, tp=0x559becb5c7b0) at /home/apollo1321/neovim/src/nvim/window.c:3072
#4  0x0000559beb72e8ac in win_close_othertab (win=0x559becc7d780, free_buf=0, tp=0x559becb5c7b0) at /home/apollo1321/neovim/src/nvim/window.c:3050
#5  0x0000559beb72d9ec in close_last_window_tabpage (win=0x559becc7d780, free_buf=false, prev_curtab=0x559becb5c7b0) at /home/apollo1321/neovim/src/nvim/window.c:2609
#6  0x0000559beb72dd9b in win_close (win=0x559becc7d780, free_buf=false, force=false) at /home/apollo1321/neovim/src/nvim/window.c:2711
#7  0x0000559beb4d1a03 in ex_quit (eap=0x7ffe293b5280) at /home/apollo1321/neovim/src/nvim/ex_docmd.c:4776
#8  0x0000559beb4c9970 in execute_cmd0 (retv=0x7ffe293b5238, eap=0x7ffe293b5280, errormsg=0x7ffe293b5250, preview=false) at /home/apollo1321/neovim/src/nvim/ex_docmd.c:1714
#9  0x0000559beb4cb829 in do_one_cmd (cmdlinep=0x7ffe293b54a0, flags=0, cstack=0x7ffe293b55b0, fgetline=0x559beb4e47c7 <getexline>, cookie=0x0) at /home/apollo1321/neovim/src/nvim/ex_docmd.c:2358
#10 0x0000559beb4c730b in do_cmdline (cmdline=0x0, fgetline=0x559beb4e47c7 <getexline>, cookie=0x0, flags=0) at /home/apollo1321/neovim/src/nvim/ex_docmd.c:667
#11 0x0000559beb5ce4ab in nv_colon (cap=0x7ffe293b5c20) at /home/apollo1321/neovim/src/nvim/normal.c:3191
#12 0x0000559beb5c9f0e in normal_execute (state=0x7ffe293b5bb0, key=58) at /home/apollo1321/neovim/src/nvim/normal.c:1243
#13 0x0000559beb6a98c5 in state_enter (s=0x7ffe293b5bb0) at /home/apollo1321/neovim/src/nvim/state.c:102
#14 0x0000559beb5c806d in normal_enter (cmdwin=false, noexmode=false) at /home/apollo1321/neovim/src/nvim/normal.c:521
#15 0x0000559beb56b798 in main (argc=2, argv=0x7ffe293b5fb8) at /home/apollo1321/neovim/src/nvim/main.c:660
```

Related to https://github.com/nvim-treesitter/nvim-treesitter-context/issues/522

### Steps to reproduce

```
cat > init.lua << EOF 
vim.api.nvim_create_autocmd({ "WinLeave" }, {
  callback = function()
    local buf = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_open_win(buf, false, {
      win = 0,
      relative = "win",
      row = 10,
      col = 2,
      width = 12,
      height = 3,
      border = "single",
    })
  end
})
EOF

nvim --clean -c "source init.lua"

:tab split
:q
```

### Expected behavior

No segfault

### Nvim version (nvim -v)

v0.11.0-dev-29ded8895

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Linux 6.8.0-48-generic

### Terminal name/version

iterm 2, 3.5.3

### $TERM environment variable

xterm-256color

### Installation

build from repo

**Comment by zeertzjq** [comment]
Related #21409

**Comment by ece-jacob-scott** [comment]
unable to reproduce with this nvim version. 

```
> ./build/bin/nvim -v                                        
NVIM v0.11.0-dev-b165ad0
Build type: Debug
LuaJIT 2.1.1741730670
Run "nvim -V1 -v" for more info
```

When I reproduced the steps with gdb I saw this 

```
Reading symbols from ./build/bin/nvim...
(gdb) r --clean -c "source ./issue_31236/init.lua"
quit
Starting program: /../neovim/build/bin/nvim --clean -c "source ./issue_31236/init.lua"

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.ubuntu.com>
Enable debuginfod for this session? (y or [n]) n

Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 29830]
[Inferior 1 (process 29824) exited normally]

(gdb) bt

No stack.
(gdb) quit
```

Which I think means there was no segfault.

**Comment by zeertzjq** [comment]
Still happens
```
**/src/nvim/window.c:3207:25: runtime error: null pointer passed as argument 1, which is declared to never be null
**/build/include/window.h.generated.h:50:42: note: nonnull attribute specified here
    #0 0x5d5aa8a05358 in winframe_find_altwin **/src/nvim/window.c:3207:15
    #1 0x5d5aa89f2d50 in winframe_remove **/src/nvim/window.c:3144:15
    #2 0x5d5aa8a0266a in win_free_mem **/src/nvim/window.c:3068:10
    #3 0x5d5aa89ff79d in win_close_othertab **/src/nvim/window.c:3046:3
    #4 0x5d5aa8a002b0 in close_last_window_tabpage **/src/nvim/window.c:2605:5
    #5 0x5d5aa89c07db in win_close **/src/nvim/window.c:2707:7
    #6 0x5d5aa7b2878d in ex_quit **/src/nvim/ex_docmd.c:4789:5
    #7 0x5d5aa7af5bf1 in execute_cmd0 **/src/nvim/ex_docmd.c:1721:7
    #8 0x5d5aa7ad55bb in do_one_cmd **/src/nvim/ex_docmd.c:2365:7
    #9 0x5d5aa7aca5a2 in do_cmdline **/src/nvim/ex_docmd.c:672:20
    #10 0x5d5aa80b957d in nv_colon **/src/nvim/normal.c:3189:18
    #11 0x5d5aa80a678a in normal_execute **/src/nvim/normal.c:1244:3
    #12 0x5d5aa85d3fd5 in state_enter **/src/nvim/state.c:102:26
    #13 0x5d5aa80892e1 in normal_enter **/src/nvim/normal.c:523:3
    #14 0x5d5aa7e0bb92 in main **/src/nvim/main.c:651:3
    #15 0x740ff6d46487 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #16 0x740ff6d4654b in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #17 0x5d5aa7274d44 in _start (**/build/bin/nvim+0xc62d44) (BuildId: a76278a6d2fb20337b27d57abe047f44794b0933)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior **/src/nvim/window.c:3207:25 
```
