### ISSUE TITLE
Crashes when picking an nonexist file from filter /pat/ brow oldfiles

### ISSUE THREAD

**Issue by alexaschee** [neovim/neovim#31501]
### Problem

Rename a folder, eg. old_folder to new_folder.

In nvim:

    filter /file_in_old_folder/ brow oldfiles

then pick a file that used to be in old_folder and nvim crashes.

BUT picking from

    brow oldfiles

works fine.

### Steps to reproduce

    
    :filer /pat/ brow oldfiles

pick a file that doesn't exist any more and nvim crashes.

### Expected behavior

Not crash.

### Nvim version (nvim -v)

NVIM v0.11.0-dev-1300+g1077843b9b-dirty

### Vim (not Nvim) behaves the same?

no

### Operating system/version

window 10

### Terminal name/version

cmd

### $TERM environment variable

 ---

### Installation

  build from repo

**Comment by zeertzjq** [comment]
ASAN:
```
=================================================================
==98269==ERROR: AddressSanitizer: attempting double-free on 0x502000026c30 in thread T0:
    #0 0x6055d2813e62 in free.part.0 asan_malloc_linux.cpp.o
    #1 0x6055d3520d5b in xfree **/src/nvim/memory.c:145:3
    #2 0x6055d301071b in undo_cmdmod **/src/nvim/ex_docmd.c:2781:3
    #3 0x6055d2ff3e9b in do_one_cmd **/src/nvim/ex_docmd.c:2398:3
    #4 0x6055d2fe74a5 in do_cmdline **/src/nvim/ex_docmd.c:667:20
    #5 0x6055d3641ce7 in nv_colon **/src/nvim/normal.c:3191:18
    #6 0x6055d362d795 in normal_execute **/src/nvim/normal.c:1243:3
    #7 0x6055d3bc0bd8 in state_enter **/src/nvim/state.c:102:26
    #8 0x6055d360de51 in normal_enter **/src/nvim/normal.c:521:3
    #9 0x6055d335de87 in main **/src/nvim/main.c:651:3
    #10 0x764883fc6e07 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #11 0x764883fc6ecb in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #12 0x6055d2728d24 in _start (**/build/bin/nvim+0xc4ad24) (BuildId: ccf26c4bf9dff788ce66fb3a0e7847ea049c4487)

0x502000026c30 is located 0 bytes inside of 10-byte region [0x502000026c30,0x502000026c3a)
freed by thread T0 here:
    #0 0x6055d2813e62 in free.part.0 asan_malloc_linux.cpp.o
    #1 0x6055d3520d5b in xfree **/src/nvim/memory.c:145:3
    #2 0x6055d301071b in undo_cmdmod **/src/nvim/ex_docmd.c:2781:3
    #3 0x6055d33491bf in nlua_with **/src/nvim/lua/stdlib.c:658:3
    #4 0x6055d4191be5 in lj_BC_FUNCC (**/build/bin/nvim+0x26b3be5) (BuildId: ccf26c4bf9dff788ce66fb3a0e7847ea049c4487)

previously allocated by thread T0 here:
    #0 0x6055d2814e09 in malloc (**/build/bin/nvim+0xd36e09) (BuildId: ccf26c4bf9dff788ce66fb3a0e7847ea049c4487)
    #1 0x6055d3520a49 in try_malloc **/src/nvim/memory.c:99:15
    #2 0x6055d3520c74 in xmalloc **/src/nvim/memory.c:133:15
    #3 0x6055d3521142 in xmallocz **/src/nvim/memory.c:205:15
    #4 0x6055d3521293 in xmemdupz **/src/nvim/memory.c:223:17
    #5 0x6055d35227e7 in xstrdup **/src/nvim/memory.c:470:10
    #6 0x6055d2ffffb8 in parse_command_modifiers **/src/nvim/ex_docmd.c:2592:33
    #7 0x6055d2feeccf in do_one_cmd **/src/nvim/ex_docmd.c:2006:7
    #8 0x6055d2fe74a5 in do_cmdline **/src/nvim/ex_docmd.c:667:20
    #9 0x6055d3641ce7 in nv_colon **/src/nvim/normal.c:3191:18
    #10 0x6055d362d795 in normal_execute **/src/nvim/normal.c:1243:3
    #11 0x6055d3bc0bd8 in state_enter **/src/nvim/state.c:102:26
    #12 0x6055d360de51 in normal_enter **/src/nvim/normal.c:521:3
    #13 0x6055d335de87 in main **/src/nvim/main.c:651:3
    #14 0x764883fc6e07 in __libc_start_call_main /usr/src/debug/glibc/glibc/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #15 0x764883fc6ecb in __libc_start_main /usr/src/debug/glibc/glibc/csu/../csu/libc-start.c:360:3
    #16 0x6055d2728d24 in _start (**/build/bin/nvim+0xc4ad24) (BuildId: ccf26c4bf9dff788ce66fb3a0e7847ea049c4487)

SUMMARY: AddressSanitizer: double-free asan_malloc_linux.cpp.o in free.part.0
==98269==ABORTING
```

**Comment by zeertzjq** [comment]
I think this will fix the problem:
```diff
diff --git a/src/nvim/lua/stdlib.c b/src/nvim/lua/stdlib.c
index e719d99640..5ebff3a809 100644
--- a/src/nvim/lua/stdlib.c
+++ b/src/nvim/lua/stdlib.c
@@ -619,6 +619,7 @@ static int nlua_with(lua_State *L)
   int rets = 0;
 
   cmdmod_T save_cmdmod = cmdmod;
+  CLEAR_FIELD(cmdmod);
   cmdmod.cmod_flags = flags;
   apply_cmdmod(&cmdmod);
 
```
