### ISSUE TITLE
Can't import runpy error when trying to do a keyword lookup on a module in Python

### ISSUE THREAD

**Issue by FranzMartyn** [neovim/neovim#31728]
### Problem

This error appears when trying to use shift + k on a module in a Python file while having Python 3.13.x installed:

```
Could not import runpy module
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in exec_module
  File "<frozen runpy>", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 1176, in exec_module
    File "<frozen importlib.util>", line 16, in <module>
    File "D:\Programme\Python\Lib\threading.py", line 35, in <module>
      _start_joinable_thread = _thread.start_joinable_thread
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: module '_thread' has no attribute 'start_joinable_thread'
```

### Steps to reproduce

- nvim file.py
- import a python library (in my example `import shutil`)
- select `shutil`
- shift+k

### Expected behavior

keyword lookup works fine when Python 3.12.x is installed:

![Image](https://github.com/user-attachments/assets/4226163c-6bd8-4444-8383-11dc303203c3)

Setting keywordprg to `python -m pydoc` instead of `python3 -m pydoc` might be a quick fix

![Image](https://github.com/user-attachments/assets/8890de6f-f5b2-4f5f-af51-59d291722d10)

### Nvim version (nvim -v)

NVIM v0.10.3

### Vim (not Nvim) behaves the same?

yes, vim 9.1

### Operating system/version

Windows 11 24H2

### Terminal name/version

Windows Terminal V1.21.3231.0

### $TERM environment variable

(not set)

### Installation

chocolatey

**Comment by zeertzjq** [comment]
Since this happens when you run `python3 -m pydoc` on the command line as well, this is not an Nvim issue.
