### ISSUE TITLE
error starting neovim with python -- missing zlib

### ISSUE THREAD

**Issue by danielb2** [neovim/neovim#3268]
Looks like the error is `can't decompress data; zlib not available`

What need I do?

```
2015/08/18 18:29:54 [info @ main_loop:513] 95019 - Starting Neovim main loop.
2015/08/18 23:03:22 [info @ main_loop:513] 14164 - Starting Neovim main loop.
2015/08/27 15:02:37 [error @ job_err:346] 2464 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2015/08/27 15:02:37 [error @ job_err:346] 2464 - Channel 1 stderr:   File "/Library/Python/2.7/site-p
ackages/neovim-0.0.36-py2.7.egg/neovim/__init__.py", line 9, in <module>
    from .api import DecodeHook, Nvim, SessionHook
  File "/Library/Python/2.7/site-packages/neovim-0.0.36-py2.7.egg/neovim/api/__init__.py", line 9
2015/08/27 15:02:37 [error @ job_err:346] 2464 - Channel 1 stderr: , in <module>
    from .nvim import Nvim, NvimError
  File "/Library/Python/2.7/site-packages/neovim-0.0.36-py2.7.egg/neovim/api/nvim.py", line 4, in <mo
dule>
    from msgpack import ExtType
zipimport.ZipImportError: can't decompress data; zlib not availa
2015/08/27 15:02:37 [error @ job_err:346] 2464 - Channel 1 stderr: ble

2015/08/27 15:02:37 [error @ call_set_error:742] 2464 - msgpack-rpc: Channel was closed by the client
2015/08/27 15:02:47 [info @ main_loop:513] 2464 - Starting Neovim main loop.
2015/08/29 17:29:50 [error @ forward_stderr:333] 62719 - Channel 1 stderr: Traceback (most recent cal
l last):
  File "<string>", line 1, in <module>

2015/08/29 17:29:50 [error @ forward_stderr:333] 62719 - Channel 1 stderr:   File "/Library/Python/2.
7/site-packages/neovim-0.0.36-py2.7.egg/neovim/__init__.py", line 9, in <module>
    from .api import DecodeHook, Nvim, SessionHook
  File "/Library/Python/2.7/site-packages/neovim-0.0.36-py2.7.egg/neovim/api/__init__.py", line 9
2015/08/29 17:29:50 [error @ forward_stderr:333] 62719 - Channel 1 stderr: , in <module>
    from .nvim import Nvim, NvimError
  File "/Library/Python/2.7/site-packages/neovim-0.0.36-py2.7.egg/neovim/api/nvim.py", line 4, in <mo
dule>
    from msgpack import ExtType
zipimport.ZipImportError: can't decompress data; zlib not availa
2015/08/29 17:29:50 [error @ forward_stderr:333] 62719 - Channel 1 stderr: ble

2015/08/29 17:29:50 [error @ call_set_error:743] 62719 - msgpack-rpc: Channel was closed by the clien
t
2015/08/29 17:30:01 [info @ main_loop:558] 62719 - Starting Neovim main loop.
```

**Comment by fwalch** [comment]
Not sure if that will help, but try updating the python client. Current version is 0.0.38.

**Comment by danielb2** [comment]
I just compiled python with homebrew. I looked at it a little bit but Im not really familiar with python to know how to fix that particular issue.

**Comment by danielb2** [comment]
actually, I just tried removing the brew install, and ran nvim, and it worked with no issue. thanks
