### ISSUE TITLE
`TERM=dumb nvim` hangs

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#3471]
This command:

```
TERM=dumb nvim
```

hangs. nvim should do something other than hang when TERM contains an unknown[1] value.

[1] Actually I have confirmed this issue only for the value "dumb", so it may be that specific value.

**Comment by mseeber** [comment]
dumb is not an unknown value, in my arch system, there exists a termifo file named "dumb" maybe it is inkompatible with the used Terminal, sice it hangs in my system too.

**Comment by ZyX-I** [comment]
It waits in `compress_trie` in libtermkey in UI thread, another thread waits UI:

```
(gdb) thread apply all bt full

Thread 2 (Thread 0x7fdc75e37700 (LWP 13467)):
#0  0x00007fdc798064c0 in compress_trie () from /usr/lib64/libtermkey.so.1
No symbol table info available.
#1  0x00007fdc79806bbf in new_driver () from /usr/lib64/libtermkey.so.1
No symbol table info available.
#2  0x00007fdc79803e5d in termkey_init () from /usr/lib64/libtermkey.so.1
No symbol table info available.
#3  0x00007fdc79804073 in termkey_new_abstract () from /usr/lib64/libtermkey.so.1
No symbol table info available.
#4  0x0000000002215908 in term_input_init (input=0x631000010870, loop=0x7fdc75e36680)
    at /home/zyx/a.a/Proj/c/neovim/src/nvim/tui/input.c:33
        term = 0x7ffef9e85a76 "dumb"
        enc_flag = 8
        curflags = 1969793792
#5  0x00000000021f92a8 in tui_main (bridge=0x61300002f980, ui=0x6110001c9ac0)
    at /home/zyx/a.a/Proj/c/neovim/src/nvim/tui/tui.c:202
        tui_loop = {uv = {data = 0x7fdc75e36680, active_handles = 2, handle_queue = {0x7fdc75e36908, 0x631000011098},
            active_reqs = {0x7fdc75e366a0, 0x7fdc75e366a0}, stop_flag = 0, flags = 0, backend_fd = 17,
            pending_queue = {0x7fdc75e366c8, 0x7fdc75e366c8}, watcher_queue = {0x7fdc75e368c8, 0x7fdc75e36860},
            watchers = 0x6110001c1f00, nwatchers = 30, nfds = 2, wq = {0x7fdc75e366f8, 0x7fdc75e366f8}, wq_mutex = {
              __data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0,
                __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, wq_async = {
              data = 0x0, loop = 0x7fdc75e36680, type = UV_ASYNC, close_cb = 0x0, handle_queue = {0x7fdc75e36be0,
                0x7fdc75e36908}, u = {fd = 0, reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 49152,
              async_cb = 0x7fdc7a8f0100 <uv.work_done>, queue = {0x7fdc75e36c28, 0x7fdc75e36830}, pending = 0},
            cloexec_lock = {__data = {__lock = 0, __nr_readers = 0, __readers_wakeup = 0, __writer_wakeup = 0,
                __nr_readers_queued = 0, __nr_writers_queued = 0, __writer = 0, __shared = 0, __rwelision = 0 '\000',
                __pad1 = "\000\000\000\000\000\000", __pad2 = 0, __flags = 0}, __size = '\000' <repeats 55 times>,
              __align = 0}, closing_handles = 0x0, process_handles = {0x7fdc75e367f0, 0x7fdc75e367f0},
            prepare_handles = {0x7fdc75e36800, 0x7fdc75e36800}, check_handles = {0x7fdc75e36810, 0x7fdc75e36810},
            idle_handles = {0x7fdc75e36820, 0x7fdc75e36820}, async_handles = {0x7fdc75e36798, 0x7fdc75e36c28},
            async_watcher = {cb = 0x7fdc7a8f1f80 <uv.async_event>, io_watcher = {cb = 0x7fdc7a8f1fe0 <uv.async_io>,
                pending_queue = {0x7fdc75e36850, 0x7fdc75e36850}, watcher_queue = {0x7fdc75e366d8, 0x7fdc75e368c8},
                pevents = 1, events = 0, fd = 20}, wfd = -1}, timer_heap = {min = 0x0, nelts = 0}, timer_counter = 0,
            time = 901024177, signal_pipefd = {18, 19}, signal_io_watcher = {cb = 0x7fdc7a8f8dc0 <uv.signal_event>,
              pending_queue = {0x7fdc75e368b8, 0x7fdc75e368b8}, watcher_queue = {0x7fdc75e36860, 0x7fdc75e366d8},
              pevents = 1, events = 0, fd = 18}, child_watcher = {data = 0x0, loop = 0x7fdc75e36680,
              type = UV_SIGNAL, close_cb = 0x0, handle_queue = {0x7fdc75e36750, 0x7fdc75e36690}, u = {fd = 0,
                reserved = {0x0, 0x0, 0x0, 0x0}}, next_closing = 0x0, flags = 32768, signal_cb = 0x0, signum = 0,
              tree_entry = {rbe_left = 0x0, rbe_right = 0x0, rbe_parent = 0x0, rbe_color = 0}, caught_signals = 0,
              dispatched_signals = 0}, emfile_fd = -1, inotify_read_watcher = {cb = 0x0, pending_queue = {0x0, 0x0},
              watcher_queue = {0x0, 0x0}, pevents = 0, events = 0, fd = 0}, inotify_watchers = 0x0, inotify_fd = -1},
          events = 0x604000039fd0, fast_events = 0x604000039f90, thread_events = 0x604000039f50,
          children = 0x60300002ffb0, children_watcher = {data = 0x7fdc7ad33148, loop = 0x7fdc75e36680,
            type = UV_SIGNAL, close_cb = 0x7fdc7ab19b26 <do_lookup_x+2054>, handle_queue = {0x7fdc75e36aa8,
              0x7fdc75e36be0}, u = {fd = 2060661064, reserved = {0x7fdc7ad33148, 0x7fdc75e36ab8, 0x7fdc75e36ab4,
                0x7fdc75e36ac8}}, next_closing = 0x0, flags = 8192, signal_cb = 0x7fdc7a4c0f68, signum = 0,
            tree_entry = {rbe_left = 0x7c96f087, rbe_right = 0x1f25bc2 <win_exchange+13490>, rbe_parent = 0x7,
              rbe_color = 1977838480}, caught_signals = 0, dispatched_signals = 0}, children_kill_timer = {
            data = 0x7fdc75e36ab4, loop = 0x7fdc75e36680, type = UV_TIMER, close_cb = 0x10, handle_queue = {
              0x7fdc75e36b40, 0x7fdc75e36a10}, u = {fd = 0, reserved = {0x0, 0x7ad2f358, 0x7fdc7ad2f358,
                0x7fdc75e36c20}}, next_closing = 0x0, flags = 8192, timer_cb = 0x0, heap_node = {0x0,
              0x7fdc7ab19f3f <_dl_lookup_symbol_x+351>, 0x0}, timeout = 140584929945464, repeat = 0, start_id = 0},
          poll_timer = {data = 0x1, loop = 0x7fdc75e36680, type = UV_TIMER, close_cb = 0x7fdc7ad33148,
            handle_queue = {0x631000010fe0, 0x7fdc75e36aa8}, u = {fd = 2060645208, reserved = {0x7fdc7ad2f358,
                0x7fdc75e36b90, 0x17ad334a0, 0x7fdc75e36b80}}, next_closing = 0x0, flags = 8192, timer_cb = 0x0,
            heap_node = {0x431f16, 0x421c28, 0x7fdc7ad33148}, timeout = 140584921344400, repeat = 0, start_id = 5},
          children_stop_requests = 0, async = {data = 0x7fdc75e37700, loop = 0x7fdc75e36680, type = UV_ASYNC,
            close_cb = 0x7fdc7ab254e0 <_dl_runtime_resolve+80>, handle_queue = {0x7fdc75e36a10, 0x7fdc75e36750}, u = {
              fd = 981, reserved = {0x3d5, 0x7fdc7a6d7020 <free@got.plt>, 0x7fdc75e36e98, 0x0}}, next_closing = 0x0,
            flags = 24576, async_cb = 0x2273590 <async_cb>, queue = {0x7fdc75e36830, 0x7fdc75e36798}, pending = 0},
          mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0,
              __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>,
            __align = 0}, recursive = 0}
        data = 0x631000000800
#6  0x00000000010fc1cd in ui_thread_run (data=0x61300002f980) at /home/zyx/a.a/Proj/c/neovim/src/nvim/ui_bridge.c:80
        bridge = 0x61300002f980
#7  0x00007fdc7a8fca97 in uv.thread_start () from /usr/lib64/libuv.so.1
No symbol table info available.
#8  0x00007fdc7a4c7486 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#9  0x00007fdc78c049ed in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7fdc7acf3780 (LWP 13437)):
#0  0x00007fdc7a4ccc4f in pthread_cond_wait () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007fdc7a8fcfa9 in uv_cond_wait () from /usr/lib64/libuv.so.1
No symbol table info available.
#2  0x00000000010f3196 in ui_bridge_attach (ui=0x6110001c9ac0, ui_main=0x21f8050 <tui_main>,
    scheduler=0x21f9fa0 <tui_scheduler>) at /home/zyx/a.a/Proj/c/neovim/src/nvim/ui_bridge.c:69
        rv = 0x61300002f980
---Type <return> to continue, or q <return> to quit---
#3  0x00000000021ea93d in tui_start () at /home/zyx/a.a/Proj/c/neovim/src/nvim/tui/tui.c:102
        ui = 0x6110001c9ac0
#4  0x0000000000be7bad in ui_builtin_start () at /home/zyx/a.a/Proj/c/neovim/src/nvim/ui.c:75
No locals.
#5  0x0000000001162c06 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/zyx/a.a/Proj/c/neovim/src/nvim/main.c:430
        fname = <optimized out>
        params = <optimized out>
        reading_input = <optimized out>
```

**Comment by mseeber** [comment]
nvim also hangs with TERM=northstar

**Comment by ZyX-I** [comment]
I think that based on where it hangs it may be moved to other bug tracker. Also CC @leonerd. But first it is needed to migrate to libtickit since libtermkey is no longer supported and thus it is pointless to move to its bug tracker.

Note that some code may be taken from #1966 (where libtickit was removed).

**Comment by justinmk** [comment]
Doesn't seem to be a problem any more.
