### ISSUE TITLE
when neomake plugin is loaded neovim crashes on entering 04

### ISSUE THREAD

**Issue by torpak** [neovim/neovim#3538]
reproduce:
put neomake in your init.vim. (i use vimplug, but that's not relevant, i think)
start nvim
enter 
```vim
04
```
wait a few seconds:
nvim: /build/neovim-H96Rof/neovim-0.0.0+git201510270507+1948+14~ubuntu14.04.1/src/nvim/os/input.c:87: create_cursorhold_event: Assertion `queue_empty(loop.events)' failed.
Aborted

**Comment by equalsraf** [comment]
Confirmed here ([full trace](https://gist.github.com/equalsraf/6279787dba9f2213e585)) using 68e596856828e61a5fed5a515647509b0cd77100 in Linux.

```gdb
#0  0x00007f7998093638 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f7998094a1a in __GI_abort () at abort.c:78
#2  0x00007f799808c3a7 in __assert_fail_base (fmt=<optimized out>, 
    assertion=assertion@entry=0x695772 "queue_empty(loop.events)", 
    file=file@entry=0x695748 "/home/raf/Code/neovim/src/nvim/os/input.c", line=line@entry=87, 
    function=function@entry=0x695800 <__PRETTY_FUNCTION__.12262> "create_cursorhold_event")
    at assert.c:92
#3  0x00007f799808c452 in __GI___assert_fail (assertion=0x695772 "queue_empty(loop.events)", 
    file=0x695748 "/home/raf/Code/neovim/src/nvim/os/input.c", line=87, 
    function=0x695800 <__PRETTY_FUNCTION__.12262> "create_cursorhold_event") at assert.c:101
#4  0x000000000061f449 in create_cursorhold_event ()
    at /home/raf/Code/neovim/src/nvim/os/input.c:87
#5  0x000000000061f551 in os_inchar (buf=0x8f5462 <typebuf_init+2> "", maxlen=87, ms=-1, 
    tb_change_cnt=3) at /home/raf/Code/neovim/src/nvim/os/input.c:106
#6  0x00000000004fdcea in inchar (buf=0x8f5462 <typebuf_init+2> "", maxlen=262, wait_time=-1, 
    tb_change_cnt=3) at /home/raf/Code/neovim/src/nvim/getchar.c:2462
#7  0x00000000004fd913 in vgetorpeek (advance=1)
    at /home/raf/Code/neovim/src/nvim/getchar.c:2282
```

The [assert is here](https://github.com/neovim/neovim/blob/29d64a901df6eff436b100374b2a240eea1906d9/src/nvim/os/input.c#L87).  The comment in the assertion suggests otherwise but [inbuf_poll returned kInputNone](https://github.com/neovim/neovim/blob/29d64a901df6eff436b100374b2a240eea1906d9/src/nvim/os/input.c#L104)
