### ISSUE TITLE
File path error

### ISSUE THREAD

**Issue by Passw** [neovim/neovim#3575]
https://github.com/severin-lemaignan/vim-minimap/issues/34

**Comment by fmoralesc** [comment]
It looks like you need to update your plugin location: neovim follows the XDG spec now, so plugins should be at `~/.config/nvim/` or `~/.local/share/nvim/site/` instead of `~/.nvim`. See https://github.com/neovim/neovim/wiki/Following-HEAD

**Comment by Passw** [comment]
After move plugins to ```~/.config/nvim```, this issue still there. 

```
Error detected while processing function provider#python#Call:
line   18:
IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/share/nvim/runtime/autoload/provider/script_host.py", line 82, in python_execute_file
    with open(file_path) as f:
IOError: [Errno 2] No such file or directory: '/home/sun/.config/nvim/bundle/vim-minimap/autoload/minimap.py\n/home/sun/.vim/bundle/vi
m-minimap/autoload/minimap.py'
Error detected while processing function minimap#ShowMinimap..provider#python#Call:
line   18:
NameError("name 'showminimap' is not defined",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/local/lib/python2.7/dist-packages/neovim-0.0.38-py2.7.egg/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/usr/local/share/nvim/runtime/autoload/provider/script_host.py", line 76, in python_execute
    exec(script, self.module.__dict__)
  File "<string>", line 1, in <module>
NameError: name 'showminimap' is not defined
```
