### ISSUE TITLE
python3 not working

### ISSUE THREAD

**Issue by jorrete** [neovim/neovim#3618]
Since I installed Fedora 23 I am having problems with python3.

- nvim from source
- pip install neovim
- pip3 install neovim

nvim version:
```
NVIM v0.1.0-6-ge19f1c5 (compiled Nov  4 2015 8:50:00)                                                                                                                                                
Commit: e19f1c54914527da7a20d49905ed1c1b95eb9ceb 
```
If I run:
```
:echo has('python')
```
returns
```
1
```
If I run:
```
:echo has('python3')
```
returns:
```
2015/11/06 18:11:05 [error @ forward_stderr:333] 6221 - Channel 3 stderr: /lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 83, in request
    v = self._blocking_request(method, args)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 155, in _blocking_request
    self._async_session.r
2015/11/06 18:11:05 [error @ forward_stderr:333] 6221 - Channel 3 stderr: equest(method, args, response_cb)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/async_session.py", line 44, in request
    self._msgpack_stream.send([0, request_id, method, args])
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/m
2015/11/06 18:11:05 [error @ forward_stderr:333] 6221 - Channel 3 stderr: sgpack_stream.py", line 37, in send
    self._event_loop.send(self._packer.pack(msg))
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 734, in pack
    self._pack(obj)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", l
2015/11/06 18:11:05 [error @ forward_stderr:333] 6221 - Channel 3 stderr: ine 722, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 676, in _pack
    obj = obj.encode(self._encoding, self._unicode_errors)
TypeError: encode() argument 1 must be str, not bytes

2015/11/06 18:11:05 [error @ call_set_error:743] 6221 - msgpack-rpc: Channel was closed by the client
```

python3
```
Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
```

Probably is not a neovim problem since it was working before the Fedora update, but I'm lost and I don't know where to report the problem.

Thanks.

**Comment by justinmk** [comment]
AFAIK we require 3.5 minimum for python 3.

**Comment by Shougo** [comment]
@justinmk Current minimum is Python3.3.
Python3.5 is not major version.

@jorrete Please test `import neovim` from `python3` command.

**Comment by justinmk** [comment]
:+1:

**Comment by jorrete** [comment]
It seems to work. There is no exception. I did it from python3 console.

**Comment by justinmk** [comment]
@jorrete please try from `:python3` nvim command. Not python3 console.

**Comment by jorrete** [comment]
from neovim command
```
:python3 import neovim
```
output
```
2015/11/08 22:29:31 [info @ main:532] 22949 - Starting Neovim main loop.
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/neovim/__init__.py", line 65, in start_host
    host = Host(Nvim.from_session(session))
  File "/usr/lib/python3.4/site-packages/neovim/plug
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: in/host.py", line 39, in __init__
    self._nvim_encoding = nvim.options['encoding']
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 43, in __getitem__
    return self._get(key)
  File "/usr/lib/python3.4/site-packages/neovim/api/comm
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: on.py", line 265, in <lambda>
    return lambda *args: session.request(method, *args)
  File "/usr/lib/python3.4/site-packages/neovim/api/common.py", line 230, in request
    return walk(self._in, self._session.request(name, *args, **kwargs),
  File "/usr
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: /lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 83, in request
    v = self._blocking_request(method, args)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/session.py", line 155, in _blocking_request
    self._async_session.r
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: equest(method, args, response_cb)
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/async_session.py", line 44, in request
    self._msgpack_stream.send([0, request_id, method, args])
  File "/usr/lib/python3.4/site-packages/neovim/msgpack_rpc/m
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: sgpack_stream.py", line 37, in send
    self._event_loop.send(self._packer.pack(msg))
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 734, in pack
    self._pack(obj)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", l
2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: ine 722, in _pack
    self._pack(obj[i], nest_limit - 1)
  File "/usr/lib64/python3.4/site-packages/msgpack/fallback.py", line 676, in _pack
    obj = obj.encode(self._encoding, self._unicode_errors)
TypeError: encode() argument 1 must be str, not bytes

2015/11/08 22:29:55 [error @ forward_stderr:333] 22949 - Channel 2 stderr: Exception ignored in: 
2015/11/08 22:29:55 [error @ call_set_error:743] 22949 - msgpack-rpc: Channel was closed by the client
```

**Comment by bfredl** [comment]
just to be sure, you have latest python-client version (0.0.38) ?
Seems like `encoding` option doesn't get decoded properly. What `&encoding` in neovim do you have?

**Comment by jorrete** [comment]
yes, it's 0.0.38.
I'm not sure what is &encoding, but
```
:set encoding
```
returns
```
encoding=utf-8
```

**Comment by bfredl** [comment]
ok, that's what I meant. Somehow we ask the mskpack packer to use an encoding where the encoding itself is specified as `bytes`. I think these lines in `api/nvim.py` are the relevant ones
```
    encoding = session.request(b'vim_get_option', b'encoding')
    session._async_session._msgpack_stream.set_packer_encoding(encoding)
```
but as neovim uses a mskpack STR to represents strings now, the return value form `session.request` should be a `str` and not `bytes` ....

**Comment by bfredl** [comment]
Looking a bit more into, there should be no need to mess with `msgpack.Packer` encoding in the first place as the encoding of STR is defined to be `utf-8` and Packer uses this by the default, but we first set it to `None` and then `&encoding` for some reason. I will send PR to remove it.

**Comment by bfredl** [comment]
I still can't reproduce this locally, but please try neovim/python-client#141 and see if it helps.

**Comment by bfredl** [comment]
I can reproduce now: cython compiled python-msgpack allows `encoding` to be bytes, but the pure python fallback does not. Anyway, the PR should fix it.

**Comment by jorrete** [comment]
Sorry, How can I clone the repo with your changes?

**Comment by bfredl** [comment]
To quickly test this I think the simplest is
```
git clone https://github.com/bfredl/python-client -b str_enc
cd python-client
python3 setup.py install 
```
(add `sudo` to last line if needed.)

**Comment by jorrete** [comment]
Ok!!. I've uninstalled the previous version of python3 neovim and installed your branch and It seems to be working.

**Comment by bfredl** [comment]
Fix will be in next python-client release.

**Comment by drasill** [comment]
Thank you, I confirm I had the same error, fixed by this patch.
