### ISSUE TITLE
Crash in check_lnums with "tabdo Gdiff"

### ISSUE THREAD

**Issue by blueyed** [neovim/neovim#3738]
I am seeing a crash with `vi -p -c "tabdo Gdiff HEAD~1 | tabfirst" $(git diff --name-only)`, where `git diff --name-only` contains 3 files.

It only happens with the terminal being not maximized, but taking half of the screen.

The crash happens in https:…/nvim/window.c#L5094.

Something in [fugitive](https://github.com/tpope/vim-fugitive) seems to trigger it, I could not reproduce it with other commands (instead of `Gdiff`), but `Glog` also did not crash.

```
#0  0x0000000000433433 in check_lnums (do_curwin=do_curwin@entry=1) at ……/nvim/window.c:5094
#1  0x00000000005130c5 in apply_autocmds_group (event=event@entry=EVENT_BUFLEAVE,
    fname=0x7ffbbeccea80 "fugitive:…/project/.git//deadbeef/project/app/tests/test_api.py", fname@entry=0x0,
    fname_io=fname_io@entry=0x0, force=force@entry=0, group=group@entry=-3, buf=0x7ffbbe9db800, eap=0x0) at ……/nvim/fileio.c:6587
#2  0x0000000000513711 in apply_autocmds (event=event@entry=EVENT_BUFLEAVE, fname=fname@entry=0x0, fname_io=fname_io@entry=0x0, force=force@entry=0, buf=<optimized out>)
    at ……/nvim/fileio.c:6207
#3  0x0000000000431776 in win_enter_ext (wp=wp@entry=0x7ffbbf45d000, undo_sync=undo_sync@entry=true, curwin_invalid=curwin_invalid@entry=0,
    trigger_enter_autocmds=trigger_enter_autocmds@entry=1, trigger_leave_autocmds=trigger_leave_autocmds@entry=1) at ……/nvim/window.c:3493
#4  0x0000000000431ce2 in win_enter (wp=wp@entry=0x7ffbbf45d000, undo_sync=undo_sync@entry=true) at ……/nvim/window.c:3473
#5  0x00000000004320a7 in win_goto (wp=0x7ffbbf45d000) at ……/nvim/window.c:3327
#6  0x0000000000435194 in do_window (nchar=112, Prenum=0, xchar=xchar@entry=0) at ……/nvim/window.c:290
#7  0x00000000005311f6 in ex_wincmd (eap=0x7ffeee2073f0) at ……/nvim/ex_docmd.c:6946
#8  0x0000000000535b65 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffeee207530, sourcing=sourcing@entry=1, cstack=cstack@entry=0x7ffeee2075c0,
    fgetline=fgetline@entry=0x5690de <get_func_line>, cookie=cookie@entry=0x7ffbbf4b6e00) at ……/nvim/ex_docmd.c:2185
#9  0x00000000005364de in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, fgetline=fgetline@entry=0x5690de <get_func_line>, cookie=cookie@entry=0x7ffbbf4b6e00, flags=flags@entry=7)
    at ……/nvim/ex_docmd.c:611
#10 0x000000000055c83b in call_user_func (fp=fp@entry=0x7ffbbedde440, argcount=argcount@entry=3, argvars=argvars@entry=0x7ffeee207e90, rettv=rettv@entry=0x7ffeee2084d0,
    firstline=firstline@entry=1, lastline=lastline@entry=1, selfdict=0x0) at ……/nvim/eval.c:20605
#11 0x000000000055d264 in call_func (funcname=funcname@entry=0x7ffbbf49f609 "s:Diff('',0,\"HEAD~1\")", len=len@entry=6, rettv=rettv@entry=0x7ffeee2084d0, argcount=argcount@entry=3,
    argvars=argvars@entry=0x7ffeee207e90, firstline=firstline@entry=1, lastline=1, doesrange=0x7ffeee208060, evaluate=1, selfdict=0x0)
    at ……/nvim/eval.c:7663
#12 0x00000000005622a6 in get_func_tv (name=0x7ffbbf49f609 "s:Diff('',0,\"HEAD~1\")", len=6, rettv=rettv@entry=0x7ffeee2084d0, arg=arg@entry=0x7ffeee2084c8, firstline=1, lastline=1,
    doesrange=0x7ffeee208060, evaluate=1, selfdict=0x0) at ……/nvim/eval.c:7529
#13 0x000000000056088b in eval7 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=evaluate@entry=1, want_string=want_string@entry=0)
    at ……/nvim/eval.c:4230
#14 0x0000000000560ab9 in eval6 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=evaluate@entry=1, want_string=want_string@entry=0)
    at ……/nvim/eval.c:3940
#15 0x0000000000560d64 in eval5 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=evaluate@entry=1)
    at ……/nvim/eval.c:3792
#16 0x000000000056108e in eval4 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=evaluate@entry=1)
    at ……/nvim/eval.c:3536
#17 0x0000000000561918 in eval3 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=evaluate@entry=1)
    at ……/nvim/eval.c:3456
#18 0x0000000000561a58 in eval2 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=evaluate@entry=1)
    at ……/nvim/eval.c:3393
#19 0x0000000000561b95 in eval1 (arg=arg@entry=0x7ffeee2084c8, rettv=rettv@entry=0x7ffeee2084d0, evaluate=1) at ……/nvim/eval.c:3326
#20 0x000000000056610e in ex_execute (eap=0x7ffeee208590) at ……/nvim/eval.c:18996
```

```
NVIM v0.1.0-114-g5da7ea9 (compiled Nov 24 2015 18:36:06)
Commit: 5da7ea98cac53549dbbbbfafd7fcda3d93e3f99c
Build type: Dev
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvl
a -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I…/neovim-git/build/config -I/tmp/pacaurtmp-user/ne
ovim-git/src/neovim-git/src -I/usr/include -I/usr/include -I/usr/include/luajit-2.0 -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/tmp/pacaurtmp-user/neovim-
git…/nvim/auto -I…/neovim-git/build/include
Compiled by user@a.example.com

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by justinmk** [comment]
Possibly helped by https://github.com/neovim/neovim/pull/5500. @blueyed are you still able to reproduce this?

**Comment by blueyed** [comment]
@justinmk 
Hard to say.. probably depends on the input/context.
I would close it: #5500 sounds related.
Thanks!
