### ISSUE TITLE
Python crashes on start on windows

### ISSUE THREAD

**Issue by RedX2501** [neovim/neovim#3862]
When starting the latest build from equalsraf repo python will not start properly.

The command executed was ```:py 42```

My question is how do you debug this? Python quits to fast for me to able able to attach...

The python log file contains:
```
2015-12-16 19:30:08,586 [ERROR @ base_events.py:default_exception_handler:1053] 16700 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x027314B0>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\trollius\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 428, in recv
    self._register_with_iocp(conn)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 609, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
WindowsError: [Error 6] Das Handle ist ungültig
```

The neovim log file nvimlog:
```
015/12/16 20:43:55 [error @ call_set_error:743] 17716 - msgpack-rpc: Channel was closed by the client
2015/12/16 20:44:33 [info @ main:533] 16324 - Starting Neovim main loop.
2015/12/16 20:44:41 [error @ forward_stderr:333] 16324 - Channel 2 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\neovim\__init__.py", line 64, in start_host
    session = stdio_session()
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\__init__
2015/12/16 20:44:42 [error @ forward_stderr:333] 16324 - Channel 2 stderr: .py", line 36, in stdio_session
    return session('stdio')
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 17, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "C:\Python27\lib\site-packages\neovim\m
2015/12/16 20:44:42 [error @ forward_stderr:333] 16324 - Channel 2 stderr: sgpack_rpc\event_loop\base.py", line 88, in __init__
    getattr(self, '_connect_{0}'.format(transport_type))(*args)
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 90, in _connect_stdio
    self._loop.run_until_co
2015/12/16 20:44:43 [error @ forward_stderr:333] 16324 - Channel 2 stderr: mplete(coroutine)
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 348, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

2015/12/16 20:44:43 [error @ call_set_error:743] 16324 - msgpack-rpc: Channel was closed by the client
```

**Comment by equalsraf** [comment]
@RedX2501  in the end I was unable to reproduce this one, maybe this should be reported in neovim/python-client.

Ping @brcolow because this issue is suspiciously similar to the one we discussed in gitter.

**Comment by justinmk** [comment]
Moved to https://github.com/neovim/python-client/issues/152
