### ISSUE TITLE
I hit an infinite loop (I think)

### ISSUE THREAD

**Issue by teto** [neovim/neovim#4227]
Hi,

This is the first time I hit such a situation, where I can't do anything in neovim, type anything etc.. and it doesn't crash. Hence I attached gdb and provide a backtrace below.
I wouldn't now how to reproduce it, I was working on 2 buffers , one with vimtex in background (tex file), the other with a csv file (and I have csv.vim).

```
$nvim --version
NVIM v0.1.3-40-gc238459
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Og -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/teto/neovim/config -I/home/teto/neovim/src -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include/luajit-2.0 -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/home/teto/neovim/.deps/usr/include -I/usr/include -I/home/teto/neovim/src/nvim/auto -I/home/teto/neovim/include
Compilé par teto@teto-Mac

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   fichier vimrc système : "$VIM/sysinit.vim"
  $VIM par défaut : "/usr/local/share/nvim"

```

the backtrace
```

#0  0x0000000000554877 in eval1 (arg=arg@entry=0x7ffe53750788, rettv=rettv@entry=0x7ffe53750790, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3390
#1  0x0000000000554de2 in get_func_tv (name=0x7f0fd7a560a0 "escape(b:csv_cmt[0], '\\\\')", len=6, rettv=rettv@entry=0x7ffe53750a70, 
    arg=arg@entry=0x7ffe53750e60, firstline=1, lastline=1, doesrange=0x7ffe53750960, evaluate=1, selfdict=0x0)
    at /home/teto/neovim/src/nvim/eval.c:7535
#2  0x000000000055343d in eval7 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750a70, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=1) at /home/teto/neovim/src/nvim/eval.c:4228
#3  0x0000000000553671 in eval6 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750a70, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=1) at /home/teto/neovim/src/nvim/eval.c:3959
#4  0x00000000005539b6 in eval5 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750eb0, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3842
#5  0x0000000000553c49 in eval4 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750eb0, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3555
#6  0x00000000005544d3 in eval3 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750eb0, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3475
#7  0x0000000000554613 in eval2 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750eb0, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3412
#8  0x0000000000554750 in eval1 (arg=arg@entry=0x7ffe53750e60, rettv=rettv@entry=0x7ffe53750eb0, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3345
#9  0x0000000000554f2c in eval0 (arg=0x7f0fd7a56096 "'^\\s*\\V'. escape(b:csv_cmt[0], '\\\\')", rettv=rettv@entry=0x7ffe53750eb0, 
    nextcmd=nextcmd@entry=0x7ffe53750f68, evaluate=1) at /home/teto/neovim/src/nvim/eval.c:3307
#10 0x000000000055b082 in ex_let (eap=0x7ffe53750f60) at /home/teto/neovim/src/nvim/eval.c:1421
#11 0x0000000000527092 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffe537510a0, sourcing=sourcing@entry=1, 
    cstack=cstack@entry=0x7ffe53751130, fgetline=fgetline@entry=0x51c990 <get_loop_line>, cookie=cookie@entry=0x7ffe537510d0)
    at /home/teto/neovim/src/nvim/ex_docmd.c:2192
#12 0x0000000000527a10 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, fgetline=fgetline@entry=0x55be70 <get_func_line>, 
    cookie=cookie@entry=0x7f0fd8259a00, flags=flags@entry=7) at /home/teto/neovim/src/nvim/ex_docmd.c:602
#13 0x000000000054f046 in call_user_func (fp=fp@entry=0x7f0fd83d2b40, argcount=argcount@entry=0, argvars=argvars@entry=0x7ffe53751a30, 
    rettv=rettv@entry=0x7ffe53752150, firstline=firstline@entry=1, lastline=lastline@entry=1, selfdict=0x0)
    at /home/teto/neovim/src/nvim/eval.c:20954
#14 0x000000000054fa7b in call_func (funcname=funcname@entry=0x7f0fd7a97bdf "<SID>MaxColumns()", len=len@entry=15, 
    rettv=rettv@entry=0x7ffe53752150, argcount=argcount@entry=0, argvars=argvars@entry=0x7ffe53751a30, firstline=firstline@entry=1, 
    lastline=1, doesrange=0x7ffe53751c00, evaluate=1, selfdict=0x0) at /home/teto/neovim/src/nvim/eval.c:7683
#15 0x0000000000554e67 in get_func_tv (name=0x7f0fd7a97bdf "<SID>MaxColumns()", len=15, rettv=rettv@entry=0x7ffe53752150, 
    arg=arg@entry=0x7ffe53752100, firstline=1, lastline=1, doesrange=0x7ffe53751c00, evaluate=1, selfdict=0x0)
    at /home/teto/neovim/src/nvim/eval.c:7549
#16 0x000000000055343d in eval7 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=0) at /home/teto/neovim/src/nvim/eval.c:4228
#17 0x0000000000553671 in eval6 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=0) at /home/teto/neovim/src/nvim/eval.c:3959
#18 0x000000000055391c in eval5 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3811
#19 0x0000000000553c49 in eval4 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3555
#20 0x00000000005544d3 in eval3 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3475
#21 0x0000000000554613 in eval2 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3412
#22 0x0000000000554750 in eval1 (arg=arg@entry=0x7ffe53752100, rettv=rettv@entry=0x7ffe53752150, evaluate=evaluate@entry=1)
    at /home/teto/neovim/src/nvim/eval.c:3345
#23 0x0000000000554f2c in eval0 (arg=0x7f0fd7a97bdf "<SID>MaxColumns()", rettv=rettv@entry=0x7ffe53752150, 
    nextcmd=nextcmd@entry=0x7ffe53752208, evaluate=1) at /home/teto/neovim/src/nvim/eval.c:3307
#24 0x000000000055b082 in ex_let (eap=0x7ffe53752200) at /home/teto/neovim/src/nvim/eval.c:1421
#25 0x0000000000527092 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffe53752340, sourcing=sourcing@entry=1, 
    cstack=cstack@entry=0x7ffe537523d0, fgetline=fgetline@entry=0x55be70 <get_func_line>, cookie=cookie@entry=0x7f0fd8259000)
    at /home/teto/neovim/src/nvim/ex_docmd.c:2192
#26 0x0000000000527a10 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, fgetline=fgetline@entry=0x55be70 <get_func_line>, 
    cookie=cookie@entry=0x7f0fd8259000, flags=flags@entry=7) at /home/teto/neovim/src/nvim/ex_docmd.c:602
#27 0x000000000054f046 in call_user_func (fp=fp@entry=0x7f0fd83d35c0, argcount=argcount@entry=2, argvars=argvars@entry=0x7ffe53752cd0, 
    rettv=rettv@entry=0x7ffe53752ea0, firstline=firstline@entry=1, lastline=lastline@entry=1, selfdict=0x0)
    at /home/teto/neovim/src/nvim/eval.c:20954
#28 0x000000000054fa7b in call_func (funcname=funcname@entry=0x7f0fd7999250 "\200\375Q156_MoveCol", len=len@entry=14, 
    rettv=rettv@entry=0x7ffe53752ea0, argcount=argcount@entry=2, argvars=argvars@entry=0x7ffe53752cd0, firstline=firstline@entry=1, 
    lastline=1, doesrange=0x7ffe53752e94, evaluate=1, selfdict=0x0) at /home/teto/neovim/src/nvim/eval.c:7683
#29 0x0000000000554e67 in get_func_tv (name=name@entry=0x7f0fd7999250 "\200\375Q156_MoveCol", len=14, 
    rettv=rettv@entry=0x7ffe53752ea0, arg=arg@entry=0x7ffe53752e98, firstline=1, lastline=1, doesrange=0x7ffe53752e94, evaluate=1, 
    selfdict=0x0) at /home/teto/neovim/src/nvim/eval.c:7549
#30 0x00000000005595f2 in ex_call (eap=0x7ffe53752f70) at /home/teto/neovim/src/nvim/eval.c:2771
#31 0x0000000000527092 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffe537530b0, sourcing=sourcing@entry=0, 
    cstack=cstack@entry=0x7ffe53753140, fgetline=fgetline@entry=0x50086b <getexline>, cookie=cookie@entry=0x0)
    at /home/teto/neovim/src/nvim/ex_docmd.c:2192
#32 0x0000000000527a10 in do_cmdline (cmdline=<optimized out>, cmdline@entry=0x0, fgetline=0x50086b <getexline>, 
    cookie=cookie@entry=0x0, flags=0) at /home/teto/neovim/src/nvim/ex_docmd.c:602
#33 0x00000000004d0023 in nv_colon (cap=0x7ffe53753730) at /home/teto/neovim/src/nvim/normal.c:4482
#34 0x00000000004d971c in normal_execute (state=0x7ffe53753690, key=<optimized out>) at /home/teto/neovim/src/nvim/normal.c:1147
#35 0x00000000004afef9 in state_enter (s=s@entry=0x7ffe53753690) at /home/teto/neovim/src/nvim/state.c:55
#36 0x00000000004d154e in normal_enter (cmdwin=cmdwin@entry=false, noexmode=noexmode@entry=false)
    at /home/teto/neovim/src/nvim/normal.c:464
#37 0x00000000004a1042 in main (argc=<optimized out>, argv=<optimized out>) at /home/teto/neovim/src/nvim/main.c:528
Detaching from program: /usr/local/bin/nvim, process 8203

``

**Comment by chrisbra** [comment]
On Mi, 10 Feb 2016, Matthieu Coudron wrote:

> Hi,
> 
> This is the first time I hit such a situation, where I can't do anything in neovim, type anything etc.. and it doesn't crash. Hence I attached gdb and provide a backtrace below.
> I wouldn't now how to reproduce it, I was working on 2 buffers , one with vimtex in background (tex file), the other with a csv file (and I have csv.vim).

Looks like a problem with the csv plugin. Can you say what exactly you did there?

**Comment by teto** [comment]
The csv I was working on was really simple, just a header and one entry maybe. I've no idea how it was triggered but if it happens again and I can find a way to reproduce it, I will report it.

**Comment by justinmk** [comment]
Going to assume this is a plugin bug. If you find a way to reproduce, please check whether it occurs in Vim as well.
