### ISSUE TITLE
updated YouCompleteMe recently spawns error in nvim

### ISSUE THREAD

**Issue by atomic** [neovim/neovim#4359]
- Neovim version:   0.1.3-dev
- Operating system: elementaryOS Freya (or Ubuntu 14.04)
- Terminal emulator: zsh in tmux in pantheon-terminal

### Actual behaviour
```
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
NvimError('Vim:E685: Internal error: get_tv_string_buf()',)
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/session.py", line 177, in handler
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
    rv = self._request_cb(name, args)
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
  File "/usr/local/lib/python2.7/dist-packages/neovim/api/common.py", line 237, in filter_request_cb
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
    walk(self._in, args, self, name, 'request'))
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
  File "/usr/local/lib/python2.7/dist-packages/neovim/plugin/host.py", line 65, in _on_request
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
    rv = handler(*args)
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
  File "/usr/share/nvim/runtime/autoload/provider/script_host.py", line 77, in python_execute
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
    exec(script, self.module.__dict__)
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
NvimError: Vim:E685: Internal error: get_tv_string_buf()
Press ENTER or type command to continue
Error detected while processing function <SNR>193_OnInsertLeave[6]..<SNR>193_OnFileReadyToParse[9]..provider#python#Call:
line   18:
P
```

### Expected behaviour
I has been working well for over a year, this error might have something to do with either nvim updates or YCM updates.
My other environment with same OS,shell,term has nvim version 0.1.2-dev, and updated YCM, with pretty much same .vimrc and .ycm_config configurations and it works smoothly.

### Steps to reproduce
with updated YCM and neovim, open and edit C codes and triggering completion. Or even just wait few seconds, the errors will show.

**Comment by wsdjeg** [comment]
please update neovim ,this should be fixed
