### ISSUE TITLE
Channel was closed by client

### ISSUE THREAD

**Issue by Alok** [neovim/neovim#4473]
- Neovim version: v0.1.3-332-g5730ad9 (the latest)
- Operating system: OSX 10.11.3
- Terminal emulator: iTerm2 (build 2.9.20160319-nightly)

### Actual behaviour
Error message immediately pops up.
### Expected behaviour
No errors.
### Steps to reproduce
Start neovim with Startify or anything that uses Python 2.  `nvim -u NONE` gives no error.

Here's part of my `~/.nvimlog`. I do in fact have all the necessary pip packages installed (checked manually), so the importErrors are really confusing me.
```
  File "<string>", line 1, in <module>

2016/03/19 01:34:54 [error @ forward_stderr:333] 10792 - Channel 4 stderr: ImportError: No module named neovim

2016/03/19 01:34:54 [error @ call_set_error:743] 10792 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:35:36 [error @ forward_stderr:333] 11158 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:35:36 [error @ forward_stderr:333] 11158 - Channel 1 stderr: ImportError: No module named neovim

2016/03/19 01:35:36 [error @ call_set_error:743] 11158 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:35:36 [info @ main:533] 11158 - Starting Neovim main loop.
2016/03/19 01:35:52 [error @ call_set_error:743] 11158 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:37:13 [error @ call_set_error:743] 10792 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:39:44 [error @ forward_stderr:333] 12238 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:39:44 [error @ forward_stderr:333] 12238 - Channel 1 stderr: ImportError: No module named neovim

2016/03/19 01:39:44 [error @ call_set_error:743] 12238 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:39:44 [info @ main:533] 12238 - Starting Neovim main loop.
2016/03/19 01:39:49 [error @ call_set_error:743] 12238 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:39:59 [error @ forward_stderr:333] 12352 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:39:59 [error @ forward_stderr:333] 12352 - Channel 1 stderr: ImportError: No module named neovim

2016/03/19 01:39:59 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:39:59 [info @ main:533] 12352 - Starting Neovim main loop.
2016/03/19 01:40:00 [error @ forward_stderr:333] 12352 - Channel 2 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:00 [error @ forward_stderr:333] 12352 - Channel 2 stderr: ImportError: No module named neovim

2016/03/19 01:40:00 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:01 [error @ forward_stderr:333] 12352 - Channel 3 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:01 [error @ forward_stderr:333] 12352 - Channel 3 stderr: ImportError: No module named neovim

2016/03/19 01:40:01 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:02 [error @ forward_stderr:333] 12352 - Channel 4 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:02 [error @ forward_stderr:333] 12352 - Channel 4 stderr: ImportError: No module named neovim

2016/03/19 01:40:02 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:12 [error @ forward_stderr:333] 12352 - Channel 5 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:12 [error @ forward_stderr:333] 12352 - Channel 5 stderr: ImportError: No module named neovim

2016/03/19 01:40:12 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:15 [error @ forward_stderr:333] 12352 - Channel 7 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:15 [error @ forward_stderr:333] 12352 - Channel 7 stderr: ImportError: No module named neovim

2016/03/19 01:40:15 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:16 [error @ forward_stderr:333] 12352 - Channel 8 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:16 [error @ forward_stderr:333] 12352 - Channel 8 stderr: ImportError: No module named neovim

2016/03/19 01:40:16 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:17 [error @ forward_stderr:333] 12352 - Channel 9 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:17 [error @ forward_stderr:333] 12352 - Channel 9 stderr: ImportError: No module named neovim

2016/03/19 01:40:17 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:17 [error @ forward_stderr:333] 12352 - Channel 10 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:17 [error @ forward_stderr:333] 12352 - Channel 10 stderr: ImportError: No module named neovim

2016/03/19 01:40:17 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:19 [error @ call_set_error:743] 12352 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:42 [error @ forward_stderr:333] 12621 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:40:42 [error @ forward_stderr:333] 12621 - Channel 1 stderr: ImportError: No module named neovim

2016/03/19 01:40:42 [error @ call_set_error:743] 12621 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:40:42 [info @ main:533] 12621 - Starting Neovim main loop.
2016/03/19 01:41:19 [error @ forward_stderr:333] 12978 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:41:19 [error @ forward_stderr:333] 12978 - Channel 1 stderr: ImportError: No module named neovim

2016/03/19 01:41:19 [error @ call_set_error:743] 12978 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:41:19 [info @ main:533] 12978 - Starting Neovim main loop.
2016/03/19 01:41:21 [error @ call_set_error:743] 12978 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:42:54 [error @ forward_stderr:333] 13587 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:42:54 [error @ forward_stderr:333] 13587 - Channel 1 stderr: ImportError: No module named neovim

2016/03/19 01:42:54 [error @ call_set_error:743] 13587 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:42:54 [info @ main:533] 13587 - Starting Neovim main loop.
2016/03/19 01:42:56 [error @ forward_stderr:333] 13587 - Channel 3 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:42:56 [error @ forward_stderr:333] 13587 - Channel 3 stderr: ImportError: No module named neovim

2016/03/19 01:42:56 [error @ call_set_error:743] 13587 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:42:56 [error @ forward_stderr:333] 13587 - Channel 4 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/03/19 01:42:56 [error @ forward_stderr:333] 13587 - Channel 4 stderr: ImportError: No module named neovim

2016/03/19 01:42:56 [error @ call_set_error:743] 13587 - msgpack-rpc: Channel was closed by the client
2016/03/19 01:43:24 [error @ call_set_error:743] 13587 - msgpack-rpc: Channel was closed by the client
```

**Comment by Shougo** [comment]
http://neovim.io/doc/user/nvim_python.html
https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working

**Comment by Alok** [comment]
I get "/usr/bin/python" for `echo interp` and `echo errors` is empty. Setting my `g:python_host_prog = '/usr/local/bin/python` causes Python to crash.

**Comment by Shougo** [comment]
@Alok Your `/usr/local/bin/python` is Python2?

**Comment by Alok** [comment]
yes

**Comment by Alok** [comment]
Just to clarify, I get this error with **both** `/usr/local/bin/python` and `/usr/bin/python`.

**Comment by Shougo** [comment]
neovim-python is installed?
It seems not installed.

**Comment by Shougo** [comment]
You can check the installation.

```
$ /usr/local/bin/python
>>> import neovim
```

**Comment by Alok** [comment]
`import neovim` gives no errors in the interpreter for either `/usr/local/bin/python` or `/usr/bin/python`.

**Comment by Shougo** [comment]
But neovim cannot load neovim...
Please test it in neovim.
And do you use virtualenv?

**Comment by Shougo** [comment]
Your `:echo has('python')` is 1?

**Comment by Alok** [comment]
I do not use virtualenv. the `:echo has('python')` is `1.`

**Comment by bfredl** [comment]
please try `NVIM_PYTHON_LOG_FILE=pylog NVIM_PYTHON_LOG_LEVEL=DEBUG nvim` and check the `pylog` file afterwise

**Comment by Alok** [comment]
I get these two `pylog` files after.
[pylog1.txt](https://github.com/neovim/neovim/files/180749/pylog1.txt)
[pylog2.txt](https://github.com/neovim/neovim/files/180750/pylog2.txt)

**Comment by bfredl** [comment]
Both these seem for python3. have you upgraded with `pip2` recently like
`pip2 install --upgrade neovim`

**Comment by Alok** [comment]
Yes. Attempting to run again gives:

```
Requirement already satisfied (use --upgrade to upgrade): neovim in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): trollius in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already satisfied (use --upgrade to upgrade): msgpack-python>=0.4.0 in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already satisfied (use --upgrade to upgrade): greenlet in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already satisfied (use --upgrade to upgrade): futures in /usr/local/lib/python2.7/site-packages (from trollius->neovim)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from trollius->neovim)
```

**Comment by bfredl** [comment]
It didn't seem you used `--upgrade` ?

**Comment by Alok** [comment]
Running `--upgrade` gives 

```
Requirement already up-to-date: neovim in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: trollius in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already up-to-date: msgpack-python>=0.4.0 in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already up-to-date: greenlet in /usr/local/lib/python2.7/site-packages (from neovim)
Requirement already up-to-date: futures in /usr/local/lib/python2.7/site-packages (from trollius->neovim)
Requirement already up-to-date: six in /usr/local/lib/python2.7/site-packages (from trollius->neovim)
```

**Comment by Alok** [comment]
I ended up uninstalling pip's neovim package manually and then reinstalled it to both `/usr/local/lib/python2.7/site-packages` and `/Library/Python/2.7/site-packages/`. The second one seemed to fix it.
