### ISSUE TITLE
Python sys.path does not get populated when resuming a session

### ISSUE THREAD

**Issue by msmith491** [neovim/neovim#4619]
- Neovim version: NVIM 0.1.4-dev
- Vim behaves differently?
  - Vim version: VIM - Vi IMproved 7.3
- Operating system/version: Mac OSX
- Terminal name/version: ITerm2
- `$TERM`: xterm-256color
### Actual behaviour

executing `:py import pprint; pprint.pprint( sys.path )` gives this error message (executed with the `-u NONE` flag to ensure my init.vim isn't the contributing factor) 

```
function provider#python#Call[9]..remote#host#Require[13]..provider#pythonx#Require, line 15
Vim(if):Channel was closed by the client
Failed to load python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file.
 Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
```
#### Contents of .nvimlog

```
2016/04/20 07:51:57 [error @ call_set_error:743] 10124 - msgpack-rpc: Channel was closed by the client
2016/04/20 07:55:00 [info @ main:533] 10920 - Starting Neovim main loop.
2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>

2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr:   File "/usr/local/lib/python2.7/site-packages/neovim/__init__.py", line 66, in start_host

2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr:     host.start(plugins)

2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr:   File "/usr/local/lib/python2.7/site-packages/neovim/plugin/host.py", line 47, in start

2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr:     lambda: self._load(plugins))
  File "/usr/local/lib/python2.7/site-packages/neovim/api/common.py", line 244, in run

2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr:     self._session.run(filter_request_cb, filter_notification_cb, setup_cb)
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 118, in run

2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr:     raise self._setup_exception
ImportError:
2016/04/20 07:55:08 [error @ forward_stderr:333] 10920 - Channel 1 stderr: No module named script_host

2016/04/20 07:55:08 [error @ call_set_error:743] 10920 - msgpack-rpc: Channel was closed by the client
```
### Expected behaviour

sys.path gets populated and plugins depending on python function
### Steps to reproduce using `nvim -u NONE`
1. `nvim -u NONE`
2.  open any python file
3. `:mksession ~/test_session.vim` 
4. `:qa`
5. `nvim -u NONE -S ~/test_session.vim`
6. `:py import pprint; pprint.pprint( sys.path )`

Originally found during investigation for this bug:
Valloric/YouCompleteMe/issues/2126

**Comment by justinmk** [comment]
Thanks for the clear steps. Works fine on master. Last step returned:

```
['/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/home/vagrant/.local/lib/python3.4/site-packages',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages',
 '_vim_path_']
```
