### ISSUE TITLE
Neomake and Deoplete combination causes Segmentation fault on save and exit

### ISSUE THREAD

**Issue by lluixhi** [neovim/neovim#4662]
- Neovim version: Master (0.1.5-69-g81e0874) **Not present in 0.1.4**
- Operating system/version: Gentoo Linux (Hardened Musl x86_64)
- Terminal name/version: st 0.6
- `$TERM`: st-256color

### Actual behaviour
Segmentation fault on closing and saving file (:x :wq)

### Expected behaviour
No segfault!

### Steps to reproduce:
The segmentation fault appears to be triggered when I do the following:
1. Have neomake and deoplete enabled (note: i am using vim-plug)
vimrc:
```viml
call plug#begin('~/.config/nvim/plugged')
Plug 'benekastah/neomake'
Plug 'Shougo/deoplete.vim'
call plug#end()

let g:deoplete#enable_at_startup=1
autocmd! BufWritePost * Neomake
```
2. Insert a line in a  **tex** file.
3. save and exit

Here is the GDB backtrace (if that helps any):
```
Starting program: /usr/bin/nvim test.tex
[New LWP 29150]
[LWP 29150 exited]

Thread 1 "nvim" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
#0  0x0000000000000000 in ?? ()
#1  0x000003fff7fb3e9e in __fwritex (s=0x3ffffff9de0 "\r\n", l=2, f=0x3fff7ffbb00 <__stderr_used>) at src/stdio/fwrite.c:16
#2  0x000003fff7fb3f5f in fwrite (src=src@entry=0x3ffffff9de0, size=size@entry=1, nmemb=nmemb@entry=2, f=f@entry=0x3fff7ffbb00 <__stderr_used>) at src/stdio/fwrite.c:33
#3  0x000003fff7fb3218 in fputs (s=s@entry=0x3ffffff9de0 "\r\n", f=f@entry=0x3fff7ffbb00 <__stderr_used>) at src/stdio/fputs.c:7
#4  0x000002aaaabd255b in msg_puts_printf (maxlen=<optimized out>, str=<optimized out>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:1960
#5  msg_puts_attr_len (str=str@entry=0x3ffffff9e20 "\n", maxlen=maxlen@entry=-1, attr=<optimized out>, attr@entry=0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:1552
#6  0x000002aaaabd261c in msg_puts_attr (attr=0, s=0x3ffffff9e20 "\n") at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:1507
#7  msg_putchar_attr (c=c@entry=10, attr=attr@entry=0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:1024
#8  0x000002aaaabd4414 in msg_putchar (c=10) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:1009
#9  msg_start () at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:982
#10 0x000002aaaabd44ae in msg_attr_keep (s=0x2aaab168c40 "Neomake: lacheck complete with exit code 0", attr=0, keep=keep@entry=0)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:176
#11 0x000002aaaabd47a7 in msg_attr (s=<optimized out>, attr=<optimized out>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/message.c:133
#12 0x000002aaaab4586a in ex_execute (eap=0x3ffffffa110) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:18837
#13 0x000002aaaab71fe0 in do_one_cmd (cookie=0x2aaaaf88f60, fgetline=0x2aaaab48ef0 <get_func_line>, cstack=0x3ffffffa1c0, sourcing=1, cmdlinep=0x3ffffffa060)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:2192
#14 do_cmdline (cmdline=cmdline@entry=0x0, fgetline=fgetline@entry=0x2aaaab48ef0 <get_func_line>, cookie=cookie@entry=0x2aaaaf88f60, flags=flags@entry=7)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:601
#15 0x000002aaaab37c9d in call_user_func (fp=0x2aaab33ff00, argcount=argcount@entry=2, argvars=argvars@entry=0x3ffffffaae0, rettv=rettv@entry=0x3fffffface0, firstline=firstline@entry=3, 
    lastline=lastline@entry=3, selfdict=0x0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:20436
#16 0x000002aaaab38d7b in call_func (funcname=funcname@entry=0x2aaaaf833e0 "neomake#utils#LogMessage", len=len@entry=24, rettv=rettv@entry=0x3fffffface0, argcount=argcount@entry=2, 
    argvars=argvars@entry=0x3ffffffaae0, firstline=firstline@entry=3, lastline=3, doesrange=0x3ffffffacd4, evaluate=1, selfdict=0x0)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:7237
#17 0x000002aaaab3f447 in get_func_tv (name=name@entry=0x2aaaaf833e0 "neomake#utils#LogMessage", len=24, rettv=rettv@entry=0x3fffffface0, arg=arg@entry=0x3ffffffacd8, firstline=firstline@entry=3, 
    lastline=lastline@entry=3, doesrange=0x3ffffffacd4, evaluate=1, selfdict=0x0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:7103
#18 0x000002aaaab45d7f in ex_call (eap=0x3ffffffaf40) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:2761
#19 0x000002aaaab71fe0 in do_one_cmd (cookie=0x2aaab19eb20, fgetline=0x2aaaab48ef0 <get_func_line>, cstack=0x3ffffffaff0, sourcing=1, cmdlinep=0x3ffffffae90)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:2192
#20 do_cmdline (cmdline=cmdline@entry=0x0, fgetline=fgetline@entry=0x2aaaab48ef0 <get_func_line>, cookie=cookie@entry=0x2aaab19eb20, flags=flags@entry=7)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:601
#21 0x000002aaaab37c9d in call_user_func (fp=0x2aaab1936c0, argcount=argcount@entry=1, argvars=argvars@entry=0x3ffffffb910, rettv=rettv@entry=0x3ffffffbb10, firstline=firstline@entry=3, 
    lastline=lastline@entry=3, selfdict=0x0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:20436
#22 0x000002aaaab38d7b in call_func (funcname=funcname@entry=0x2aaaad82b40 "neomake#utils#QuietMessage", len=len@entry=26, rettv=rettv@entry=0x3ffffffbb10, argcount=argcount@entry=1, 
    argvars=argvars@entry=0x3ffffffb910, firstline=firstline@entry=3, lastline=3, doesrange=0x3ffffffbb04, evaluate=1, selfdict=0x0)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:7237
#23 0x000002aaaab3f447 in get_func_tv (name=name@entry=0x2aaaad82b40 "neomake#utils#QuietMessage", len=26, rettv=rettv@entry=0x3ffffffbb10, arg=arg@entry=0x3ffffffbb08, firstline=firstline@entry=3, 
    lastline=lastline@entry=3, doesrange=0x3ffffffbb04, evaluate=1, selfdict=0x0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:7103
#24 0x000002aaaab45d7f in ex_call (eap=0x3ffffffbd70) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:2761
#25 0x000002aaaab71fe0 in do_one_cmd (cookie=0x2aaaaf8c0c0, fgetline=0x2aaaab48ef0 <get_func_line>, cstack=0x3ffffffbe20, sourcing=1, cmdlinep=0x3ffffffbcc0)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:2192
#26 do_cmdline (cmdline=cmdline@entry=0x0, fgetline=fgetline@entry=0x2aaaab48ef0 <get_func_line>, cookie=cookie@entry=0x2aaaaf8c0c0, flags=flags@entry=7)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:601
#27 0x000002aaaab37c9d in call_user_func (fp=0x2aaab1526e0, argcount=3, argvars=argvars@entry=0x3ffffffc630, rettv=rettv@entry=0x3ffffffc620, firstline=<optimized out>, lastline=<optimized out>, 
    selfdict=0x2aaab19fbe0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:20436
#28 0x000002aaaab384d3 in on_job_event (ev=ev@entry=0x3ffffffc6d0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:21715
#29 0x000002aaaab38641 in process_job_event (status=0, count=0, buf=0x0, type=0x2aaaacade34 "exit", callback=<optimized out>, data=0x2aaab19cfe0)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:21589
#30 on_process_exit (proc=<optimized out>, status=0, d=0x2aaab19cfe0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/eval.c:21645
#31 0x000002aaaab55292 in queue_process_events (queue=0x2aaaad41b40) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/event/queue.c:142
#32 0x000002aaaab543dc in process_teardown (loop=0x2aaaad38860 <loop>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/event/process.c:135
#33 0x000002aaaabb65da in event_teardown () at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/main.c:161
#34 0x000002aaaac136c9 in mch_exit (r=0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/os_unix.c:167
#35 0x000000000010c7ca in ?? ()
#36 0x000002aaaab6be9c in ex_exit (eap=0x3ffffffcaa0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:6024
#37 0x000002aaaab71fe0 in do_one_cmd (cookie=0x0, fgetline=0x2aaaab81c00 <getexline>, cstack=0x3ffffffcb50, sourcing=0, cmdlinep=0x3ffffffc9f0)
    at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:2192
#38 do_cmdline (cmdline=cmdline@entry=0x0, fgetline=<optimized out>, cookie=cookie@entry=0x0, flags=<optimized out>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/ex_docmd.c:601
#39 0x000002aaaabe9f14 in nv_colon (cap=0x3ffffffd170) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/normal.c:4486
#40 0x000002aaaabf35c5 in normal_execute (state=0x3ffffffd0d0, key=<optimized out>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/normal.c:1147
#41 0x000002aaaac82524 in state_enter (s=s@entry=0x3ffffffd0d0) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/state.c:55
#42 0x000002aaaabea578 in normal_enter (cmdwin=<optimized out>, noexmode=<optimized out>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/normal.c:464
#43 0x000002aaaaaedff7 in main (argc=<optimized out>, argv=<optimized out>) at /var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src/nvim/main.c:538
```

**Comment by lluixhi** [comment]
Duplicate of #4664
