### ISSUE TITLE
Segfault in memfile.c

### ISSUE THREAD

**Issue by fwalch** [neovim/neovim#5454]
- `nvim --version`: NVIM v0.1.6-171-g87fa495
- Operating system/version: Arch Linux
- Terminal name/version: sakura 3.3.4
- `$TERM`: xterm-256color

Just got a pretty random segfault while editing a LaTeX document. I don't recall what exactly I was doing before the crash.

Backtrace:

```
#0  0x00000000004f07bf in mf_sync (mfp=0x7f38f5423b00, flags=6) at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/memfile.c:433
#1  0x00000000004f3ea8 in ml_sync_all (check_file=check_file@entry=1, check_char=check_char@entry=1)
    at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/memline.c:1617
#2  0x00000000004cdd39 in updatescript (c=c@entry=0) at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/getchar.c:1348
#3  0x00000000004cdd53 in before_blocking () at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/getchar.c:1329
#4  0x0000000000533e48 in os_inchar (buf=buf@entry=0x0, maxlen=maxlen@entry=0, ms=ms@entry=-1, tb_change_cnt=tb_change_cnt@entry=0)
    at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/os/input.c:111
#5  0x000000000059d1d3 in state_enter (s=s@entry=0x7fff63484920) at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/state.c:49
#6  0x0000000000510eab in normal_enter (cmdwin=cmdwin@entry=false, noexmode=noexmode@entry=false)
    at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/normal.c:463
#7  0x00000000004e521a in main (argc=<optimized out>, argv=<optimized out>) at /home/florian/.cache/pacaur/neovim-git/src/neovim-git/src/nvim/main.c:543
```

If I can somehow reproduce this, I'll update..

**Comment by blueyed** [comment]
Let's close this for now, assuming it was fixed.
