### ISSUE TITLE
Segmentation fault using <afile> from python

### ISSUE THREAD

**Issue by hardenedapple** [neovim/neovim#5617]
- `nvim --version`:
```
NVIM 0.1.6
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.6/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```

- Vim (version: ) behaves differently?
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 30 2016 15:27:09)
Included patches: 1-55
Compiled by Arch Linux
...
```
Yes -- does not crash

- Operating system/version:
```
Linux hardenedapple_work 4.8.7-1-ARCH #1 SMP PREEMPT Thu Nov 10 17:22:48 CET 2016 x86_64 GNU/Linux
```

- Terminal name/version: `XTerm(327)`

- `$TERM`: `xterm-256color`

### Actual behaviour
Segmentation fault

```
$ coredumpctl gdb
           PID: 5513 (nvim)
           UID: 1000 (hardenedapple)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Wed 2016-11-16 11:07:17 GMT (6min ago)
  Command Line: nvim -N -u NONE --cmd source test.vim
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (hardenedapple)
       Boot ID: 57e34acd480d40c48f16baf705016eb4
    Machine ID: 6ed30f96bc5a4ab28c374490122bec58
      Hostname: apple_work
      Coredump: /var/lib/systemd/coredump/core.nvim.1000.57e34acd480d40c48f16baf705016eb4.5513.1479294437000000000000.lz4
       Message: Process 5513 (nvim) of user 1000 dumped core.

                Stack trace of thread 5513:
                #0  0x000000000050c368 n/a (nvim)
                #1  0x0000000000510a1f n/a (nvim)
                #2  0x0000000000510f78 n/a (nvim)
                #3  0x000000000051115d msg_putchar_attr (nvim)
                #4  0x00000000004bcb55 n/a (nvim)
                #5  0x00000000004c1e6d n/a (nvim)
                #6  0x00000000004b3390 do_cmdline (nvim)
                #7  0x00000000005268a3 n/a (nvim)
                #8  0x000000000052fcb9 n/a (nvim)
                #9  0x00000000005bc694 state_enter (nvim)
                #10 0x0000000000526e61 normal_enter (nvim)
                #11 0x000000000042cae6 main (nvim)
                #12 0x00007fd5342f9291 __libc_start_main (libc.so.6)
                #13 0x000000000042ddda _start (nvim)

                Stack trace of thread 5516:
                #0  0x00007fd5355ff10f pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fd5358278f9 uv_cond_wait (libuv.so.1)
                #2  0x00000000005d172b n/a (nvim)
                #3  0x00000000005d1e5a n/a (nvim)
                #4  0x0000000000497084 n/a (nvim)
                #5  0x0000000000497209 n/a (nvim)
                #6  0x00007fd5358252fd n/a (libuv.so.1)
                #7  0x00007fd535825c0c n/a (libuv.so.1)
                #8  0x00007fd53582a938 uv__io_poll (libuv.so.1)
                #9  0x00007fd53581c2b4 uv_run (libuv.so.1)
                #10 0x0000000000495a70 loop_poll_events (nvim)
                #11 0x00000000005d336c n/a (nvim)
                #12 0x00007fd5355f9454 start_thread (libpthread.so.0)
                #13 0x00007fd5343c17df __clone (libc.so.6)

GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/nvim...(no debugging symbols found)...done.
[New LWP 5513]
[New LWP 5516]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `nvim -N -u NONE --cmd source test.vim'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000050c368 in ?? ()
[Current thread is 1 (Thread 0x7fd535c1c780 (LWP 5513))]
(gdb)
```

### Expected behaviour
No segmentation fault.

### Steps to reproduce using `nvim -u NORC`

With the commands
```vimL
python3 << EOF
import vim
def autocmd_test():
  print(vim.eval('expand("<afile>:p")'))
  print(vim.eval('bufnr(expand("<afile>:p"))'))
EOF

autocmd BufUnload * python3 autocmd_test()
```
in the file `test.vim`

```
$ nvim -N -u NONE --cmd 'source test.vim'
:exe 'split ' . tempname()<CR>
:bw<CR>
:help press-enter<CR>
:
```

NOTE This isn't a stable bug -- it *almost* always happens with this series of
events on my machine.
Moreover, when sourcing my vimrc and plugins I get a segmentation fault with a
different backtrace after the do_cmdline function if I just run `:messages`
after wiping the first buffer, but this doesn't happen with `nvim -u NONE`.
With sourcing plugins etc I can still reproduce in the first way.

```
$ nvim --cmd 'source test.vim'
:exe 'split ' . tempname()<CR>
:bw<CR>
:messages<CR>
```

```
           PID: 8316 (nvim)
           UID: 1000 (hardenedapple)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Wed 2016-11-16 11:15:49 GMT (1min 10s ago)
  Command Line: nvim --cmd source test.vim
    Executable: /usr/bin/nvim
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (hardenedapple)
       Boot ID: 57e34acd480d40c48f16baf705016eb4
    Machine ID: 6ed30f96bc5a4ab28c374490122bec58
      Hostname: apple_work
      Coredump: /var/lib/systemd/coredump/core.nvim.1000.57e34acd480d40c48f16baf705016eb4.8316.1479294949000000000000.lz4
       Message: Process 8316 (nvim) of user 1000 dumped core.

                Stack trace of thread 8316:
                #0  0x00007f0d8c61d446 strlen (libc.so.6)
                #1  0x0000000000511520 msg_outtrans_attr (nvim)
                #2  0x0000000000512ded msg_attr_keep (nvim)
                #3  0x0000000000513303 ex_messages (nvim)
                #4  0x00000000004b4630 do_cmdline (nvim)
                #5  0x00000000005268a3 n/a (nvim)
                #6  0x000000000052fcb9 n/a (nvim)
                #7  0x00000000005bc694 state_enter (nvim)
                #8  0x0000000000526e61 normal_enter (nvim)
                #9  0x000000000042cae6 main (nvim)
                #10 0x00007f0d8c5bd291 __libc_start_main (libc.so.6)
                #11 0x000000000042ddda _start (nvim)

                Stack trace of thread 8385:
                #0  0x00007fff9e321b02 __vdso_clock_gettime (linux-vdso.so.1)
                #1  0x00007f0d8c6926b6 __clock_gettime (libc.so.6)
                #2  0x00007f0d8daee56c uv__hrtime (libuv.so.1)
                #3  0x00007f0d8dae01fc uv_run (libuv.so.1)
                #4  0x0000000000495a70 loop_poll_events (nvim)
                #5  0x00000000005d336c n/a (nvim)
                #6  0x00007f0d8d8bd454 start_thread (libpthread.so.0)
                #7  0x00007f0d8c6857df __clone (libc.so.6)

GNU gdb (GDB) 7.12
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/nvim...(no debugging symbols found)...done.
[New LWP 8316]
[New LWP 8385]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `nvim --cmd source test.vim'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f0d8c61d446 in strlen () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f0d8dee0780 (LWP 8316))]
(gdb) quit
```

Though it is less reliable, and takes more activity inside neovim, there is no
need to open a new file with `tempname()`. I can reproduce this by just viewing
multiple help files until a problem happens. I can also reproduce it by just
opening multiple files and calling `:bw` on them, but this takes much longer.
It also isn't necessary to have both lines in the `autocmd_test()` function: removing
either one still gives the error, but not as reliably or as quick.

It appears that the important element of this problem is using `"<afile>"` from
inside python code.
The two following versions of `test.vim` don't produce this problem:

```
python3 << EOF
import vim
def autocmd_test(filename):
  print(filename)
  print(vim.eval('bufnr("{}")'.format(filename)))
EOF

autocmd BufUnload * exe 'python3 autocmd_test("' . expand("<afile>:p") . '")'
```

```
function AutocmdTest()
  echomsg expand('<afile>:p')
  echomsg bufnr(expand('<afile>:p'))
endfunction

autocmd BufUnload * call AutocmdTest()
```

**Comment by justinmk** [comment]
This is a [classic Vim problem](https://groups.google.com/forum/#!searchin/vim_dev/BufUnload%7Csort:date) (e.g. most recent vim_dev report was [in September](https://groups.google.com/d/msg/vim_dev/Gao-PqyS6Tk/r8RX-Yr_CQAJ)). Usually Bram also mentions something like "we should have never allowed buffers to be deleted in BufUnload/BufDelete/etc...".

However we probably exacerbated it with remote plugins. I think it's just a matter of "clearing the queue" before deleting the buffer.
