### ISSUE TITLE
vim.feedkeys('', 'x') is broken using if_python/if_python3

### ISSUE THREAD

**Issue by Shougo** [neovim/neovim#5627]
- `nvim --version`: v0.2.0-411-gacbce46
- Vim (version: ) behaves differently?:  Vim has not feedkeys attribute
- Operating system/version: Manjaro Linux 4.7.10-1
- Terminal name/version: st 0.6
- `$TERM`: st-256color

### Actual behaviour
Segmentation Fault.

### Expected behaviour
No error.

### Steps to reproduce using `nvim -u NORC`

```
$ nvim -u NORC
:py3 import vim
:py3 vim.feedkeys('', 'x')
```

**Comment by jamessan** [comment]
```
/home/jamessan/src/github.com/neovim/src/nvim/getchar.c:3759:25: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:395:33: note: nonnull attribute specified here
    #0 0xcdf007 in vim_strsave_escape_csi /home/jamessan/src/github.com/neovim/src/nvim/getchar.c:3759:25
    #1 0x60fa1a in nvim_feedkeys /home/jamessan/src/github.com/neovim/src/nvim/api/vim.c:83:26
    #2 0x56583b in handle_nvim_feedkeys /home/jamessan/src/github.com/neovim/build/src/nvim/auto/api/private/dispatch_wrappers.generated.h:1720:3
    #3 0xf91463 in on_request_event /home/jamessan/src/github.com/neovim/src/nvim/msgpack_rpc/channel.c:455:19
    #4 0x9b7e4f in multiqueue_process_events /home/jamessan/src/github.com/neovim/src/nvim/event/multiqueue.c:143:7
    #5 0xf86838 in channel_send_call /home/jamessan/src/github.com/neovim/src/nvim/msgpack_rpc/channel.c:206:3
    #6 0x8b2aa4 in f_rpcrequest /home/jamessan/src/github.com/neovim/src/nvim/eval.c:13797:19
    #7 0x7a4271 in call_func /home/jamessan/src/github.com/neovim/src/nvim/eval.c:7004:11
    #8 0x7e3dbd in func_call /home/jamessan/src/github.com/neovim/src/nvim/eval.c:7836:9
    #9 0x8793ed in f_call /home/jamessan/src/github.com/neovim/src/nvim/eval.c:7877:9
    #10 0x7a4271 in call_func /home/jamessan/src/github.com/neovim/src/nvim/eval.c:7004:11
    #11 0x7b8294 in get_func_tv /home/jamessan/src/github.com/neovim/src/nvim/eval.c:6855:11
    #12 0x849e5c in eval7 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:4301:15
    #13 0x8458c5 in eval6 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:4022:7
    #14 0x842559 in eval5 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:3874:7
    #15 0x83dad1 in eval4 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:3626:7
    #16 0x83d073 in eval3 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:3548:7
    #17 0x83c613 in eval2 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:3485:7
    #18 0x79cc32 in eval1 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:3418:7
    #19 0x79b41c in eval0 /home/jamessan/src/github.com/neovim/src/nvim/eval.c:3380:9
    #20 0x81679c in ex_return /home/jamessan/src/github.com/neovim/src/nvim/eval.c:21065:10
    #21 0xab85b1 in do_one_cmd /home/jamessan/src/github.com/neovim/src/nvim/ex_docmd.c:2197:5
    #22 0xa97177 in do_cmdline /home/jamessan/src/github.com/neovim/src/nvim/ex_docmd.c:601:20
    #23 0x7ded20 in call_user_func /home/jamessan/src/github.com/neovim/src/nvim/eval.c:20867:3
    #24 0x7a3caa in call_func /home/jamessan/src/github.com/neovim/src/nvim/eval.c:6989:11
    #25 0x82a407 in eval_call_provider /home/jamessan/src/github.com/neovim/src/nvim/eval.c:22244:9
    #26 0xa5946e in script_host_execute /home/jamessan/src/github.com/neovim/src/nvim/ex_cmds2.c:3688:11
    #27 0xa5a1e1 in ex_python3 /home/jamessan/src/github.com/neovim/src/nvim/ex_cmds2.c:916:3
    #28 0xab85b1 in do_one_cmd /home/jamessan/src/github.com/neovim/src/nvim/ex_docmd.c:2197:5
    #29 0xa97177 in do_cmdline /home/jamessan/src/github.com/neovim/src/nvim/ex_docmd.c:601:20
    #30 0x102090b in nv_colon /home/jamessan/src/github.com/neovim/src/nvim/normal.c:4494:18
    #31 0x1008113 in normal_execute /home/jamessan/src/github.com/neovim/src/nvim/normal.c:1143:3
    #32 0x1674003 in state_enter /home/jamessan/src/github.com/neovim/src/nvim/state.c:58:26
    #33 0xfbdceb in normal_enter /home/jamessan/src/github.com/neovim/src/nvim/normal.c:463:3
    #34 0xd7ff62 in main /home/jamessan/src/github.com/neovim/src/nvim/main.c:542:3
    #35 0x7f1a4c1db2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #36 0x44b2d9 in _start (/home/jamessan/src/github.com/neovim/build/bin/nvim+0x44b2d9)

SUMMARY: AddressSanitizer: undefined-behavior /home/jamessan/src/github.com/neovim/src/nvim/getchar.c:3759:25 in
```

This change avoids the crash:

```diff
diff --git a/src/nvim/msgpack_rpc/helpers.c b/src/nvim/msgpack_rpc/helpers.c
index e9416f4..312842a 100644
--- a/src/nvim/msgpack_rpc/helpers.c
+++ b/src/nvim/msgpack_rpc/helpers.c
@@ -125,7 +125,7 @@ bool msgpack_rpc_to_object(const msgpack_object *const obj, Object *const arg)
         dest = conv(((String) { \
           .size = obj->via.attr.size, \
           .data = (obj->via.attr.ptr == NULL || obj->via.attr.size == 0 \
-                   ? NULL \
+                   ? xmemdupz("", 0) \
                    : xmemdupz(obj->via.attr.ptr, obj->via.attr.size)), \
         })); \
         break; \
```

If this looks right, I can open a PR.

**Comment by Shougo** [comment]
I have tested your fix and it works!
Could you open the PR?
