### ISSUE TITLE
Infinite loop, nvim seems stuck

### ISSUE THREAD

**Issue by teto** [neovim/neovim#5803]
- `nvim --version`: NVIM v0.2.0-150-g33319b1
- Vim (version: ) behaves differently?
- Operating system/version: Ubuntu 16.10
- Terminal name/version: termite

### Actual behaviour
Was editing a file then nvim stopped responding while system remains responsive. Hence I attached gdb, continued/C-c several times with nvim stuck in the same function:
```
Reading in symbols for ../src/nvim/eval.c...done.
Reading in symbols for ../src/nvim/ex_docmd.c...done.
Reading in symbols for ../src/nvim/buffer.c...done.
Reading in symbols for ../src/nvim/screen.c...done.
Reading in symbols for ../src/nvim/edit.c...done.
Reading in symbols for ../src/nvim/state.c...done.
Reading in symbols for ../src/nvim/normal.c...done.
#0  0x000055fb23348b18 in hash_lookup (ht=0x7f59f5c4d990, key=0x7ffe2fc35310 "typeinfo", hash=12566401773334778)
    at ../src/nvim/hashtab.c:137
#1  0x000055fb23348a24 in hash_find (ht=0x7f59f5c4d990, key=0x7ffe2fc35310 "typeinfo") at ../src/nvim/hashtab.c:85
#2  0x000055fb232ac924 in dict_find (d=0x7f59f5c4d980, key=0x7f59f5b6379c "typeinfo", len=8) at ../src/nvim/eval.c:6662
#3  0x000055fb232a874f in eval_index (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1, verbose=1) at ../src/nvim/eval.c:4660
#4  0x000055fb232c83f2 in handle_subscript (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1, verbose=1)
    at ../src/nvim/eval.c:18650
#5  0x000055fb232a7d71 in eval7 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1, want_string=0) at ../src/nvim/eval.c:4385
#6  0x000055fb232a7447 in eval6 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1, want_string=0) at ../src/nvim/eval.c:4070
#7  0x000055fb232a6f25 in eval5 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1) at ../src/nvim/eval.c:3922
#8  0x000055fb232a6191 in eval4 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1) at ../src/nvim/eval.c:3663
#9  0x000055fb232a5fba in eval3 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1) at ../src/nvim/eval.c:3585
#10 0x000055fb232a5e0f in eval2 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1) at ../src/nvim/eval.c:3522
#11 0x000055fb232a5c21 in eval1 (arg=0x7ffe2fc359f0, rettv=0x7ffe2fc35a50, evaluate=1) at ../src/nvim/eval.c:3455
#12 0x000055fb232a5b50 in eval0 (arg=0x7f59f5b63793 "fileinfo.typeinfo", rettv=0x7ffe2fc35a50, nextcmd=0x7ffe2fc35b68, evaluate=1)
    at ../src/nvim/eval.c:3417
#13 0x000055fb232a0e6e in ex_let (eap=0x7ffe2fc35b60) at ../src/nvim/eval.c:1479
#14 0x000055fb23300145 in do_one_cmd (cmdlinep=0x7ffe2fc35c80, flags=7, cstack=0x7ffe2fc35d90, 
    fgetline=0x55fb232d0bf2 <get_func_line>, cookie=0x7f59f62c0800) at ../src/nvim/ex_docmd.c:2198
#15 0x000055fb232fcb6b in do_cmdline (cmdline=0x0, fgetline=0x55fb232d0bf2 <get_func_line>, cookie=0x7f59f62c0800, flags=7)
    at ../src/nvim/ex_docmd.c:601
#16 0x000055fb232cffe1 in call_user_func (fp=0x7f59f5c29940, argcount=2, argvars=0x7ffe2fc368e0, rettv=0x7ffe2fc36f90, firstline=234, 
    lastline=234, selfdict=0x0) at ../src/nvim/eval.c:21579
#17 0x000055fb232adfb6 in call_func (funcname=0x7f59f5c87f8e "s:GetNearbyTag(0, 1)", len=14, rettv=0x7ffe2fc36f90, argcount_in=2, 
    argvars_in=0x7ffe2fc368e0, firstline=234, lastline=234, doesrange=0x7ffe2fc36a90, evaluate=true, partial=0x0, selfdict_in=0x0)
    at ../src/nvim/eval.c:7241
#18 0x000055fb232ad895 in get_func_tv (name=0x7f59f5c87f8e "s:GetNearbyTag(0, 1)", len=14, rettv=0x7ffe2fc36f90, arg=0x7ffe2fc36f30, 
    firstline=234, lastline=234, doesrange=0x7ffe2fc36a90, evaluate=1, partial=0x0, selfdict=0x0) at ../src/nvim/eval.c:7061
#19 0x000055fb232a7c96 in eval7 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1, want_string=0) at ../src/nvim/eval.c:4350
#20 0x000055fb232a7447 in eval6 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1, want_string=0) at ../src/nvim/eval.c:4070
#21 0x000055fb232a6f25 in eval5 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1) at ../src/nvim/eval.c:3922
#22 0x000055fb232a6191 in eval4 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1) at ../src/nvim/eval.c:3663
#23 0x000055fb232a5fba in eval3 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1) at ../src/nvim/eval.c:3585
#24 0x000055fb232a5e0f in eval2 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1) at ../src/nvim/eval.c:3522
#25 0x000055fb232a5c21 in eval1 (arg=0x7ffe2fc36f30, rettv=0x7ffe2fc36f90, evaluate=1) at ../src/nvim/eval.c:3455
#26 0x000055fb232a5b50 in eval0 (arg=0x7f59f5c87f8e "s:GetNearbyTag(0, 1)", rettv=0x7ffe2fc36f90, nextcmd=0x7ffe2fc370a8, evaluate=1)
    at ../src/nvim/eval.c:3417
#27 0x000055fb232a0e6e in ex_let (eap=0x7ffe2fc370a0) at ../src/nvim/eval.c:1479
#28 0x000055fb23300145 in do_one_cmd (cmdlinep=0x7ffe2fc371c0, flags=7, cstack=0x7ffe2fc372d0, 
    fgetline=0x55fb232d0bf2 <get_func_line>, cookie=0x7f59f62bfe00) at ../src/nvim/ex_docmd.c:2198
#29 0x000055fb232fcb6b in do_cmdline (cmdline=0x0, fgetline=0x55fb232d0bf2 <get_func_line>, cookie=0x7f59f62bfe00, flags=7)
    at ../src/nvim/ex_docmd.c:601
#30 0x000055fb232cffe1 in call_user_func (fp=0x7f59f5c0e500, argcount=3, argvars=0x7ffe2fc37e20, rettv=0x7ffe2fc384d0, firstline=234, 
    lastline=234, selfdict=0x0) at ../src/nvim/eval.c:21579
#31 0x000055fb232adfb6 in call_func (funcname=0x7f59f61d4a2d "tagbar#currenttag('%s', '', s:flags)", len=17, rettv=0x7ffe2fc384d0, 
    argcount_in=3, argvars_in=0x7ffe2fc37e20, firstline=234, lastline=234, doesrange=0x7ffe2fc37fd0, evaluate=true, partial=0x0, 
    selfdict_in=0x0) at ../src/nvim/eval.c:7241
#32 0x000055fb232ad895 in get_func_tv (name=0x7f59f61d4a2d "tagbar#currenttag('%s', '', s:flags)", len=17, rettv=0x7ffe2fc384d0, 
    arg=0x7ffe2fc38470, firstline=234, lastline=234, doesrange=0x7ffe2fc37fd0, evaluate=1, partial=0x0, selfdict=0x0)
    at ../src/nvim/eval.c:7061
#33 0x000055fb232a7c96 in eval7 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1, want_string=0) at ../src/nvim/eval.c:4350
#34 0x000055fb232a7447 in eval6 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1, want_string=0) at ../src/nvim/eval.c:4070
#35 0x000055fb232a6f25 in eval5 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1) at ../src/nvim/eval.c:3922
#36 0x000055fb232a6191 in eval4 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1) at ../src/nvim/eval.c:3663
#37 0x000055fb232a5fba in eval3 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1) at ../src/nvim/eval.c:3585
#38 0x000055fb232a5e0f in eval2 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1) at ../src/nvim/eval.c:3522
---Type <return> to continue, or q <return> to quit---
#39 0x000055fb232a5c21 in eval1 (arg=0x7ffe2fc38470, rettv=0x7ffe2fc384d0, evaluate=1) at ../src/nvim/eval.c:3455
#40 0x000055fb232a5b50 in eval0 (arg=0x7f59f61d4a2d "tagbar#currenttag('%s', '', s:flags)", rettv=0x7ffe2fc384d0, 
    nextcmd=0x7ffe2fc385e8, evaluate=1) at ../src/nvim/eval.c:3417
#41 0x000055fb232a0e6e in ex_let (eap=0x7ffe2fc385e0) at ../src/nvim/eval.c:1479
#42 0x000055fb23300145 in do_one_cmd (cmdlinep=0x7ffe2fc38700, flags=7, cstack=0x7ffe2fc38810, 
    fgetline=0x55fb232d0bf2 <get_func_line>, cookie=0x7f59f62bf400) at ../src/nvim/ex_docmd.c:2198
#43 0x000055fb232fcb6b in do_cmdline (cmdline=0x0, fgetline=0x55fb232d0bf2 <get_func_line>, cookie=0x7f59f62bf400, flags=7)
    at ../src/nvim/ex_docmd.c:601
#44 0x000055fb232cffe1 in call_user_func (fp=0x7f59f61e4340, argcount=0, argvars=0x7ffe2fc39360, rettv=0x7ffe2fc399e0, firstline=234, 
    lastline=234, selfdict=0x0) at ../src/nvim/eval.c:21579
#45 0x000055fb232adfb6 in call_func (funcname=0x7ffe2fc3bddd "airline#extensions#tagbar#currenttag(),0)", len=36, 
    rettv=0x7ffe2fc399e0, argcount_in=0, argvars_in=0x7ffe2fc39360, firstline=234, lastline=234, doesrange=0x7ffe2fc39510, 
    evaluate=true, partial=0x0, selfdict_in=0x0) at ../src/nvim/eval.c:7241
#46 0x000055fb232ad895 in get_func_tv (name=0x7ffe2fc3bddd "airline#extensions#tagbar#currenttag(),0)", len=36, rettv=0x7ffe2fc399e0, 
    arg=0x7ffe2fc399d8, firstline=234, lastline=234, doesrange=0x7ffe2fc39510, evaluate=1, partial=0x0, selfdict=0x0)
    at ../src/nvim/eval.c:7061
#47 0x000055fb232a7c96 in eval7 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1, want_string=0) at ../src/nvim/eval.c:4350
#48 0x000055fb232a7447 in eval6 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1, want_string=0) at ../src/nvim/eval.c:4070
#49 0x000055fb232a6f25 in eval5 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1) at ../src/nvim/eval.c:3922
#50 0x000055fb232a6191 in eval4 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1) at ../src/nvim/eval.c:3663
#51 0x000055fb232a5fba in eval3 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1) at ../src/nvim/eval.c:3585
#52 0x000055fb232a5e0f in eval2 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1) at ../src/nvim/eval.c:3522
#53 0x000055fb232a5c21 in eval1 (arg=0x7ffe2fc399d8, rettv=0x7ffe2fc399e0, evaluate=1) at ../src/nvim/eval.c:3455
#54 0x000055fb232ad7b1 in get_func_tv (name=0x7ffe2fc3bdc8 "airline#util#prepend(airline#extensions#tagbar#currenttag(),0)", len=20, 
    rettv=0x7ffe2fc3a080, arg=0x7ffe2fc3a030, firstline=234, lastline=234, doesrange=0x7ffe2fc39b90, evaluate=1, partial=0x0, 
    selfdict=0x0) at ../src/nvim/eval.c:7047
#55 0x000055fb232a7c96 in eval7 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1, want_string=0) at ../src/nvim/eval.c:4350
#56 0x000055fb232a7447 in eval6 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1, want_string=0) at ../src/nvim/eval.c:4070
#57 0x000055fb232a6f25 in eval5 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1) at ../src/nvim/eval.c:3922
#58 0x000055fb232a6191 in eval4 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1) at ../src/nvim/eval.c:3663
#59 0x000055fb232a5fba in eval3 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1) at ../src/nvim/eval.c:3585
#60 0x000055fb232a5e0f in eval2 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1) at ../src/nvim/eval.c:3522
#61 0x000055fb232a5c21 in eval1 (arg=0x7ffe2fc3a030, rettv=0x7ffe2fc3a080, evaluate=1) at ../src/nvim/eval.c:3455
#62 0x000055fb232a5b50 in eval0 (arg=0x7ffe2fc3bdc8 "airline#util#prepend(airline#extensions#tagbar#currenttag(),0)", 
    rettv=0x7ffe2fc3a080, nextcmd=0x7ffe2fc3a218, evaluate=1) at ../src/nvim/eval.c:3417
#63 0x000055fb2329fee6 in eval_to_string (arg=0x7ffe2fc3bdc8 "airline#util#prepend(airline#extensions#tagbar#currenttag(),0)", 
    nextcmd=0x7ffe2fc3a218, convert=0) at ../src/nvim/eval.c:1003
#64 0x000055fb232a0070 in eval_to_string_safe (arg=0x7ffe2fc3bdc8 "airline#util#prepend(airline#extensions#tagbar#currenttag(),0)", 
    nextcmd=0x7ffe2fc3a218, use_sandbox=0) at ../src/nvim/eval.c:1039
#65 0x000055fb2327ebe6 in build_stl_str_hl (wp=0x7f59f6a59000, 
    out=0x7ffe2fc3bd90 " INSERT  +0 ~0 -2 new_plots  mptcpanalyzer/data.py[+]   airline#util#prepend(airline#extensions#tagbar#currenttag(),0)", outlen=4096, fmt=0x7f59f5bc9ec0 "%!airline#statusline(1)", use_sandbox=0, fillchar=32, maxwidth=136, hltab=0x7ffe2fc3b110, 
    tabtab=0x7ffe2fc3b610) at ../src/nvim/buffer.c:3352
#66 0x000055fb2340ddde in win_redr_custom (wp=0x7f59f6a59000, draw_ruler=0) at ../src/nvim/screen.c:5136
#67 0x000055fb2340d7af in redraw_custom_statusline (wp=0x7f59f6a59000) at ../src/nvim/screen.c:4958
#68 0x000055fb2340d2d4 in win_redr_status (wp=0x7f59f6a59000) at ../src/nvim/screen.c:4855
#69 0x000055fb2340158d in update_screen (type=40) at ../src/nvim/screen.c:419
#70 0x000055fb2329029c in ins_redraw (ready=1) at ../src/nvim/edit.c:1389
#71 0x000055fb2328e931 in insert_check (state=0x7ffe2fc3cfa0) at ../src/nvim/edit.c:577
#72 0x000055fb23454c7c in state_enter (s=0x7ffe2fc3cfa0) at ../src/nvim/state.c:22
#73 0x000055fb2328e544 in insert_enter (s=0x7ffe2fc3cfa0) at ../src/nvim/edit.c:454
#74 0x000055fb23290074 in edit (cmdchar=111, startln=true, count=1) at ../src/nvim/edit.c:1328
#75 0x000055fb233a4689 in invoke_edit (cap=0x7ffe2fc3d1c0, repl=0, cmd=111, startln=1) at ../src/nvim/normal.c:7515
#76 0x000055fb233a365b in n_opencmd (cap=0x7ffe2fc3d1c0) at ../src/nvim/normal.c:6981
#77 0x000055fb233a5123 in nv_open (cap=0x7ffe2fc3d1c0) at ../src/nvim/normal.c:7806
#78 0x000055fb2339684d in normal_execute (state=0x7ffe2fc3d120, key=111) at ../src/nvim/normal.c:1143
#79 0x000055fb23454d4f in state_enter (s=0x7ffe2fc3d120) at ../src/nvim/state.c:58
#80 0x000055fb23394af7 in normal_enter (cmdwin=false, noexmode=false) at ../src/nvim/normal.c:463
#81 0x000055fb233587e4 in main (Reading in symbols for ../sysdeps/x86/libc-start.c...done.
argc=1, argv=0x7ffe2fc3d478) at ../src/nvim/main.c:542
```

### Expected behaviour
Responsive

### Steps to reproduce using `nvim -u NORC`
No idea (yet)
```
nvim -u NORC

```

**Comment by justinmk** [comment]
Looks like https://github.com/neovim/neovim/issues/5817
