### ISSUE TITLE
Segfault with SessionLoadPost au that wipes buffers

### ISSUE THREAD

**Issue by blankname** [neovim/neovim#6308]
- `nvim --version`:
 NVIM v0.2.0-842-gec4e84210
Build type: RelWithDebInfo

- Vim (version: ) behaves differently? Same crash, but outputs this message before crashing:
```
Vim: Caught deadly signal SEGV

Vim: Finished.
```
- Operating system/version: Linux 4.10.1-1-ARCH 
- Terminal name/version: Using Terminator 1.91 with fish shell
- `$TERM`: xterm-256color

### Actual behaviour
Segfaults

### Expected behaviour
Not segfaulting

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC hello
:w
:tabnew
:mksession
:qa
```
then using this init.vim:
```
set shada=
set noswapfile

function! DeleteInactiveBufs()
  exe 'tabfirst'
  let tabblist = []
  for i in range(1, tabpagenr('$'))
    " get errors when I have + 1 like docs show
    call extend(tabblist, tabpagebuflist(i))
  endfor

  for b in range(1, bufnr('$'))
    if bufexists(b) && buflisted(b) && (index(tabblist, b) == -1 || bufname(b) =~# '^$')
      exec 'bwipeout ' . b
    endif
  endfor
endfunction

au SessionLoadPost * call DeleteInactiveBufs()
```
run this:
```
nvim -u init.vim -S Session.vim --noplugin
```
The setting of no shada, noswapfile, and running with --noplugin aren't necessary to reproduce the crash.

bt:
```
#0  aucmd_restbuf (aco=aco@entry=0x7fffffffd4d0) at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/fileio.c:6491
#1  0x00000000004d5796 in ex_doautoall (eap=<optimized out>) at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/fileio.c:6333
#2  0x00000000004bc83f in do_one_cmd (cookie=0x7fffffffdd00, fgetline=0x4ae650 <getsourceline>, cstack=0x7fffffffd750, flags=7, cmdlinep=0x7fffffffd5f8)
    at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:2200
#3  do_cmdline (cmdline=cmdline@entry=0x7ffff5c15300 "let SessionLoad = 1", fgetline=fgetline@entry=0x4ae650 <getsourceline>, cookie=cookie@entry=0x7fffffffdd00, 
    flags=flags@entry=7) at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:602
#4  0x00000000004aec93 in do_source (fname=fname@entry=0x7ffff5dffeb3 "Session.vim", check_other=check_other@entry=0, is_vimrc=is_vimrc@entry=0)
    at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_cmds2.c:2918
#5  0x00000000004af65c in cmd_source (fname=0x7ffff5dffeb3 "Session.vim", eap=<optimized out>) at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_cmds2.c:2656
#6  0x00000000004bc83f in do_one_cmd (cookie=0x0, fgetline=0x0, cstack=0x7fffffffdfc0, flags=10, cmdlinep=0x7fffffffde68)
    at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:2200
#7  do_cmdline (cmdline=cmdline@entry=0x7ffff5c2f620 "so Session.vim", fgetline=fgetline@entry=0x0, cookie=cookie@entry=0x0, flags=flags@entry=10)
    at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:602
#8  0x00000000004bd75e in do_cmdline_cmd (cmd=cmd@entry=0x7ffff5c2f620 "so Session.vim") at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/ex_docmd.c:274
#9  0x000000000042cfc6 in exe_commands (parmp=0x7fffffffe560) at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/main.c:1611
#10 main (argc=<optimized out>, argv=<optimized out>) at /home/blank/misc/pacaur/neovim-git/src/neovim-git/src/nvim/main.c:498
```

**Comment by justinmk** [comment]
What version of vim did you test? Cc @chrisbra

**Comment by blankname** [comment]
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  6 2017 14:11:23)
Included patches: 1-427
Compiled by Arch Linux
```

**Comment by chrisbra** [comment]
please share Session.vim

**Comment by chrisbra** [comment]
It's usually a bad idea to kill buffers in an autocommand and has been source of many segfaults in the past. That does not mean we are not trying to fix it, but in general you shouldn't do that in an autocommand.

**Comment by blankname** [comment]
gist of the session: https://gist.github.com/blankname/f808af730136bbee9c435d2e1d15c056

**Comment by chrisbra** [comment]
fixed [upstream](https://github.com/vim/vim/releases/tag/v8.0.0486)
