### ISSUE TITLE
Crash after pressing <Tab> in command mode

### ISSUE THREAD

**Issue by bradst** [neovim/neovim#6650]
- `nvim --version`:
```
NVIM v0.2.1-7-g13ec52141
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -march=native -mtune=native -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/brad/neovim-git/build/config -I/home/brad/neovim-git/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/home/brad/neovim-git/build/src/nvim/auto -I/home/brad/neovim-git/build/include
Compiled by brad@desktop

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

```
- Vim (version: 8.0.0586) behaves differently? Issue not reproducible in Vim
- Operating system/version: Arch Linux
- Terminal name/version: Terminator (vte3)
- `$TERM`: `xterm-256color`

### Actual behaviour
Neovim suddenly exits/crashes after pressing `<Tab>` in command mode. (in certain conditions)

### Expected behaviour
Neovim should not suddenly exit/crash.

### Steps to reproduce using `nvim -u NORC`
The second line is a Neovim key sequence that always triggers the crash. The issue is also observed with `-u NONE -i NONE`.
```
nvim -u NORC
:j<Tab><Tab><Tab><BS><Tab>
```
There is no visible error, and launching Neovim with `-V999/tmp/nvim.log` does not show any errors or crash messages in the log file. The process exit code is `1`.

**Comment by bradst** [comment]
I was able to spot an error message, which is only visible for for a split second before Neovim terminates:

```
E41: Out of memory!
Vim: Finished.
```

**Comment by jamessan** [comment]
Can you get a [backtrace]?  I've tried the steps you listed and everything works fine locally.

Are you sure you can reproduce it when using `nvim -u NONE -i NONE`?

[backtrace]: https://github.com/neovim/neovim/wiki/Development-tips#backtrace-linux

**Comment by brcolow** [comment]
I can reproduce with `nvim -u NORC` specifically as mentioned in the issue with version:

```
NVIM v0.2.0-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/build/config -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/src -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/.deps/usr/include -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/.deps/usr/include -I/usr/include -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/build/src/nvim/auto -I/build/neovim-JuzSu6/neovim-0.1.7ubuntu1+git201704081626+3315+23~ubuntu16.04.1/build/include
Compiled by root@lcy01-05

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by bradst** [comment]
@jamessan Neovim doesn't actually segfault or produce a core dump. It seems to terminate "gracefully", even restoring the terminal state upon exit.

**Comment by jamessan** [comment]
Ah, I was misreading the reproduction steps.  I can reproduce it now.

The important part is to cycle through the completions until the command line is back to just `j`, _then_ backspace and tab.

```
==19952==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000003991 at pc 0x000000bf70c0 bp 0x7ffc373bd300 sp 0x7ffc373bd2f8
WRITE of size 1 at 0x602000003991 thread T0
    #0 0xbf70bf in addstar /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:3557:19
    #1 0xc2d9b2 in nextwild /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:2791:15
    #2 0xc1d44a in command_line_execute /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:775:18
    #3 0x16e6de3 in state_enter /home/jamessan/src/github.com/neovim/src/nvim/state.c:61:26
    #4 0xbdb25c in command_line_enter /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:275:3
    #5 0xbd5670 in getcmdline /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:1672:10
    #6 0xbde2b5 in getexline /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:1839:10
    #7 0xafe396 in do_cmdline /home/jamessan/src/github.com/neovim/src/nvim/ex_docmd.c:525:47
    #8 0x1080a9b in nv_colon /home/jamessan/src/github.com/neovim/src/nvim/normal.c:4498:18
    #9 0x10683ca in normal_execute /home/jamessan/src/github.com/neovim/src/nvim/normal.c:1137:3
    #10 0x16e6de3 in state_enter /home/jamessan/src/github.com/neovim/src/nvim/state.c:61:26
    #11 0x102037b in normal_enter /home/jamessan/src/github.com/neovim/src/nvim/normal.c:467:3
    #12 0xdf425a in main /home/jamessan/src/github.com/neovim/src/nvim/main.c:556:3
    #13 0x7fc193a992b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #14 0x44cf89 in _start (/home/jamessan/src/github.com/neovim/build/bin/nvim+0x44cf89)

0x602000003991 is located 0 bytes to the right of 1-byte region [0x602000003990,0x602000003991)
allocated by thread T0 here:
    #0 0x4eb548 in malloc (/home/jamessan/src/github.com/neovim/build/bin/nvim+0x4eb548)
    #1 0xf14224 in try_malloc /home/jamessan/src/github.com/neovim/src/nvim/memory.c:87:15
    #2 0xf143e4 in xmalloc /home/jamessan/src/github.com/neovim/src/nvim/memory.c:121:15
    #3 0xbf654e in addstar /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:3527:16
    #4 0xc2d9b2 in nextwild /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:2791:15
    #5 0xc1d44a in command_line_execute /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:775:18
    #6 0x16e6de3 in state_enter /home/jamessan/src/github.com/neovim/src/nvim/state.c:61:26
    #7 0xbdb25c in command_line_enter /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:275:3
    #8 0xbd5670 in getcmdline /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:1672:10
    #9 0xbde2b5 in getexline /home/jamessan/src/github.com/neovim/src/nvim/ex_getln.c:1839:10
    #10 0xafe396 in do_cmdline /home/jamessan/src/github.com/neovim/src/nvim/ex_docmd.c:525:47
    #11 0x1080a9b in nv_colon /home/jamessan/src/github.com/neovim/src/nvim/normal.c:4498:18
    #12 0x10683ca in normal_execute /home/jamessan/src/github.com/neovim/src/nvim/normal.c:1137:3
    #13 0x16e6de3 in state_enter /home/jamessan/src/github.com/neovim/src/nvim/state.c:61:26
    #14 0x102037b in normal_enter /home/jamessan/src/github.com/neovim/src/nvim/normal.c:467:3
    #15 0xdf425a in main /home/jamessan/src/github.com/neovim/src/nvim/main.c:556:3
    #16 0x7fc193a992b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
```
