### ISSUE TITLE
:CheckHealth Ruby error

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/neovim#6710]
- `nvim --version`:
```
NVIM v0.2.1-134-gd76a9582
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170510-4361-11t5qbq/build/config -I/tmp/neovim-20170510-4361-11t5qbq/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170510-4361-11t5qbq/build/src/nvim/auto -I/tmp/neovim-20170510-4361-11t5qbq/build/include
Compiled by ahmed@box.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-d76a958/share/nvim"
```
- Operating system/version: macOS Sierra 10.12.4
- Terminal name/version: iterm2 Build 3.1.20170427-nightly
- `$TERM`: 
`xterm-256color` in zsh
`tmux-256color` in tmux

### Actual behaviour

`:CheckHealth` output

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python"
  - INFO: Executable: /usr/local/bin/python
  - INFO: Python2 version: 2.7.13
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - ERROR: Command error (11) /usr/local/bin/neovim-ruby-host --version: /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib (LoadError)  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack.rb:11:in `rescue in <top (required)>'	from /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack.rb:8:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim/session/serializer.rb:2:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim/session.rb:5:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim.rb:4:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim/host.rb:1:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/bin/neovim-ruby-host:3:in `<top (required)>'	from /usr/local/bin/neovim-ruby-host:22:in `load'	from /usr/local/bin/neovim-ruby-host:22:in `<main>'
  - ERROR: Failed to run: /usr/local/bin/neovim-ruby-host --version
    - SUGGESTIONS:
      - Report this issue with the output of: 
      - /usr/local/bin/neovim-ruby-host --version
```

`/usr/local/bin/neovim-ruby-host --version` output

```
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle
  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack.rb:11:in `rescue in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack.rb:8:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim/session/serializer.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim/session.rb:5:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim.rb:4:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/lib/neovim/host.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.4.0/bin/neovim-ruby-host:3:in `<top (required)>'
	from /usr/local/bin/neovim-ruby-host:22:in `load'
	from /usr/local/bin/neovim-ruby-host:22:in `<main>'
```

### Expected behaviour

No errors

### Steps to reproduce using `nvim -u NORC`

`nvim -u NORC` & then `:CheckHealth`

---

I removed the `gem` & installed it again but this didn't fix the problem.

**Comment by justinmk** [comment]
> Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib

That's a env issue. Update `gem` or ruby or whatever.

**Comment by ahmedelgabri** [comment]
@justinmk I have the latest Homebrew, Ruby (from Homebrew) & RubyGems. Still not working

**Comment by ahmedelgabri** [comment]
I had to update `msgpack` itself

**Comment by justinmk** [comment]
Hmm, maybe neovim-ruby needs to declare a specific version dependency of its msgpack lib? cc @alexgenco

**Comment by alexgenco** [comment]
It declares msgpack ~> 1.0 https://github.com/alexgenco/neovim-ruby/blob/master/neovim.gemspec#L20. I just installed msgpack 1.0.2 (which looks like the version you had) and didn't see any problems. What version of msgpack are you on now that it's working?

**Comment by ahmedelgabri** [comment]
I have msgpack (1.1.0)

**Comment by alexgenco** [comment]
Is this possibly the same issue as https://github.com/Homebrew/homebrew-core/issues/11636

**Comment by lyc2345** [comment]
I do ```gem install msgpack``` solve my problem
