### ISSUE TITLE
Error detected while processing function <SNR>107_PollServerReady[

### ISSUE THREAD

**Issue by greencopper** [neovim/neovim#6840]
nvim version:

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
```

Vim (version: ) behaves differently? I don't use Vim.

Operating system/version: Arch Linux

Terminal name/version: xterm-256color

When I am editing bash scripts and exits the script, the following error occurs:

```
Error detected while processing function <SNR>107_PollServerReady[1]..<SNR>107_Pyeval[2]..provider#python3#Call:
line   18:
Invalid channel: 1
Error detected while processing function <SNR>107_PollFileParseResponse[1]..<SNR>107_Pyeval[2]..provider#python3#Call:
line   18:
Invalid channel: 1
```

List of plugins:

```
Finished. 0 error(s). 
[===================]

- phpcomplete.vim: OK
- vim_pygments_colorscheme: OK
- YouCompleteMe: OK
- vim-snippets: OK
- Zenburn: OK
- github-theme: OK
- vim-aldmeris: OK
- vim-phpfmt: OK
- pw: OK
- nerdtree: OK
- vim-colors-codeschool: OK
- vim-bufkill: OK
- ultisnips: OK
- supertab: OK
- tcomment_vim: OK
- vim-go: OK
- syntastic: OK
- vim-signature: OK
- vim-airline: OK
```

**Comment by manipnip** [comment]
YouCompleteMe is the culprit...From what I was told it has to do with timers that was introduced in this pull request 

https://github.com/Valloric/YouCompleteMe/issues/2636

**Comment by Shougo** [comment]
The python process is crashed.
You can get the crash log by below.

```
$ export NVIM_PYTHON_LOG_FILE=/tmp/log
$ export NVIM_PYTHON_LOG_LEVEL=DEBUG
$ nvim
do something
```

**Comment by micbou** [comment]
Stopping the timers on the `VimLeave` event seems to fix that issue. However, wouldn't it make sense for Neovim to automatically stop them before terminating the python process at exit?

**Comment by timfeirg** [comment]
same issue here, got the python crash log like you said:

```
2018-03-13 16:29:33,055 [DEBUG @ session.py:response_cb:153] 58788 - response is available for greenlet <greenlet.greenlet object at 0x10adff3d8>, switching back
2018-03-13 16:29:33,055 [WARNING @ async_session.py:_on_message:83] 58788 - Traceback (most recent call last):
  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 80, in _on_message
    self._handlers.get(msg[0], self._on_invalid_message)(msg)
  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 101, in _on_response
    self._pending_requests.pop(msg[1])(msg[2], msg[3])
  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 154, in response_cb
    gr.switch(err, rv)
greenlet.error: cannot switch to a different thread

2018-03-13 16:29:33,055 [DEBUG @ msgpack_stream.py:send:34] 58788 - sent [1, 0, 'Traceback (most recent call last):\n  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 80, in _on_message\n    self._handlers.get(msg[0], self._on_invalid_message)(msg)\n  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 101, in _on_response\n    self._pending_requests.pop(msg[1])(msg[2], msg[3])\n  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 154, in response_cb\n    gr.switch(err, rv)\ngreenlet.error: cannot switch to a different thread\n', None]
2018-03-13 16:29:33,055 [DEBUG @ base.py:send:117] 58788 - Sending 'b'\x94\x01\x00\xda\x02uTraceback (most recent call last):\n  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 80, in _on_message\n    self._handlers.get(msg[0], self._on_invalid_message)(msg)\n  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 101, in _on_response\n    self._pending_requests.pop(msg[1])(msg[2], msg[3])\n  File "/Users/timfeirg/.virtualenvs/citadel/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 154, in response_cb\n    gr.switch(err, rv)\ngreenlet.error: cannot switch to a different thread\n\xc0''
2018-03-13 16:29:33,055 [DEBUG @ msgpack_stream.py:_on_data:59] 58788 - waiting for message...
2018-03-13 16:29:33,055 [DEBUG @ msgpack_stream.py:_on_data:64] 58788 - unpacker needs more data...
2018-03-13 16:29:33,055 [DEBUG @ base.py:_on_error:175] 58788 - 32
2018-03-13 16:29:33,055 [DEBUG @ base.py:stop:153] 58788 - Stopped event loop
2018-03-13 16:29:33,056 [DEBUG @ base.py:run:144] 58788 - Exited event loop
```

@Shougo

**Comment by Shougo** [comment]
Hm.  It seems greenlet error.
