### ISSUE TITLE
Broken shada files can cause assertion error

### ISSUE THREAD

**Issue by languitar** [neovim/neovim#6957]
- `nvim --version`:
```
NVIM v0.2.0-303-gb674fd2c
Build type: Debug
Compilation: /usr/bin/afl-gcc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/home/languitar/src/neovim/build/config -I/home/languitar/src/neovim/src -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/home/languitar/src/neovim/.deps/usr/include -I/usr/include -I/home/languitar/src/neovim/build/src/nvim/auto -I/home/languitar/src/neovim/build/include
Compiled by languitar@jaco

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim
```
- Operating system/version: archlinux 64
- Terminal name/version: termite
- `$TERM`:  xterm-termite

### Actual behaviour

I have fuzzed neovim for issues regarding the shada files. One thing that I have found is that an assertion error can be triggered with a broken file. I would expect that a usual warning is raised instead of an assertion error (which might be skipped for release builds).

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC -i ./fuzzer02/crashes/id:000005,sig:06,src:000503+000235,op:splice,rep:16 -Z -R
```

This file (with broken extension due to github) is attached.
[id:000005,sig:06,src:000503+000235,op:splice,rep:16.txt](https://github.com/neovim/neovim/files/1121917/id.000005.sig.06.src.000503.000235.op.splice.rep.16.txt)

Will result in:

```
/home/languitar/src/neovim/src/nvim/shada.c:738: sd_reader_skip_read: Assertion `skip_bytes < (ptrdiff_t)offset' failed.
fish: “~/src/neovim/build/bin/nvim -u…” terminated by signal SIGABRT (Abort)
```

```
#0  0x00007ffff6d10670 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6d11d00 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6d0945a in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff6d094d2 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000000000d82c85 in sd_reader_skip_read (sd_reader=0x7fffffffdd10, offset=14920435247833816829) at /home/languitar/src/neovim/src/nvim/shada.c:738
#5  0x0000000000d8a9e2 in sd_reader_skip (offset=14920435247833816829, sd_reader=0x7fffffffdd10) at /home/languitar/src/neovim/src/nvim/shada.c:762
#6  shada_read_next_item (sd_reader=sd_reader@entry=0x7fffffffdd10, entry=entry@entry=0x7fffffffd8f0, flags=flags@entry=3580, max_kbyte=max_kbyte@entry=0) at /home/languitar/src/neovim/src/nvim/shada.c:3536
#7  0x0000000000d924b0 in shada_read (sd_reader=sd_reader@entry=0x7fffffffdd10, flags=flags@entry=11) at /home/languitar/src/neovim/src/nvim/shada.c:1226
#8  0x0000000000db4436 in shada_read_file (flags=<optimized out>, file=0x0) at /home/languitar/src/neovim/src/nvim/shada.c:904
#9  shada_read_everything (fname=fname@entry=0x0, forceit=forceit@entry=false, missing_ok=missing_ok@entry=true) at /home/languitar/src/neovim/src/nvim/shada.c:3098
#10 0x000000000043d0de in main (argc=<optimized out>, argv=<optimized out>) at /home/languitar/src/neovim/src/nvim/main.c:387
```

**Comment by ZyX-I** [comment]
The assertion error indicates a bug in `file_skip`: if it was requested to skip X bytes, it should skip no more then X bytes. Most likely this has something to do with overflow.

**Comment by ZyX-I** [comment]
Yes, `(ptrdiff_t)offset` in your constructed file yields negative value. Need to cast `skip_bytes` instead (which is still somewhat incorrect, except that you will need incredibly large file to trigger the error after moving the cast).
