### ISSUE TITLE
win: python: "OSError: [WinError 6] The handle is invalid"

### ISSUE THREAD

**Issue by duytrung** [neovim/neovim#7326]
- `nvim --version`: 0.2.1
- Vim (version: ) behaves differently? Yes
- Operating system/version: Windows 10
- Terminal name/version: CMD
- `$TERM`:
```
nvim learnpy.py
function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):^M
  File "<string>", line 1, in <module>^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\__init__.py", line 70, in start_host^M
    session = stdio_session()^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 37, in stdio_session^M
    return session('stdio')^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 18, in session^M
    loop = EventLoop(transport_type, *args, **kwargs)^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 88, in __init__^M
    getattr(self, '_connect_{}'.format(transport_type))(*args)^M
  File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 93, in _connect_stdio^M
    self._loop.run_until_complete(coroutine)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 467, in run_until_complete^M
    return future.result()^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 1115, in connect_write_pipe^M
    transport = self._make_write_pipe_transport(pipe, protocol, waiter)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 424, in _make_write_pipe_transport^M
    sock, protocol, waiter, extra)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 317, in __init__^M
    self._read_fut = self._loop._proactor.recv(self._sock, 16)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\windows_events.py", line 430, in recv^M
    self._register_with_iocp(conn)^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\windows_events.py", line 611, in _register_with_iocp^M
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)^M
OSError: [WinError 6] The handle is invalid^M
Exception ignored in: <bound method _ProactorBasePipeTransport.__del__ of <_ProactorWritePipeTransport closing fd=1>>^M
Traceback (most recent call last):^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 97, in __del__^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\proactor_events.py", line 84, in close^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 574, in call_soon^M
  File "C:\MyPrograms\Anaconda\lib\asyncio\base_events.py", line 357, in _check_closed^M
RuntimeError: Event loop is closed^M
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the
 generated log file. Also, the host stderr is available in messages.
Press ENTER or type command to continue

```
### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC

```

### Actual behaviour
nvim just stop, and display the message: "Press ENTER or type command to continue"
### Expected behaviour

nVim should run, with a message saying that the plugin has caused error and it will not be loaded.

**Comment by Shougo** [comment]
You should upload the log file.

```

    export NVIM_PYTHON_LOG_FILE=/tmp/log
    export NVIM_PYTHON_LOG_LEVEL=DEBUG
    nvim -u minimal.vimrc
    some works
    cat /tmp/log_{PID}
```

**Comment by justinmk** [comment]
@duytrung did you try `:CheckHealth` ? 

> nVim should run, with a message saying that the plugin has caused error and it will not be loaded

I'll interpret this as a request for "message UX". I plan to revisit https://github.com/neovim/neovim/pull/1802 in the next couple months for this purpose.

**Comment by duytrung** [comment]
Here is the results:
```
> nvim -u minimal.vimrc
E282: Cannot read from "minimal.vimrc"
Press ENTER or type command to continue
```

Log in nvim-data:
```
2017/09/06 12:29:37 INFO  22788/wmain:564: starting main loop
2017/09/06 12:42:27 INFO  18480/wmain:564: starting main loop
2017/09/06 12:43:27 INFO  21436/wmain:564: starting main loop
2017/09/06 12:45:55 INFO  2012/wmain:564: starting main loop
2017/09/06 12:51:39 INFO  16000/wmain:564: starting main loop
2017/09/06 12:54:02 INFO  5456/wmain:564: starting main loop
2017/09/06 12:55:29 INFO  6044/wmain:564: starting main loop
2017/09/06 13:03:32 INFO  22568/wmain:564: starting main loop
2017/09/06 13:04:17 INFO  19696/wmain:564: starting main loop
2017/09/06 13:05:32 INFO  7808/wmain:564: starting main loop
2017/09/06 13:07:45 INFO  5128/wmain:564: starting main loop
2017/09/06 13:09:11 INFO  15824/wmain:564: starting main loop
2017/09/06 13:09:59 INFO  14676/wmain:564: starting main loop
2017/09/06 13:12:11 INFO  15952/wmain:564: starting main loop
2017/09/06 13:12:53 INFO  21124/wmain:564: starting main loop
2017/09/06 13:14:14 INFO  15424/wmain:564: starting main loop
2017/09/06 14:23:24 INFO  24536/wmain:564: starting main loop
2017/09/06 14:24:34 INFO  10248/wmain:564: starting main loop
2017/09/06 14:25:00 INFO  15860/wmain:564: starting main loop
2017/09/06 14:41:41 INFO  3552/wmain:564: starting main loop
2017/09/06 14:44:42 INFO  17112/wmain:564: starting main loop
2017/09/06 14:45:00 INFO  8292/wmain:564: starting main loop
2017/09/18 19:23:42 INFO  9772 wmain:564: starting main loop
2017/09/18 19:33:57 INFO  9772 process_stop:238: Sending SIGTERM to pid 1548
2017/09/18 19:33:57 INFO  9772 process_stop:254: Starting job kill timer
2017/09/18 19:34:01 INFO  9772 register_channel:826: new channel 119 (proc): function youcompleteme#Enable[5]..<SNR>139_SetUpPython[39]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/18 19:51:40 INFO  10396 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/18 19:51:44 WARN  10396 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/18 20:42:33 INFO  18300 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/18 20:42:33 WARN  18300 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/18 20:42:34 INFO  18300 wmain:564: starting main loop
2017/09/18 20:44:45 INFO  19112 register_channel:826: new channel 1 (proc): function jedi#init_python[3]..<SNR>168_init_python[50]..jedi#setup_py_version[23]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/18 20:44:45 WARN  19112 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/18 20:44:46 INFO  19112 wmain:564: starting main loop
2017/09/18 21:29:38 INFO  14688 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/18 21:29:38 WARN  14688 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/18 21:29:38 INFO  14688 wmain:564: starting main loop
2017/09/18 21:48:22 INFO  21056 register_channel:826: new channel 1 (proc): function jedi#init_python[3]..<SNR>170_init_python[50]..jedi#setup_py_version[23]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/18 21:48:22 WARN  21056 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/18 21:48:23 INFO  21056 wmain:564: starting main loop
2017/09/19 18:51:02 INFO  2512 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/19 18:51:13 WARN  2512 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/19 18:51:13 INFO  2512 wmain:564: starting main loop
2017/09/24 19:00:27 INFO  8756 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:00:34 WARN  8756 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/24 19:00:34 INFO  8756 wmain:564: starting main loop
2017/09/24 19:01:13 INFO  11724 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:01:13 WARN  11724 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/24 19:01:14 INFO  11724 wmain:564: starting main loop
2017/09/24 19:03:28 INFO  18696 register_channel:826: new channel 1 (stdio): ?
2017/09/24 19:03:30 INFO  18696 register_channel:826: new channel 2 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:03:30 WARN  18696 call_set_error:864: RPC: ch 2 was closed by the client
2017/09/24 19:03:31 INFO  18696 wmain:564: starting main loop
2017/09/24 19:15:35 WARN  18364 server_start:154: Failed to start server: address already in use
2017/09/24 19:15:35 INFO  18364 register_channel:826: new channel 1 (stdio): ?
2017/09/24 19:15:38 INFO  18364 register_channel:826: new channel 2 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:15:38 WARN  18364 call_set_error:864: RPC: ch 2 was closed by the client
2017/09/24 19:15:48 WARN  6136 server_start:154: Failed to start server: address already in use
2017/09/24 19:15:48 INFO  6136 register_channel:826: new channel 1 (stdio): ?
2017/09/24 19:15:50 INFO  6136 register_channel:826: new channel 2 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:15:51 WARN  6136 call_set_error:864: RPC: ch 2 was closed by the client
2017/09/24 19:16:05 WARN  18592 server_start:154: Failed to start server: address already in use
2017/09/24 19:16:05 INFO  18592 register_channel:826: new channel 1 (stdio): ?
2017/09/24 19:16:06 WARN  18364 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/24 19:16:06 WARN  6136 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/24 19:16:06 ERROR 18592 call_set_error:864: RPC: ch 1: stream write failed. RPC canceled; closing channel
2017/09/24 19:16:06 INFO  6136 register_channel:826: new channel 3 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[22]..<SNR>124_startup[2]..cm#_auto_enable_check[6]..cm#enable_for_buffer[48]..<SNR>197_start_core_channel[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:16:06 INFO  18364 register_channel:826: new channel 3 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require[22]..<SNR>124_startup[2]..cm#_auto_enable_check[6]..cm#enable_for_buffer[48]..<SNR>197_start_core_channel[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:16:06 WARN  18364 call_set_error:864: RPC: ch 3 was closed by the client
2017/09/24 19:16:06 WARN  6136 call_set_error:864: RPC: ch 3 was closed by the client
2017/09/24 19:16:06 INFO  18364 process_stop:238: Sending SIGTERM to pid 19032
2017/09/24 19:16:06 INFO  6136 process_stop:238: Sending SIGTERM to pid 19336
2017/09/24 19:16:06 INFO  18364 process_stop:254: Starting job kill timer
2017/09/24 19:16:06 INFO  6136 process_stop:254: Starting job kill timer
2017/09/24 19:16:26 WARN  18932 server_start:154: Failed to start server: address already in use
2017/09/24 19:16:28 INFO  18932 register_channel:826: new channel 1 (proc): function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/24 19:16:29 WARN  18932 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/24 19:16:29 INFO  18932 wmain:564: starting main loop
2017/09/27 16:06:25 INFO  1864 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/27 16:06:28 WARN  1864 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/27 16:08:38 INFO  1800 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/27 16:08:39 WARN  1800 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/27 18:14:26 INFO  6772 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/27 18:14:28 WARN  6772 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/27 21:18:49 INFO  13852 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/27 21:18:49 WARN  13852 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/27 21:22:23 INFO  11032 wmain:564: starting main loop
2017/09/27 21:25:57 INFO  12904 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/27 21:25:57 WARN  12904 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/27 21:26:10 INFO  10504 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/27 21:26:11 WARN  10504 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/28 22:02:45 INFO  10876 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/28 22:02:48 WARN  10876 call_set_error:864: RPC: ch 1 was closed by the client
2017/09/28 22:04:19 INFO  3008 register_channel:826: new channel 1 (proc): function <SNR>139_Initialize[10]..provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require:14
2017/09/28 22:04:20 WARN  3008 call_set_error:864: RPC: ch 1 was closed by the client
```
> nvim -u NORC

```
![image](https://user-images.githubusercontent.com/2046672/30966953-dba68454-a499-11e7-8ea6-3137459b8a3b.png)


Regards

**Comment by justinmk** [comment]
@duytrung Did I interpret your original request correctly? There's no need to post any debugging results, the problem is obvious: you need the neovim python module if you want to use python-based plugins.

**Comment by erw7** [comment]
I do not know how you installed pyuv, so it's not clear, but is pyuv not working? Especially you are using Anaconda. In that case, I think that there is a high possibility that it will not work, if binary is installed from PyPI using pip.

If you installed pyuv from the source code, I think that it will probably work. However, I do not recommend it because it seems that it is much easier to use python distributed on python.org.

**Comment by justinmk** [comment]
@erw7 I also wonder about the anaconda stuff.

> if binary is installed from PyPI using pip.

What are you referring to? IIUC it looks like the neovim module was installed with conda:

    File "C:\MyPrograms\Anaconda\lib\site-packages\neovim\__init__.py", line 70, in start_host^M

**Comment by erw7** [comment]
I am sorry to write inaccuracies guess. I thought that it would be installed in `site-packages(sysconfig.get_python_lib()?)` regardless of the installation method, but can you guess the installation method from the installation location?

I checked the package of pyyv of anaconda,  where python36.dll was linked to _cpyuv.cp36-win_amd64.pyd. Therefore, I think that even installed using pip will work.

I think that the cause of this problem is that pyuv does not work for some reason, so here it is not an appropriate place to discuss the cause.

**Comment by bfredl** [comment]
conda and pip are not mutually exclusive, one can install `pip` packages into a conda environment just fine, when conda doesn't have the package or when the conda binary package has issues.
