### ISSUE TITLE
Segfault on put with vim-peekaboo, under certain conditions

### ISSUE THREAD

**Issue by gleachkr** [neovim/neovim#7538]
- `nvim --version`:

```
NVIM v0.2.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
     fall-back for $VIM: "/usr/share/nvim"

     Run :checkhealth for more info
```

- Vim (version: ) behaves differently?

N/A

- Operating system/version:

Arch Linux, Kernel 4.13.11-1

- Terminal name/version:
- `$TERM`: rxvt-unicode-256color

### Actual behaviour

A segfault occurs in when taking the following steps with https://github.com/junegunn/vim-peekaboo:

1. open nvim, using peekaboo as a plugin.
2. open a split
3. `:terminal` in the upper split
4. `""p` to put into the lower split (works with any register)

Here's the stacktrace:

```
#0  0x00005555556e98ef in signcolumn_on ()
#1  0x00005555556b832c in win_col_off ()
#2  0x0000555555784c83 in win_new_width ()
#3  0x0000555555784ec1 in ?? ()
#4  0x0000555555784e1f in ?? ()
#5  0x0000555555785b19 in winframe_remove ()
#6  0x000055555578aa7a in ?? ()
#7  0x000055555578b4d4 in win_close ()
#8  0x00005555555d299a in do_buffer ()
#9  0x00005555555d306a in do_bufdel ()
#10 0x0000555555641fa6 in ?? ()
#11 0x000055555564aec4 in do_cmdline ()
#12 0x0000555555611197 in ex_execute ()
#13 0x000055555564aec4 in do_cmdline ()
#14 0x0000555555608274 in call_user_func ()
#15 0x0000555555608c8c in call_func ()
#16 0x000055555560de38 in ?? ()
#17 0x000055555561295a in ex_call ()
#18 0x000055555564aec4 in do_cmdline ()
#19 0x0000555555608274 in call_user_func ()
#20 0x0000555555608c8c in call_func ()
#21 0x000055555560de38 in ?? ()
#22 0x000055555561295a in ex_call ()
#23 0x000055555564aec4 in do_cmdline ()
#24 0x00005555556c4928 in ?? ()
#25 0x00005555556cde88 in ?? ()
#26 0x000055555575ca56 in state_enter ()
#27 0x00005555556c52da in normal_enter ()
#28 0x00005555555aefba in main ()
```

### Expected behaviour

no segfault.

**Comment by justinmk** [comment]
Thanks, repro'd. Caused by #5310. Can't take anything for granted with buffers and windows, can we ...
