### ISSUE TITLE
Segfault when resizing terminal to small sizes

### ISSUE THREAD

**Issue by apsun** [neovim/neovim#7628]
- `nvim --version`: 0.2.3-24-gd9b3ebfed (also tested on 0.2.2 release)
- Vim (version: ) behaves differently? Yes
- Operating system/version: Arch Linux, Xfce 4.12
- Terminal name/version: Terminator 1.91
- `$TERM`: xterm-256color

### Steps to reproduce using `nvim -u NORC`

See below

### Actual behaviour

Neovim crashes with a segmentation fault

### Expected behaviour

No crash

---

First one occurs when changing the width of the terminal to less than 5 *columns*. Crashes in `ugrid_put`, caused by an out-of-bounds access on `grid->cells[grid->row]` (when `grid->row == grid->height`). 

```
Thread 2 "nvim" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fcbb55ff700 (LWP 21095)]
0x000055e9421b6168 in ugrid_put (grid=0x7fcbb4a248e8, text=0x7fcbb5c24b38 " ", size=1) at /home/andrew/Desktop/neovim/src/nvim/ugrid.c:108
108	  cell->data[size] = 0;
(gdb) bt
#0  0x000055e9421b6168 in ugrid_put (grid=0x7fcbb4a248e8, text=0x7fcbb5c24b38 " ", size=1) at /home/andrew/Desktop/neovim/src/nvim/ugrid.c:108
#1  0x000055e9421b3a2e in tui_put (ui=0x7fcbb5cd7300, text=...) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:965
#2  0x000055e9421ba843 in ui_bridge_put_event (argv=0x7fcbb55fe7b8) at /home/andrew/Desktop/neovim/build/src/nvim/auto/ui_events_bridge.generated.h:141
#3  0x000055e942000d4c in multiqueue_process_events (this=0x7fcbb4a10030) at /home/andrew/Desktop/neovim/src/nvim/event/multiqueue.c:150
#4  0x000055e94200046e in loop_poll_events (loop=0x7fcbb55fe850, ms=-1) at /home/andrew/Desktop/neovim/src/nvim/event/loop.c:59
#5  0x000055e9421b1b79 in tui_main (bridge=0x7fcbb5c29080, ui=0x7fcbb5cd7300) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:329
#6  0x000055e9421bb42d in ui_thread_run (data=0x7fcbb5c29080) at /home/andrew/Desktop/neovim/src/nvim/ui_bridge.c:104
#7  0x00007fcbb70f108a in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fcbb62a647f in clone () from /usr/lib/libc.so.6
```

Second one happens when resizing the terminal to one *row*, then resizing to one *column* (interestingly, making the height very small avoids the first crash), then increasing the number of *rows* to 4. Crash happens in `cheap_to_print`, also caused by OOB access when `grid->row == grid->height`:

```
Thread 2 "nvim" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f6eb53ff700 (LWP 21048)]
0x0000560759804366 in cheap_to_print (ui=0x7f6eb5ad7300, row=4, col=1, next=1) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:489
489	    if (attrs_differ(cell->attrs, data->print_attrs)) {
(gdb) bt
#0  0x0000560759804366 in cheap_to_print (ui=0x7f6eb5ad7300, row=4, col=1, next=1) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:489
#1  0x0000560759804594 in cursor_goto (ui=0x7f6eb5ad7300, row=3, col=3) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:535
#2  0x0000560759804a9c in clear_region (ui=0x7f6eb5ad7300, top=0, bot=3, left=0, right=11) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:646
#3  0x0000560759804f6a in tui_clear (ui=0x7f6eb5ad7300) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:743
#4  0x000056075980bcae in ui_bridge_clear_event (argv=0x7f6eb53fe7b8) at /home/andrew/Desktop/neovim/build/src/nvim/auto/ui_events_bridge.generated.h:14
#5  0x0000560759652d4c in multiqueue_process_events (this=0x7f6eb4810030) at /home/andrew/Desktop/neovim/src/nvim/event/multiqueue.c:150
#6  0x000056075965246e in loop_poll_events (loop=0x7f6eb53fe850, ms=-1) at /home/andrew/Desktop/neovim/src/nvim/event/loop.c:59
#7  0x0000560759803b79 in tui_main (bridge=0x7f6eb5a29080, ui=0x7f6eb5ad7300) at /home/andrew/Desktop/neovim/src/nvim/tui/tui.c:329
#8  0x000056075980d42d in ui_thread_run (data=0x7f6eb5a29080) at /home/andrew/Desktop/neovim/src/nvim/ui_bridge.c:104
#9  0x00007f6eb6ed708a in start_thread () from /usr/lib/libpthread.so.0
#10 0x00007f6eb608c47f in clone () from /usr/lib/libc.so.6
```

**Comment by oni-link** [comment]
Can you try the first patch in https://github.com/neovim/neovim/issues/7572#issuecomment-345257295 and check if that fixes the problem?

**Comment by apsun** [comment]
Yep, looks like that did the trick!
