### ISSUE TITLE
Netrw directory browsing causes segfaulting

### ISSUE THREAD

**Issue by tstirrat15** [neovim/neovim#7643]
- `nvim --version`:
```
NVIM v0.2.3-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/build/config -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/src -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/.deps/usr/include -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/.deps/usr/include -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/.deps/usr/include -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/.deps/usr/include -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/.deps/usr/include -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/.deps/usr/include -I/usr/include -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/build/src/nvim/auto -I/build/neovim-F1yEvH/neovim-0.2.0ubuntu1+git201711260918+3780+26~ubuntu17.10.1/build/include
Compiled by buildd@lcy01-amd64-010

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
- Vim (version: ) behaves differently?
I don't have Vim installed.
- Operating system/version:
Ubuntu 17.10
- Terminal name/version:
GNOME Terminal 3.24.2
- `$TERM`:
xterm-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC .
<press `i` a couple of times to trigger directory change>
```

### Actual behaviour
It throws `hash_add` errors, and if you attempt to navigate into a directory, it segfaults.
### Expected behaviour
Browsing the directory as normal.

### Stack trace
```
#1  0x00007fa95dae3f5d in __GI_abort () at abort.c:90
#2  0x0000557d0aadf720 in loop_poll_events ()
#3  0x0000557d0ab95575 in os_breakcheck ()
#4  0x0000557d0ab2a80a in ?? ()
#5  0x0000557d0ab2b8c2 in vgetc ()
#6  0x0000557d0ab2bc70 in safe_vgetc ()
#7  0x0000557d0ab5d588 in wait_return ()
#8  0x0000557d0ab5d7d1 in msg_end ()
#9  0x0000557d0ab5ddaf in msg_attr_keep ()
#10 0x0000557d0ab5dfcf in msg_attr ()
#11 0x0000557d0ab5e3b9 in emsg ()
#12 0x0000557d0ab5e4cd in emsgf ()
#13 0x0000557d0ab332a8 in hash_add ()
#14 0x0000557d0aadc412 in tv_dict_add ()
#15 0x0000557d0aadd6f6 in tv_dict_add_list ()
#16 0x0000557d0aa9125b in ?? ()
#17 0x0000557d0aa9169c in on_job_stderr ()
#18 0x0000557d0aae11ab in ?? ()
#19 0x0000557d0aae1289 in ?? ()
#20 0x0000557d0aae1414 in ?? ()
#21 0x0000557d0ac383c7 in ?? ()
#22 0x0000557d0ac385cf in ?? ()
#23 0x0000557d0ac393ac in ?? ()
#24 0x0000557d0ac3e230 in uv.io_poll ()
#25 0x0000557d0ac2f928 in uv_run ()
#26 0x0000557d0aadf746 in loop_poll_events ()
#27 0x0000557d0ab95575 in os_breakcheck ()
#28 0x0000557d0ab62f95 in line_breakcheck ()
#29 0x0000557d0ab17553 in ?? ()
#30 0x0000557d0ab190ca in ?? ()
#31 0x0000557d0ab19963 in apply_autocmds ()
#32 0x0000557d0ab6f688 in ?? ()
#33 0x0000557d0ab732dd in ?? ()
#34 0x0000557d0ac0112c in state_enter ()
#35 0x0000557d0ab7026d in normal_enter ()
#36 0x0000557d0ab46ad9 in main ()
```

**Comment by fmoralesc** [comment]
This should be fixed by @bfredl's last commit to HEAD.

**Comment by tstirrat15** [comment]
Awesome. That means it will be available tomorrow morning on the unstable PPA?

**Comment by fmoralesc** [comment]
It should be available now. Can you confirm?

**Comment by tstirrat15** [comment]
Just checked - not yet. It may be a caching thing?

**Comment by fmoralesc** [comment]
Maybe. I checked from the PPA website and it said it had been rebuilt 15 hours ago. Oh well. You can always get it from https://github.com/neovim/neovim/releases/tag/nightly

**Comment by tstirrat15** [comment]
Whups. Never mind. I didn't have the PPA configured properly on my local. There it is! Thank you!
