### ISSUE TITLE
Wrong Ruby provider

### ISSUE THREAD

**Issue by huyvohcmc** [neovim/neovim#8145]
- `nvim --version`: v0.2.2
- Operating system/version: MacOS High Sierra 10.13.3
- Terminal name/version: iterm2 3.1.5
- `$TERM`: xterm-256color

I have installed Ruby version 2.3.3 using RVM (1.29.3) and use it as the default Ruby on my machine. The system Ruby version is 2.5.0.

### Steps to reproduce:

```
nvim -u NORC
:checkhealth
```

### Actual behaviour

```
## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  - INFO: Host: /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host
  - ERROR: Command error (job=17): /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host --version
    Output: Ignoring bcrypt-3.1.11 because its extensions are not built. Try: gem pristine bcrypt --version 3.1.11Ignoring bindex-0.5.0 because its extensions are not built. Try: gem pristine bindex --version 0.5.0Ignoring binding_of_caller-0.7.2 because its extensions are not built. Try: gem pristine binding_of_caller --version 0.7.2Ignoring bootsnap-1.1.8 because its extensions are not built. Try: gem pristine bootsnap --version 1.1.8Ignoring byebug-9.1.0 because its extensions are not built. Try: gem pristine byebug --version 9.1.0Ignoring debug_inspector-0.0.3 because its extensions are not built. Try: gem pristine debug_inspector --version 0.0.3Ignoring executable-hooks-1.4.2 because its extensions are not built. Try: gem pristine executable-hooks --version 1.4.2Ignoring fast_stack-0.1.0 because its extensions are not built. Try: gem pristine fast_stack --version 0.1.0Ignoring ffi-1.9.18 because its extensions are not built. Try: gem pristine ffi --version 1.9.18Ignoring ffi-1.9.8 because its extensions are not built. Try: gem pristine ffi --version 1.9.8Ignoring gem-wrappers-1.3.2 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.3.2Ignoring hamlit-2.3.1 because its extensions are not built. Try: gem pristine hamlit --version 2.3.1Ignoring hitimes-1.2.6 because its extensions are not built. Try: gem pristine hitimes --version 1.2.6Ignoring hitimes-1.2.3 because its extensions are not built. Try: gem pristine hitimes --version 1.2.3Ignoring json-1.8.6 because its extensions are not built. Try: gem pristine json --version 1.8.6Ignoring levenshtein-ffi-1.1.0 because its extensions are not built. Try: gem pristine levenshtein-ffi --version 1.1.0Ignoring msgpack-1.2.4 because its extensions are not built. Try: gem pristine msgpack --version 1.2.4Ignoring msgpack-1.2.2 because its extensions are not built. Try: gem pristine msgpack --version 1.2.2Ignoring nio4r-2.1.0 because its extensions are not built. Try: gem pristine nio4r --version 2.1.0Ignoring nokogiri-1.8.1 because its extensions are not built. Try: gem pristine nokogiri --version 1.8.1Ignoring nokogumbo-1.4.1 because its extensions are not built. Try: gem pristine nokogumbo --version 1.4.1Ignoring oj-3.3.9 because its extensions are not built. Try: gem pristine oj --version 3.3.9Ignoring passenger-5.0.22 because its extensions are not built. Try: gem pristine passenger --version 5.0.22Ignoring pg-0.21.0 because its extensions are not built. Try: gem pristine pg --version 0.21.0Ignoring pg-0.18.2 because its extensions are not built. Try: gem pristine pg --version 0.18.2Ignoring psych-2.2.4 because its extensions are not built. Try: gem pristine psych --version 2.2.4Ignoring puma-3.10.0 because its extensions are not built. Try: gem pristine puma --version 3.10.0Ignoring puma-3.4.0 because its extensions are not built. Try: gem pristine puma --version 3.4.0Ignoring rainbow-2.2.2 because its extensions are not built. Try: gem pristine rainbow --version 2.2.2Ignoring rainbow-2.2.1 because its extensions are not built. Try: gem pristine rainbow --version 2.2.1Ignoring rbtrace-0.4.7 because its extensions are not built. Try: gem pristine rbtrace --version 0.4.7Ignoring redcarpet-3.4.0 because its extensions are not built. Try: gem pristine redcarpet --version 3.4.0Ignoring rmagick-2.15.2 because its extensions are not built. Try: gem pristine rmagick --version 2.15.2Ignoring stackprof-0.2.11 because its extensions are not built. Try: gem pristine stackprof --version 0.2.11Ignoring unf_ext-0.0.7.1 because its extensions are not built. Try: gem pristine unf_ext --version 0.0.7.1Ignoring websocket-driver-0.6.5 because its extensions are not built. Try: gem pristine websocket-driver --version 0.6.5/usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': incompatible library version - /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/msgpack-1.2.4/lib/msgpack/msgpack.bundle (LoadError)	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/msgpack-1.2.4/lib/msgpack.rb:11:in `rescue in <top (required)>'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/msgpack-1.2.4/lib/msgpack.rb:8:in `<top (required)>'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/neovim-0.7.1/lib/neovim/connection.rb:3:in `<top (required)>'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/neovim-0.7.1/lib/neovim/event_loop.rb:2:in `<top (required)>'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/neovim-0.7.1/lib/neovim.rb:3:in `<top (required)>'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/neovim-0.7.1/lib/neovim/host.rb:1:in `<top (required)>'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /usr/local/Cellar/ruby/2.5.0_2/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/gems/neovim-0.7.1/bin/neovim-ruby-host:3:in `<top (required)>'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host:23:in `load'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host:23:in `<main>'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'	from /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
  - ERROR: Failed to run: /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host --version
    - ADVICE:
      - Report this issue with the output of: 
      - /Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host --version
```

### Expected behaviour

```
checkhealth success, ruby provider match current ruby version set by RVM
```

Running `/Users/huyvo/.rvm/gems/ruby-2.3.3/bin/neovim-ruby-host --version` returns `0.7.1`. Also `gem env` has everything point to Ruby `2.3.3`.

And lastly, `echo :$PATH`:
```
:/Users/huyvo/.rvm/gems/ruby-2.3.3/bin:/Users/huyvo/.rvm/gems/ruby-
2.3.3@global/bin:/Users/huyvo/.rvm/rubies/ruby-2.3.3/bin:
/Users/huyvo/.nvm/versions/node/v8.9.4/bin:
/usr/local/bin:/usr/bin:/usr/local/opt/imagemagick@6/bin:
/usr/bin:/bin:/usr/sbin:/sbin:/Users/huyvo/.fzf/bin:/Users/huyvo/.rvm/bin
```

Does anyone know how to fix it?

**Comment by justinmk** [comment]
Try using `g:ruby_host_prog` to set the absolute path to the correction location. See `:help g:ruby_host_prog`.

**Comment by huyvohcmc** [comment]
Thank you @justinmk. I'm just wondering why `checkhealth` list ruby 2.5.0 and not the default and current 2.3.3?

**Comment by justinmk** [comment]
because that's what `ruby -v` reported: https://github.com/neovim/neovim/blob/1d5eec2c626bd8125940c0425cc6f33213851781/runtime/autoload/health/provider.vim#L452
