### ISSUE TITLE
Ex command parsing fails for neovim-remote in terminal

### ISSUE THREAD

**Issue by munyari** [neovim/neovim#8252]
From https://github.com/mhinz/neovim-remote/issues/81
After starting nvim -u NORC
Write a script test with this content
```
$EDITOR
```

and run like `EDITOR="nvr +'set spell'" ./test` inside terminal mode.

Expected behavior:
New buffer with no title opened in the current window.

Actual behavior:
```
Traceback (most recent call last):
  File "/usr/bin/nvr", line 11, in <module>
    load_entry_point('neovim-remote==2.0.4', 'console_scripts', 'nvr')()
  File "/usr/lib/python3.6/site-packages/nvr/nvr.py", line 412, in main
    nvr.execute(arguments, 'edit', silent=True)
  File "/usr/lib/python3.6/site-packages/nvr/nvr.py", line 132, in execute
    self.server.command(cmd if cmd else '$')
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 242, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 140, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in requ
est
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim:E20: Mark not set'
```

New buffer with name $CWD/tmp/spell' opened

NVIM v0.2.2
nvr 2.0.4

**Comment by justinmk** [comment]
What is being sent to Nvim? 

Assuming this is an nvr bug until minimal steps (without nvr) are provided.
