### ISSUE TITLE
Segmentation fault when resizing split window in terminator

### ISSUE THREAD

**Issue by nettrino** [neovim/neovim#8403]
Segmentation Fault 
Possibly relevant with 
* [#7628](https://github.com/neovim/neovim/issues/7628)
* [#7572](https://github.com/neovim/neovim/issues/7572)

- `nvim --version`:
```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=
auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
```
- Vim (version: 8.0.1839) behaves differently? Yes
- Operating system/version: 
```
Ubuntu 16.04.4 LTS 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Terminal name/version: terminator v0.98
- `$TERM`: Ubuntu 16.04.4 LTS

### Steps to reproduce using `nvim -u NORC`
 * Create a terminator with a vertical split
 * Open any file on neovim on the left split 
 * Drag the split all the way to the left (make the window essentially a vertical column), then reopen the split.

### Actual behaviour
Segmentation Fault
Coredump:
```
[New LWP 25988]
[New LWP 25987]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nvim -u NONE test.txt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056220205513f in ?? ()
[Current thread is 1 (Thread 0x7f1cf03ff700 (LWP 25988))]
#0  0x000056220205513f in ?? ()
#1  0x0000562202056262 in ?? ()
#2  0x000056220205679a in ?? ()
#3  0x000056220205684e in ?? ()
#4  0x000056220205a965 in ?? ()
#5  0x0000562201f2872a in multiqueue_process_events ()
#6  0x0000562201f27ce1 in loop_poll_events ()
#7  0x000056220205833b in ?? ()
#8  0x000056220205ab2c in ?? ()
#9  0x00007f1cf31421d7 in ?? () from /usr/lib/x86_64-linux-gnu/libuv.so.1
#10 0x00007f1cf2f176ba in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#11 0x00007f1cf1a6941d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

### Expected behaviour
Everything should be working as expected regardless of the size of the window split

**Comment by justinmk** [comment]
This was already fixed on master.
