### ISSUE TITLE
Pip already installed neovim but module not found

### ISSUE THREAD

**Issue by huyvohcmc** [neovim/neovim#9246]
- `nvim --version`: 0.3.1
- Vim (version: ) behaves differently? I don't use Vim
- Operating system/version: MacOS 10.14.1
- Terminal name/version: iTerm2 3.2.5
- `$TERM`: screen-256color

```bash
$ which python
/usr/local/bin/python
$ which python3
/usr/local/bin/python3
$ which pip
/usr/local/bin/pip
$ which pip3
/usr/local/bin/pip3
$ pip freeze (or) pip3 freeze
GDAL==2.3.1
greenlet==0.4.13
msgpack==0.5.6
neovim==0.3.1
nose==1.3.7
numpy==1.15.4
pynvim==0.3.1
```

### Steps to reproduce using `nvim -u NORC`
```bash
$ python
>>> import neovim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named neovim

$ python3
>>> import neovim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named neovim

$ nvim -u NORC
:checkhealth
```

### Actual behaviour

```bash
## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/local/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/local/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/local/bin/python3 does not have the "neovim" module. :help provider-python
          /usr/local/bin/python3.7 does not have the "neovim" module. :help provider-python
          python3.6 not found in search path or not executable.
          python3.5 not found in search path or not executable.
          python3.4 not found in search path or not executable.
          python3.3 not found in search path or not executable.
          /usr/local/bin/python is Python 2.7 and cannot provide Python 3.
  - INFO: Executable: Not found
```

### Expected behaviour
CheckHealth runs fine without any error.

Both `:echo has('python')` and `:echo has('python3')` ran inside `nvim -u NORC` returns `0`. I tried reinstall python2/3 and even nvim in brew, no luck.

**Comment by clason** [comment]
Try `pip uninstall`ing *both* `neovim` and `pynvim`, and then reinstalling *just* `pynvim` -- that worked for me (both on 0.3.1 and HEAD).

**Comment by bfredl** [comment]
@clason  installing `neovim` (0.3.1) should work the same, it depends on `pynvim`.

**Comment by huyvohcmc** [comment]
@bfredl I just tried @clason's way and it indeed worked for me.

**Comment by bfredl** [comment]
Nice, I will update the instructions.

**Comment by clason** [comment]
Just `pip installing pynvim` (without previously uninstalling `neovim` also works).

**Comment by bfredl** [comment]
> Just pip installing pynvim (without previously uninstalling neovim also works).

I don't think this is safe in general, python might come to prefer the old version of `neovim` rather than the alias included in the `pynvim` package (no difference for now, but will be an issue with later upgrades).

**Comment by bfredl** [comment]
> True, and manually uninstalling neovim later breaks pynvim,

`pip` is _supposed_ to not break pynvim in such a case (separate pypi packages should be isloated into `site-package/name-version-pyversion.egg/` folders), but I guess it breaks under unpredictable circumstances just like every other non-trivial action pip does.

**Comment by clason** [comment]
I should add that when I wrote "break", I meant "not visible from `nvim`" (`:checkhealth` or python plugins such as UltiSnips); I didn't test from `python`.

**Comment by bfredl** [comment]
> I should add that when I wrote "break", I meant "not visible from nvim" (:checkhealth or python plugins such as UltiSnips); I didn't test from python.

what nvim does is trying to `import neovim` in `python3` in `PATH` (and then `python` if the first fails), unless `g:python3_host_prog` is set, in case that (and only that) python is tried.

**Comment by clason** [comment]
I suspect there's a subtle issue with `python3` installed via `homebrew` (the original issue -- and my tests -- were on macOS; `g:python3_host_prog` is not set) and `pip` getting confused. I've had issues before when upgrading either macOS, python3, or pip that were only solved by removing pip and reinstalling.

**Comment by bfredl** [comment]
>  removing pip and reinstalling.

Yes, the nuclear option should always work, but I was hoping for a simpler reliable upgrade path. I ostensibly followed the same procedure as `msgpack-python` when they renamed their pypi package,  naively expecting that it should work also for us.

**Comment by clason** [comment]
That wasn't necessary here, fortunately, and only seems to be an issue with homebrew on macOS (never had a similar problem on Linux). So I don't think you did anything wrong, it's just that `pip`+`homebrew` is fragile and requires uninstall + reinstall rather than upgrade if anything more complicated than a minor version tick is involved. Good to be aware of, but I don't see what package developers can do about it.

**Comment by clason** [comment]
Well, I take that back -- I just tested on my Linux box and had the same problem (`pip3 install -U neovim` doesn't suffice, need to `pip3 uninstall neovim pynvim && pip3 install pynvim` instead).

**Comment by bfredl** [comment]
looking at `msgpack-python` history they also ended up recommending uninstall+install.

`pip` seems to _sometimes_ put packages into a isolated and versioned `.egg` dir, and _sometimes_ dump package contents directly in `site-packages`, or perhaps the behavior was changed with a relatively recent `pip` version, and any upgrade on a python env that has been touched by different versions of pip can has unintended results..

**Comment by justinmk** [comment]
Is this resolved then ?

**Comment by Qix-** [comment]
`:help provider-python` still instructs you to install `neovim` when in reality you want `pynvim`. Should this be updated?

**Comment by jamessan** [comment]
> `:help provider-python` still instructs you to install `neovim` when in reality you want `pynvim`. Should this be updated?

That was changed to `pynvim` in [November](https://github.com/neovim/neovim/commit/0c2ca48e5f27ed2dc2cecceffaa83976ee7e9e3e).

**Comment by Qix-** [comment]
Thanks @jamessan, I must be on a slightly older version.

**Comment by yochem** [comment]
For someone having the same problem (MacOS):
Python3 worked fine, but python2 didn't work (same problem as this issue). But when I ran this:
> Try `pip uninstall`ing _both_ `neovim` and `pynvim`, and then reinstalling _just_ `pynvim` -- that worked for me (both on 0.3.1 and HEAD).

It didn't work because `pip` checks if it's already installed for python3 and python2. So in order to make it work for me I had to run pip like this: `{{your python2 version}} -m pip install pynvim`.

**Comment by justinmk** [comment]
@yochem good point, and these days AFAIK `python -m pip` is the recommended way to run pip. So I will update docs to that effect.

**Comment by rmarinbe** [comment]
Hi, I know this is old but make sure wherever you installed the pynvim, the Python version you are using is in $PATH
