### ISSUE TITLE
Segfault when searching on startup

### ISSUE THREAD

**Issue by andrewla** [neovim/neovim#9366]
$ nvim --version
NVIM v0.3.2-77-g2b9fc9a13

Cannot reproduce reliably; this seems to happen when I start typing after starting neovim but before the display has had a chance to redraw.  In the stack trace below this was a search:
```
#0  __memmove_avx_unaligned_erms ()    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:268
#1  0x00005555556b25a4 in put_on_cmdline (str=0x555555c0f440 <IObuff> "U", len=1, redraw=1)
    at /.../src/nvim/ex_getln.c:3146
#2  0x00005555556ae81a in command_line_handle_key (s=0x7fffffffdca0)
    at /.../src/nvim/ex_getln.c:1775
#3  0x00005555556ac7b7 in command_line_execute (state=0x7fffffffdca0, key=85)
    at /.../src/nvim/ex_getln.c:1024
#4  0x000055555580a2c9 in state_enter (s=0x7fffffffdca0)
    at /.../src/nvim/state.c:67
#5  0x00005555556aab26 in command_line_enter (firstc=47, count=1, indent=0)
    at /.../src/nvim/ex_getln.c:393
#6  0x00005555556aef7b in getcmdline (firstc=47, count=1, indent=0)
    at /.../src/nvim/ex_getln.c:1996
#7  0x0000555555746f01 in nv_search (cap=0x7fffffffe040)
    at /.../src/nvim/normal.c:5304
#8  0x000055555573d61b in normal_execute (state=0x7fffffffdfa0, key=47)
    at /.../src/nvim/normal.c:1137
#9  0x000055555580a2c9 in state_enter (s=0x7fffffffdfa0)
    at /.../src/nvim/state.c:67
#10 0x000055555573b8c0 in normal_enter (cmdwin=false, noexmode=false)
    at /.../src/nvim/normal.c:467
#11 0x00005555556ff5ea in main (argc=2, argv=0x7fffffffe2f8)
    at /.../src/nvim/main.c:566

```
I did a little bit of debugging:
```
(gdb) up
#1  0x00005555556b25a4 in put_on_cmdline (str=0x555555c0f440 <IObuff> "U",
    len=1, redraw=1)
    at /usr/local/google/home/andrewla/bin/src/nvim/neovim/src/nvim/ex_getln.c:3146
(gdb) print ccline
$1 = {cmdbuff = 0x0, cmdbufflen = 100, cmdlen = 18, cmdpos = 17, cmdspos = 18,
  cmdfirstc = 58, cmdindent = 0, cmdprompt = 0x0, cmdattr = 0, overstrike = 0,
  xpc = 0x0, xp_context = 0, xp_arg = 0x0, input_fn = 0, prompt_id = 1,
  highlight_callback = {data = {funcref = 0x0, partial = 0x0},
    type = kCallbackNone}, last_colors = {prompt_id = 1,
    cmdbuff = 0x7ffff5e3b620 "", colors = {size = 0, capacity = 0,
      items = 0x0}}, level = 1, prev_ccline = 0x0, special_char = 0 '\000',
  special_shift = false, redraw_state = kCmdRedrawNone}
(gdb) list
3141          } else
3142            ccline.cmdlen = ccline.cmdpos + len;
3143        } else if (ccline.cmdpos + len > ccline.cmdlen)
3144          ccline.cmdlen = ccline.cmdpos + len;
3145      }
3146      memmove(ccline.cmdbuff + ccline.cmdpos, str, (size_t)len);
3147      ccline.cmdbuff[ccline.cmdlen] = NUL;
3148
3149      if (enc_utf8) {
3150        /* When the inserted text starts with a composing character,
(gdb)
```

So `ccline.cmdbuff` is `NULL` at the point where we try to memmove it.  `cmdbufflen` is 100, which seems like an odd condition to be in.  I'll add more information when I have more time to investigate.

**Comment by justinmk** [comment]
2b9fc9a13 is ~800 patches behind HEAD. 

https://github.com/neovim/neovim/pull/8859
