### ISSUE TITLE
python2: nvim_err_write feedback loop (with NVIM_PYTHON_LOG_LEVEL=DEBUG)

### ISSUE THREAD

**Issue by khalidchawtany** [neovim/neovim#9381]
- `nvim --version`:
```
NVIM v0.3.2-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20181215-76218-yvt9ar/build/config -I/tmp/neovim-20181215-76218-yvt9ar/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20181215-76218-yvt9ar/build/src/nvim/auto -I/tmp/neovim-20181215-76218-yvt9ar/build/include
Compiled by juju@JuJus-MacBook-Pro.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-5e8f204/share/nvim"

Run :checkhealth for more info
```
- Vim (version: ) behaves differently?
- Operating system/version: `Mac OS 10.14.2`
- Terminal name/version: `iTerm2 version 3.2.6`
- `$TERM`: `xterm-256color`

### Steps to reproduce using `nvim -u NORC`
Cannot reproduce as I don't know if the provider is used at all when ran in this way
### Actual behaviour
Exception thrown and plugins relying on the python provider (I think python2) fail
### Expected behaviour
Work without error

![screen shot 2018-12-20 at 9 11 01 am](https://user-images.githubusercontent.com/1681606/50267598-d7fef200-0438-11e9-9f7c-fd05aca23c4a.png)

The error occurs the moment I open a PHP file. If I dismiss it, I continuously get the following error every time I move the cursor:
```
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    1:
E714: List required
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    5:
E121: Undefined variable: opening_tag_line
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    5:
E15: Invalid expression: opening_tag_line < first_window_line
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    9:
E121: Undefined variable: opening_tag_line
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    1:
E714: List required
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    5:
E121: Undefined variable: opening_tag_line
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:
line    5:
E15: Invalid expression: opening_tag_line < first_window_line
```

### Update attached log file:
[_py2_script.txt](https://github.com/neovim/neovim/files/2697649/_py2_script.txt)

**Comment by khalidchawtany** [comment]
The result of checkhealth:
```

health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/juju/.config/nvim/dein/repos/github.com/autozimu/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.132 cffa8b55eb93d33bc00795c8c85ea7dc6912f21f

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.1
  - INFO: pynvim version: 0.3.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node.js provider (optional)
  - INFO: Node.js: v11.4.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.2.1


```

**Comment by justinmk** [comment]
Error detected while processing function <SNR>319_HighlightEnclosingTagsIfPossible[12]..<SNR>319_HighlightEnclosingTags:

Use `:scriptnames` to see which script is number 319.

Anyways, from https://github.com/neovim/neovim/files/2697649/_py2_script.txt it looks  like  `nvim_err_write`  gets in a feedback loop. 

```
2018-12-20 09:28:50,294 [DEBUG @ msgpack_stream.py:send:34] 4658 - sent [0, 41, 'nvim_err_write', ('Traceback (most recent call last):\n',)]
2018-12-20 09:28:50,284 [DEBUG @ msgpack_stream.py:send:34] 4658 - sent [2, 'nvim_command', ('au DirChanged * call rpcnotify(15, "python_chdir", v:event.cwd)',)]
2018-12-20 09:28:50,284 [DEBUG @ msgpack_stream.py:send:34] 4658 - sent [0, 2, 'nvim_err_write', ('Traceback (most recent call last):\n',)]
...
2018-12-20 09:28:50,294 [DEBUG @ msgpack_stream.py:send:34] 4658 - sent [0, 41, 'nvim_err_write', ('Traceback (most recent call last):\n',)]
2018-12-20 09:28:50,296 [ERROR @ host.py:_load:146] 4658 - Encountered RuntimeError loading plugin at script_host.py: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pynvim/plugin/host.py", line 137, in _load
    self._discover_classes(module, handlers, path)
  File "/usr/local/lib/python2.7/site-packages/pynvim/plugin/host.py", line 178, in _discover_classes
    plugin = cls(self._configure_nvim_for(cls))
  File "/usr/local/lib/python2.7/site-packages/pynvim/plugin/script_host.py", line 51, in __init__
    .format(nvim.channel_id), async_=True)
  File "/usr/local/lib/python2.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
RuntimeError: maximum recursion depth exceeded
```

**Comment by khalidchawtany** [comment]
The script 319 is
```
 319: ~/.config/nvim/dein/repos/github.com/Valloric/MatchTagAlways/autoload/Match
TagAlways.vim. 
```

**Comment by bfredl** [comment]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 0: ordinal not in range(128)

Seem that somewhere something is trying to encode/decode stuff. This should be avoided, logging must never try to "interpret" bytes as anything, it should just pass them trough. 

Probably a python2 specific problem, python3 would never give a "decode" error when attempting to encode anything.

**Comment by bfredl** [comment]
It is even worse that that, python2.7 logging does ` msg.encode("UTF-8")` as a _direct result_ of an already `UnicodeError`, why would anyone think that possibly could do anything useful?  Seems like if we would want to properly support logging in python2.7, we would need to purify all data ourselves before it ever touches the logging interface.

If the plugin supports python3, using python3 is the proper workaround.
