### ISSUE TITLE
TUI: crash: grid_puts_line_flush

### ISSUE THREAD

**Issue by justinmk** [neovim/neovim#9554]
- `nvim --version`: NVIM v0.4.0-207 7e6980a16101
- Vim (version: ) behaves differently?
- Operating system/version: ubuntu 18.04
- Terminal name/version: macOS Terminal.app => ssh => tmux
- `$TERM`: screen-256color

### Steps to reproduce using `nvim -u NORC`

Don't have reliable steps yet. Here's roughly what my session looked like:

```
nvim -u NORC
:edit some file
:Man git-log
q
```

### Actual behaviour

segfault

### Expected behaviour

no segfault

Similar to https://github.com/neovim/neovim/issues/8936 (ends up in `cheap_to_print`).

backtrace: https://gitlab.com/justinmk/gist/snippets/1802260

```
             Stack trace of thread 3742:
                #0  0x00000000006d7ed0 cursor_goto (nvim)
                #1  0x00000000006d3c61 tui_raw_line.llvm.5756000633998662627 (nvim)
                #2  0x00000000006de14b ui_bridge_raw_line_event (nvim)
                #3  0x00000000004f44f9 loop_poll_events (nvim)
                #4  0x00000000006d42cd tui_main.llvm.5756000633998662627 (nvim)
                #5  0x00007ff5166366db start_thread (libpthread.so.0)
                #6  0x00007ff51578888f __clone (libc.so.6)
                
                Stack trace of thread 3741:
                #0  0x00007ff5166401aa __lll_unlock_wake (libpthread.so.0)
                #1  0x00007ff51663a7df __pthread_mutex_unlock_usercnt (libpthread.so.0)
                #2  0x0000000000714916 uv_mutex_unlock (nvim)
                #3  0x00000000004f46c7 loop_schedule (nvim)
                #4  0x00000000006d4408 tui_scheduler.llvm.5756000633998662627 (nvim)
                #5  0x00000000006ddaf5 ui_bridge_raw_line (nvim)
                #6  0x00000000006dbcc3 ui_line (nvim)
                #7  0x00000000006645cf grid_puts_len (nvim)
                #8  0x000000000065de4c draw_tabline.llvm.15626745971120929434 (nvim)
                #9  0x000000000065cdeb update_screen (nvim)
                #10 0x00000000005e7208 normal_check.llvm.882668486163963439 (nvim)
                #11 0x00000000006b0067 state_enter (nvim)
                #12 0x0000000000595242 main (nvim)
                #13 0x00007ff515688b97 __libc_start_main (libc.so.6)
                #14 0x0000000000439f2a _start (nvim)
```

**Comment by bfredl** [comment]
We might want to add a synchronous mode for ui_bridge/TUI: when the brigde sends any event, wait until TUI has processed that event. Then we can know for sure that the TUI crash was caused by what `screen.c` code (as for now, it could be any event before that tabline draw). Though `'writedelay'` might work as approximation for `ui_line` only.

**Comment by justinmk** [comment]
At commit c0a29c3656b0:

```
#1  0x00007fbe3a4d1801 in __GI_abort () at abort.c:79
#2  0x00007fbe3a51a897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fbe3a647b9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fbe3a52190a in malloc_printerr (str=str@entry=0x7fbe3a649828 "double free or corruption (fasttop)") at malloc.c:5350
#4  0x00007fbe3a529004 in _int_free (have_lock=0, p=0x1e223c0, av=0x7fbe3a87cc40 <main_arena>) at malloc.c:4230
#5  __GI___libc_free (mem=0x1e223d0) at malloc.c:3124
#6  0x00000000006dcd4d in xfree (ptr=0x2) at ../src/nvim/memory.c:115
#7  ui_bridge_raw_line_event (argv=0x7fbe39c9b728) at ../src/nvim/ui_bridge.c:157
#8  0x00000000004f3da9 in multiqueue_process_events (this=<optimized out>) at ../src/nvim/event/multiqueue.c:150
#9  loop_poll_events (loop=<optimized out>, ms=<optimized out>) at ../src/nvim/event/loop.c:66
#10 0x00000000006d176d in tui_main (bridge=0x1b0ce30, ui=0x1b0cd30) at ../src/nvim/tui/tui.c:428
#11 0x00007fbe3b4606db in start_thread (arg=0x7fbe39c9c700) at pthread_create.c:463
```

**Comment by bfredl** [comment]
Has this been reproduced anytime recently? Changes has been done to ui/tui since Mar 12.
