### ISSUE TITLE
Assertion failure in regexp.c reginsert_limits()

### ISSUE THREAD

**Issue by kcwu** [neovim/neovim#9602]
- `nvim --version`:
NVIM v0.4.0-250-g3ff1228f7
Build type: RelWithDebInfo

- Vim (version: ) behaves differently? 
Yes -- no crash (vim doesn't have corresponding assertions).

### Steps to reproduce using `nvim -u NORC`
```
./build/bin/nvim -u NORC --headless -c 'echo search("0\\{--800}")'
nvim: ../src/nvim/regexp.c:2632: void reginsert_limits(int, long, long, char_u *): Assertion `maxval >= 0 && (uintmax_t)maxval <= UINT32_MAX' failed.
```

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6b0e3fa in __GI_abort () at abort.c:89
#2  0x00007ffff6b05e37 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0xe24ca0 <.str.49> "maxval >= 0 && (uintmax_t)maxval <= UINT32_MAX", file=file@entry=0xe26710 "../src/nvim/regexp.c", line=line@entry=2632, function=function@entry=0xe24c40 <__PRETTY_FUNCTION__.reginsert_limits> "void reginsert_limits(int, long, long, char_u *)")
    at assert.c:92
#3  0x00007ffff6b05ee2 in __GI___assert_fail (assertion=0xe24ca0 <.str.49> "maxval >= 0 && (uintmax_t)maxval <= UINT32_MAX", file=0xe26710 "../src/nvim/regexp.c", line=2632, function=0xe24c40 <__PRETTY_FUNCTION__.reginsert_limits> "void reginsert_limits(int, long, long, char_u *)") at assert.c:101
#4  0x0000000000a493b8 in reginsert_limits (op=17, minval=<optimized out>, maxval=-800, opnd=0x60700000b0a1 "\021") at ../src/nvim/regexp.c:2632
#5  0x0000000000a44c6b in regpiece (flagp=0x7fffffff9700) at ../src/nvim/regexp.c:1712
#6  0x0000000000a43b1b in regconcat (flagp=<optimized out>) at ../src/nvim/regexp.c:1587
#7  regbranch (flagp=0x7fffffff9800) at ../src/nvim/regexp.c:1507
#8  0x0000000000a4305b in reg (paren=0, flagp=0x7fffffff98e0) at ../src/nvim/regexp.c:1433
#9  0x0000000000a41fee in bt_regcomp (expr=0x602000056370 "0\\{--800}", re_flags=<optimized out>) at ../src/nvim/regexp.c:1265
#10 0x0000000000a3fb24 in vim_regcomp (expr_arg=<optimized out>, re_flags=1) at ../src/nvim/regexp.c:7146
#11 0x0000000000ac7b40 in search_regcomp (pat=0x602000056370 "0\\{--800}", pat_save=0, pat_use=<optimized out>, options=1024, regmatch=0x7fffffff9a80) at ../src/nvim/search.c:196
#12 0x0000000000ac9553 in searchit (win=0x625000000100, buf=0x626000000100, pos=0x7fffffff9e60, dir=FORWARD, pat=0x602000056370 "0\\{--800}", count=1, options=1024, pat_use=0, stop_lnum=<optimized out>, tm=0x0) at ../src/nvim/search.c:552
#13 0x00000000006f436f in search_cmn (argvars=<optimized out>, match_pos=0x0, flagsp=<optimized out>) at ../src/nvim/eval.c:13796
#14 0x00000000006e286b in f_search (argvars=<optimized out>, rettv=0x7fffffffb5a0, fptr=<optimized out>) at ../src/nvim/eval.c:14103
#15 0x0000000000675b89 in call_func (funcname=<optimized out>, len=<optimized out>, rettv=0x7fffffffb5a0, argcount_in=1, argvars_in=0x7fffffffa420, argv_func=0x0, firstline=<optimized out>, lastline=<optimized out>, doesrange=<optimized out>, evaluate=<optimized out>, partial=<optimized out>, selfdict_in=0x0) at ../src/nvim/eval.c:6398
#16 0x000000000067ce4a in get_func_tv (name=0x602000056350 "search", len=6, rettv=0x7fffffffb5a0, arg=0x7fffffffb580, firstline=0, lastline=0, doesrange=<optimized out>, evaluate=<optimized out>, partial=<optimized out>, selfdict=<optimized out>) at ../src/nvim/eval.c:6144
#17 0x00000000006ab2cd in eval7 (arg=<optimized out>, rettv=0x7fffffffb5a0, evaluate=1, want_string=<optimized out>) at ../src/nvim/eval.c:4245
#18 0x00000000006a7f1f in eval6 (arg=<optimized out>, rettv=0x7fffffffb5a0, evaluate=1, want_string=<optimized out>) at ../src/nvim/eval.c:3942
#19 0x00000000006a7377 in eval5 (arg=0x7fffffffb580, rettv=0x7fffffffb5a0, evaluate=1) at ../src/nvim/eval.c:3793
#20 0x00000000006a6031 in eval4 (arg=0x7fffffffb580, rettv=0x7fffffffb5a0, evaluate=1) at ../src/nvim/eval.c:3530
#21 0x00000000006a5a91 in eval3 (arg=0x7fffffffb580, rettv=0x7fffffffb5a0, evaluate=1) at ../src/nvim/eval.c:3448
#22 0x00000000006730c1 in eval2 (arg=<optimized out>, rettv=<optimized out>, evaluate=<optimized out>) at ../src/nvim/eval.c:3379
#23 eval1 (arg=0x7fffffffb580, rettv=0x7fffffffb5a0, evaluate=1) at ../src/nvim/eval.c:3306
#24 0x0000000000691da1 in ex_echo (eap=<optimized out>) at ../src/nvim/eval.c:19571
#25 0x000000000078cc9a in do_one_cmd (cmdlinep=0x7fffffffbc80, flags=10, cstack=0x7fffffffbca0, fgetline=<optimized out>, cookie=0x0) at ../src/nvim/ex_docmd.c:2242
#26 0x00000000007828c9 in do_cmdline (cmdline=<optimized out>, fgetline=0x0, cookie=0x0, flags=10) at ../src/nvim/ex_docmd.c:593
#27 0x00000000008ac4f0 in do_cmdline_cmd (cmd=0x2 <error: Cannot access memory at address 0x2>) at ../src/nvim/ex_docmd.c:269
#28 exe_commands (parmp=<optimized out>) at ../src/nvim/main.c:1708
#29 main (argc=<optimized out>, argv=<optimized out>) at ../src/nvim/main.c:552
```

This is found by fuzzing (libfuzzer)

### Actual behaviour
assertion failed

### Expected behaviour
no crash

**Comment by justinmk** [comment]
Related but different: https://github.com/neovim/neovim/issues/8607#issuecomment-399572809

Maybe Vim fixed the bug in a recent patch (please check).

**Comment by kcwu** [comment]
No, vim have the same issue (negtive `maxval`). It just doesn't check and thus doesn't crash.

**Comment by justinmk** [comment]
> This is found by fuzzing (libfuzzer)

What was the input?

**Comment by kcwu** [comment]
Isn't the reproduce step enough for you?
```
./build/bin/nvim -u NORC --headless -c 'echo search("0\\{--800}")'
```

I have written a fuzzer like this https://github.com/vim/vim/pull/3991
so the fuzzer input is just
```
0\{--800}
```

**Comment by glepnir** [comment]
just give it a try seems like neovim not crash now.
