### ISSUE TITLE
neovim stuck when run with document on the command line

### ISSUE THREAD

**Issue by mcepl** [neovim/neovim#9691]
This somehow resembles #9675, but not exactly. With neovim from master (commit 299f32dc0 to be exact) on OpenSUSE/Tumbleweed from [my repo](https://build.opensuse.org/package/show/home:mcepl:neovim/neovim), I cannot reproduce anything with ``nvim -u NORC -c "sleep 5m"`` (that starts without any noticeable delay), nor with running just plain ``nvim`` without anything else on the command line (but long ``~/.vim/vimrc``), but TUI nvim (not [neovim-gtk](https://github.com/daa84/neovim-gtk/), which has no problems) gets stuck for very long time (half-an-hour) when started with the document on the command line, like ``nvim TODO.otl`` (or Python file, it doesn't matter).

There is rather substantial backtrace in the moment:
```
Attaching to process 13864
[New LWP 13868]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
__GI___libc_write (nbytes=8, buf=0x7fbca459ae78 <val>, fd=12)
    at ../sysdeps/unix/sysv/linux/write.c:26
26	  return SYSCALL_CANCEL (write, fd, buf, nbytes);
(gdb) t a a bt

Thread 2 (Thread 0x7fbca4026700 (LWP 13868)):
#0  0x00007fbca46a17fe in __GI_epoll_pwait (epfd=16, events=events@entry=0x7fbca4022710, 
    maxevents=maxevents@entry=1024, timeout=timeout@entry=-1, set=set@entry=0x0)
    at ../sysdeps/unix/sysv/linux/epoll_pwait.c:42
#1  0x00007fbca45974f9 in uv__io_poll (loop=loop@entry=0x7fbca40258c0, timeout=-1)
    at src/unix/linux-core.c:279
#2  0x00007fbca4588fb5 in uv_run (loop=0x7fbca40258c0, mode=UV_RUN_ONCE)
    at src/unix/core.c:361
#3  0x000055fc785bef5e in loop_poll_events (loop=0x7fbca40258c0, ms=-1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/event/loop.c:58
#4  0x000055fc78482cc8 in tui_main (bridge=0x55fc7a8c7f70, ui=0x55fc7a8e58c0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/tui/tui.c:428
#5  0x000055fc784741a1 in ui_thread_run (data=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ui_bridge.c:102
#6  0x00007fbca455dfab in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007fbca46a169f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fbca42f2fc0 (LWP 13864)):
#0  __GI___libc_write (nbytes=8, buf=0x7fbca459ae78 <val>, fd=12)
    at ../sysdeps/unix/sysv/linux/write.c:26
#1  __GI___libc_write (fd=fd@entry=12, buf=buf@entry=0x7fbca459ae78 <val>, 
    nbytes=nbytes@entry=8) at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007fbca4588a01 in uv__async_send (loop=<optimized out>, loop=<optimized out>)
    at src/unix/async.c:143
#3  uv_async_send (handle=<optimized out>) at src/unix/async.c:65
#4  0x000055fc785c03a8 in loop_schedule (loop=0x55fc78719ba0 <main_loop>, event=...)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/event/loop.c:82
#5  0x000055fc7848543f in set_bg_deferred (argv=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/tui/input.c:362
#6  0x000055fc785bed1c in multiqueue_process_events (this=0x55fc7a489290)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/event/multiqueue.c:150
#7  0x000055fc785bef82 in loop_poll_events (loop=0x55fc78719ba0 <main_loop>, 
    ms=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/event/loop.c:66
#8  0x000055fc785a1937 in do_sleep (msec=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:7391
#9  0x000055fc785a1a61 in ex_sleep (eap=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:7380
#10 0x000055fc785ac585 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffd14fe8638, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffd14fe86c0, 
    fgetline=fgetline@entry=0x55fc785a801f <get_loop_line>, 
--Type <RET> for more, q to quit, c to continue without paging--
    cookie=cookie@entry=0x7ffd14fe8660)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:2242
#11 0x000055fc785a9997 in do_cmdline (cmdline=<optimized out>, 
    fgetline=0x55fc785d398c <get_func_line>, cookie=0x55fc7a8ad520, flags=7)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:593
#12 0x000055fc785d8e80 in call_user_func (fp=0x55fc7a8afb50, argcount=<optimized out>, 
    argvars=0x7ffd14fe93d0, rettv=0x7ffd14fe9a40, firstline=<optimized out>, 
    lastline=<optimized out>, selfdict=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:21573
#13 0x000055fc785ee80f in call_func (
    funcname=funcname@entry=0x55fc7a8b63b0 "gitgutter#diff#run_diff", len=len@entry=23, 
    rettv=rettv@entry=0x7ffd14fe9a40, argcount_in=argcount_in@entry=3, 
    argvars_in=argvars_in@entry=0x7ffd14fe93d0, argv_func=argv_func@entry=0x0, 
    firstline=1, lastline=1, doesrange=0x7ffd14fe95a4, evaluate=true, partial=0x0, 
    selfdict_in=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:6383
#14 0x000055fc785ef35d in get_func_tv (name=0x55fc7a8b63b0 "gitgutter#diff#run_diff", 
    len=23, rettv=0x7ffd14fe9a40, arg=0x7ffd14fe99f0, firstline=1, lastline=1, 
    doesrange=0x7ffd14fe95a4, evaluate=1, partial=0x0, selfdict=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:6144
#15 0x000055fc785f4480 in eval7 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:4245
#16 0x000055fc785f464d in eval6 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1, 
    want_string=want_string@entry=0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3942
#17 0x000055fc785f4979 in eval5 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3793
#18 0x000055fc785f2b00 in eval4 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3530
#19 0x000055fc785f3474 in eval3 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3448
#20 0x000055fc785f35b9 in eval2 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3379
--Type <RET> for more, q to quit, c to continue without paging--
#21 0x000055fc785f36ff in eval1 (arg=arg@entry=0x7ffd14fe99f0, 
    rettv=rettv@entry=0x7ffd14fe9a40, evaluate=evaluate@entry=1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3306
#22 0x000055fc785f4cf0 in eval0 (
    arg=0x55fc7a8bfd73 "gitgutter#diff#run_diff(a:bufnr, 'index', 0)", 
    rettv=rettv@entry=0x7ffd14fe9a40, nextcmd=nextcmd@entry=0x7ffd14fe9ae8, evaluate=1)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:3266
#23 0x000055fc785f81e7 in ex_let (eap=0x7ffd14fe9ae0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:1489
#24 0x000055fc785ac585 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffd14fe9d08, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffd14fe9d90, 
    fgetline=fgetline@entry=0x55fc785d398c <get_func_line>, 
    cookie=cookie@entry=0x55fc7a8b7df0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:2242
#25 0x000055fc785a9997 in do_cmdline (cmdline=<optimized out>, 
    fgetline=0x55fc785d398c <get_func_line>, cookie=0x55fc7a8b7df0, flags=7)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:593
#26 0x000055fc785d8e80 in call_user_func (fp=0x55fc7a8e2190, argcount=<optimized out>, 
    argvars=0x7ffd14feaaa0, rettv=0x7ffd14feac80, firstline=<optimized out>, 
    lastline=<optimized out>, selfdict=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:21573
#27 0x000055fc785ee80f in call_func (
    funcname=funcname@entry=0x55fc7a8bf920 "gitgutter#process_buffer", len=len@entry=24, 
    rettv=rettv@entry=0x7ffd14feac80, argcount_in=argcount_in@entry=2, 
    argvars_in=argvars_in@entry=0x7ffd14feaaa0, argv_func=argv_func@entry=0x0, 
    firstline=1, lastline=1, doesrange=0x7ffd14feac68, evaluate=true, partial=0x0, 
    selfdict_in=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:6383
#28 0x000055fc785ef35d in get_func_tv (name=0x55fc7a8bf920 "gitgutter#process_buffer", 
    len=24, rettv=0x7ffd14feac80, arg=0x7ffd14feac78, firstline=1, lastline=1, 
    doesrange=0x7ffd14feac68, evaluate=1, partial=0x0, selfdict=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:6144
#29 0x000055fc785f5b4f in ex_call (eap=0x7ffd14fead40)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:2742
#30 0x000055fc785ac585 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffd14feaf68, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffd14feaff0, 
    fgetline=fgetline@entry=0x55fc785d398c <get_func_line>, 
    cookie=cookie@entry=0x55fc7a88b7b0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:2242
#31 0x000055fc785a9997 in do_cmdline (cmdline=<optimized out>, 
    fgetline=0x55fc785d398c <get_func_line>, cookie=0x55fc7a88b7b0, flags=7)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:593
#32 0x000055fc785d8e80 in call_user_func (fp=0x55fc7a7c44f0, argcount=<optimized out>, 
    argvars=0x7ffd14febd00, rettv=0x7ffd14febee0, firstline=<optimized out>, 
    lastline=<optimized out>, selfdict=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:21573
#33 0x000055fc785ee80f in call_func (
    funcname=funcname@entry=0x55fc7a8232f0 "\200\375R86_on_bufenter", len=len@entry=17, 
    rettv=rettv@entry=0x7ffd14febee0, argcount_in=argcount_in@entry=0, 
    argvars_in=argvars_in@entry=0x7ffd14febd00, argv_func=argv_func@entry=0x0, 
    firstline=1, lastline=1, doesrange=0x7ffd14febec8, evaluate=true, partial=0x0, 
    selfdict_in=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:6383
#34 0x000055fc785ef35d in get_func_tv (name=0x55fc7a8232f0 "\200\375R86_on_bufenter", 
    len=17, rettv=0x7ffd14febee0, arg=0x7ffd14febed8, firstline=1, lastline=1, 
    doesrange=0x7ffd14febec8, evaluate=1, partial=0x0, selfdict=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:6144
#35 0x000055fc785f5b4f in ex_call (eap=0x7ffd14febfa0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/eval.c:2742
#36 0x000055fc785ac585 in do_one_cmd (cmdlinep=cmdlinep@entry=0x7ffd14fec1c8, 
    flags=flags@entry=7, cstack=cstack@entry=0x7ffd14fec250, 
    fgetline=fgetline@entry=0x55fc78581516 <getnextac>, 
    cookie=cookie@entry=0x7ffd14fec810)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:2242
#37 0x000055fc785a9997 in do_cmdline (cmdline=<optimized out>, 
    fgetline=0x55fc78581516 <getnextac>, cookie=0x7ffd14fec810, flags=7)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/ex_docmd.c:593
#38 0x000055fc7858212f in apply_autocmds_group (event=EVENT_BUFENTER, 
    fname=0x55fc7a8a2800 "/home/matej/TODO.otl", fname_io=<optimized out>, 
    force=<optimized out>, group=group@entry=-3, buf=0x55fc7a482440, eap=0x0)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/fileio.c:7023
#39 0x000055fc785823d4 in apply_autocmds (event=<optimized out>, fname=<optimized out>, 
    fname_io=<optimized out>, force=<optimized out>, buf=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/fileio.c:6655
#40 0x000055fc7855d600 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/neovim-0.4.0~git.1551822532.299f32dc0-11.1.x86_64/src/nvim/main.c:511
(gdb) 
```
This is [the log](https://github.com/neovim/neovim/files/2938095/log.txt) from ``nvim -Vlog.txt TODO.otl``.

**Comment by justinmk** [comment]
Thanks for the backtrace!
I don't see how this is any different than https://github.com/neovim/neovim/issues/9675. Will have that fixed shortly.
